UAT_AllStar_8Jan2024_0636/Backup-Source/objects/cus_ord_trend_dates_info__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>SAP_Created_DateTime__c</fullName>
        <label>SAP Created DateTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_DateTime__c</fullName>
        <label>GCP Update DateTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Update_Date__c</fullName>
        <label>Update Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Updated_DateTime__c</fullName>
        <label>Vision Updated DateTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vision_GCP_Update_Date__c</fullName>
        <label>GCP Update Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Order Trend Dates Info</label>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_GCP_SFDC_Order_Status__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Unique_Identifier__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>GCP Unique Identifier that we are getting from GCP</inlineHelpText>
        <label>GCP Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRISM_SAP_Created_Date__c</fullName>
        <label>SAP_Created_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PRISM_SAP_Created_Time__c</fullName>
        <label>SAP_Created_Time</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Testing_field__c</fullName>
        <label>Testing field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Created_Date__c</fullName>
        <description>This field is used to store the created date of data</description>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_DateTime__c</fullName>
        <label>GCP Update DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_Date__c</fullName>
        <description>This field is when GCP is pulling their data</description>
        <label>Data Lake Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_SAP_Created_DateTime__c</fullName>
        <label>SAP_Created_DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_Updated_DateTime__c</fullName>
        <label>Vision Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <label>GCP SFDC Order Status</label>
    <nameField>
        <displayFormat>sfdc-ord-status-{0000000}</displayFormat>
        <label>GCP SFDC Order Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP SFDC Order Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/PrismOrderstatusDatesUpdate_REST.cls
@RestResource(urlMapping='/UpdateVisiondata/*')
global with sharing class PrismOrderstatusDatesUpdate_REST{
    @HttpGet
    global static string doGet() {
      Vision_GCP_SFDC_Order_Status__c cusOrdRec = [select Vision_GCP_Update_Date__c,GCP_Unique_Identifier__c,Testing_field__c,	PRISM_SAP_Created_Date__c,PRISM_SAP_Created_Time__c,lastmodifieddate,Vision_Created_Date__c,Vision_GCP_Update_DateTime__c,Vision_SAP_Created_DateTime__c from Vision_GCP_SFDC_Order_Status__c order by
PRISM_SAP_Created_Date__c desc ,PRISM_SAP_Created_Time__c desc, Vision_Created_Date__c desc,Vision_GCP_Update_DateTime__c desc limit 1];
                  // cusOrdRec.Testing_field__c='tet1';
               // update cusOrdRec;
String Vision_gcp_update_date  = String.valueOf(cusOrdRec.Vision_GCP_Update_Date__c);
                     String Vision_GCP_Update_DateTime = String.valueOfGmt(cusOrdRec.Vision_GCP_Update_DateTime__c);
                    String SAP_Created_DateTime  = String.valueOfGMT(cusOrdRec.Vision_SAP_Created_DateTime__c);
                    String Vision_update_date = String.valueOf(Phoenix_Util.getTodayEST()).substringbefore(' ');
                    cus_ord_trend_dates_info__c  cotdi = cus_ord_trend_dates_info__c.getInstance('Data1');
      
                    cotdi.Vision_GCP_Update_Date__c = Vision_gcp_update_date;
        
                    cotdi.Vision_Update_Date__c = Vision_update_date;
                    cotdi.Vision_GCP_Update_DateTime__c=Vision_GCP_Update_DateTime;
                    cotdi.SAP_Created_DateTime__c=SAP_Created_DateTime;
                    cotdi.Vision_Updated_DateTime__c=string.valueofGmt(Phoenix_Util.getUserTime(cusOrdRec.lastmodifieddate,'America/New_York'));
        
                    update cotdi;
        
        return 'success';
    }
    
}