UAT_AllStar_8Jan2024_0636/Backup-Source/objects/cus_ord_trend_dates_info__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>SAP_Created_DateTime__c</fullName>
        <label>SAP Created DateTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_DateTime__c</fullName>
        <label>GCP Update DateTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Update_Date__c</fullName>
        <label>Update Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Updated_DateTime__c</fullName>
        <label>Vision Updated DateTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vision_GCP_Update_Date__c</fullName>
        <label>GCP Update Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Order Trend Dates Info</label>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_GCP_SFDC_Order_Status__c.object
<CustomObject>
    <fields>
        <fullName>PRISM_SAP_Created_Time__c</fullName>
        <label>SAP_Created_Time</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Created_Date__c</fullName>
        <description>This field is used to store the created date of data</description>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_DateTime__c</fullName>
        <label>GCP Update DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_Date__c</fullName>
        <description>This field is when GCP is pulling their data</description>
        <label>Data Lake Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Updated_DateTime__c</fullName>
        <label>Vision Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <label>GCP SFDC Order Status</label>
    <nameField>
        <displayFormat>sfdc-ord-status-{0000000}</displayFormat>
        <label>GCP SFDC Order Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP SFDC Order Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/PrismOrderstatusDatesUpdate_REST_Test.cls
@isTest (seealldata=true)//positive unit test for the REST API GET call
    public class  PrismOrderstatusDatesUpdate_REST_Test {
        
      static testmethod void gettt(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();  
        
        req.requestURI = '/services/apexrest/UpdateVisiondata/';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
          Vision_GCP_SFDC_Order_Status__c nn=new Vision_GCP_SFDC_Order_Status__c();
         // nn.LastModifiedDate=today();
          nn.PRISM_SAP_Created_Time__c=string.valueof(system.today());
          nn.Vision_GCP_Update_Date__c=system.today();
          nn.Vision_Created_Date__c=system.today();
          nn.Vision_GCP_Update_Date__c=system.today();
         insert nn;
          
          cus_ord_trend_dates_info__c cotdi=new cus_ord_trend_dates_info__c();
                     cotdi.Vision_GCP_Update_Date__c = ' ';
        
                    cotdi.Vision_Update_Date__c = ' ';
                    cotdi.Vision_GCP_Update_DateTime__c='';
                    cotdi.SAP_Created_DateTime__c=' ';
                    cotdi.Vision_Updated_DateTime__c=' ';
                    cotdi.Name='data1';
                    insert cotdi;
        Test.startTest();
      PrismOrderstatusDatesUpdate_REST.doGet();
        Test.stopTest(); 
        }
    }