UAT_AllStar_8Jan2024_0636/Backup-Source/objects/doh_report_dates_info__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Vision_GCP_Update_Date__c</fullName>
        <label>GCP Update Date</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Vision_Update_Date__c</fullName>
        <label>Update Date</label>
        <type>TextArea</type>
    </fields>
    <label>DOH Report Dates Info</label>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/GCP_DOH_Trade_Partner_NDC__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GCP DOH Trade Partner NDC</relationshipLabel>
        <relationshipName>GCP_DOH_Trade_Partner_NDC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_Date__c</fullName>
        <description>This field is when GCP is pulling their data</description>
        <label>Data Lake Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vision_gcp_ndc__c</fullName>
        <label>GCP NDC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vision_gcp_package_description__c</fullName>
        <label>GCP Package Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vision_gcp_trade_partner_name__c</fullName>
        <label>GCP Trade Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP DOH Trade Partner NDC</label>
    <nameField>
        <displayFormat>DOH-NDC-{00000}</displayFormat>
        <label>GCP DOH Trade Partner NDC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP DOH Trade Partner NDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_Trade_Partner_DOH_Report__c.object
<CustomObject>
    <fields>
        <fullName>Package_Description__c</fullName>
        <label>Package Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Partner_Name__c</fullName>
        <label>Trade Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_Date__c</fullName>
        <description>This field is when GCP is pulling their data</description>
        <label>Data Lake Update Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W3_DOH__c</fullName>
        <label>W3 DOH</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>GCP Trade Partner DOH Report</label>
    <nameField>
        <displayFormat>GCP trade-rep-{0000000}</displayFormat>
        <label>GCP Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Trade Partner DOH Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Vision_DoH_Search_By_Product_Test.cls
@isTest
public class Vision_DoH_Search_By_Product_Test {
	@isTest
    public static void testMethod1(){
        GCP_DOH_Trade_Partner_NDC__c gcpDoh = new GCP_DOH_Trade_Partner_NDC__c();
		gcpDoh.vision_gcp_ndc__c = 'Test';
        gcpDoh.vision_gcp_package_description__c = 'Test';
        gcpDoh.Vision_GCP_Update_Date__c = system.today();
        gcpDoh.vision_gcp_trade_partner_name__c = 'Test';
        insert gcpDoh;
        GCP_DOH_Trade_Partner_NDC__c gcpDoh2 = new GCP_DOH_Trade_Partner_NDC__c();
		gcpDoh2.vision_gcp_ndc__c = 'Test2';
        gcpDoh2.vision_gcp_package_description__c = 'Test2';
        gcpDoh2.Vision_GCP_Update_Date__c = system.today();
        gcpDoh2.vision_gcp_trade_partner_name__c = 'Test2';
        insert gcpDoh2;
       // Vision_DoH_Search_By_Product.getAccountGroups();
       List<String> strList = new List<String>();
        strList.add('Hello');
       Vision_DoH_Search_By_Product.getFilterDoHData('Test','Test2');
        GCP_DOH_Trade_Partner_NDC__c gcpDoh3 = new GCP_DOH_Trade_Partner_NDC__c();
		gcpDoh3.vision_gcp_ndc__c = 'Test2';
        gcpDoh3.vision_gcp_package_description__c = 'Test2';
        gcpDoh3.Vision_GCP_Update_Date__c = system.today();
        gcpDoh3.vision_gcp_trade_partner_name__c = 'Test2';
        insert gcpDoh3;
        Product2 pr = new Product2();
        pr.Name  = 'test product';
        insert pr;
        gcpDoh2.Product__c = pr.Id;
        update gcpDoh2;
        List < GCP_DOH_Trade_Partner_NDC__c > productList1 = new List < GCP_DOH_Trade_Partner_NDC__c >();
       productList1.add(gcpDoh2);
       Vision_DoH_Search_By_Product.fetchSortResults('','Test4',true,'Test2',productList1);
        
        Vision_DoH_Search_By_Product.getAwardedPositionData(gcpDoh2.Id,gcpDoh2.Id);
        
        
    }
    static testmethod void  test1(){
        GCP_Trade_Partner_DOH_Report__c tradeDoH= new GCP_Trade_Partner_DOH_Report__c(Trade_Partner_Name__c='test Trade',Package_Description__c='testProduct',W3_DOH__c=2,Vision_GCP_Update_Date__c ='2022-02-11');
        insert tradeDoH;
        GCP_DOH_Trade_Partner_NDC__c ndcDOH = new  GCP_DOH_Trade_Partner_NDC__c(vision_gcp_trade_partner_name__c ='test small');
        insert ndcDOH;
        List<GCP_DOH_Trade_Partner_NDC__c> ndcList = new List<GCP_DOH_Trade_Partner_NDC__c>{ndcDOH};
            
            doh_report_dates_info__c dohRepinfo = new  doh_report_dates_info__c(Vision_Update_Date__c ='2022-02-11', Name='Test');
        insert dohRepinfo;
        string customer = 'test';
        List<String> productType=new List<String> {}; 
            
            Vision_DoH_Search_By_Product.getAccountGroups();

    }
     static testmethod void  test7(){
        GCP_Trade_Partner_DOH_Report__c tradeDoH= new GCP_Trade_Partner_DOH_Report__c(Trade_Partner_Name__c='test Trade',Package_Description__c='testProduct',W3_DOH__c=2,Vision_GCP_Update_Date__c ='2022-02-11');
        insert tradeDoH;
        GCP_DOH_Trade_Partner_NDC__c ndcDOH = new  GCP_DOH_Trade_Partner_NDC__c(vision_gcp_trade_partner_name__c ='test small');
        insert ndcDOH;
        List<GCP_DOH_Trade_Partner_NDC__c> ndcList = new List<GCP_DOH_Trade_Partner_NDC__c>{ndcDOH};
            
            doh_report_dates_info__c dohRepinfo = new  doh_report_dates_info__c(Vision_Update_Date__c ='2022-02-11', Name='Test');
        insert dohRepinfo;
        string customer = 'test';
        List<String> productType=new List<String> {'Rx','Srx'}; 
            Vision_DoH_Search_By_Product.getAccountGroups();
       
    }
}