UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_Product_Family_Map__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SULFADIAZINE 1 CREAM</fullName>
                </value>
                <value>
                    <fullName>HABITROL PATCH</fullName>
                </value>
                <value>
                    <fullName>FENOFIBRATE CAPS</fullName>
                </value>
                <value>
                    <fullName>RANITIDINE CAPS</fullName>
                </value>
                <value>
                    <fullName>FEBUXOSTAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Product_Family__c</fullName>
        <label>SFDC Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SSD Cream</fullName>
                </value>
                <value>
                    <fullName>Fenofibrate Capsules</fullName>
                </value>
                <value>
                    <fullName>Ranitidine Caps</fullName>
                </value>
                <value>
                    <fullName>Febuxostat</fullName>
                </value>
                <value>
                    <fullName>Naproxen Sodium</fullName>
                </value>
                <value>
                    <fullName>Nicotine Lozenge Original</fullName>
                </value>
                <value>
                    <fullName>Pemetrexed</fullName>
                </value>
                <value>
                    <fullName>Sorafenib</fullName>
                </value>
                <value>
                    <fullName>Fesoterodine</fullName>
                </value>
                <value>
                    <fullName>CHLORDIAZEPOXIDE HCL-CLIDINIUM BROMIDE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GCP Product Family Map</label>
    <nameField>
        <displayFormat>GCPFamilyMap-{0000000}</displayFormat>
        <label>GCP Product Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Product Family Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family_Map__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Product Family Map</label>
        <referenceTo>GCP_Product_Family_Map__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_GCN_Sequence_Number__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GCN Sequence Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_GPI_Generic_Product_Identifier__c</fullName>
        <description>It contains 14 characters.</description>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GPI (Generic Product Identifier)  </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <inlineHelpText>National Drug Code: SAP field</inlineHelpText>
        <label>NDC - 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_GCP_Backorder_SRx_Rx__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Anticipated_Date_of_Availability__c</fullName>
        <label>Anticipated Date of Availability</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Available_for_Dropship__c</fullName>
        <label>Available for Dropship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Avg_unit_Price__c</fullName>
        <label>Avg unit Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Back_Order_SKU_In_Transit__c</fullName>
        <label>Back Order SKU In Transit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Back_Order_Value__c</fullName>
        <label>Back Order Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Backorder_Qty__c</fullName>
        <label>Backorder Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Date_Dispatched__c</fullName>
        <label>Date Dispatched</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Update_Date__c</fullName>
        <label>GCP Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Manufacturer__c</fullName>
        <label>Manufacturer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Vision_GCP_Backorder_SRx_Rx</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_SKU_Description__c</fullName>
        <label>SKU Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Total_in_Transit__c</fullName>
        <label>Total in Transit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_ndc__c</fullName>
        <label>NDC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP Backorder SRx Rx</label>
    <nameField>
        <displayFormat>backorder-Srx-Rx -{0000000}</displayFormat>
        <label>GCP Backorder SRX and RxName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Backorder SRx Rx</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/GoogleBackOrderSRxandRxFetchTest.cls
@istest
public class GoogleBackOrderSRxandRxFetchTest {
    static testmethod void setup(){
        Account A = new Account();
        a.name='Test';
        a.AccountNumber='11111';
        insert a;
        Account a1= new account();
        a1.name='test1';
        a1.AccountNumber=null;
        insert a1;
         Product2 p=new Product2();
        p.Name='abc pharma';
        p.Phoenix_NDC_11__c='23364848';
        p.ProductCode='123566';
        p.Phoenix_NDC__c='5555555';
        p.Phoenix_GPI_Generic_Product_Identifier__c = '11111';
        p.Family = 'Test Family';
        p.Phoenix_Throughput_cost__c=10.23456576;
        p.Phoenix_GCN_Sequence_Number__c='666666';
        p.Phoenix_Pkg_Size__c=25.0;
        insert p;
        GCP_Product_Family_Map__c gcpf= new GCP_Product_Family_Map__c();
        gcpf.SFDC_Product_Family__c='A';
        gcpf.GCP_Product_Family__c='A';
        insert gcpf;
        Vision_GCP_Backorder_SRx_Rx__c bosrx = new Vision_GCP_Backorder_SRx_Rx__c();
        bosrx.Vision_Anticipated_Date_of_Availability__c='24-06-2022';
        bosrx.Vision_Available_for_Dropship__c='yes';
        bosrx.Vision_Avg_unit_Price__c='25';
        bosrx.Vision_Back_Order_SKU_In_Transit__c='256';
        bosrx.Vision_Back_Order_Value__c=25000;
        bosrx.Vision_Backorder_Qty__c=250;
      //  bosrx.Vision_Date_Dispatched__c='jjj';
        bosrx.Vision_Manufacturer__c='phonenix';
        bosrx.Vision_GCP_Update_Date__c=Date.newInstance(2022, 02, 24);
        bosrx.Vision_ndc__c='25666';
        bosrx.Vision_SKU_Code__c='22222';
        bosrx.Vision_SKU_Description__c='ddff';
        bosrx.Vision_Product__c=p.id;
        bosrx.Vision_Total_in_Transit__c=250;
        insert bosrx;
        test.startTest();
        GoogleBackOrderSRxandRxFetch b = new GoogleBackOrderSRxandRxFetch();
        database.executeBatch(b);
         Database.executeBatch(new GoogleBackOrderSRxandRxFetch(5,4));
        test.stopTest();
        
        
        
    }
}