UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Date__c</fullName>
        <label>Comment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comment_Type__c</fullName>
        <label>Comment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Panorama</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GCP_Unique_Identifier__c</fullName>
        <label>GCP Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rx</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>long_term_strategy__c</fullName>
        <label>long term strategy</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>short_term_strategy__c</fullName>
        <label>short term strategy</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>GCP Comment</label>
    <nameField>
        <displayFormat>Cmnt - {00000}</displayFormat>
        <label>GCP Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product_Family__c.object
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/GoogleCommentsFetchBatchTest.cls
@isTest
public class GoogleCommentsFetchBatchTest {
    @testSetup static void setup() {
        // Create common test accounts and DRL Sales
        List<Account> accList = new List<Account>();
        Account acc = new Account(Name = 'Test Record');
        accList.add(acc);
        insert accList;
        List<GCP_Comment__c> gcp_comment_List = new List<GCP_Comment__c>();
        for(Account a : accList){
            GCP_Comment__c cmm = new GCP_Comment__c();
            cmm.GCP_Product_Family__c= 'Test Comment Record';
            cmm.long_term_strategy__c= 'Test Long Term Strategy';
            cmm.Segment__c= 'Test Segment';
            cmm.short_term_strategy__c= 'Test Short Term Strategy';
            cmm.Author__c= 'Test Author';
            cmm.Comment_Date__c = Date.today();
            cmm.Product_Family__c = 'Test Product Family';
            cmm.Comment_Type__c  = 'Panorama';
            cmm.GCP_Unique_Identifier__c= cmm.GCP_Product_Family__c+'_'+cmm.Segment__c+'_'+cmm.Comment_Date__c;
            gcp_comment_List.add(cmm);
        }
        upsert gcp_comment_List;
    }
    @isTest static void testMethod1() 
    {
        
        map<String,Id > existingGCPMap =new Map<String,Id >();
        for( GCP_Comment__c gcp : [select Id,GCP_Unique_Identifier__c  From GCP_Comment__c Where GCP_Product_Family__c = 'Test Comment Record'])existingGCPMap.put(gcp.GCP_Unique_Identifier__c,gcp.Id);
        Test.startTest();
        GoogleCommentsFetchBatch batch = new GoogleCommentsFetchBatch();
        batch.execute(null);
        Test.stopTest();
        GCP_Comment__c gcp = [ SELECT GCP_Product_Family__c ,GCP_Unique_Identifier__c,Id FROM GCP_Comment__c WHERE GCP_Product_Family__c = 'Test Comment Record'];
        System.assertEquals('Test Comment Record', gcp.GCP_Product_Family__c );
    }
    
    @isTest static void testMethod2() 
    {
        map<String,Id > existingGCPMap =new Map<String,Id >();
        for( GCP_Comment__c gcp : [select Id,GCP_Unique_Identifier__c  From GCP_Comment__c Where GCP_Product_Family__c = 'Test Comment Record'])existingGCPMap.put(gcp.GCP_Unique_Identifier__c,gcp.Id);
        Test.startTest();
        Database.executeBatch(new GoogleCommentsFetchBatch(1,1));
        Test.stopTest();
        GCP_Comment__c gcp = [ SELECT GCP_Product_Family__c ,GCP_Unique_Identifier__c,Id FROM GCP_Comment__c WHERE GCP_Product_Family__c= 'Test Comment Record'];
        System.assertEquals('Test Comment Record', gcp.GCP_Product_Family__c );
    }
}