UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_SFDC_100pct_Analysis_SKU__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GCP SFDC 100pct Analysis SKU</relationshipLabel>
        <relationshipName>GCP_SFDC_100pct_Analysis_SKU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_isAlerted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAlerted</label>
        <type>Checkbox</type>
    </fields>
    <label>GCP SFDC 100pct Analysis SKU</label>
    <nameField>
        <displayFormat>100PCT-Analysis-SKU-{00000}</displayFormat>
        <label>GCP SFDC 100pct Analysis SKU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP SFDC 100pct Analysis SKU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_GCP_Opportunity_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Vision_isAlerted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAlerted</label>
        <type>Checkbox</type>
    </fields>
    <label>GCP Opportunity Tracker</label>
    <nameField>
        <displayFormat>GCP Opp Tracker-{0000000}</displayFormat>
        <label>GCP Opportunity Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Opportunity Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_Alert__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vision Alerts</relationshipLabel>
        <relationshipName>Vision_Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GCP_Opportunity_Tracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Opportunity Tracker</label>
        <referenceTo>Phoenix_GCP_Opportunity_Tracker__c</referenceTo>
        <relationshipLabel>Vision Alerts</relationshipLabel>
        <relationshipName>Vision_Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GCP_SFDC_100pct_Analysis_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP SFDC 100pct Analysis SKU</label>
        <referenceTo>GCP_SFDC_100pct_Analysis_SKU__c</referenceTo>
        <relationshipLabel>Vision Alerts</relationshipLabel>
        <relationshipName>Vision_Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Alert_Type__c</fullName>
        <label>Alert Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GCP 100% Customer Analysis</fullName>
                </value>
                <value>
                    <fullName>DOH</fullName>
                </value>
                <value>
                    <fullName>Net Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_isActiveAlert__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActiveAlert</label>
        <type>Checkbox</type>
    </fields>
    <label>Vision Alert</label>
    <nameField>
        <label>Vision Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vision Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Vision_AlertCtrl.cls
public class Vision_AlertCtrl {
    public class alertWrapper{
        //Add your items here to return updated "Is Alerted" value back to UI
        @auraEnabled
        public Phoenix_GCP_Opportunity_Tracker__c gcpObj;
        @auraEnabled
        public GCP_SFDC_100pct_Analysis_SKU__c ndcObj;
        @auraEnabled
        public boolean isError = false;
        @auraEnabled
        public string errorMessage = '';
    }
    
    @AuraEnabled
    public static Vision_Alert__c fetchVisionAlertList(String recId, String recType, String accId){
        system.debug('rectype --> '+recType);
        //Add your own recType from Lightning component and add your own Query below to pull existing alerts.
        String query = 'SELECT '+Phoenix_Util.getsObjectFieds('Vision_Alert__c')+' FROM Vision_Alert__c';
        if(recType=='gcpItem')
            query += ' WHERE GCP_Opportunity_Tracker__c =: recId';
        else if(recType == 'ndcItem')
            query += ' WHERE GCP_SFDC_100pct_Analysis_SKU__c =: recId';
        else if(recType == 'accCalendar'){
            string queryItem = 'Account Calendar';
            query += ' WHERE Vision_Alert_Type__c =: queryItem AND Account__c =: accId';
        }
        list<Vision_Alert__c> visionAlertList = Database.query(query);
        system.debug('visionAlertList.size() ---> '+visionAlertList.size());
        if(visionAlertList.size() > 0)
            return visionAlertList[0];
        else{ 
            Vision_Alert__c alertObj = new Vision_Alert__c();
            return alertObj;
        }
    }
   @auraEnabled
    public static alertWrapper saveAlert(Vision_Alert__c alertObj, Account accObj, String recId, String itemType)
    {
        alertWrapper wrapObj = new alertWrapper();
        if(alertObj.id == null){
            if(itemType == 'accCalendar')
                alertObj.Name = 'Account Calendar - '+accObj.Name;
            else
                alertObj.Name = 'CxAnalysis - '+accObj.Name;
            if(itemType == 'gcpItem')
                alertObj.GCP_Opportunity_Tracker__c = recId;
            else if(itemType == 'ndcItem')
                alertObj.GCP_SFDC_100pct_Analysis_SKU__c = recId;
        }
        if(itemType == 'accCalendar')
            alertObj.Vision_Alert_Type__c = 'Account Calendar';
        else
            alertObj.Vision_Alert_Type__c = 'GCP 100% Customer Analysis';
        alertObj.Account__c = accObj.Id; 
        UPSERT alertObj; 
        //update your corresponding record if it's alert is activated or now and return the record to show in UI.
        if(itemType == 'gcpItem'){
            String query = 'SELECT '+Phoenix_Util.getsObjectFieds('Phoenix_GCP_Opportunity_Tracker__c')+' FROM Phoenix_GCP_Opportunity_Tracker__c WHERE Id =: recId';
            Phoenix_GCP_Opportunity_Tracker__c gcpObj = Database.query(query);
            gcpObj.Vision_isAlerted__c = alertObj.Vision_isActiveAlert__c;
            update gcpObj;
            wrapObj.gcpObj = gcpObj;
            return wrapObj;
        }
        else if(itemType == 'ndcItem'){
            String query = 'SELECT Vision_Product__r.Id,Vision_Product__r.Name, Vision_Product__r.Phoenix_NDC_11__c, '+Phoenix_Util.getsObjectFieds('GCP_SFDC_100pct_Analysis_SKU__c')+' FROM GCP_SFDC_100pct_Analysis_SKU__c WHERE Id =: recId';
            GCP_SFDC_100pct_Analysis_SKU__c ndcObj = Database.query(query);
            ndcObj.Vision_isAlerted__c = alertObj.Vision_isActiveAlert__c;
            update ndcObj;
            wrapObj.ndcObj = ndcObj;
            return wrapObj;
        } 
        else{
            wrapObj.isError =  false;
            wrapObj.errorMessage = 'Saved Successfully!';
            return wrapObj;
        }
    }
  
}