UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_Trade_Partner_DOH_Report__c.object
<CustomObject>
    <fields>
        <fullName>Package_Description__c</fullName>
        <label>Package Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Partner_Name__c</fullName>
        <label>Trade Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP Trade Partner DOH Report</label>
    <nameField>
        <displayFormat>GCP trade-rep-{0000000}</displayFormat>
        <label>GCP Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Trade Partner DOH Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Vision_GCP_Short_Date__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Customer_Name__c</fullName>
        <label>GCP Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP Short Date</label>
    <nameField>
        <displayFormat>GCP short-date-{0000000}</displayFormat>
        <label>GCP  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Short Date</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/Vision_GCP_Short_DateCls_Test.cls
@isTest
public class Vision_GCP_Short_DateCls_Test {
      static testmethod void  test(){
        //GCP_Trade_Partner_DOH_Report__c tradeDoH= new GCP_Trade_Partner_DOH_Report__c(Trade_Partner_Name__c='test Trade',Package_Description__c='testProduct');
    //insert tradeDoH;
    Vision_GCP_Short_Date__c visionShort=new Vision_GCP_Short_Date__c(GCP_Customer_Name__c='test');
          insert visionShort;
        Vision_GCP_Short_DateCls.getAccountGroups();
        Vision_GCP_Short_DateCls.getShortDateData('test');
         Vision_GCP_Short_DateCls.getFiltershortDate('test','test');
    }

}