UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_Trade_Partner_DOH_Report__c.object
<CustomObject>
    <fields>
        <fullName>Package_Description__c</fullName>
        <label>Package Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Partner_Name__c</fullName>
        <label>Trade Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>W3_DOH__c</fullName>
        <label>W3 DOH</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>GCP Trade Partner DOH Report</label>
    <nameField>
        <displayFormat>GCP trade-rep-{0000000}</displayFormat>
        <label>GCP Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Trade Partner DOH Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Vision_DoH_Summary_Batch_Test.cls
@isTest
public class Vision_DoH_Summary_Batch_Test {
    @testSetup static void setup() {
       List<Account> accList = new List<Account>();
        Account acc = new Account(Name = 'Test Record', accountNumber='12345');
        accList.add(acc);
        insert accList;
        
         GCP_Trade_Partner_DOH_Report__c tradeDoH= new GCP_Trade_Partner_DOH_Report__c(Trade_Partner_Name__c='test Trade',Package_Description__c='testProduct',W3_DOH__c=2);
          insert tradeDoH;
        
    }
    @isTest static void testMethod1() 
    {
        Test.startTest();
        Vision_DoH_Summary_Batch batch = new Vision_DoH_Summary_Batch();
        Database.executeBatch(batch);
        //
        //batch.execute(); 
        Test.stopTest();
        
    }
    @isTest static void testMethod2() 
    {
        Test.startTest();
        Database.executeBatch(new Vision_DoH_Summary_Batch());
        Test.stopTest();
        GCP_Trade_Partner_DOH_Report__c gcp = [ SELECT Id, Trade_Partner_Name__c, Package_Description__c FROM GCP_Trade_Partner_DOH_Report__c limit 1];
        
    } 
}