UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_SFDC_100pct_Analysis_SKU__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Drl_Act_Price__c</fullName>
        <label>GCP Drl Act Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Drl_Act_Sales__c</fullName>
        <label>GCP Drl Act Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Update_date__c</fullName>
        <label>GCP Update date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_isIncludeProduct__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Vision isIncludeProduct</label>
        <type>Checkbox</type>
    </fields>
    <label>GCP SFDC 100pct Analysis SKU</label>
    <nameField>
        <displayFormat>100PCT-Analysis-SKU-{00000}</displayFormat>
        <label>GCP SFDC 100pct Analysis SKU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP SFDC 100pct Analysis SKU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/UpdateRecordsBatchCls_TC.cls
@isTest
public class UpdateRecordsBatchCls_TC {
    static testmethod void test1() {
        Test.startTest();
        GCP_SFDC_100pct_Analysis_SKU__c newObj = new GCP_SFDC_100pct_Analysis_SKU__c();
        newObj.Vision_Update_Date__c = system.today();
        newObj.Vision_isIncludeProduct__c = true;
        insert newObj;
        
        Database.executeBatch(new UpdateRecordsBatchCls('GCP_SFDC_100pct_Analysis_SKU__c','Vision_isIncludeProduct__c','false','boolean'));
        Test.stopTest();
    }
    static testmethod void test2() {
        Test.startTest();
        GCP_SFDC_100pct_Analysis_SKU__c newObj = new GCP_SFDC_100pct_Analysis_SKU__c();
        newObj.Vision_Update_Date__c = system.today();
        newObj.Vision_isIncludeProduct__c = true;
        insert newObj;
        
        Database.executeBatch(new UpdateRecordsBatchCls('GCP_SFDC_100pct_Analysis_SKU__c','Vision_Update_Date__c',''+system.today(),'date'));
        Test.stopTest();
    }
    static testmethod void test3() {
        Test.startTest();
        GCP_SFDC_100pct_Analysis_SKU__c newObj = new GCP_SFDC_100pct_Analysis_SKU__c();
        newObj.Vision_Update_Date__c = system.today();
        newObj.Vision_Drl_Act_Price__c = 100;
        insert newObj;
        
        Database.executeBatch(new UpdateRecordsBatchCls('GCP_SFDC_100pct_Analysis_SKU__c','Vision_Drl_Act_Price__c','200','Integer'));
        Test.stopTest();
    }
    static testmethod void test4() {
        Test.startTest();
        GCP_SFDC_100pct_Analysis_SKU__c newObj = new GCP_SFDC_100pct_Analysis_SKU__c();
        newObj.Vision_Update_Date__c = system.today();
        newObj.Vision_Drl_Act_Sales__c = 100;
        insert newObj;
        
        Database.executeBatch(new UpdateRecordsBatchCls('GCP_SFDC_100pct_Analysis_SKU__c','Vision_Drl_Act_Sales__c','200','decimal'));
        Test.stopTest();
    }
}