UAT_AllStar_8Jan2024_0636/Backup-Source/objects/IDN_Charge_Back__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IDN Charge Back</relationshipLabel>
        <relationshipName>IDN_Charge_Back</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_1__c</fullName>
        <label>Child1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_2__c</fullName>
        <label>Child 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Description__c</fullName>
        <label>Contact Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hospital_Name__c</fullName>
        <label>Hospital Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Territory__c</fullName>
        <label>Sales Rep Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Settlement_Paid_Date__c</fullName>
        <label>Settlement Paid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>material_description__c</fullName>
        <label>Material Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>revised_product_family__c</fullName>
        <label>Revised Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IDN Charge Back</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>IDN Charge Back Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IDN Charge Back</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/IDN_Charge_Back_Hospital_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IDN Charge Back Hospital Summarys</relationshipLabel>
        <relationshipName>IDN_Charge_Back_Hospital_Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child1__c</fullName>
        <label>Child1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_2__c</fullName>
        <label>Child 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Description__c</fullName>
        <label>Contact Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hospital_Name__c</fullName>
        <label>Hospital Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Territory__c</fullName>
        <label>Sales Rep Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Settlement_Paid_Date__c</fullName>
        <label>Settlement Paid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>material_description__c</fullName>
        <label>Material Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>revised_product_family__c</fullName>
        <label>Revised Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IDN Charge Back Hospital Summary</label>
    <nameField>
        <displayFormat>IDN Chargeback-{0000}</displayFormat>
        <label>IDN Charge Back Hospital Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IDN Charge Back Hospital Summarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Vision_IDN_Tab2_Summary_Batch_test.cls
@istest
public class Vision_IDN_Tab2_Summary_Batch_test {

    public testmethod static void test1(){
           account acc1 = new account(name = 'acc1');
        List<IDN_Charge_Back__c> chargebackrecList = new List<IDN_Charge_Back__c>();
        IDN_Charge_Back__c rec1 = new  IDN_Charge_Back__c();
       rec1.Account__c = '0011K00002UrWG9QAN';
        rec1.Hospital_Name__c = 'University of Wisconsin Health (AKA UW Health)';
        rec1.Child_1__c = 'University Hospital';
        rec1.Child_2__c = 'None';
       	rec1.Sales_Rep_Territory__c = 'Zack McClard';
        rec1.Region__c = 'West';
        rec1.Category__c = 'GPO';
        rec1.revised_product_family__c = 'Thiotepa';
        rec1.material_description__c = 'Thiotepa For Injection 100mg/Vial 1s USA';
        rec1.Contact_Description__c = 'RCA-N';
        rec1.Settlement_Paid_Date__c = system.today();
        chargebackrecList.add(rec1);
        insert chargebackrecList;
      IDN_Charge_Back__c rec2 = new  IDN_Charge_Back__c();
       rec2.Account__c = '0011K00002UrWG9QAN';
        rec2.Hospital_Name__c = 'University of Wisconsin Health (AKA UW Health)';
        rec2.Child_1__c = 'University Hospital';
        rec2.Child_2__c = 'None';
       	rec2.Sales_Rep_Territory__c = 'Zack McClard';
        rec2.Region__c = 'West';
        rec2.Category__c = 'GPO';
        rec2.revised_product_family__c = 'Thiotepa';
        rec2.material_description__c = 'Thiotepa For Injection 100mg/Vial 1s USA';
        rec2.Contact_Description__c = 'RCA-N';
        rec2.Settlement_Paid_Date__c = system.today().addmonths(-1);
        insert rec2;
        IDN_Charge_Back_Hospital_Summary__c rec3 = new  IDN_Charge_Back_Hospital_Summary__c();
     
          IDN_Charge_Back_Hospital_Summary__c rec4 = new  IDN_Charge_Back_Hospital_Summary__c();
       rec4.Account__c = '0011K00002UrWG9QAN';
        rec4.Hospital_Name__c = 'University of Wisconsin Health (AKA UW Health)';
        rec4.Child1__c = 'University Hospital1';
        rec4.Child_2__c = 'None';
       	rec4.Sales_Rep_Territory__c = 'Zack McClard';
        rec4.Region__c = 'West';
        rec4.Category__c = 'GPi';
        rec4.revised_product_family__c = 'Thiotepa';
        rec4.material_description__c = 'Thiotepa For Injection 100mg/Vial 1s USA';
        rec4.Contact_Description__c = 'RCA-N';
        rec4.Settlement_Paid_Date__c = system.today().addyears(-1);
        insert rec4;
        test.startTest();
        database.executeBatch(new Vision_IDN_Tab2_Summary_Batch());
        test.stopTest();
    }
    
    public testmethod static void test2(){
           account acc1 = new account(name = 'acc1');
        List<IDN_Charge_Back__c> chargebackrecList = new List<IDN_Charge_Back__c>();
        IDN_Charge_Back__c rec1 = new  IDN_Charge_Back__c();
       rec1.Account__c = '0011K00002UrWG9QAN';
        rec1.Hospital_Name__c = 'University of Wisconsin Health (AKA UW Health)';
        rec1.Child_1__c = 'University Hospital';
        rec1.Child_2__c = 'None';
       	rec1.Sales_Rep_Territory__c = 'Zack McClard';
        rec1.Region__c = 'West';
        rec1.Category__c = 'GPO';
        rec1.revised_product_family__c = 'Thiotepa';
        rec1.material_description__c = 'Thiotepa For Injection 100mg/Vial 1s USA';
        rec1.Contact_Description__c = 'RCA-N';
        rec1.Settlement_Paid_Date__c = system.today();
        chargebackrecList.add(rec1);
          IDN_Charge_Back__c rec2 = new  IDN_Charge_Back__c();
       rec2.Account__c = '0011K00002UrWG9QAN';
        rec2.Hospital_Name__c = 'University of Wisconsin Health (AKA UW Health)';
        rec2.Child_1__c = 'University Hospital';
        rec2.Child_2__c = 'None';
       	rec2.Sales_Rep_Territory__c = 'Zack McClard';
        rec2.Region__c = 'West';
        rec2.Category__c = 'GPO';
        rec2.revised_product_family__c = 'Thiotepa';
        rec2.material_description__c = 'Thiotepa For Injection 100mg/Vial 1s USA';
        rec2.Contact_Description__c = 'RCA-N';
        rec2.Settlement_Paid_Date__c = system.today();
        insert rec2;
        insert chargebackrecList;
          IDN_Charge_Back_Hospital_Summary__c rec4 = new  IDN_Charge_Back_Hospital_Summary__c();
       rec4.Account__c = '0011K00002UrWG9QAN';
        rec4.Hospital_Name__c = 'University of Wisconsin Health (AKA UW Health)';
        rec4.Child1__c = 'University Hospital';
        rec4.Child_2__c = 'None';
       	rec4.Sales_Rep_Territory__c = 'Zack McClard';
        rec4.Region__c = 'West';
        rec4.Category__c = 'GPO';
        rec4.revised_product_family__c = 'Thiotepa';
        rec4.material_description__c = 'Thiotepa For Injection 100mg/Vial 1s USA';
        rec4.Contact_Description__c = 'RCA-N';
        rec4.Settlement_Paid_Date__c = system.today();
        insert rec4;
        
        Vision_IDN_Tab2_Summary_Batch.codecoverageBlock();
        test.startTest();
        database.executeBatch(new Vision_IDN_Tab2_Summary_Batch());
        test.stopTest();
    }
}