UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Job_Calendar__c.object
<CustomObject>
    <fields>
        <fullName>ApexClass_Name__c</fullName>
        <label>ApexClass Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Job Calendar</label>
    <nameField>
        <displayFormat>JC-{0000}</displayFormat>
        <label>Job Calendar No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/Scheduled_Job_Calendar_ClassTest.cls
/**
 * @Apex Class      : ScheduleJobCalendarClass
 * @description       : To fetch the all job calendar class
 * @author            : Ramakrishna Y
 * @group             : 
 * @last modified on  : 13-13-2022
 * @last modified by  : Ramakrishna Y
 * Modifications Loag 
**/
@isTest(SeeAllData=true)
private class Scheduled_Job_Calendar_ClassTest
{
   public static testMethod void ScheduledJobClassMethod() 
    {  
        // Create your test data
        Job_Calendar__c rt=new Job_Calendar__c();
        rt.ApexClass_Name__c='Test Apex';
        
        
    
        Test.StartTest();
        Scheduled_Job_Calendar_Class.getApeSyncObjAll();
        Scheduled_Job_Calendar_Class.getApeSyncObjCompleted();
        Scheduled_Job_Calendar_Class.getApeSyncObjFailed();
        Scheduled_Job_Calendar_Class.getApeSyncObjPending();
        Scheduled_Job_Calendar_Class.getApeSyncObjAborted();
        //testsche.getApeSyncObjAll();
        Test.stopTest();
         
         
    }
}