UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_12Months_Actual_Sales_Unit__c</fullName>
        <inlineHelpText>Rollup of last 12 months quantity</inlineHelpText>
        <label>12Months Actual Sales Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Dead_Net_Tracking_GR__c</fullName>
        <label>Dead Net(Tracking GR)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_NPR_Status__c</fullName>
        <label>NPR Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_NPR_Volume__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Throughput__c</fullName>
        <label>Actual Throughput $</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Throughput_per__c</fullName>
        <label>Actual Throughput %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Phoenix_Actual_Sales__c</fullName>
        <label>Actual Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Dead_Net_Price__c</fullName>
        <label>Dead Net Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_NPR_Data__c</fullName>
        <label>NPR Data</label>
        <referenceTo>Phoenix_NPR_Data__c</referenceTo>
        <relationshipLabel>NPR Volumes</relationshipLabel>
        <relationshipName>NPR_Volumes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <formula>IF(ISBLANK( Phoenix_NPR_Data__c ), &apos;&apos;, HYPERLINK(&quot;/lightning/r/&quot;+  Phoenix_NPR_Data__r.Phoenix_Product__r.Id
+&quot;/view?fv0=&quot;,Phoenix_NPR_Data__r.Phoenix_Product__r.Name))</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_Cost__c</fullName>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Volume__c</fullName>
        <label>Volume</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NPR Volume</label>
    <nameField>
        <label>NPR Volume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPR Volumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_NPR12MonthsSalesUnitRollup.cls
/*   Author      :  Mamatha Neela
Created Date:  15th April, 2021.
*/


public class Phoenix_NPR12MonthsSalesUnitRollup implements Database.Batchable<sObject>,Database.Stateful,Schedulable {
    public Phoenix_NPR12MonthsSalesUnitRollup() {
    }
    
    //schedule controller
    public void execute(SchedulableContext sc) {
        database.executeBatch(new Phoenix_NPR12MonthsSalesUnitRollup(),100);
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT'+ Phoenix_Util.nprDataFields+'FROM Phoenix_NPR_Data__c WHERE Phoenix_NPR_Status__c= \'Active\'';
        if(Test.isRunningTest()) query += ' Limit 1';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Phoenix_NPR_Data__c> nprData){
        List<Phoenix_NPR_Data__c> nprListData= new List<Phoenix_NPR_Data__c>();
        List<Phoenix_NPR_Volume__c> nprVolumeList= new List<Phoenix_NPR_Volume__c>();
        List<Date> dateList= new List<Date>();
        Map<Id,Phoenix_NPR_Data__c> nprMap= new Map<Id,Phoenix_NPR_Data__c>();
        date dateBefore;
        for (Phoenix_NPR_Data__c nprDataList : nprData){
            nprMap.put(nprDataList.Id,nprDataList);
        }
        for(Integer i=1;i<=12;i++){
            dateBefore=System.today().addMonths(-i).toStartOfMonth();
            dateList.add(dateBefore);
        }
        
        Map<Id,List<Phoenix_NPR_Volume__c>> nprVolMap =new Map<Id,List<Phoenix_NPR_Volume__c>>();
        Map<Product2,List<Phoenix_NPR_Data__c>> prodNPR= new Map<Product2,List<Phoenix_NPR_Data__c>>();
        for(Phoenix_NPR_Volume__c vol : [select id, Phoenix_Volume__c, Phoenix_NPR_Data__r.Phoenix_Dead_Net_Tracking_GR__c,Phoenix_NPR_Volume__c.Actual_Throughput__c,Phoenix_NPR_Data__r.Phoenix_Product__r.Phoenix_Throughput_Cost__c,Phoenix_NPR_Data__c,Phoenix_Dead_Net_Price__c from Phoenix_NPR_Volume__c where Phoenix_Date__c>=:dateList AND Phoenix_NPR_Data__c=:nprMap.keySet()]){
            
            System.debug('---------------vol--------'+vol);
            if(nprVolMap.containsKey(vol.Phoenix_NPR_Data__c)){
                List<Phoenix_NPR_Volume__c> existingNPRs = nprVolMap.get(vol.Phoenix_NPR_Data__c);
                existingNPRs.add(vol);
                nprVolMap.put(vol.Phoenix_NPR_Data__c,existingNPRs);
            }else{
                nprVolMap.put(vol.Phoenix_NPR_Data__c,new List<Phoenix_NPR_Volume__c>{vol}); 
            }
        }
        
        //NPR Volume Calculations
        List<Phoenix_NPR_Volume__c> nprVol=[select id,Phoenix_Volume__c,Phoenix_NPR_Volume__c.Actual_Throughput__c,Phoenix_Throughput_Cost__c,Phoenix_NPR_Data__r.Phoenix_Product__r.Phoenix_Throughput_cost__c,Phoenix_NPR_Data__c,Phoenix_NPR_Data__r.Phoenix_Dead_Net_Tracking_GR__c from Phoenix_NPR_Volume__c WHERE Phoenix_NPR_Data__c=:nprMap.Values()];
        for(Phoenix_NPR_Volume__c npr1:nprVol){
            if(npr1.Phoenix_NPR_Data__r.Phoenix_Dead_Net_Tracking_GR__c!=null ){
                npr1.Phoenix_Dead_Net_Price__c=npr1.Phoenix_NPR_Data__r.Phoenix_Dead_Net_Tracking_GR__c; 
                if(npr1.Phoenix_Volume__c!=null)
                    npr1.Phoenix_Actual_Sales__c=npr1.Phoenix_Dead_Net_Price__c*npr1.Phoenix_Volume__c;
                if(npr1.Phoenix_NPR_Data__r.Phoenix_Product__r.Phoenix_Throughput_cost__c!=null)
                    npr1.Phoenix_Throughput_Cost__c=npr1.Phoenix_NPR_Data__r.Phoenix_Product__r.Phoenix_Throughput_cost__c;
                if(npr1.Phoenix_Throughput_Cost__c!=null && npr1.Phoenix_Volume__c!=null)
                    npr1.Actual_Throughput__c=(npr1.Phoenix_Dead_Net_Price__c.setscale(2)-npr1.Phoenix_Throughput_Cost__c.setscale(2))*npr1.Phoenix_Volume__c;
                if(npr1.Phoenix_Actual_Sales__c!=0 && npr1.Phoenix_Actual_Sales__c!=null && npr1.Actual_Throughput__c!=null)
                    npr1.Actual_Throughput_per__c=(npr1.Actual_Throughput__c/npr1.Phoenix_Actual_Sales__c)*100;  
            }
            nprVolumeList.add(npr1);
        }
        
        for(Id np:nprMap.keySet()){
            Double salesUnit=0;
            if(nprVolMap.get(np)!=null){
                for(Phoenix_NPR_Volume__c  nprVolList :nprVolMap.get(np)){
                    if(nprVolList.Phoenix_Volume__c!=null ){// Processing the NPR Data which has last 12 months volume records
                        System.debug('----------1-----------');  
                        salesUnit+=nprVolList.Phoenix_Volume__c;
                    }
                }    
            }
            
            Phoenix_NPR_Data__c updatedNPR = new Phoenix_NPR_Data__c(id=np,Phoenix_12Months_Actual_Sales_Unit__c=salesUnit);
            nprListData.add(updatedNPR);
        }
        
        if(!nprListData.isEmpty()){
            update nprListData;   
        }
        if(!nprVolumeList.isEmpty()){
            update nprVolumeList;   
        }
    }
    public void finish(Database.BatchableContext BC){
        
    }
}