UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_User_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Group_Behavior__c</fullName>
        <label>Approval Group Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single User</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
                <value>
                    <fullName>Account based</fullName>
                </value>
                <value>
                    <fullName>Product based</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver_Group_Name__c</fullName>
        <label>Approver Group Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phoenix_Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Phoenix_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Phoenix_User_Approval_Matrix__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Approval User Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phoenix_User_Approval_Matrix__c</referenceTo>
        <relationshipLabel>User_Groups</relationshipLabel>
        <relationshipName>User_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Approval Matrix</label>
    <nameField>
        <label>User Approval Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/globalValueSets/Phoenix_Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Business Head</fullName>
    </customValue>
    <customValue>
        <fullName>Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Country Head</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Government Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Home Office</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Head</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead OTC</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead SRx</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sr Director or VP Finance</fullName>
    </customValue>
    <customValue>
        <fullName>SRx IPA Contracts Approver</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Demand Planning</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Marketing Head</fullName>
        <isActive>false</isActive>
        <label>Sales &amp; Marketing Head</label>
    </customValue>
    <customValue>
        <fullName>VP / Director Finance</fullName>
        <isActive>false</isActive>
        <label>VP / Director Finance</label>
    </customValue>
    <customValue>
        <fullName>SCM &amp; Marketing</fullName>
        <isActive>false</isActive>
        <label>SCM &amp; Marketing</label>
    </customValue>
    <masterLabel>Phoenix_Teams</masterLabel>
</GlobalValueSet>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/Phoenix_UserApprovalMatrix_Tgr_Test.cls
/**
 * @description       : 
 * @author            : Surender Dhruvsoft
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Dhruvsoft
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   25-05-2021   Surender Dhruvsoft   Initial Version
**/
@isTest
public class Phoenix_UserApprovalMatrix_Tgr_Test {
    static testmethod void test1() {
        try {
            Phoenix_TestDataCreator testData = new Phoenix_TestDataCreator();
            //testData.generateUsers();
            testData.generateApprovalMatrix();
            List < Phoenix_User_Approval_Matrix__c > groups = new List < Phoenix_User_Approval_Matrix__c > ();
            Phoenix_User_Approval_Matrix__c group1 = new Phoenix_User_Approval_Matrix__c(
                Phoenix_Approver_Group_Name__c = 'Sales', Phoenix_Approval_Group_Behavior__c = 'Team'
            );
            groups.add(group1);

            Phoenix_User_Approval_Matrix__c group2 = testData.approvalGroups[0];
            group2.Phoenix_Approver_Group_Name__c = 'Marketing';
            group2.Phoenix_Approval_Group_Behavior__c = 'Team';

            groups.add(group2);

            upsert group2;

            List < Phoenix_User_Approval_Matrix__c > users = new List < Phoenix_User_Approval_Matrix__c > ();
            Phoenix_User_Approval_Matrix__c user1 = new Phoenix_User_Approval_Matrix__c(
                User_Group__c = testData.approvalGroups[0].Id, Phoenix_Approver__c = UserInfo.getUserId()
            );

            users.add(user1);

            Phoenix_User_Approval_Matrix__c user2 = testData.approvalUsers[1];
            user2.User_Group__c = testData.approvalGroups[2].Id;
            user2.Phoenix_Approver__c = UserInfo.getUserId();


            users.add(user2);

            upsert users;







        } catch (Exception ex) {}


    }
}