UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_SAP_Customer_Staging__c.object
<CustomObject>
    <description>This will be used for SAP to send the Request and to update record in salesforce Internally.</description>
    <fields>
        <fullName>Phoenix_Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Parent_SAP_Customer_Code__c</fullName>
        <label>Parent SAP Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_SAP_Customer_Code__c</fullName>
        <label>SAP Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SAP Customer Staging</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>SAP Customer Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Customers Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_SAPCustomerStagingProcessorTest.cls
/**
 * @description       : 
 * @author            : Surender Dhruvsoft
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   25-05-2021   Surender Dhruvsoft   Initial Version
 **/
@isTest
public class Phoenix_SAPCustomerStagingProcessorTest {
    @isTest
    public static void nprStgngTest1() {
        Phoenix_SAP_Customer_Staging__c custStg = new Phoenix_SAP_Customer_Staging__c();
        custStg.Phoenix_Division__c = '40';
        custStg.Phoenix_Parent_SAP_Customer_Code__c = '1234567';
        custStg.Phoenix_SAP_Customer_Code__c = '123456';
        insert custStg;
        DataBase.executeBatch(new Phoenix_SAPCustomerStagingProcessorBatch());
        System.assertEquals(1, 1);
    }

}