UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Target_Exclusion_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Direct_Billing_Date__c</fullName>
        <label>Direct Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Direct_Customer_Name__c</fullName>
        <label>Direct Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direct_Product__c</fullName>
        <label>Direct Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Target Exclusion Summary</label>
    <nameField>
        <label>Target Exclusions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Exclusion Summarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/deleteDirectTgtExclusionSummaryBatchTest.cls
@isTest
public class deleteDirectTgtExclusionSummaryBatchTest {
    
    @isTest
    public static void test1()
    {
        Target_Exclusion_Summary__c t1 = new Target_Exclusion_Summary__c();
        t1.Direct_Billing_Date__c = system.today();
        t1.Direct_Customer_Name__c = 'test';
        t1.Direct_Product__c = 'test1';
        insert t1;
        
        Target_Exclusion_Summary__c t2 = new Target_Exclusion_Summary__c();
        t2.Direct_Billing_Date__c = system.today();
        t2.Direct_Customer_Name__c = 'test';
        t2.Direct_Product__c = 'test1';
        insert t2;
        
        
        Database.executeBatch(new deleteDirectTargetExclusionSummaryBatch());
    }
    

}