UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Target_Achieved_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>SRx Head</fullName>
                </value>
                <value>
                    <fullName>SRx Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>RSM Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>RSM Head</fullName>
                </value>
                <value>
                    <fullName>West RSM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financial_Year__c</fullName>
        <label>Financial Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initiator_Status__c</fullName>
        <label>Initiator Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intial_Approver__c</fullName>
        <label>Intial Approver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Head_Status__c</fullName>
        <label>Marketing Head Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_Head_Status__c</fullName>
        <label>RSM Head Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>East RSM Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RSM_West_Head_Status__c</fullName>
        <label>RSM West Head Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>West RSM Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SRx_Head_Status__c</fullName>
        <label>SRx Head Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>SRx Head Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Target Achieved Approval</label>
    <nameField>
        <label>Target Achieved Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Achieved Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/QuarterlyTargetRecordCreation_Test.cls
@isTest
public class QuarterlyTargetRecordCreation_Test 
{
  @isTest
    public static void testData(){
        Target_Achieved_Approval__c trgt = new Target_Achieved_Approval__c();
        trgt.Financial_Year__c = '2024';
        trgt.Quarter__c = 'Q2';
        trgt.Name = 'Test Target';
        trgt.Initiator_Status__c = 'Completed';
        trgt.Marketing_Head_Status__c = 'Not Initiated';
        trgt.SRx_Head_Status__c = 'Not Initiated';
        trgt.Approval_Status__c= 'RSM Head';
        trgt.RSM_Head_Status__c = 'In Process';
        trgt.RSM_West_Head_Status__c = 'In Process';
        trgt.Intial_Approver__c = 'Automatic BRIGHT';
       
        insert trgt;
        
        String cronExpression = '0 42 17 * * ? 2023';
        String jobId = System.schedule('QuarterlyTargetRecordCreation_Test', cronExpression, new QuarterlyTargetRecordCreation());
        
        CronTrigger cronTrigger = [SELECT Id, CronExpression, CronJobDetail.Name FROM CronTrigger WHERE Id = :jobId LIMIT 1];
        System.assertEquals(cronExpression, cronTrigger.CronExpression);
        //System.assertEquals('QuarterlyTargetRecordCreation', cronTrigger.CronJobDetail.Name);
    }
}