UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Account_Cooling_Period__c</fullName>
        <label>Account Cooling Period (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Reference_Contracts__c</fullName>
        <label>Contracts</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Proposed_ASP_Dose__c</fullName>
        <formula>Phoenix_Proposed_Sales__c / IF(Phoenix_SCM_Final_Approval__c,Phoenix_Total_SCM_Approved_Qty__c,Phoenix_Final_Total_Selling_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Proposed ASP/ Dose</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Bid_Line_Created_Date__c</fullName>
        <label>Bid Line Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Bid_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid Line Item</label>
        <referenceTo>Phoenix_Bid_Line_Item__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Account_Cooling_Period_Days__c</fullName>
        <label>Account Cooling Period Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Bid_Created_Date__c</fullName>
        <label>Bid Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_Bid_Name__c</fullName>
        <label>Bid Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Product_Status__c</fullName>
        <label>Contract Product Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_In_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Bid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_In_Cooling_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Cooling Period</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <formula>Vision_Product_Code__c+&quot;_&quot;+Vision_Contract_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Identifier</label>
        <type>Text</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/BidLineContractProductStatusBatchCls.cls
public class BidLineContractProductStatusBatchCls implements Database.Batchable < sObject > , Database.Stateful,Schedulable,Database.AllowsCallouts {
    public void execute(SchedulableContext sc) {
        //Database.executeBatch(new BidLineContractProductStatusBatchCls());
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //Query - If a New Account has become bid account in last 24 Hours
        //String query = 'Select Phoenix_Product__r.ProductCode, Phoenix_Contract__r.Phoenix_Contract_Number__c, Phoenix_Bid__r.Phoenix_Approval_Status__c,Phoenix_Bid__r.Name,Phoenix_Bid__r.createdDate,' +Phoenix_Util.getsObjectFieds('Phoenix_Bid_Line_Item__c')+' from Phoenix_Bid_Line_Item__c Where Phoenix_Bid__r.Phoenix_Approval_Status__c != \'Draft\' and CreatedDate = LAST_N_DAYS:1';
        String query = 'Select Phoenix_Product__r.ProductCode, Phoenix_Contract__r.Phoenix_Contract_Number__c, Phoenix_Bid__r.Phoenix_Approval_Status__c,Phoenix_Bid__r.Name,Phoenix_Bid__r.createdDate, ' +Phoenix_Util.getsObjectFieds('Phoenix_Bid_Line_Item__c')+' from Phoenix_Bid_Line_Item__c Where Phoenix_Bid__r.Phoenix_Approval_Status__c != \'Draft\'';
        if(Test.isRunningTest())query += ' LIMIT 1';
        return Database.getQueryLocator(query);
        
    }
    public void execute(Database.BatchableContext BC, List <Phoenix_Bid_Line_Item__c> bidLineItemList) {
        try{
            if(bidLineItemList.size() > 0){
                List<Vision_Customer_Product_Tracker__c> existingCusPrdTrkRecs = new List<Vision_Customer_Product_Tracker__c>();
                Map<Id,list<Phoenix_Bid_Line_Item__c>> existingBidRecsMap = new Map<Id,list<Phoenix_Bid_Line_Item__c>>();
                for(Phoenix_Bid_Line_Item__c bidLine:bidLineItemList){
                    if (!existingBidRecsMap.containsKey(bidLine.Phoenix_Bid__c)){
                        existingBidRecsMap.put(bidLine.Phoenix_Bid__c,new list<Phoenix_Bid_Line_Item__c>{bidLine});
                    }
                    else{
                        existingBidRecsMap.get(bidLine.Phoenix_Bid__c).add(bidLine);
                    }
                }
                map<String, Phoenix_Bid__c > UniqueIdsMap = new map<String, Phoenix_Bid__c >();
                map<String, Phoenix_Bid_Line_Item__c> existingBidLineItemRecs = new map<String, Phoenix_Bid_Line_Item__c>();
                for(Phoenix_Bid__c bid: [select Id,Phoenix_Reference_Contracts__c,createdDate,Name,Phoenix_Customer__r.Phoenix_Account_Cooling_Period__c from Phoenix_Bid__c where id in : existingBidRecsMap.keySet()]){
                    if (existingBidRecsMap.containsKey(bid.Id)){
                        for(Phoenix_Bid_Line_Item__c bidLineItem : existingBidRecsMap.get(bid.Id)){
                            if(bid.Phoenix_Reference_Contracts__c != null){
                                List<String> refContractsList = bid.Phoenix_Reference_Contracts__c.split(',');
                                for(String cntrNum : refContractsList){
                                    if(bidLineItem.Phoenix_Product__r.ProductCode != null && String.isNotBlank(cntrNum)){
                                        UniqueIdsMap.put(bidLineItem.Phoenix_Product__r.ProductCode+'_'+cntrNum, bid);
                                        existingBidLineItemRecs.put(bidLineItem.Phoenix_Product__r.ProductCode+'_'+cntrNum, bidLineItem);
                                    }
                                }
                            }
                        }
                    }
                }
                
                for(Vision_Customer_Product_Tracker__c CPT :[select Id,Vision_In_Cooling_Period__c,Vision_Account_Cooling_Period_Days__c,Vision_In_Bid__c,Vision_Contract_Product_Status__c,Vision_Unique_Identifier__c,Bid_Line_Created_Date__c,Bid_Line_Item__c, Vision_Bid__c, Vision_Bid_Created_Date__c , Vision_Bid_Name__c from Vision_Customer_Product_Tracker__c Where Vision_Unique_Identifier__c in : existingBidLineItemRecs.keySet()]){
                    if(existingBidLineItemRecs.containsKey(CPT.Vision_Unique_Identifier__c)){ 
                        CPT.Vision_Contract_Product_Status__c ='In Bid';
                        CPT.Vision_In_Bid__c = true;
                        //CPT.Vision_Temp_Awarded_Value__c = existingBidLineItemRecs.get(CPT.Vision_Unique_Identifier__c).Phoenix_Proposed_ASP_Dose__c;
                        CPT.Bid_Line_Created_Date__c = existingBidLineItemRecs.get(CPT.Vision_Unique_Identifier__c).createdDate;
                        CPT.Bid_Line_Item__c = existingBidLineItemRecs.get(CPT.Vision_Unique_Identifier__c).Id;
                        if(UniqueIdsMap.containsKey(CPT.Vision_Unique_Identifier__c)){
                            CPT.Vision_Bid__c = UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).Id; 
                            CPT.Vision_Bid_Created_Date__c = UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).createdDate;
                            CPT.Vision_Bid_Name__c = UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).Name;
                            Integer diffDateVal = (system.today()).daysBetween(Date.valueOf(UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).createdDate));
                            if(String.valueOf(diffDateVal).contains('-')){
                                String diffDateValString = String.valueOf(diffDateVal).replace('-','');
                                diffDateVal = Integer.valueOf(diffDateValString);
                            }
                            if(UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).Phoenix_Customer__c != null && UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).Phoenix_Customer__r.Phoenix_Account_Cooling_Period__c != null){
                                if(diffDateVal <= UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).Phoenix_Customer__r.Phoenix_Account_Cooling_Period__c){
                                    CPT.Vision_Account_Cooling_Period_Days__c = UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).Phoenix_Customer__r.Phoenix_Account_Cooling_Period__c - diffDateVal;
                                    CPT.Vision_In_Cooling_Period__c = true;
                                }
                                else{
                                    CPT.Vision_Account_Cooling_Period_Days__c = diffDateVal - UniqueIdsMap.get(CPT.Vision_Unique_Identifier__c).Phoenix_Customer__r.Phoenix_Account_Cooling_Period__c;
                                    CPT.Vision_In_Cooling_Period__c = false;
                                }
                            }
                        }
                        existingCusPrdTrkRecs.add(CPT);
                    }
                }
                if(existingCusPrdTrkRecs.size() > 0){
                    update existingCusPrdTrkRecs;
                }
            }
            else{
                system.debug('---No Records to Process---');
            }
        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'BidLineContractProductStatusBatchCls', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
    public void finish(Database.BatchableContext BC) {
        if(!Test.isRunningTest())
        	Database.executeBatch(new BidLineRejectedContractPrdStatusBatchCls(),2000);
    }
    
}