UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Is_Bid_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick to make the customer visible for Bid Creation</inlineHelpText>
        <label>Is Bid Account</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product_Pipeline__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Pipelines</relationshipLabel>
        <relationshipName>Product_Pipelines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>SRx</fullName>
                </value>
                <value>
                    <fullName>OTC</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Pipeline</label>
    <nameField>
        <displayFormat>Pipeline-{00000}</displayFormat>
        <label>Pipeline No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/VisionProductPipelineCls_Test.cls
@isTest
public class VisionProductPipelineCls_Test {
    static testmethod void  test1(){
        Account acc = new Account();
        acc.Name='Alphine Health';
        acc.Phoenix_Is_Bid_Account__c = true;
        acc.OwnerId = userInfo.getUserId();
        insert acc;
        Product_Pipeline__c pipe = new Product_Pipeline__c();
        pipe.Vision_Segment__c ='Rx';
        pipe.Account__c = acc.Id;
        insert pipe;
        Product_Pipeline__c pipe1 = new Product_Pipeline__c();
        pipe1.Vision_Segment__c ='Rx';
        pipe1.Account__c = acc.Id;
        insert pipe1;
        Product_Pipeline__c pipe2 = new Product_Pipeline__c();
        pipe2.Vision_Segment__c ='Rx';
        pipe2.Account__c = acc.Id;
        insert pipe2;
          
        Attachment attach=new Attachment();   	
    	attach.Name='Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=acc.Id;
        insert attach;
    	
    	List<Attachment> attachments=[select id, name from Attachment where parent.Id=:acc.Id];
        
        VisionProductPipelineCls.getAccountInPreview(acc.Id);
        VisionProductPipelineCls.getProductPipelines();
        VisionProductPipelineCls.fetchSortResults('Vision_Segment__c', true,new List<Product_Pipeline__c>{pipe,pipe1});
        VisionProductPipelineCls.getSearch(new List<Product_Pipeline__c>{pipe,pipe1}, 'Rx', new List<String>{'Rx','SRx'});
      VisionProductPipelineCls.getAccounts();
        VisionProductPipelineCls.getOTCData(new List<Product_Pipeline__c>{pipe,pipe1});
        Map<String , boolean> testMap = new Map<String , boolean>();
        testMap.put('alp',true);
        VisionProductPipelineCls.getFilterAccounts('alp', testMap);
         list < string > RxSrxList1 = new list < string > ();
        RxSrxList1.add('Rx');
        RxSrxList1.add('SRx');
         string search = 'Test';
      //VisionProductPipelineCls.findBySrxOtc(RxSrxList1, search, new List<Product_Pipeline__c>{pipe,pipe1});
        //VisionProductPipelineCls.generateDocument(new List<Product_Pipeline__c>{pipe,pipe1}, new List<String>{acc.Id},new List<String>{'Vision_Segment__c'});
        VisionProductPipelineCls.generateDocument(new List<Product_Pipeline__c>{pipe,pipe1});
        VisionProductPipelineCls.getOTCData(new List<Product_Pipeline__c>{pipe,pipe1});
    }
}