UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Name__c</fullName>
        <label>Bid Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Initial Order Discount for WAC Customers (No-Contract Price Offering)</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                    <label>One Time Buy – Good Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                    <label>One Time Buy – Short Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>One Time Buy Good Dated Shelf Life for New Product Launch</fullName>
                    <label>One Time Buy – Good Dated Shelf Life for New Product Launch</label>
                </value>
                <value>
                    <fullName>OTC New Product</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Good Dated</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Short Dated</fullName>
                </value>
                <value>
                    <fullName>OTC Price Change</fullName>
                </value>
                <value>
                    <fullName>OTC Product Addition</fullName>
                </value>
                <value>
                    <fullName>OTC Rebate Change</fullName>
                </value>
                <value>
                    <fullName>OTC RFP</fullName>
                </value>
                <value>
                    <fullName>OTC Volume Review</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                    <label>Product Removals</label>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>Sales Out Rebate</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                    <label>SRx Direct Pricing</label>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                    <label>SRx IPA Floor Pricing Update</label>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                    <label>SRx IPA Member Addition</label>
                </value>
                <value>
                    <fullName>SRx IPA Price Change</fullName>
                </value>
                <value>
                    <fullName>SRx IPA Product Addition</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                    <label>SRx NEW Individual Pricing Agreement (IPA)</label>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                    <label>SRx RCA/IPA Member GPO or Wholesaler Change</label>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                    <label>SRx RCA Member Addition</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Response_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response Line</label>
        <referenceTo>Phoenix_Customer_Response_Line__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response</label>
        <referenceTo>Phoenix_Customer_Response__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Customer_Response__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Name__c</fullName>
        <formula>Phoenix_Bid_No__r.Phoenix_Bid_Name__c</formula>
        <label>Bid Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Responses</relationshipLabel>
        <relationshipName>Customer_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Response</label>
    <nameField>
        <displayFormat>CR-{0000000}</displayFormat>
        <label>Customer Response No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Customer_Response_Line__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Customer Response Lines</relationshipLabel>
        <relationshipName>Customer_Response_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response</label>
        <referenceTo>Phoenix_Customer_Response__c</referenceTo>
        <relationshipLabel>Customer Response Lines</relationshipLabel>
        <relationshipName>Customer_Response_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to store GCP Product Family</description>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Customer Response Lines</relationshipLabel>
        <relationshipName>Customer_Response_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Response Line</label>
    <nameField>
        <displayFormat>CRLineItem-{0000000}</displayFormat>
        <label>Customer Response Line No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Response Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Rx_SRx_OTC__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Rx/SRx/OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OTC</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>SRx</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Supply_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipName>Did_Not_Bid_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supply Issue</label>
    <nameField>
        <displayFormat>Supply Issue-{000000}</displayFormat>
        <label>Supply Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/Vision_COLO_Controller_Test.cls
@isTest
public class Vision_COLO_Controller_Test {
    static testmethod void  test(){
        
        Product_Family__c prodFamily = new Product_Family__c();
        prodFamily.Name = 'Test Family';
        insert prodFamily;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u = new User(Alias = 'standt', Email='testmmm@testorg.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='testmmm@testorg.com', Division='Rx');
        insert u;
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Owner = u;
        insert acc;
        Product2 prod = new Product2();
        prod.Name = 'Test Product';
        prod.ProductCode = '1234567';
        prod.Phoenix_Rx_SRx_OTC__c = 'Rx';
        prod.Family = 'Test Family';
        insert prod;    
        Product2 prod2 = new Product2();
        prod2.Name = 'Test Product2';
        prod2.ProductCode = '1234568';
        prod2.Phoenix_Rx_SRx_OTC__c = 'SRx';
        prod2.Family = 'Test Family2';
        insert prod2; 
        
        Phoenix_Contract__c cont = new Phoenix_Contract__c();
        cont.Name = 'Test';
        cont.Phoenix_Contract_Number__c = '1234';
        cont.Phoenix_Customer__c = acc.Id;
        insert cont;
        
        Date d1=Date.newInstance(2022,01,01);
        Date d2=Date.newInstance(2022,03,31);
        
        Phoenix_Customer_Response__c custResponse = new Phoenix_Customer_Response__c();
        insert custResponse;
        Phoenix_Customer_Response_Line__c custResponseLine = new Phoenix_Customer_Response_Line__c();
        custResponseLine.Phoenix_Customer_Response__c = custResponse.Id;
        insert custResponseLine;
        
        Phoenix_Bid__c bid = new Phoenix_Bid__c();
        bid.Phoenix_Bid_Name__c = 'Test Bid';
        bid.Phoenix_Bid_Type__c = 'Product Addition';
        bid.OwnerId = u.Id;
        bid.Phoenix_Customer_Type__c = 'Net Indirect Pricing';
        bid.Phoenix_Customer__c = acc.id;
        bid.Phoenix_Approval_Status__c = 'Closed';
        bid.Phoenix_Bid_Closed_Date__c = Date.newInstance(2022,02,01);
        bid.Phoenix_Bid_Submitted_Date__c = Date.newInstance(2022,01,01);
        bid.Phoenix_Sent_to_Customer_Date__c = Date.newInstance(2022,01,01);
        insert bid;

        Phoenix_Bid_Line_Item__c bidLine = new Phoenix_Bid_Line_Item__c();
        bidLine.Phoenix_Bid__c = bid.id;
        bidLine.Phoenix_Customer_Response_Line__c = custResponseLine.Id;
        bidLine.Phoenix_Product__c = prod.Id;
        bidLine.Phoenix_Contract__c = cont.Id;
        bidLine.Phoenix_Bid_Status__c = '';
        bidLine.Phoenix_Proposed_Sales__c = 1000;
        bidLine.Phoenix_Current_Direct_Price__c = 100;
        bidLine.Finance_Current_Sales__c = 100;
        insert bidLine;
        
        custResponse.Phoenix_Bid_No__c = bid.Id;
        upsert custResponse;
        
        custResponseLine.Phoenix_Bid__c = bid.Id;
        custResponseLine.Phoenix_Bid_Line_Item__c = bidLine.Id;
        custResponseLine.Phoenix_Bid_Status__c = 'Awarded';
        custResponseLine.Phoenix_Customer_Response__c = custResponse.Id;
        upsert custResponseLine;

        Phoenix_Customer_Response__c custResponse2 = new Phoenix_Customer_Response__c();
        insert custResponse2;
        Phoenix_Customer_Response_Line__c custResponseLine2 = new Phoenix_Customer_Response_Line__c();
        custResponseLine2.Phoenix_Customer_Response__c = custResponse2.Id;
        insert custResponseLine2;
        
        Phoenix_Bid__c bid2 = new Phoenix_Bid__c();
        bid2.Phoenix_Bid_Name__c = 'Test Bid';
        bid2.Phoenix_Bid_Type__c = 'New Product Launch';
        bid2.OwnerId = u.Id;
        bid2.Phoenix_Customer_Type__c = 'Net Indirect Pricing';
        bid2.Phoenix_Customer__c = acc.id;
        bid2.Phoenix_Approval_Status__c = 'Closed';
        bid2.Phoenix_Bid_Closed_Date__c = Date.newInstance(2022,02,01);
        bid2.Phoenix_Bid_Submitted_Date__c = Date.newInstance(2022,01,01);
        bid2.Phoenix_Sent_to_Customer_Date__c = Date.newInstance(2022,01,01);
        insert bid2;

        Phoenix_Bid_Line_Item__c bidLine2 = new Phoenix_Bid_Line_Item__c();
        bidLine2.Phoenix_Bid__c = bid2.id;
        bidLine2.Phoenix_Customer_Response_Line__c = custResponseLine2.Id;
        bidLine2.Phoenix_Product__c = prod.Id;
        bidLine2.Phoenix_Contract__c = cont.Id;
        bidLine2.Phoenix_Bid_Status__c = '';
        bidLine2.Phoenix_Proposed_Sales__c = 1000;
        bidLine2.Phoenix_Current_Direct_Price__c = 100;
        bidLine2.Finance_Current_Sales__c = 200;
        insert bidLine2;
        
        custResponse2.Phoenix_Bid_No__c = bid2.Id;
        upsert custResponse2;
        
        custResponseLine2.Phoenix_Bid__c = bid2.Id;
        custResponseLine2.Phoenix_Bid_Line_Item__c = bidLine2.Id;
        custResponseLine2.Phoenix_Bid_Status__c = 'Awarded';
        custResponseLine2.Phoenix_Customer_Response__c = custResponse2.Id;
        upsert custResponseLine2;

        
        Phoenix_Customer_Response__c custResponse3 = new Phoenix_Customer_Response__c();
        insert custResponse3;
        Phoenix_Customer_Response_Line__c custResponseLine3 = new Phoenix_Customer_Response_Line__c();
        custResponseLine3.Phoenix_Customer_Response__c = custResponse3.Id;
        insert custResponseLine3;
        
        Phoenix_Bid__c bid3 = new Phoenix_Bid__c();
        bid3.Phoenix_Bid_Name__c = 'Test Bid';
        bid3.Phoenix_Bid_Type__c = 'Price Change';
        bid3.OwnerId = u.Id;
        bid3.Phoenix_Customer_Type__c = 'Net Indirect Pricing';
        bid3.Phoenix_Customer__c = acc.id;
        bid3.Phoenix_Approval_Status__c = 'Closed';
        bid3.Phoenix_Bid_Closed_Date__c = Date.newInstance(2022,02,01);
        bid3.Phoenix_Bid_Submitted_Date__c = Date.newInstance(2022,01,01);
        bid3.Phoenix_Sent_to_Customer_Date__c = Date.newInstance(2022,01,01);
        insert bid3;
        
        Phoenix_Bid_Line_Item__c bidLine3 = new Phoenix_Bid_Line_Item__c();
        bidLine3.Phoenix_Bid__c = bid3.id;
        bidLine3.Phoenix_Customer_Response_Line__c = custResponseLine3.Id;
        bidLine3.Phoenix_Product__c = prod.Id;
        bidLine3.Phoenix_Contract__c = cont.Id;
        bidLine3.Phoenix_Bid_Status__c = '';
        bidLine3.Phoenix_Proposed_Sales__c = 1000;
        bidLine3.Phoenix_Current_Direct_Price__c = 100;
        bidLine3.Finance_Current_Sales__c = 200;
        insert bidLine3;
        
        custResponse3.Phoenix_Bid_No__c = bid3.Id;
        upsert custResponse3;
        
        custResponseLine3.Phoenix_Bid__c = bid3.Id;
        custResponseLine3.Phoenix_Bid_Line_Item__c = bidLine3.Id;
        custResponseLine3.Phoenix_Bid_Status__c = 'Awarded';
        custResponseLine3.Phoenix_Customer_Response__c = custResponse3.Id;
        upsert custResponseLine3;
        
        Supply_Issue__c supIssue = new Supply_Issue__c();
        supIssue.Product_Family__c = prodFamily.Id;
        insert supIssue;
        
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {1}, new List<Integer> {2022}, 'Rx', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {1}, new List<Integer> {2022}, 'Rx+SRx', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {1}, new List<Integer> {2022}, 'Rx+OTC', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {1}, new List<Integer> {2022}, 'SRx+OTC', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {1}, new List<Integer> {2022}, 'SRx', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {1}, new List<Integer> {2022}, 'OTC', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {1}, new List<Integer> {2022}, 'All', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {2}, new List<Integer> {2022}, 'Rx', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {2}, new List<Integer> {2022}, 'Rx+SRx', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {2}, new List<Integer> {2022}, 'Rx+OTC', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {2}, new List<Integer> {2022}, 'SRx+OTC', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {2}, new List<Integer> {2022}, 'SRx', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {2}, new List<Integer> {2022}, 'OTC', '');
        Vision_COLO_Controller.getDataBasedOnQuarter(new List<Integer> {2}, new List<Integer> {2022}, 'All', '');
        Vision_COLO_Controller.getUserName(u.Id);
        Vision_COLO_Controller.upsertRecords(supIssue);
        Vision_COLO_Controller.getExistingSupplyIssues(new List<String> {prodFamily.Name});
        //Vision_COLO_Controller.codeCoverage();
    }

}