UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Add_ABS_Value__c</fullName>
        <label>Add ABS Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Phoenix_Dead_Net_Tracking_GR__c</fullName>
        <label>Dead Net(Tracking GR)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_NPR_Status__c</fullName>
        <label>NPR Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_NPR_Volume__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <formula>IF(ISBLANK( Phoenix_NPR_Data__c ), &apos;&apos;, HYPERLINK(&quot;/lightning/r/&quot;+ Phoenix_NPR_Data__r.Phoenix_Contract__r.Id
  +&quot;/view?fv0=&quot;,Phoenix_NPR_Data__r.Phoenix_Contract__r.Name))</formula>
        <label>Contract</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <formula>IF(ISBLANK( Phoenix_NPR_Data__c ), &apos;&apos;, HYPERLINK(&quot;/lightning/r/&quot;+ Phoenix_NPR_Data__r.Phoenix_Contract__r.Phoenix_Customer__r.Id
  +&quot;/view?fv0=&quot;, Phoenix_NPR_Data__r.Phoenix_Contract__r.Phoenix_Customer__r.Name ))</formula>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_NPR_Data__c</fullName>
        <label>NPR Data</label>
        <referenceTo>Phoenix_NPR_Data__c</referenceTo>
        <relationshipLabel>NPR Volumes</relationshipLabel>
        <relationshipName>NPR_Volumes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <formula>IF(ISBLANK( Phoenix_NPR_Data__c ), &apos;&apos;, HYPERLINK(&quot;/lightning/r/&quot;+  Phoenix_NPR_Data__r.Phoenix_Product__r.Id
+&quot;/view?fv0=&quot;,Phoenix_NPR_Data__r.Phoenix_Product__r.Name))</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_Cost__c</fullName>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Volume__c</fullName>
        <label>Volume</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NPR Volume</label>
    <nameField>
        <label>NPR Volume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPR Volumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_NPR12MonthsSalesUnitRollupTest.cls
/**
 * @description       : 
 * @author            : Surender Patel (Dhruvsoft)
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
@isTest
public class Phoenix_NPR12MonthsSalesUnitRollupTest {
    @isTest
    public static void setupTestData1() {
        Account acc = new Account();
        acc.Name = 'Test';
        acc.AccountNumber = '1234';
        insert acc;
        Product2 pro = new Product2();
        pro.Name = 'Test';
        pro.Family = 'Test';
        pro.Phoenix_Throughput_cost__c = 2;
        pro.ProductCode = '30000001';
        insert pro;

        Phoenix_Contract__c cont = new Phoenix_Contract__c();
        cont.Name = 'Test';
        cont.Phoenix_Contract_Number__c = '1234';
        cont.Phoenix_Customer__c = acc.Id;
        insert cont;

        Phoenix_NPR_Data__c npr = new Phoenix_NPR_Data__c();
        npr.Phoenix_Account__c = acc.Id;
        npr.Phoenix_Contract__c = cont.Id;
        npr.Phoenix_Product__c = pro.Id;
        npr.Phoenix_Add_ABS_Value__c = 2.00;
        npr.Phoenix_NPR_Status__c = 'Active';
        npr.Phoenix_Dead_Net_Tracking_GR__c = 2;
        insert npr;

        Phoenix_NPR_Volume__c nprVol = new Phoenix_NPR_Volume__c();
        nprVol.Phoenix_NPR_Data__c = npr.Id;
        nprVol.Phoenix_Volume__c = 10;
        nprVol.Phoenix_Date__c = System.today().addMonths(-1).toStartOfMonth();
        nprVol.Name = 'test';
        insert nprVol;

        Phoenix_NPR12MonthsSalesUnitRollup processProd = new Phoenix_NPR12MonthsSalesUnitRollup();
        Test.startTest();
        DataBase.executeBatch(processProd);
        Test.stopTest();
    }
}