UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contracts_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contracts Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Phoenix_Contracts_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Deadline_Date__c</fullName>
        <label>Customer Bid Deadline Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Initial Order Discount for WAC Customers (No-Contract Price Offering)</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                    <label>One Time Buy – Good Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                    <label>One Time Buy – Short Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>One Time Buy Good Dated Shelf Life for New Product Launch</fullName>
                    <label>One Time Buy – Good Dated Shelf Life for New Product Launch</label>
                </value>
                <value>
                    <fullName>OTC New Product</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Good Dated</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Short Dated</fullName>
                </value>
                <value>
                    <fullName>OTC Price Change</fullName>
                </value>
                <value>
                    <fullName>OTC Product Addition</fullName>
                </value>
                <value>
                    <fullName>OTC Rebate Change</fullName>
                </value>
                <value>
                    <fullName>OTC RFP</fullName>
                </value>
                <value>
                    <fullName>OTC Volume Review</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                    <label>Product Removals</label>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>Sales Out Rebate</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                    <label>SRx Direct Pricing</label>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                    <label>SRx IPA Floor Pricing Update</label>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                    <label>SRx IPA Member Addition</label>
                </value>
                <value>
                    <fullName>SRx IPA Price Change</fullName>
                </value>
                <value>
                    <fullName>SRx IPA Product Addition</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                    <label>SRx NEW Individual Pricing Agreement (IPA)</label>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                    <label>SRx RCA/IPA Member GPO or Wholesaler Change</label>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                    <label>SRx RCA Member Addition</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Bid_Deadline_Date_Time__c</fullName>
        <label>Customer Bid Deadline Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Bid_Deadline_Time__c</fullName>
        <defaultValue>&quot;6:00 PM&quot;</defaultValue>
        <label>Customer Bid Deadline Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>12:00 AM</fullName>
                </value>
                <value>
                    <fullName>12:15 AM</fullName>
                </value>
                <value>
                    <fullName>12:30 AM</fullName>
                </value>
                <value>
                    <fullName>12:45 AM</fullName>
                </value>
                <value>
                    <fullName>1:00 AM</fullName>
                </value>
                <value>
                    <fullName>1:15 AM</fullName>
                </value>
                <value>
                    <fullName>1:30 AM</fullName>
                </value>
                <value>
                    <fullName>1:45 AM</fullName>
                </value>
                <value>
                    <fullName>2:00 AM</fullName>
                </value>
                <value>
                    <fullName>2:15 AM</fullName>
                </value>
                <value>
                    <fullName>2:30 AM</fullName>
                </value>
                <value>
                    <fullName>2:45 AM</fullName>
                </value>
                <value>
                    <fullName>3:00 AM</fullName>
                </value>
                <value>
                    <fullName>3:15 AM</fullName>
                </value>
                <value>
                    <fullName>3:30 AM</fullName>
                </value>
                <value>
                    <fullName>3:45 AM</fullName>
                </value>
                <value>
                    <fullName>4:00 AM</fullName>
                </value>
                <value>
                    <fullName>4:15 AM</fullName>
                </value>
                <value>
                    <fullName>4:30 AM</fullName>
                </value>
                <value>
                    <fullName>4:45 AM</fullName>
                </value>
                <value>
                    <fullName>5:00 AM</fullName>
                </value>
                <value>
                    <fullName>5:15 AM</fullName>
                </value>
                <value>
                    <fullName>5:30 AM</fullName>
                </value>
                <value>
                    <fullName>5:45 AM</fullName>
                </value>
                <value>
                    <fullName>6:00 AM</fullName>
                </value>
                <value>
                    <fullName>6:15 AM</fullName>
                </value>
                <value>
                    <fullName>6:30 AM</fullName>
                </value>
                <value>
                    <fullName>6:45 AM</fullName>
                </value>
                <value>
                    <fullName>7:00 AM</fullName>
                </value>
                <value>
                    <fullName>7:15 AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Bid_Deadline_Time_zone__c</fullName>
        <defaultValue>&quot;EST&quot;</defaultValue>
        <label>Customer Bid Deadline Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phoenix_Timezone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Type__c</fullName>
        <label>Bid Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABC Pharmagen</fullName>
                </value>
                <value>
                    <fullName>ABC Progen</fullName>
                </value>
                <value>
                    <fullName>BASE/DSH</fullName>
                </value>
                <value>
                    <fullName>ClarusOne</fullName>
                </value>
                <value>
                    <fullName>Costco</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Direct and Indirect</fullName>
                </value>
                <value>
                    <fullName>Econdisc</fullName>
                </value>
                <value>
                    <fullName>Government Pricing</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Net Indirect Pricing</fullName>
                </value>
                <value>
                    <fullName>ROS</fullName>
                </value>
                <value>
                    <fullName>RXSS</fullName>
                </value>
                <value>
                    <fullName>Sams Club</fullName>
                </value>
                <value>
                    <fullName>Walgreens</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Contracts Approved</fullName>
                </value>
                <value>
                    <fullName>SCM Approved</fullName>
                </value>
                <value>
                    <fullName>Marketing Approved</fullName>
                </value>
                <value>
                    <fullName>Finance Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Submitted</fullName>
                </value>
                <value>
                    <fullName>Proposal Accepted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/globalValueSets/Phoenix_Timezone.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PST</fullName>
    </customValue>
    <customValue>
        <fullName>EST</fullName>
    </customValue>
    <customValue>
        <fullName>CST</fullName>
    </customValue>
    <customValue>
        <fullName>America/Los_Angeles</fullName>
        <isActive>false</isActive>
        <label>(GMT-08:00/-7:00) Pacific Standard / Daylight Time (America/Los_Angeles)</label>
    </customValue>
    <customValue>
        <fullName>America/New_York</fullName>
        <isActive>false</isActive>
        <label>(GMT-5:00/-04:00) Eastern  Standard / Daylight Time (America/New_York)</label>
    </customValue>
    <masterLabel>Phoenix_Timezone</masterLabel>
</GlobalValueSet>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_CustomReportControllerTest.cls
@isTest
public class Phoenix_CustomReportControllerTest {
    static testmethod void controllerMethod(){
        Account testAccount = new Account(Name = 'Test Account');
        testAccount.Phoenix_Contracts_Approver__c = Userinfo.getUserId();
        insert testAccount;
        Phoenix_Bid__c pb1 = new Phoenix_Bid__c();
        pb1.Phoenix_Status__c = 'New';
        pb1.Phoenix_Comments__c = 'Test Comments';
        pb1.Phoenix_Customer__c = testAccount.Id;
        pb1.Phoenix_Customer_Bid_Deadline_Date_Time__c = DateTime.now();
        pb1.Phoenix_Customer_Bid_Deadline_Time_zone__c = 'PST';
        pb1.Phoenix_Customer_Bid_Deadline_Time__c = '6 PM';
        pb1.Phoenix_Customer_Type__c = 'Direct and Indirect';
        pb1.Phoenix_Bid_Deadline_Date__c = System.today();
        pb1.Phoenix_Bid_Type__c = 'RFP Bids';
        pb1.Phoenix_Approval_Status__c = 'Closed';
        pb1.Phoenix_Bid_Submitted_Date__c = system.today()-1;// DateTime.now()-1;
        insert pb1;
        
        Phoenix_Bid__c pb2 = new Phoenix_Bid__c();
        pb2.Phoenix_Status__c = 'New';
        pb2.Phoenix_Comments__c = 'Test Comments';
        pb2.Phoenix_Customer__c = testAccount.Id;
        pb2.Phoenix_Customer_Bid_Deadline_Date_Time__c = DateTime.now();
        pb2.Phoenix_Customer_Bid_Deadline_Time_zone__c = 'PST';
        pb2.Phoenix_Customer_Bid_Deadline_Time__c = '6 PM';
        pb2.Phoenix_Customer_Type__c = 'Direct and Indirect';
        pb2.Phoenix_Bid_Deadline_Date__c = System.today();
        pb2.Phoenix_Bid_Type__c = 'RFP Bids';
        pb2.Phoenix_Approval_Status__c = 'Closed';
        pb2.Phoenix_Bid_Submitted_Date__c = system.today()-1;// DateTime.now()-1;
        insert pb2;
        
        Phoenix_Bid__c pb3 = new Phoenix_Bid__c();
        pb3.Phoenix_Status__c = 'New';
        pb3.Phoenix_Comments__c = 'Test Comments';
        pb3.Phoenix_Customer__c = testAccount.Id;
        pb3.Phoenix_Customer_Bid_Deadline_Date_Time__c = DateTime.now();
        pb3.Phoenix_Customer_Bid_Deadline_Time_zone__c = 'PST';
        pb3.Phoenix_Customer_Bid_Deadline_Time__c = '6 PM';
        pb3.Phoenix_Customer_Type__c = 'Direct and Indirect';
        pb3.Phoenix_Bid_Deadline_Date__c = System.today();
        pb3.Phoenix_Bid_Type__c = 'RFP Bids';
        pb3.Phoenix_Approval_Status__c = 'Closed';
     //   pb1.Phoenix_Bid_Submitted_Date__c = DateTime.now()-1;
        insert pb3;
        
        Phoenix_Bid__c pb4 = new Phoenix_Bid__c();
        pb4.Phoenix_Status__c = 'New';
        pb4.Phoenix_Comments__c = 'Test Comments';
        pb4.Phoenix_Customer__c = testAccount.Id;
        pb4.Phoenix_Customer_Bid_Deadline_Date_Time__c = DateTime.now();
        pb4.Phoenix_Customer_Bid_Deadline_Time_zone__c = 'PST';
        pb4.Phoenix_Customer_Bid_Deadline_Time__c = '6 PM';
        pb4.Phoenix_Customer_Type__c = 'Direct and Indirect';
        pb2.Phoenix_Bid_Deadline_Date__c = System.today();
        pb4.Phoenix_Bid_Type__c = 'RFP Bids';
        pb4.Phoenix_Approval_Status__c = 'Closed';
        pb4.Phoenix_Bid_Submitted_Date__c = system.today()-1;// DateTime.now()-1;
        insert pb4;
        
        Product2 p2 = new Product2();
        p2.Family = 'Daptomycin Inj 500mg US';
        p2.Name = 'Test';
        p2.ProductCode = '300029858';
        p2.Phoenix_Marketing_Lead__c = UserInfo.getUserId();
        p2.Phoenix_Product_Director__c = UserInfo.getUserId(); 
        insert p2;
        Product2 p3 = new Product2();
        p3.Family = 'Abiraterone Acetate Tab';
        p3.ProductCode = '300029858';
        p3.Name = 'Test Product';
        p3.Phoenix_Product_Director__c = UserInfo.getUserId();
        p3.Phoenix_Marketing_Lead__c = UserInfo.getUserId();
        p3.Phoenix_Product_Director__c = UserInfo.getUserId();
        insert p3;
        
        Phoenix_Bid_Line_Item__c pb1bl = new Phoenix_Bid_Line_Item__c();
        pb1bl.Phoenix_Bid__c = pb1.Id;
        pb1bl.Phoenix_Current_Direct_Price__c = 10;
        pb1bl.Phoenix_Product_Code1__c = '300029858';
        pb1bl.Phoenix_Product_Family1__c = 'Daptomycin Inj 500mg US';
        pb1bl.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb1bl.Phoenix_Product__c = p2.Id;
        pb1bl.Phoenix_Final_Status__c = 'Approved';
        pb1bl.Phoenix_SCM_Approval_Y_N__c = 'Y- Only Current Monthly Demand Approved';
        pb1bl.Phoenix_Marketing_Final_Approval__c = true;
        insert pb1bl;
        
        Phoenix_Bid_Line_Item__c pb1bl1 = new Phoenix_Bid_Line_Item__c();
        pb1bl1.Phoenix_Bid__c = pb1.Id;
        pb1bl1.Phoenix_Final_Status__c = 'Approved';
        pb1bl1.Phoenix_Current_Direct_Price__c = 10;
        pb1bl1.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb1bl1.Phoenix_Product__c = p3.Id;
        pb1bl1.Phoenix_SCM_Approval_Y_N__c = 'Y- Only Current Monthly Demand Approved';
        pb1bl1.Phoenix_Marketing_Final_Approval__c = true;
        insert pb1bl1;
        
        Phoenix_Bid_Line_Item__c pb1bl2 = new Phoenix_Bid_Line_Item__c();
        pb1bl2.Phoenix_Bid__c = pb1.Id;
        pb1bl2.Phoenix_Final_Status__c = 'Approved';
        pb1bl2.Phoenix_Current_Direct_Price__c = 10;
        pb1bl2.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb1bl2.Phoenix_Product__c = p3.Id;
        pb1bl2.Phoenix_SCM_Approval_Y_N__c = 'N- Not Approved';
        pb1bl2.Phoenix_Marketing_Final_Approval__c = true;
        insert pb1bl2;
        
        Phoenix_Bid_Line_Item__c pb2bl = new Phoenix_Bid_Line_Item__c();
        pb2bl.Phoenix_Bid__c = pb2.Id;
        pb2bl.Phoenix_Current_Direct_Price__c = 10;
        pb2bl.Phoenix_Product_Code1__c = '300029858';
        pb2bl.Phoenix_Product_Family1__c = 'Daptomycin Inj 500mg US';
        pb2bl.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb2bl.Phoenix_Product__c = p2.Id;
        pb2bl.Phoenix_Final_Status__c = 'Approved';
        pb2bl.Phoenix_SCM_Approval_Y_N__c = 'Y- Only Current Monthly Demand Approved';
        pb2bl.Phoenix_Marketing_Final_Approval__c = true;
        insert pb2bl;
        
        Phoenix_Bid_Line_Item__c pb2bl1 = new Phoenix_Bid_Line_Item__c();
        pb2bl1.Phoenix_Bid__c = pb2.Id;
        pb2bl1.Phoenix_Final_Status__c = 'Approved';
        pb2bl1.Phoenix_Current_Direct_Price__c = 10;
        pb2bl1.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb2bl1.Phoenix_Product__c = p3.Id;
        pb2bl1.Phoenix_SCM_Approval_Y_N__c = 'Y- Only Current Monthly Demand Approved';
        pb2bl1.Phoenix_Marketing_Final_Approval__c = true;
        insert pb2bl1;
        
        Phoenix_Bid_Line_Item__c pb2bl2 = new Phoenix_Bid_Line_Item__c();
        pb2bl2.Phoenix_Bid__c = pb2.Id;
        pb2bl2.Phoenix_Final_Status__c = 'Approved';
        pb2bl2.Phoenix_Current_Direct_Price__c = 10;
        pb2bl2.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb2bl2.Phoenix_Product__c = p3.Id;
        pb2bl2.Phoenix_SCM_Approval_Y_N__c = 'N- Not Approved';
        pb2bl2.Phoenix_Marketing_Final_Approval__c = true;
        insert pb2bl2;
        
        Phoenix_Bid_Line_Item__c pb3bl = new Phoenix_Bid_Line_Item__c();
        pb3bl.Phoenix_Bid__c = pb3.Id;
        pb3bl.Phoenix_Current_Direct_Price__c = 10;
        pb3bl.Phoenix_Product_Code1__c = '300029858';
        pb3bl.Phoenix_Product_Family1__c = 'Daptomycin Inj 500mg US';
        pb3bl.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb3bl.Phoenix_Product__c = p2.Id;
        pb3bl.Phoenix_Final_Status__c = 'Approved';
        pb3bl.Phoenix_SCM_Approval_Y_N__c = 'Y- Only Current Monthly Demand Approved';
        pb3bl.Phoenix_Marketing_Final_Approval__c = true;
        insert pb3bl;
        
        Phoenix_Bid_Line_Item__c pb3bl1 = new Phoenix_Bid_Line_Item__c();
        pb3bl1.Phoenix_Bid__c = pb3.Id;
        pb3bl1.Phoenix_Final_Status__c = 'Approved';
        pb3bl1.Phoenix_Current_Direct_Price__c = 10;
        pb3bl1.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb3bl1.Phoenix_Product__c = p3.Id;
        pb3bl1.Phoenix_SCM_Approval_Y_N__c = 'Y- Only Current Monthly Demand Approved';
        pb3bl1.Phoenix_Marketing_Final_Approval__c = true;
        insert pb3bl1;
        
        Phoenix_Bid_Line_Item__c pb3bl2 = new Phoenix_Bid_Line_Item__c();
        pb3bl2.Phoenix_Bid__c = pb3.Id;
        pb3bl2.Phoenix_Final_Status__c = 'Approved';
        pb3bl2.Phoenix_Current_Direct_Price__c = 10;
        pb3bl2.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb3bl2.Phoenix_Product__c = p3.Id;
        pb3bl2.Phoenix_SCM_Approval_Y_N__c = 'N- Not Approved';
        pb3bl2.Phoenix_Marketing_Final_Approval__c = true;
        insert pb3bl2;
        
        Phoenix_Bid_Line_Item__c pb4bl = new Phoenix_Bid_Line_Item__c();
        pb4bl.Phoenix_Bid__c = pb4.Id;
        pb4bl.Phoenix_Current_Direct_Price__c = 10;
        pb4bl.Phoenix_Product_Code1__c = '300029858';
        pb4bl.Phoenix_Product_Family1__c = 'Daptomycin Inj 500mg US';
        pb4bl.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb4bl.Phoenix_Product__c = p2.Id;
        pb4bl.Phoenix_Final_Status__c = 'Approved';
        pb4bl.Phoenix_SCM_Approval_Y_N__c = 'Y- Only Current Monthly Demand Approved';
        pb4bl.Phoenix_Marketing_Final_Approval__c = true;
        insert pb4bl;
        
        Phoenix_Bid_Line_Item__c pb4bl1 = new Phoenix_Bid_Line_Item__c();
        pb4bl1.Phoenix_Bid__c = pb4.Id;
        pb4bl1.Phoenix_Final_Status__c = 'Approved';
        pb4bl1.Phoenix_Current_Direct_Price__c = 10;
        pb4bl1.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb4bl1.Phoenix_Product__c = p3.Id;
        pb4bl1.Phoenix_SCM_Approval_Y_N__c = 'Y- Only Current Monthly Demand Approved';
        pb4bl1.Phoenix_Marketing_Final_Approval__c = true;
        insert pb4bl1;
        
        Phoenix_Bid_Line_Item__c pb4bl2 = new Phoenix_Bid_Line_Item__c();
        pb4bl2.Phoenix_Bid__c = pb4.Id;
        pb4bl2.Phoenix_Final_Status__c = 'Approved';
        pb4bl2.Phoenix_Current_Direct_Price__c = 10;
        pb4bl2.Phoenix_Current_Indirect_Selling_Unit__c = 10;
        pb4bl2.Phoenix_Product__c = p3.Id;
        pb4bl2.Phoenix_SCM_Approval_Y_N__c = 'N- Not Approved';
        pb4bl2.Phoenix_Marketing_Final_Approval__c = true;
        insert pb4bl2;
        
        Date dt1 = System.today()-1;
        Date dt2 = System.today();
        Date dt3 = System.today()-2;
        Date dt4 = System.today()-1;
        Phoenix_CustomReportController.getRelatedList(dt1, dt2);
        Phoenix_CustomReportController.getRelatedList(dt3, dt4);
    }
}