UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_SFDC_Indirect_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Contract_ID__c</fullName>
        <label>GCP Contract ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>GCP SFDC Indirect Sales</relationshipLabel>
        <relationshipName>GCP_SFDC_Indirect_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Material_Number__c</fullName>
        <label>GCP Material Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_NDC__c</fullName>
        <label>GCP NDC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GCP SFDC Indirect Sales</relationshipLabel>
        <relationshipName>GCP_SFDC_Indirect_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GCP SFDC Indirect Sales</label>
    <nameField>
        <displayFormat>Indirect-Sales-{00000}</displayFormat>
        <label>GCP SFDC Indirect Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP SFDC Indirect Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Is_Exclude_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is Exclude Bid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <inlineHelpText>National Drug Code: SAP field</inlineHelpText>
        <label>NDC - 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/GooglesfdcInDirectSalesFetchTest.cls
@istest
public class GooglesfdcInDirectSalesFetchTest {
    static testmethod void Setup(){
        Account a= new Account();
        a.Name='test';
        a.AccountNumber='123';
        insert a;
        Product2 p=new Product2();
        p.Name='abc pharma';
        p.IsActive=true;
        p.Phoenix_Is_Exclude_Bid__c=false;
        p.Phoenix_NDC__c='123';
        P.ProductCode = '12122321';
        P.Phoenix_NDC_11__c = '35345435';
        
        
        insert p;
         Phoenix_Contract__c ctr = new Phoenix_Contract__c();
        ctr.Name = 'Test Contract';
        ctr.Phoenix_Contract_Number__c = '46579';
        ctr.Phoenix_Customer__c = a.Id;
        insert ctr;
        GCP_SFDC_Indirect_Sales__c ids = new GCP_SFDC_Indirect_Sales__c();
             ids.Vision_Product__c=p.id;
             ids.Vision_Contract__c=ctr.id;
             ids.Vision_Contract_ID__c='46579';
             ids.Vision_NDC__c='123';
             ids.Vision_Material_Number__c='123';
             insert ids;
        GCP_SFDC_Indirect_Sales__c ids1 = new GCP_SFDC_Indirect_Sales__c();
             ids1.Vision_Product__c=p.id;
             ids1.Vision_Contract__c=ctr.id;
             ids1.Vision_Contract_ID__c='46579';
             ids1.Vision_NDC__c='123';
             insert ids1;
        test.startTest();
         GoogleSFDCInDirectSalesFetch b = new GoogleSFDCInDirectSalesFetch();
        Database.executeBatch(new GoogleSFDCInDirectSalesFetch(1,1));
        Database.executeBatch(b);
        test.stopTest();
    }
}