UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Approval_Process_Step__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Matrix__c</fullName>
        <label>Approval Matrix</label>
        <referenceTo>Phoenix_Approval_Matrix__c</referenceTo>
        <relationshipLabel>Approval Process Steps</relationshipLabel>
        <relationshipName>Phoenix_Approval_Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approval Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid_Process_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_PHS_Price_Change__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PHS Price Change</label>
        <referenceTo>Phoenix_PHS_Price_Change__c</referenceTo>
        <relationshipLabel>Bid Process Steps</relationshipLabel>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bid Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_12Months_Sales_Unit__c</fullName>
        <label>12Months Sales Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bonafied_G_N_Indicator__c</fullName>
        <label>Bonafied G/N Indicator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <label>NDC-11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NPR_Status__c</fullName>
        <label>NPR Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Rebate_G_N_Indicator__c</fullName>
        <label>Rebate G/N Indicator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_PHS_Price_Change__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Contracts</fullName>
                </value>
                <value>
                    <fullName>Closed-Country Head</fullName>
                </value>
                <value>
                    <fullName>Closed-Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Closed-Customer Service</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Closed-Finance</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing &amp; Finance</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing Lead SRx</fullName>
                </value>
                <value>
                    <fullName>Closed-Sales &amp; Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Closed-SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Closed-Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Closed-SRx IPA Contracts Approver</fullName>
                </value>
                <value>
                    <fullName>Closed-Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Closed-Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Country Head</fullName>
                </value>
                <value>
                    <fullName>Country Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Home Office</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>PHS Price Changes</relationshipLabel>
        <relationshipName>PHS_Price_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_PHS_Price_Change_Name__c</fullName>
        <label>PHS Price Change Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PHS Price Change</label>
    <nameField>
        <displayFormat>Price Change - {000000}</displayFormat>
        <label>PHS Price Change Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PHS Price Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_PHS_Price_Change_Line__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <label>NDC-11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_PHS_Price_Change__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PHS Price Change</label>
        <referenceTo>Phoenix_PHS_Price_Change__c</referenceTo>
        <relationshipLabel>PHS Price Change Lines</relationshipLabel>
        <relationshipName>PHS_Price_Change_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>PHS Price Change Lines</relationshipLabel>
        <relationshipName>PHS_Price_Change_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PHS Price Change Line</label>
    <nameField>
        <displayFormat>PHS-{000000}</displayFormat>
        <label>PHS Price Change Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PHS Price Change Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_User_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Group_Behavior__c</fullName>
        <label>Approval Group Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single User</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
                <value>
                    <fullName>Account based</fullName>
                </value>
                <value>
                    <fullName>Product based</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver_Group_Name__c</fullName>
        <label>Approver Group Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phoenix_Teams</valueSetName>
        </valueSet>
    </fields>
    <label>User Approval Matrix</label>
    <nameField>
        <label>User Approval Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Approval Matrix</pluralLabel>
    <recordTypes>
        <fullName>Approval_User_Group</fullName>
        <active>true</active>
        <description>This will be used to manage different approver teams and their approval behavior.</description>
        <label>Approval User Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Approval_Users</fullName>
        <active>true</active>
        <label>Approval Users</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_GPI_Generic_Product_Identifier__c</fullName>
        <description>It contains 14 characters.</description>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GPI (Generic Product Identifier)  </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Rx_SRx_OTC__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Rx/SRx/OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OTC</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>SRx</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Special_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Special Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/globalValueSets/Phoenix_Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Business Head</fullName>
    </customValue>
    <customValue>
        <fullName>Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Country Head</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Government Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Home Office</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Head</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead OTC</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead SRx</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sr Director or VP Finance</fullName>
    </customValue>
    <customValue>
        <fullName>SRx IPA Contracts Approver</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Demand Planning</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Marketing Head</fullName>
        <isActive>false</isActive>
        <label>Sales &amp; Marketing Head</label>
    </customValue>
    <customValue>
        <fullName>VP / Director Finance</fullName>
        <isActive>false</isActive>
        <label>VP / Director Finance</label>
    </customValue>
    <customValue>
        <fullName>SCM &amp; Marketing</fullName>
        <isActive>false</isActive>
        <label>SCM &amp; Marketing</label>
    </customValue>
    <masterLabel>Phoenix_Teams</masterLabel>
</GlobalValueSet>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_PHSControllerClassTest.cls
@isTest
public class Phoenix_PHSControllerClassTest {
    static testmethod void AddPHSMethod() {
        
         List < Phoenix_User_Approval_Matrix__c > approvalGroups = new List < Phoenix_User_Approval_Matrix__c > ();
        List < Phoenix_User_Approval_Matrix__c > approvalUsers = new List < Phoenix_User_Approval_Matrix__c > ();
        List < User > users = new List < User > ();
        List < Phoenix_Approval_Matrix__c > bidMatrixList = new List < Phoenix_Approval_Matrix__c > ();
        
        list < Product2 > prodList = new list < Product2 > ();
        Product2 prod1 = new Product2(Name = 'Test Product', Phoenix_Rx_SRx_OTC__c = 'Rx', Phoenix_Special_Product__c = true, Phoenix_GPI_Generic_Product_Identifier__c = '11111', Phoenix_NDC_11__c = '12345678902', Family = 'Test Family', IsActive = TRUE);
        Product2 prod2 = new Product2(Name = 'Test Product1', Phoenix_Rx_SRx_OTC__c = 'Rx', Phoenix_Special_Product__c = true, Phoenix_GPI_Generic_Product_Identifier__c = '22222', Phoenix_NDC_11__c = '21345678902', Family = 'Sample Family', IsActive = TRUE);
        Product2 prod3 = new Product2(Name = 'Test Product2', Phoenix_Rx_SRx_OTC__c = 'SRx', Phoenix_Special_Product__c = true, Phoenix_NDC_11__c = '32145678902', Family = ' cetirizine', IsActive = TRUE);
        Product2 prod4 = new Product2(Name = 'Test Product3', Phoenix_Rx_SRx_OTC__c = 'OTC', Phoenix_Special_Product__c = true, Phoenix_GPI_Generic_Product_Identifier__c = '333333', Family = ' cetirizine', IsActive = TRUE);
        
        prodList.add(prod1);
        prodList.add(prod2);
        prodList.add(prod3);
        prodList.add(prod4);
        insert prodList;   
        Phoenix_Contract__c Cntrct = new Phoenix_Contract__c();
        Cntrct.name = 'taest cntrct';
        Cntrct.Phoenix_Contract_Number__c = '223';
        insert Cntrct;
        
         Phoenix_NPR_Data__c nprdat = new Phoenix_NPR_Data__c();
        nprdat.Phoenix_Contract__c = Cntrct.id;
        nprdat.Phoenix_NPR_Status__c = 'Active';
        nprdat.Phoenix_Contract_Number__c = '223';
        nprdat.Phoenix_Product__c = prod1.id;
        nprdat.Phoenix_12Months_Sales_Unit__c = 200;
        nprdat.Phoenix_Contract_Type__c = 'Direct';
        nprdat.Phoenix_Rebate_G_N_Indicator__c = '10N+ 0G';
        nprdat.Phoenix_Bonafied_G_N_Indicator__c = '5N+0G';
        insert nprdat;
        
        
        Phoenix_PHS_Price_Change__c testNDC=new Phoenix_PHS_Price_Change__c();
        testNDC.Phoenix_Approval_Status__c='Draft';   
        testNDC.Phoenix_PHS_Price_Change_Name__c    ='testRecord';
        testNDC.Phoenix_Contract__c=Cntrct.iD;
        
        insert testNDC;
        
         list < Phoenix_PHS_Price_Change_Line__c > lineItemsList = new list < Phoenix_PHS_Price_Change_Line__c > ();
        Phoenix_PHS_Price_Change_Line__c pbl1=new Phoenix_PHS_Price_Change_Line__c();
        pbl1.Phoenix_PHS_Price_Change__c=testNDC.Id;
      
        pbl1.Phoenix_Product_Name__c = prod1.id;
        
        
        lineItemsList.add(pbl1);
        Phoenix_PHS_Price_Change_Line__c pbl2=new Phoenix_PHS_Price_Change_Line__c();
        pbl2.Phoenix_PHS_Price_Change__c	=testNDC.Id;
     
        pbl2.Phoenix_Product_Name__c = prod2.id;
      
        lineItemsList.add(pbl2);
        insert lineItemsList;
        
        Attachment attach=new Attachment();   	
    	attach.Name='Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=testNDC.Id;
        insert attach;
    	
    	List<Attachment> attachments=[select id, name from Attachment where parent.Id=:testNDC.Id];
        
        ContentVersion contentVersionInsert = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersionInsert;
        ContentVersion contentVersionSelect = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersionInsert.Id LIMIT 1];
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        System.assertEquals(documents.size(), 1);
        
        Phoenix_PHSControllerClass.fetchRecordTypeValues('Phoenix_PHS_Price_Change__c');
        Phoenix_PHSControllerClass.getDataFromCustomSettings();
          Phoenix_PHSControllerClass.getProductInfo(prod1.id);
          Phoenix_PHSControllerClass.savePriceChangeLine(testNDC.Id,lineItemsList);
          Phoenix_PHSControllerClass.getNPRData(Cntrct.Id, Cntrct.Id);
       Phoenix_PHSControllerClass.getDocs(testNDC.Id);
        Phoenix_PHSControllerClass.deleteAttachments(attachments[0].Id);
        Phoenix_PHSControllerClass.updatePHSChangeLineItems(lineItemsList);
        Phoenix_PHSControllerClass.csvFileRead(contentVersionSelect.ContentDocumentId);
        Phoenix_PHSControllerClass.getProducts(new list<string>{prod1.Id,prod2.Id,prod3.Id,prod4.Id});
        Phoenix_PHSControllerClass.getupdatedforExport(lineItemsList[1].Id);
        Phoenix_PHSControllerClass.getRelatedList(testNDC.Id);
          Phoenix_PHSControllerClass.getPriceChangeData(testNDC.Id);
          Phoenix_PHSControllerClass.getPriceChangeLineData(testNDC.Id);
            Phoenix_PHSControllerClass.getChangeLineQuarterly(testNDC.Id, testNDC.Id);
        Phoenix_PHSControllerClass.getSubmitBidInfo(testNDC.Id);
        Phoenix_PHSControllerClass.submitToProceddStep1(testNDC.Id);
         Phoenix_PHSControllerClass.makeApprovals(testNDC.Id,lineItemsList,true,true,false);
        Phoenix_PHSControllerClass.makeApprovals(testNDC.Id,lineItemsList,true,false,true);
        
        
         if (approvalGroups.size() == 0) {
            Phoenix_User_Approval_Matrix__c group1 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Sales', Phoenix_Approval_Group_Behavior__c = 'Single User');
            approvalGroups.add(group1);
            Phoenix_User_Approval_Matrix__c group2 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Supply Chain', Phoenix_Approval_Group_Behavior__c = 'Team');
            approvalGroups.add(group2);
            Phoenix_User_Approval_Matrix__c group3 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Marketing', Phoenix_Approval_Group_Behavior__c = 'Product based');
            approvalGroups.add(group3);
            
            Phoenix_User_Approval_Matrix__c group4 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Sr Director or VP Finance', Phoenix_Approval_Group_Behavior__c = 'Team');
            approvalGroups.add(group4);
            Phoenix_User_Approval_Matrix__c group5 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Contracts', Phoenix_Approval_Group_Behavior__c = 'Account based');
            approvalGroups.add(group5);
            
            insert approvalGroups;
        }
        if (approvalUsers.size() == 0) {
            if (users.size() == 0) {
                Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
                String uid = ('Phoenix' + System.now().getTime()).SubString(0, 8);
                User u1 = new User(Alias = uid, Email = uid + '@phoenix.com', EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/New_York', UserName = uid + '@phoenix.com');
                
                
                users.add(u1);
                
                
                insert users;
            }
            Phoenix_User_Approval_Matrix__c userApp1 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[0].Id);
            approvalUsers.add(userApp1);
            Phoenix_User_Approval_Matrix__c userApp2 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = users[0].Id, User_Group__c = approvalGroups[2].Id);
            approvalUsers.add(userApp2);
            Phoenix_User_Approval_Matrix__c userApp3 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[1].Id);
            approvalUsers.add(userApp3);
            Phoenix_User_Approval_Matrix__c userApp4 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[2].Id);
            approvalUsers.add(userApp4);
            Phoenix_User_Approval_Matrix__c userApp5 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[3].Id);
            approvalUsers.add(userApp5);
            Phoenix_User_Approval_Matrix__c userApp6 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[4].Id);
            approvalUsers.add(userApp6);
            
            insert approvalUsers;
        }
        
        
        
        
        Phoenix_Approval_Matrix__c matrix5 = new Phoenix_Approval_Matrix__c(Phoenix_Bid_Type__c = 'PHS Price Change');
        bidMatrixList.add(matrix5);
        insert bidMatrixList;
        
        List < Phoenix_Approval_Process_Step__c > stepsList = new List < Phoenix_Approval_Process_Step__c > ();
        // List<String> bidTypes = new List<String>(){'RFP Bids','VIP Rebate','Customer Requested Pricing Confirmations','RCA Member Addition','NEW Individual Pricing Agreement (IPA)'};
        for (Phoenix_Approval_Matrix__c matrix: bidMatrixList) {
            Phoenix_Approval_Process_Step__c rfpStep1 = new Phoenix_Approval_Process_Step__c(Name = 'Initial Submission', Phoenix_Order__c = 1, Phoenix_Is_Notification_Only__c = false, Phoenix_Approval_Matrix__c = matrix.Id);
            stepsList.add(rfpStep1);
            Phoenix_Approval_Process_Step__c rfpStep2 = new Phoenix_Approval_Process_Step__c(Name = 'Sr Director or VP Finance Approval', Phoenix_Order__c = 2, Phoenix_Is_Notification_Only__c = false, Phoenix_Approver_Team__c = 'Sr Director or VP Finance', Phoenix_Approval_Matrix__c = matrix.Id);
            stepsList.add(rfpStep2);
           
             Phoenix_Approval_Process_Step__c rfpStep3 = new Phoenix_Approval_Process_Step__c(Name = 'Vistex Update', Phoenix_Order__c = 3, Phoenix_Is_Notification_Only__c = false, Phoenix_Approver_Team__c = 'Home Office', Phoenix_Approval_Matrix__c = matrix.Id);
            stepsList.add(rfpStep3);
            
            Phoenix_Approval_Process_Step__c rfpStep4 = new Phoenix_Approval_Process_Step__c(Name = 'Closed', Phoenix_Order__c = 4, Phoenix_Is_Notification_Only__c = false, Phoenix_Approval_Matrix__c = matrix.Id);
            stepsList.add(rfpStep4);
        }
        insert stepsList;
        list < Phoenix_Bid_Process_Steps__c > processList = new list < Phoenix_Bid_Process_Steps__c > ();
        Phoenix_Bid_Process_Steps__c bStep = new Phoenix_Bid_Process_Steps__c();
        bStep.Phoenix_Is_Criteria_Step__c = false;
        bStep.Phoenix_Process_Step__c = stepsList[0].Id;
        system.debug('stepsList[0].Id---------------' + stepsList[0].Id);
        bStep.Name = testNDC.Phoenix_PHS_Price_Change_Name__c + '-' + 'Intial Submission';
        bStep.Phoenix_Approver__c = UserInfo.getUserId();
        bStep.Phoenix_PHS_Price_Change__c = testNDC.Id;
        
        bStep.Phoenix_Status__c = 'Submitted';
        
        bStep.Phoenix_Sub_Step__c = 1;
        processList.add(bStep);
       
       
        
      
        
     
        
      
     
        Phoenix_Bid_Process_Steps__c bStep2 = new Phoenix_Bid_Process_Steps__c();
        bStep2.Phoenix_Is_Criteria_Step__c = false;
        bStep2.Name = testNDC.Phoenix_PHS_Price_Change_Name__c + '-' + 'Sr Director or VP Finance Approval';
        bStep2.Phoenix_Approver__c = UserInfo.getUserId();
        bStep2.Phoenix_PHS_Price_Change__c = testNDC.Id;
        bStep2.Phoenix_Process_Step__c = stepsList[1].Id;
        
        bStep2.Phoenix_Status__c = 'In Process';
        bStep2.Phoenix_Approver_Team__c = 'Sr Director or VP Finance';
        
        bStep2.Phoenix_Sub_Step__c = 1;
        processList.add(bStep2);
        
        Phoenix_Bid_Process_Steps__c bStep3 = new Phoenix_Bid_Process_Steps__c();
        bStep3.Phoenix_Is_Criteria_Step__c = false;
        bStep3.Name = testNDC.Phoenix_PHS_Price_Change_Name__c + '-' + 'Vistex Update';
        bStep3.Phoenix_Approver__c = UserInfo.getUserId();
        bStep3.Phoenix_PHS_Price_Change__c = testNDC.Id;
        bStep3.Phoenix_Process_Step__c = stepsList[2].Id;
        
        bStep3.Phoenix_Status__c = 'In Process';
        bStep3.Phoenix_Approver_Team__c = 'Home Office';
        bStep3.Phoenix_Sub_Step__c = 1;
        processList.add(bStep3);
        
        Phoenix_Bid_Process_Steps__c bStep4 = new Phoenix_Bid_Process_Steps__c();
        bStep4.Phoenix_Is_Criteria_Step__c = false;
        bStep4.Name = testNDC.Phoenix_PHS_Price_Change_Name__c + '-' + 'Closed';
        bStep4.Phoenix_Process_Step__c = stepsList[3].Id;
        bStep4.Phoenix_Approver__c = UserInfo.getUserId();
        bStep4.Phoenix_PHS_Price_Change__c = testNDC.Id;
        bStep4.Phoenix_Sub_Step__c = 1;
        processList.add(bStep4);
        insert processList;
        
        list < Phoenix_Bid_Process_Steps__c > bidProcessStepList = [SELECT Id, Name, Phoenix_PHS_Price_Change__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__r.Name, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_PHS_Price_Change__c =: testNDC.Id];
        system.debug('---bidProcessStepList---' + bidProcessStepList.size());
        
        
       
         Phoenix_PHSControllerClass.updateNextProcesSteps(testNDC.Id,bidProcessStepList,false,false,true);
        Phoenix_PHSControllerClass.updateNextProcesSteps(testNDC.Id,bidProcessStepList,true,true,false);
         
        Phoenix_PHSControllerClass.deleteLineItems(lineItemsList[1].Id);
           Phoenix_PHSControllerClass.deletePHSLine(lineItemsList[0].Id);
        
    }
    
}