UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_DRL_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DRL Sales</relationshipLabel>
        <relationshipName>DRL_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Month_dtls__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Processed_Month__c</fullName>
        <formula>CASE(MONTH( Vision_Month_dtls__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot; &quot;)+&quot;-&quot; +RIGHT(TEXT(YEAR( Vision_Month_dtls__c)) , LEN(TEXT(YEAR( Vision_Month_dtls__c))) - 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Processed Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sales_Dollar__c</fullName>
        <label>Sales Dollar</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RX</fullName>
                </value>
                <value>
                    <fullName>SRX</fullName>
                </value>
                <value>
                    <fullName>OTC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_TPT_Dollar__c</fullName>
        <label>TPT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_TPT_Pct__c</fullName>
        <label>TPT %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DRL Sales</label>
    <nameField>
        <displayFormat>DRLSales-{0000000}</displayFormat>
        <label>DRL Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_InternalDRLSales_ProductSummary__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vision Internal Sales Product Summarys</relationshipLabel>
        <relationshipName>Vision_Internal_Sales_Product_Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Is_OTC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is OTC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Is_Rx__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Rx</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Is_SRx__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is SRx</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Processed_Date__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Processed_Month__c</fullName>
        <formula>CASE(MONTH( Vision_Processed_Date__c ),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot; &quot;)+&quot;-&quot; +RIGHT(TEXT(YEAR( Vision_Processed_Date__c )) , LEN(TEXT(YEAR( Vision_Processed_Date__c ))) - 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Processed Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <formula>IF( Vision_Is_Rx__c , &apos;Rx&apos;, IF( Vision_Is_SRx__c , &apos;SRx&apos;, IF( Vision_Is_OTC__c , &apos;OTC&apos;, &apos;&apos;)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_TPT_Dollar__c</fullName>
        <label>TPT Dollar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_TPT_Percent__c</fullName>
        <label>TPT Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vision Internal Sales Product Summary</label>
    <nameField>
        <displayFormat>DRL Sales Summary-{0000}</displayFormat>
        <label>VisionInternal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vision Internal Sales Product Summarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/VisionIntDRLSalesProductLevelBatchCls.cls
public class VisionIntDRLSalesProductLevelBatchCls implements Database.Batchable < sObject > , Database.Stateful,Schedulable,Database.AllowsCallouts{
	public void execute(SchedulableContext sc) {
        //Database.executeBatch(new VisionInternalDRLSalesSummaryBatchCls());
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String cust = '0011K00002RDd6lQAD';
        String datee= '21';
        String family = 'Glimepiride Tabs';
          delete[select id from Vision_InternalDRLSales_ProductSummary__c WHERE CreatedDate != Today limit 200];
        // where Vision_Customer_Name__c =:cust AND Vision_Processed_Month__c  like \'%' + datee + '%\' AND Vision_Product_Family__c like \'%'+family+'%\'
        String query = 'Select Vision_Customer_Name__r.Name, '+Phoenix_Util.getsObjectFieds('Vision_DRL_Sales__c')+' from Vision_DRL_Sales__c  ORDER BY Vision_Product_Family__c,Vision_Month_dtls__c ASC NULLS LAST';
        return Database.getQueryLocator(query);
    }
    
      public void execute(Database.BatchableContext BC, List < Vision_DRL_Sales__c > internalSalesList) {
        try{
            System.debug('sales list size-->'+internalSalesList.size());
            Map<String, Map<Integer, Vision_InternalDRLSales_ProductSummary__c>> finalMap = new Map<String, Map<Integer, Vision_InternalDRLSales_ProductSummary__c>>();
            Map<String, Vision_InternalDRLSales_ProductSummary__c> summaryRecordsToInsert = new  Map<String, Vision_InternalDRLSales_ProductSummary__c>();
            set<String> existingUniqueIds = new set<String>();
            for(Vision_DRL_Sales__c internalSalesRecord: internalSalesList){
                String mapKey = internalSalesRecord.Vision_Customer_Name__r.Name+'-'+internalSalesRecord.Vision_Product_Family__c+'-'+internalSalesRecord.Vision_Segment__c+'_'+internalSalesRecord.Vision_Month_dtls__c.year();
                system.debug('Map Key: '+mapKey);
                system.debug(internalSalesRecord.Vision_Month_dtls__c+' ::Sales:: '+internalSalesRecord.Vision_Sales_Dollar__c);
                System.debug('finalMap>>'+finalMap);
                if(finalMap.containsKey(mapKey)){
                    Map<Integer, Vision_InternalDRLSales_ProductSummary__c> oneStepInnerMap = finalMap.get(mapKey);
                    if(oneStepInnerMap.containsKey(internalSalesRecord.Vision_Month_dtls__c.month())){
                        Vision_InternalDRLSales_ProductSummary__c summaryRec = oneStepInnerMap.get(internalSalesRecord.Vision_Month_dtls__c.month());
                        System.debug('family  is-->'+internalSalesRecord.Vision_Product_Family__c);
                        System.debug('segment is-->'+internalSalesRecord.Vision_Segment__c);
                        System.debug('summaryRec>>>'+summaryRec);
                        if(internalSalesRecord.Vision_Segment__c == 'Rx' || internalSalesRecord.Vision_Segment__c == 'RX'){
                            summaryRec.Vision_Is_Rx__c = true;
                        } else if(internalSalesRecord.Vision_Segment__c == 'SRx' || internalSalesRecord.Vision_Segment__c == 'SRX'){
                            summaryRec.Vision_Is_SRx__c = true;
                        } else if(internalSalesRecord.Vision_Segment__c == 'OTC'){
                            summaryRec.Vision_Is_OTC__c =  true;
                        }
                        summaryRec.Vision_Customer__c = internalSalesRecord.Vision_Customer_Name__c;
                        summaryRec.Vision_Processed_Date__c = internalSalesRecord.Vision_Month_dtls__c;
                        if(summaryRec.Vision_Sales__c != null && internalSalesRecord.Vision_Sales_Dollar__c !=null){
                            summaryRec.Vision_Sales__c = summaryRec.Vision_Sales__c+internalSalesRecord.Vision_Sales_Dollar__c;
                        }
                        if(summaryRec.Vision_Units__c != null && internalSalesRecord.Vision_Units__c !=null){
                            summaryRec.Vision_Units__c = summaryRec.Vision_Units__c+internalSalesRecord.Vision_Units__c;
                        }
                        if(summaryRec.Vision_TPT_Dollar__c != null && internalSalesRecord.Vision_TPT_Dollar__c !=null){
                            summaryRec.Vision_TPT_Dollar__c = summaryRec.Vision_TPT_Dollar__c+internalSalesRecord.Vision_TPT_Dollar__c;
                        }
                        if(summaryRec.Vision_TPT_Percent__c != null && internalSalesRecord.Vision_TPT_Pct__c !=null){
                            summaryRec.Vision_TPT_Percent__c = summaryRec.Vision_TPT_Percent__c+internalSalesRecord.Vision_TPT_Pct__c;
                        }
                        summaryRec.Vision_Product_Family__c = internalSalesRecord.Vision_Product_Family__c;
                        summaryRec.Vision_Unique_Identifier__c = mapKey+'_'+internalSalesRecord.Vision_Month_dtls__c.month();
                        //system.debug('Vision_Sales__c -- Inner If: '+summaryRec.Vision_Sales__c);
                    } else{
                        Vision_InternalDRLSales_ProductSummary__c newSummaryRec = new Vision_InternalDRLSales_ProductSummary__c();
                        if(internalSalesRecord.Vision_Segment__c == 'Rx' || internalSalesRecord.Vision_Segment__c == 'RX'){
                            newSummaryRec.Vision_Is_Rx__c = true;
                        } else if(internalSalesRecord.Vision_Segment__c == 'SRx' || internalSalesRecord.Vision_Segment__c == 'SRX'){
                            newSummaryRec.Vision_Is_SRx__c = true;
                        } else if(internalSalesRecord.Vision_Segment__c == 'OTC'){
                            newSummaryRec.Vision_Is_OTC__c =  true;
                        }
                        newSummaryRec.Vision_Customer__c = internalSalesRecord.Vision_Customer_Name__c;
                        newSummaryRec.Vision_Processed_Date__c = internalSalesRecord.Vision_Month_dtls__c;
                        newSummaryRec.Vision_Sales__c = internalSalesRecord.Vision_Sales_Dollar__c;
                        newSummaryRec.Vision_Units__c = internalSalesRecord.Vision_Units__c;
                        newSummaryRec.Vision_TPT_Dollar__c = internalSalesRecord.Vision_TPT_Dollar__c;
                        newSummaryRec.Vision_TPT_Percent__c = internalSalesRecord.Vision_TPT_Pct__c;
                        newSummaryRec.Vision_Product_Family__c = internalSalesRecord.Vision_Product_Family__c;
                        newSummaryRec.Vision_Unique_Identifier__c = mapKey+'_'+internalSalesRecord.Vision_Month_dtls__c.month();
                        oneStepInnerMap.put(internalSalesRecord.Vision_Month_dtls__c.month(), newSummaryRec);
                        //system.debug('Vision_Sales__c -- Inner Else: '+newSummaryRec.Vision_Sales__c);
                    }
                } else{
                    Vision_InternalDRLSales_ProductSummary__c newSummaryRec = new Vision_InternalDRLSales_ProductSummary__c();
                    if(internalSalesRecord.Vision_Segment__c == 'Rx' || internalSalesRecord.Vision_Segment__c == 'RX'){
                            newSummaryRec.Vision_Is_Rx__c = true;
                        } else if(internalSalesRecord.Vision_Segment__c == 'SRx' || internalSalesRecord.Vision_Segment__c == 'SRX'){
                            newSummaryRec.Vision_Is_SRx__c = true;
                        } else if(internalSalesRecord.Vision_Segment__c == 'OTC'){
                            newSummaryRec.Vision_Is_OTC__c =  true;
                        }
                    newSummaryRec.Vision_Customer__c = internalSalesRecord.Vision_Customer_Name__c;
                    newSummaryRec.Vision_Processed_Date__c = internalSalesRecord.Vision_Month_dtls__c;
                    newSummaryRec.Vision_Sales__c = internalSalesRecord.Vision_Sales_Dollar__c;
                    newSummaryRec.Vision_Units__c = internalSalesRecord.Vision_Units__c;
                    newSummaryRec.Vision_TPT_Dollar__c =  internalSalesRecord.Vision_TPT_Dollar__c;
                    newSummaryRec.Vision_TPT_Percent__c = internalSalesRecord.Vision_TPT_Pct__c;
                    newSummaryRec.Vision_Product_Family__c = internalSalesRecord.Vision_Product_Family__c;
                    newSummaryRec.Vision_Unique_Identifier__c = mapKey+'_'+internalSalesRecord.Vision_Month_dtls__c.month();
                    //system.debug('Vision_Sales__c -- Outer Else: '+newSummaryRec.Vision_Sales__c);
                    Map<Integer, Vision_InternalDRLSales_ProductSummary__c> oneStepInnerMap = new Map<Integer, Vision_InternalDRLSales_ProductSummary__c>();
                    oneStepInnerMap.put(internalSalesRecord.Vision_Month_dtls__c.month(), newSummaryRec);
                    finalMap.put(mapKey, oneStepInnerMap);
                    System.debug('newSummaryRec'+newSummaryRec);
                }
                if(finalMap.size() > 0){
                    for(String custKey: finalMap.keySet()){
                        Map<Integer, Vision_InternalDRLSales_ProductSummary__c> custSpecificData = finalMap.get(custKey);
                        //system.debug('Customer Specific Data: '+custSpecificData);
                        for(Integer monthKey: custSpecificData.keySet()){
                            existingUniqueIds.add(custSpecificData.get(monthKey).Vision_Unique_Identifier__c);
                                        System.debug('existingUniqueIds>>'+existingUniqueIds);

                            summaryRecordsToInsert.put(custSpecificData.get(monthKey).Vision_Unique_Identifier__c, custSpecificData.get(monthKey));
                        }
                    }
                }
            }
            for(Vision_InternalDRLSales_ProductSummary__c intDRLSalesRec : [select Id,Vision_Sales__c,Vision_Units__c,Vision_TPT_Dollar__c,Vision_TPT_Percent__c,Vision_Unique_Identifier__c From Vision_InternalDRLSales_ProductSummary__c Where Vision_Unique_Identifier__c in : existingUniqueIds]){
                 System.debug('intDRLSalesRec>>'+intDRLSalesRec.Vision_Unique_Identifier__c);
                System.debug('intDRLSalesRec>>'+intDRLSalesRec.Id);
                System.debug('summaryRecordsToInsert>>'+summaryRecordsToInsert);
                summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Id = intDRLSalesRec.Id;
                                 System.debug('intDRLSalesRec1>>'+intDRLSalesRec.Vision_Unique_Identifier__c);

               
                if(summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Sales__c != null && intDRLSalesRec.Vision_Sales__c != null){
                summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Sales__c = summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Sales__c + intDRLSalesRec.Vision_Sales__c;
                }
                if(summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Units__c != null && intDRLSalesRec.Vision_Units__c !=null){
                summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Units__c = summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Units__c + intDRLSalesRec.Vision_Units__c;
                }
                if(summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_TPT_Dollar__c != null && intDRLSalesRec.Vision_TPT_Dollar__c != null){
               	summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_TPT_Dollar__c = summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_TPT_Dollar__c + intDRLSalesRec.Vision_TPT_Dollar__c;
           		 }
                //summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_TPT_Percent__c = summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_TPT_Percent__c + intDRLSalesRec.Vision_TPT_Percent__c;
            }
            if(summaryRecordsToInsert.size() > 0)
            {
                for(String key : summaryRecordsToInsert.keySet()){
                    system.debug(key+':: Customer Specific Data:: '+summaryRecordsToInsert.get(key));
                }
                upsert summaryRecordsToInsert.values();
            }
            //if(summaryRecordsToInsert.size() > 0)
             //   insert summaryRecordsToInsert.values();
            //insert summaryRecordsToInsert.values();
        }catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'VisionIntDRLSalesProductLevelBatchCls', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
    
    public void finish(Database.BatchableContext BC) {}
    
     /*public static void coverageBlock(){
        Integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }*/
}