UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contracts_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contracts Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Phoenix_Contracts_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bids3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Name__c</fullName>
        <label>Bid Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contracts_Approval_Comments__c</fullName>
        <label>Contracts Approval Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contracts_Approval__c</fullName>
        <label>Contracts Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Not_Processed</fullName>
                    <label>Not Processed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Final_Status__c</fullName>
        <label>Final Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_IPA_Floor_Price1__c</fullName>
        <label>IPA Floor Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Marketing_Final_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketing Final Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Director1__c</fullName>
        <label>Product Director</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Proposed_IPA_Price__c</fullName>
        <label>Proposed IPA Price(Sales)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid_Process_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Process Steps</relationshipLabel>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bid Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_User_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Group_Behavior__c</fullName>
        <label>Approval Group Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single User</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
                <value>
                    <fullName>Account based</fullName>
                </value>
                <value>
                    <fullName>Product based</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver_Group_Name__c</fullName>
        <label>Approver Group Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phoenix_Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Phoenix_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Active_User__c</fullName>
        <formula>Phoenix_Approver__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Approval_Process_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approval Process User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Phoenix_User_Approval_Matrix__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Approval User Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phoenix_User_Approval_Matrix__c</referenceTo>
        <relationshipLabel>User_Groups</relationshipLabel>
        <relationshipName>User_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Approval Matrix</label>
    <nameField>
        <label>User Approval Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Is_IPA_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is IPA Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/globalValueSets/Phoenix_Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Business Head</fullName>
    </customValue>
    <customValue>
        <fullName>Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Country Head</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Government Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Home Office</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Head</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead OTC</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead SRx</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sr Director or VP Finance</fullName>
    </customValue>
    <customValue>
        <fullName>SRx IPA Contracts Approver</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Demand Planning</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Marketing Head</fullName>
        <isActive>false</isActive>
        <label>Sales &amp; Marketing Head</label>
    </customValue>
    <customValue>
        <fullName>VP / Director Finance</fullName>
        <isActive>false</isActive>
        <label>VP / Director Finance</label>
    </customValue>
    <customValue>
        <fullName>SCM &amp; Marketing</fullName>
        <isActive>false</isActive>
        <label>SCM &amp; Marketing</label>
    </customValue>
    <masterLabel>Phoenix_Teams</masterLabel>
</GlobalValueSet>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/Phoenix_EditIPABidMainPageCls.cls
/**
* @description       : 
* @author            : Surender Patel (Dhruvsoft)
* @group             : 
* @last modified on  : 20-07-2021
* @last modified by  : Surender Patel (Dhruvsoft)
* Modifications Log 
* Ver   Date         Author                       Modification
* 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
public class Phoenix_EditIPABidMainPageCls {
    
    
    @AuraEnabled
    public static Wrapper getRelatedList(Id bidId) {
        Wrapper wrapperObject = new Wrapper();
        
        String query = '';
        String SobjectApiName = 'Phoenix_Bid_Line_Item__c';
        Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
        Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
        
        String strFields = '';
        
        for (String fieldName: fieldMap.keyset()) {
            if (strFields == null || strFields == '') {
                strFields = fieldName;
            } else {
                strFields = strFields + ' , ' + fieldName;
            }
        }
        string notApproved = 'Not Approved';
        query = 'select Phoenix_Contract__r.Name,Phoenix_Bid__r.Phoenix_Customer__r.Phoenix_Contracts_Approver__r.Name,Phoenix_Contract__r.Id,Phoenix_Customer__r.Name,Phoenix_Customer__r.Id, Phoenix_Product__r.Name,Phoenix_Bid__r.Phoenix_Bid_Name__c, ' + strFields + ' from ' + SobjectApiName + ' where Phoenix_Bid__c = : bidId and Phoenix_Product__r.Phoenix_Is_IPA_Product__c=true and Phoenix_Final_Status__c !=: notApproved ORDER BY Phoenix_Product__r.Name ASC ';
        
        list < Phoenix_Bid_Line_Item__c > quoteList = Database.query(query);
        system.debug('quoteList--->' + quoteList);
        
        boolean showProceedBtn = true;
        boolean showProceedContrBtn = true;
        boolean conditionApproval = false;
        for (Phoenix_Bid_Line_Item__c lineItem: quoteList) {
            
            
            
            if (lineItem.Phoenix_Product_Director1__c != null && lineItem.Phoenix_Marketing_Final_Approval__c != null && lineItem.Phoenix_Marketing_Final_Approval__c == true && lineItem.Phoenix_Product_Director1__c == userinfo.getName()) {
                system.debug('In mARKETING APProval');
                showProceedBtn = false;
            }
            
            
            if (lineItem.Phoenix_Proposed_IPA_Price__c > 0 && (lineItem.Phoenix_Proposed_IPA_Price__c < lineItem.Phoenix_IPA_Floor_Price1__c || lineItem.Phoenix_IPA_Floor_Price1__c == null )) {
                conditionApproval = true;
            }
        }
        
        Map < String, String > userTeamUserIdMap = new Map < String, String > ();
        for (Phoenix_User_Approval_Matrix__c matrix: [Select Id, Name, RecordType.DeveloperName, User_Group__r.Phoenix_Approver_Group_Name__c, Phoenix_Approval_Group_Behavior__c, Phoenix_Approver__c, Phoenix_Approver__r.Email, Phoenix_Approver_Group_Name__c, Phoenix_Is_Active_User__c, Phoenix_Is_Approval_Process_User__c, User_Group__c from Phoenix_User_Approval_Matrix__c limit 1000]) {
            String userTeamUserIdMapKey = matrix.User_Group__r.Phoenix_Approver_Group_Name__c + '-' + matrix.Phoenix_Approver__c;
            userTeamUserIdMap.put(userTeamUserIdMapKey, matrix.Phoenix_Approver__c);
        }
        
        boolean isFinanceApprovePerson = false;
        string isMarketingApprovePerson;
        boolean isSRxApprovePerson = false;
        boolean isVistexApprovePerson = false;
        
        
        if (userTeamUserIdMap.containsKey('Finance-' + UserInfo.getUserId())) {
            isFinanceApprovePerson = true;
        }
        if (userTeamUserIdMap.containsKey('SRx IPA Contracts Approver-' + UserInfo.getUserId())) {
            isSRxApprovePerson = true;
        }
        
        if (userTeamUserIdMap.containsKey('Home Office-' + UserInfo.getUserId())) {
            isVistexApprovePerson = true;
        }
        
        
        
        if (userTeamUserIdMap.containsKey('Marketing-' + UserInfo.getUserId())) {
            isMarketingApprovePerson = userTeamUserIdMap.get(('Marketing-' + UserInfo.getUserId()));
        }
        //boolean showProceedBtn=true; 
        
        
        
        Phoenix_Bid__c bid = [SELECT Id, Phoenix_Contracts_Approval_Comments__c, Phoenix_Contracts_Approval__c, Phoenix_Customer__r.Phoenix_Contracts_Approver__r.Name, Name, Phoenix_Approval_Status__c, Phoenix_Customer__r.Name, Phoenix_Bid_Name__c, Phoenix_Bid_Type__c FROM Phoenix_Bid__c WHERE Id =: bidId];
        
        wrapperObject.lineItemsList = quoteList;
        wrapperObject.bidRecord = bid;
        wrapperObject.loggedInUserName = UserInfo.getName();
        wrapperObject.loggedInUserId = UserInfo.getUserId();
        wrapperObject.conditionApproval = conditionApproval;
        wrapperObject.isFinanceApprovePerson = isFinanceApprovePerson;
        wrapperObject.isMarketingApprovePerson = isMarketingApprovePerson;
        wrapperObject.isVistexApprovePerson = isVistexApprovePerson;
        wrapperObject.isSRxApprovePerson = isSRxApprovePerson;
        
        wrapperObject.showProceedBtn = showProceedBtn;
        
        system.debug(';loggedInUserName' + wrapperObject.loggedInUserName);
        return wrapperObject;
        
    }
    @AuraEnabled
    public static Phoenix_Bid__c saveTobid(string bidId, string comments, string status) {
        Phoenix_Bid__c bidRecord = new Phoenix_Bid__c(Id = bidId, Phoenix_Contracts_Approval__c = status, Phoenix_Contracts_Approval_Comments__c = comments);
        update bidRecord;
        return bidRecord;
    }
    
    @AuraEnabled
    public static list < Phoenix_Bid_Line_Item__c > submitToProceddStep1(string bidId, boolean isMarketing, boolean isFinance, boolean isContracts) {
        String query = '';
        String SobjectApiName = 'Phoenix_Bid_Line_Item__c';
        Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
        Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
        
        String strFields = '';
        
        for (String fieldName: fieldMap.keyset()) {
            if (strFields == null || strFields == '') {
                strFields = fieldName;
            } else {
                strFields = strFields + ' , ' + fieldName;
            }
        }
        string notApproved = 'Not Approved';
        string loggerUserName = UserInfo.getName();
        query = 'select Phoenix_Product__r.Phoenix_Rx_SRx_OTC__c,Phoenix_Bid__r.Phoenix_Customer__r.Phoenix_Contracts_Approver__r.Name, Phoenix_Product__r.name,Phoenix_Bid__r.Phoenix_Bid_Name__c, ' + strFields + ' from ' + SobjectApiName + ' where Phoenix_Bid__c = : bidId AND Phoenix_Final_Status__c !=: notApproved';
        if (isMarketing == true) {
            query += ' and Phoenix_Product_Director1__c=:loggerUserName';
        }
        list < Phoenix_Bid_Line_Item__c > bidLinesList = Database.query(query);
        return bidLinesList;
        
    }
    @AuraEnabled
    public static WrapperForNextSteps makeApprovals(String bidId, List < Phoenix_Bid_Line_Item__c > bidlines, boolean approveStatusFlag) {
        for (Phoenix_Bid_Line_Item__c line: bidlines) {
            line.Phoenix_Marketing_Final_Approval__c = true;
            if (line.Phoenix_Marketing_Approval__c == 'Not Approved') {
                line.Phoenix_Final_Status__c = 'Not Approved';
            }
        }
        if (bidlines.size() > 0) {
            update bidlines;
        }
        
        list < Phoenix_Bid_Process_Steps__c > bidProcessStepList = [SELECT Id, Name, Phoenix_Bid__c,Phoenix_Approver__r.Email, Phoenix_Is_Criteria_Step__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId order by Phoenix_Step__c];
        list < Phoenix_Bid_Line_Item__c > bidLinesUpdate = [select id,Phoenix_Marketing_Final_Approval__c,Phoenix_Contracts_Final_Approval__c,Phoenix_Customer_Final_Approval__c,Phoenix_Final_Status__c from Phoenix_Bid_Line_Item__c where Phoenix_Bid__c =: bidId];
        WrapperForNextSteps wrapSteps = new WrapperForNextSteps();
        boolean isAllRejectedCaseFound = true;
        boolean isMarketingCompleted = true;
        for (Phoenix_Bid_Line_Item__c lineItem: bidLinesUpdate) {
            if (lineItem.Phoenix_Final_Status__c != 'Not Approved') {
                isAllRejectedCaseFound = false;
            }
            if(!lineItem.Phoenix_Marketing_Final_Approval__c && lineItem.Phoenix_Final_Status__c != 'Not Approved')
                isMarketingCompleted = false;
        }
        Phoenix_Bid__c bidRec = new Phoenix_Bid__c(id = bidId, Phoenix_Bid_Marketing_Approved_Date__c = system.today()); //Closed
        if(bidRec != null && (isMarketingCompleted || isAllRejectedCaseFound))
        	update bidRec;
        
        if (isAllRejectedCaseFound) {
            
            integer currentStepNum; 
            
            
            for (Phoenix_Bid_Process_Steps__c prcsStep: bidProcessStepList) {
                if (prcsStep.Phoenix_Approver_Team__c == 'Marketing') {
                    currentStepNum = integer.valueOf(prcsStep.Phoenix_Step__c);
                }
            }
            for (Phoenix_Bid_Process_Steps__c prcsStep: bidProcessStepList) {
                if (prcsStep.Phoenix_Approver_Team__c == 'Marketing' && prcsStep.Phoenix_Approver__c == Userinfo.getUserId()) {
                    
                    prcsStep.Phoenix_Status__c = 'Completed';
                    
                }
                if (prcsStep.Phoenix_Step__c > currentStepNum) {
                    if (prcsStep.Name.contains('Closed')) {
                        prcsStep.Phoenix_Status__c = 'Completed';
                    } 
                    else {
                        prcsStep.Phoenix_Status__c = 'Not Applicable';
                    }
                }
            }
            update bidProcessStepList;
            Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Marketing Rejected');
            update bid;
            
            
            
            wrapSteps.updateProcessStepList = bidProcessStepList;
            wrapSteps.flagMarketStop = true;
            
            
            
            
            
            
        }
        else{
            list < Phoenix_Bid_Process_Steps__c > marketStepLsit = new list < Phoenix_Bid_Process_Steps__c > ();
            
            boolean flagMarketStop = false;
            for (Phoenix_Bid_Process_Steps__c step: bidProcessStepList) {
                if (step.Phoenix_Approver_Team__c == 'Marketing' && step.Phoenix_Approver__c == Userinfo.getUserId()) {
                    step.Phoenix_Status__c = 'Completed'; //approveStatusFlag==true?'Completed':'Do Not Bid';
                    // step.Phoenix_Status__c=approveStatusFlag==true?'Completed':'';
                    marketStepLsit.add(step);
                }
                //if(step.Phoenix_Approver_Team__c=='Supply Chain' && step.Phoenix_Status__c!='Completed'){
                // flagSCMStop=true;
                //}
                
                if (step.Phoenix_Approver_Team__c == 'Marketing' && step.Phoenix_Status__c != 'Completed') {
                    if (step.Phoenix_Status__c != 'Not Applicable') {
                        flagMarketStop = true;
                    }
                }
            }
            //   WrapperForNextSteps wrapSteps = new WrapperForNextSteps();
            if (!marketStepLsit.isEmpty()) {
                update marketStepLsit;
                wrapSteps.updateProcessStepList = bidProcessStepList;
                
                wrapSteps.flagMarketStop = flagMarketStop;
            }
        }
        
        return wrapSteps;
    }
    public class WrapperForNextSteps {
        @AuraEnabled public list < Phoenix_Bid_Process_Steps__c > updateProcessStepList;
        
        @AuraEnabled public boolean flagMarketStop;
        @AuraEnabled public boolean contractNextStepFlag;
        
        WrapperForNextSteps() {
            updateProcessStepList = new List < Phoenix_Bid_Process_Steps__c > ();
            contractNextStepFlag = false;
            flagMarketStop = false;
        }
    }
    @AuraEnabled
    public static void updateNextMarketingProcessSteps(string bidId, string bidName, list < Phoenix_Bid_Process_Steps__c > processStepLsit, boolean flagMarketStop) {
        system.debug('In Marketing');
        if (flagMarketStop == false && !processStepLsit.isEmpty()) {
            Map < Integer, List < Phoenix_Bid_Process_Steps__c >> stepMap = new Map < Integer, List < Phoenix_Bid_Process_Steps__c >> ();
            Map < String, List < Phoenix_Bid_Process_Steps__c >> stepNamesMap = new Map < String, List < Phoenix_Bid_Process_Steps__c >> ();
            Map < String, Integer > stepnameNoMap = new Map < String, Integer > ();
            for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
                
                Integer stepNo = Integer.valueOf(step.Phoenix_Step__c);
                if (stepMap.get(stepNo) != null) {
                    List < Phoenix_Bid_Process_Steps__c > adededSteps = stepMap.get(stepNo);
                    adededSteps.add(step);
                    stepMap.put(stepNo, adededSteps);
                } else {
                    stepMap.put(stepNo, new List < Phoenix_Bid_Process_Steps__c > {
                        step
                            });
                }
                
                String stepName = step.Phoenix_Approver_Team__c;
                if (stepNamesMap.get(stepName) != null) {
                    List < Phoenix_Bid_Process_Steps__c > adededSteps = stepNamesMap.get(stepName);
                    adededSteps.add(step);
                    stepNamesMap.put(stepName, adededSteps);
                } else {
                    stepNamesMap.put(stepName, new List < Phoenix_Bid_Process_Steps__c > {
                        step
                            });
                }
                stepnameNoMap.put(stepName, stepNo);
                
            }
            
            
            String query = '';
            String SobjectApiName = 'Phoenix_Bid_Line_Item__c';
            Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
            Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
            
            String strFields = '';
            
            for (String fieldName: fieldMap.keyset()) {
                if (strFields == null || strFields == '') {
                    strFields = fieldName;
                } else {
                    strFields = strFields + ' , ' + fieldName;
                }
            }
            string notApproved = 'Not Approved';
            query = 'select Phoenix_Contract__r.Name,Phoenix_Bid__r.Phoenix_Customer__r.Phoenix_Contracts_Approver__r.Name,Phoenix_Contract__r.Id,Phoenix_Customer__r.Name,Phoenix_Customer__r.Id, Phoenix_Product__r.Name,Phoenix_Bid__r.Phoenix_Bid_Name__c, ' + strFields + ' from ' + SobjectApiName + ' where Phoenix_Bid__c = : bidId and Phoenix_Product__r.Phoenix_Is_IPA_Product__c=true and Phoenix_Final_Status__c !=: notApproved ORDER BY Phoenix_Product__r.Name ASC ';
            
            list < Phoenix_Bid_Line_Item__c > quoteList = Database.query(query);
            boolean conditionalApproval=false;
            for(Phoenix_Bid_Line_Item__c lineItem:quoteList){
                if (lineItem.Phoenix_Proposed_IPA_Price__c > 0 && lineItem.Phoenix_Proposed_IPA_Price__c < lineItem.Phoenix_IPA_Floor_Price1__c) {
                    conditionalApproval = true;
                }
            }
            
            
            
            system.debug('stepnamemap--' + stepnameNoMap.get('Marketing') + 1);
            system.debug('stepnamemap--' + stepMap.get(4));
            List < Phoenix_Bid_Process_Steps__c > nextSteps = new list < Phoenix_Bid_Process_Steps__c > ();
            List < Phoenix_Bid_Process_Steps__c > nextStepscopy = new list < Phoenix_Bid_Process_Steps__c > ();
            Integer stepNo;
            
            
            
            if (conditionalApproval == true) {
                stepNo = stepnameNoMap.get('Marketing') + 1;
                nextSteps = stepMap.get(stepNo);
            } else {
                stepNo = stepnameNoMap.get('Marketing') + 2;
                system.debug('stepNo' + stepNo);
                system.debug('stepMap' + stepMap);
                
                nextSteps = stepMap.get(stepNo);
                stepNo = stepnameNoMap.get('Marketing') + 1;
                nextStepscopy = stepMap.get(stepNo);
                for (Phoenix_Bid_Process_Steps__c bstep: nextStepscopy) {
                    nextSteps.add(bstep);
                }
            }
            
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Completed';
                } else if (conditionalApproval == false && step.Name.contains('Finance')) {
                    step.Phoenix_Status__c = 'Not Applicable';
                } else {
                    step.Phoenix_Status__c = 'In Process';
                } //'In Process' Submitted //Diff b/w them            
            }
            if (!nextSteps.isEmpty()) {
                update nextSteps;
                if(conditionalApproval==true){
                    Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = nextSteps[0].Phoenix_Approver_Team__c);
                    update bid;
                    
                }
                else{
                    Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Contracts');
                    update bid;   
                }
                Phoenix_SubmitBidForApprovalCtrl.approvalRequestNotification(bidId , nextSteps);


                
                //Phoenix_SubmitBidForApprovalCtrl.sendForApproval(bidId,'Approval Required for '+bidName,nextSteps,'Bid_Approval');
            } else {
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Closed');
                update bid;
            }
            
        }
    }
    @AuraEnabled
    public static list < Phoenix_Bid_Process_Steps__c > makeApprovalsContracts(String bidId, List < Phoenix_Bid_Line_Item__c > bidlines, boolean approveStatusFlag, boolean isContracts, boolean isFinance) {
       
        for (Phoenix_Bid_Line_Item__c line: bidlines) {
            if (isContracts) {
                line.Phoenix_Contracts_Final_Approval__c = true;
                if (line.Phoenix_Contract_Approval__c == 'Line Error- Not Sent') {
                    line.Phoenix_Final_Status__c = 'Not Approved';
                }
            }
            
            
            if (isFinance) {
                line.Phoenix_Final_Finance_Approval__c = true;
                if (line.Phoenix_Finance_Approval__c == 'Not Approved') {
                    line.Phoenix_Final_Status__c = 'Not Approved';
                }
            }
        }
        if (bidlines.size() > 0) {
            update bidlines;
        }
        list < Phoenix_Bid_Process_Steps__c > bidProcessStepList = [SELECT Id, Name, Phoenix_Is_Criteria_Step__c,Phoenix_Bid__c, Phoenix_Process_Step__c,Phoenix_Step__c, Phoenix_Approver__r.Name, Phoenix_Approver__r.Email, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];
        list < Phoenix_Bid_Process_Steps__c > contractsStepLsit = new list < Phoenix_Bid_Process_Steps__c > ();
        System.debug('approveStatusFlag-->'+approveStatusFlag);
        for (Phoenix_Bid_Process_Steps__c step: bidProcessStepList) {
            System.debug('approver team-->'+step.Phoenix_Approver_Team__c);
            if (step.Phoenix_Approver_Team__c == 'SRx IPA Contracts Approver' && isContracts) {
                step.Phoenix_Status__c = approveStatusFlag == true ? 'Completed' : 'Completed';
                //Do Not Bid
                step.Phoenix_Approver__c=UserInfo.getUserId();
                contractsStepLsit.add(step);
               System.debug('step-->'+step); 
               System.debug('contractsStepLsit-->'+contractsStepLsit);

            }
            if (step.Phoenix_Approver_Team__c == 'Finance' && isFinance) {
                step.Phoenix_Status__c = approveStatusFlag == true ? 'Completed' : 'Completed';
                  step.Phoenix_Approver__c=UserInfo.getUserId();
                contractsStepLsit.add(step);
            }
        }
        if (!contractsStepLsit.isEmpty()) {
            update contractsStepLsit;
        }
       System.debug('updated contractsStepLsit-->'+contractsStepLsit.size());
		System.debug('bidProcessStepList-->'+bidProcessStepList);
        return bidProcessStepList;
    }
    @AuraEnabled
    public static void updateNextFinanceProcessSteps(string bidId, string bidName, list < Phoenix_Bid_Process_Steps__c > processStepLsit) {
        system.debug('In Finance');
        Map < Integer, List < Phoenix_Bid_Process_Steps__c >> stepMap = new Map < Integer, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, List < Phoenix_Bid_Process_Steps__c >> stepNamesMap = new Map < String, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, Integer > stepnameNoMap = new Map < String, Integer > ();
        for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
            
            Integer stepNo = Integer.valueOf(step.Phoenix_Step__c);
            if (stepMap.get(stepNo) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepMap.get(stepNo);
                adededSteps.add(step);
                stepMap.put(stepNo, adededSteps);
            } else {
                stepMap.put(stepNo, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            
            String stepName = step.Phoenix_Approver_Team__c;
            if (stepNamesMap.get(stepName) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepNamesMap.get(stepName);
                adededSteps.add(step);
                stepNamesMap.put(stepName, adededSteps);
            } else {
                stepNamesMap.put(stepName, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            stepnameNoMap.put(stepName, stepNo);
            
        }
        
        
        string notApproved = 'Not Approved';
        list < Phoenix_Bid_Line_Item__c > bidLinesUpdate = [select id,Phoenix_Contracts_Final_Approval__c,Phoenix_Customer_Final_Approval__c,Phoenix_Final_Status__c from Phoenix_Bid_Line_Item__c where Phoenix_Bid__c =: bidId];
        
        boolean isAllRejectedCaseFound = true;
        for (Phoenix_Bid_Line_Item__c lineItem: bidLinesUpdate) {
            if (lineItem.Phoenix_Final_Status__c != 'Not Approved') {
                isAllRejectedCaseFound = false;
            }
        }
        if (isAllRejectedCaseFound) {
            
            integer currentStepNum = stepnameNoMap.get('Finance');
            for (Phoenix_Bid_Process_Steps__c prcsStep: processStepLsit) {
                if (prcsStep.Phoenix_Approver_Team__c == 'Finance') {
                    prcsStep.Phoenix_Status__c = 'Completed';
                    prcsStep.Phoenix_Approver__c = userinfo.getuserid();
                }
                if (prcsStep.Phoenix_Step__c > currentStepNum) {
                    if (prcsStep.Name.contains('Closed')) {
                        prcsStep.Phoenix_Status__c = 'Completed';
                    } else {
                        prcsStep.Phoenix_Status__c = 'Not Applicable';
                    }
                }
            }
            update processStepLsit;
            Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Finance Rejected');
            update bid;
            
            
            
            
            
            
        }
        
        else{
            
            List < Phoenix_Bid_Process_Steps__c > nextSteps = new list < Phoenix_Bid_Process_Steps__c > ();
            Integer stepNo;
            
            stepNo = stepnameNoMap.get('Finance') + 1;
            system.debug('stepNo' + stepNo);
            system.debug('stepMap' + stepMap);
            nextSteps = stepMap.get(stepNo);
            
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Completed';
                } else {
                    step.Phoenix_Status__c = 'In Process';
                } //'In Process' Submitted //Diff b/w them            
            }
            if (!nextSteps.isEmpty()) {
                update nextSteps;
                
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Contracts');
                update bid;
                   Phoenix_SubmitBidForApprovalCtrl.approvalRequestNotification(bidId , nextSteps);
                
                //Phoenix_SubmitBidForApprovalCtrl.sendForApproval(bidId,'Approval Required for '+bidName,nextSteps,'Bid_Approval');
            } else {
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Closed');
                update bid;
            }
        }
    }
    @AuraEnabled
    public static void updateNextContractsProcessSteps(string bidId, string bidName, list < Phoenix_Bid_Process_Steps__c > processStepLsit) {
        system.debug('In Contracts');
        
        system.debug('In processStepLsit' + processStepLsit.size());
        
        Map < Integer, List < Phoenix_Bid_Process_Steps__c >> stepMap = new Map < Integer, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, List < Phoenix_Bid_Process_Steps__c >> stepNamesMap = new Map < String, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, Integer > stepnameNoMap = new Map < String, Integer > ();
        for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
            
            Integer stepNo = Integer.valueOf(step.Phoenix_Step__c);
            if (stepMap.get(stepNo) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepMap.get(stepNo);
                adededSteps.add(step);
                stepMap.put(stepNo, adededSteps);
            } else {
                stepMap.put(stepNo, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            
            String stepName = step.Phoenix_Approver_Team__c;
            if (stepNamesMap.get(stepName) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepNamesMap.get(stepName);
                adededSteps.add(step);
                stepNamesMap.put(stepName, adededSteps);
            } else {
                stepNamesMap.put(stepName, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            stepnameNoMap.put(stepName, stepNo);
            
        }
        
        
        list < Phoenix_Bid_Line_Item__c > bidLinesUpdate = [select id,Phoenix_Contracts_Final_Approval__c,Phoenix_Customer_Final_Approval__c,Phoenix_Final_Status__c from Phoenix_Bid_Line_Item__c where Phoenix_Bid__c =: bidId];
        
        boolean isAllRejectedCaseFound = true;
        for (Phoenix_Bid_Line_Item__c lineItem: bidLinesUpdate) {
            if (lineItem.Phoenix_Final_Status__c != 'Not Approved') {
                isAllRejectedCaseFound = false;
            }
        }
        if (isAllRejectedCaseFound) {
            
            
            integer currentStepNum =stepnameNoMap.get('SRx IPA Contracts Approver');
            for (Phoenix_Bid_Process_Steps__c prcsStep: processStepLsit) {
                if (prcsStep.Phoenix_Approver_Team__c == 'SRx IPA Contracts Approver' && prcsStep.Phoenix_Status__c!='Completed' ) {
                    prcsStep.Phoenix_Status__c = 'Completed';
                    prcsStep.Phoenix_Approver__c = userinfo.getuserid();
                }
                if (prcsStep.Phoenix_Step__c > currentStepNum) {
                    if (prcsStep.Name.contains('Closed')) {
                        prcsStep.Phoenix_Status__c = 'Completed';
                    } else {
                        prcsStep.Phoenix_Status__c = 'Not Applicable';
                    }
                }
            }
            update processStepLsit;
            Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Contracts Rejected');
            update bid;
            
            //close the bid other step not applicable
            
        }
        
        else{
            system.debug('stepnamemap--' + stepnameNoMap.get('SRx IPA Contracts Approver') + 1);
            system.debug('stepnamemap--' + stepMap.get(4));
            List < Phoenix_Bid_Process_Steps__c > nextSteps = new list < Phoenix_Bid_Process_Steps__c > ();
            Integer stepNo;
            
            stepNo = stepnameNoMap.get('SRx IPA Contracts Approver') + 1;
            system.debug('stepNo' + stepNo);
            system.debug('stepMap' + stepMap);
            nextSteps = stepMap.get(stepNo);
            
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Completed';
                } else {
                    step.Phoenix_Status__c = 'In Process';
                } //'In Process' Submitted //Diff b/w them            
            }
            if (!nextSteps.isEmpty()) {
                update nextSteps;
                
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Vistex Update');
                update bid;
                   Phoenix_SubmitBidForApprovalCtrl.approvalRequestNotification(bidId , nextSteps);
                
                //Phoenix_SubmitBidForApprovalCtrl.sendForApproval(bidId,'Approval Required for '+bidName,nextSteps,'Bid_Approval');
            } else {
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Closed');
                update bid;
            }
        }
        
    }
    @AuraEnabled
    public static void makeApprovalsIPAContracts(String bidId, string comments, string status) {
        
        Phoenix_Bid_Process_Steps__c currentStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId AND(Phoenix_Status__c = 'In Process'
                                                                                                                                                                                                                                                                    OR Phoenix_Status__c = 'Not Processed') limit 1];
        List < Phoenix_Bid_Process_Steps__c > processStepLsit = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];
        
        
        if (string.isNotBlank(status) && status == 'Processed') {
            system.debug('status------' + status);
            
            
            for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Completed';
                }
            }
            
            if (!processStepLsit.isEmpty()) {
                update processStepLsit;
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = comments;
                update currentStep;
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Contracts_Approval__c = status, Phoenix_Contracts_Approval_Comments__c = comments, Phoenix_Approval_Status__c = 'Closed');
                update bid;
            }
        } else {
            
            system.debug('currentStep----' + currentStep);
            
            for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Not Initiated';
                }
            }
            
            if (!processStepLsit.isEmpty()) {
                update processStepLsit;
                currentStep.Phoenix_Status__c = 'Not Processed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = comments;
                update currentStep;
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Contracts_Approval__c = status, Phoenix_Contracts_Approval_Comments__c = comments, Phoenix_Approval_Status__c = 'Contracts');
                update bid;
            }
        }
    }
    
    
    
    
    
    
    
    
    public class Wrapper {
        
        @AuraEnabled public List < Phoenix_Bid_Line_Item__c > lineItemsList;
        @AuraEnabled public Phoenix_Bid__c bidRecord;
        
        @AuraEnabled public string loggedInUserName;
        @AuraEnabled public string loggedInUserId;
        
        @AuraEnabled public boolean conditionApproval;
        @AuraEnabled public boolean isSRxApprovePerson;
        @AuraEnabled public boolean isFinanceApprovePerson;
        @AuraEnabled public boolean isVistexApprovePerson;
        @AuraEnabled public string isMarketingApprovePerson;
        @AuraEnabled public boolean showProceedBtn;
        
        Wrapper() {
            
            lineItemsList = new List < Phoenix_Bid_Line_Item__c > ();
            bidRecord = new Phoenix_Bid__c();
            
            loggedInUserName = '';
            
            loggedInUserId = '';
            
            isMarketingApprovePerson = '';
        }
    }
    @AuraEnabled
    public static void deleteLineItems(String LineItemId) {
        if (LineItemId != null) {
            Phoenix_Bid_Line_Item__c deletedLineItem = [SELECT Id FROM Phoenix_Bid_Line_Item__c WHERE Id =: LineItemId];
            delete deletedLineItem;
        }
    }
    @AuraEnabled
    public static list < Phoenix_Bid_Line_Item__c > saveLineItems(List < Phoenix_Bid_Line_Item__c > LineItemList) {
        for (Phoenix_Bid_Line_Item__c pbl: LineItemList) {
            pbl.Phoenix_ProposedContractBidPriceMktng__c = pbl.Phoenix_Proposed_IPA_Price__c;
            pbl.Phoenix_Proposed_Direct_Selling_Unit__c = pbl.Phoenix_IDN_Usage__c;
        }
        update LineItemList;
        return LineItemList;
    }
    @AuraEnabled
    public static list < Phoenix_Bid_Line_Item__c > submitToProceedVistex(string bidId) {
        String query = '';
        String SobjectApiName = 'Phoenix_Bid_Line_Item__c';
        Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
        Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
        
        String strFields = '';
        
        for (String fieldName: fieldMap.keyset()) {
            if (strFields == null || strFields == '') {
                strFields = fieldName;
            } else {
                strFields = strFields + ' , ' + fieldName;
            }
        }
        string notApproved = 'Not Approved';
        string loggerUserName = UserInfo.getName();
        query = 'select Phoenix_Product__r.Phoenix_Rx_SRx_OTC__c,Phoenix_Bid__r.Phoenix_Customer__r.Phoenix_Contracts_Approver__r.Name, Phoenix_Product__r.name,Phoenix_Bid__r.Phoenix_Bid_Name__c, ' + strFields + ' from ' + SobjectApiName + ' where Phoenix_Bid__c = : bidId AND Phoenix_Final_Status__c !=: notApproved';
        
        list < Phoenix_Bid_Line_Item__c > bidLinesList = Database.query(query);
        return bidLinesList;
    }
    @AuraEnabled
    public static WrapperForNextSteps makeApprovalsVistex(String bidId, List < Phoenix_Bid_Line_Item__c > bidlines, boolean approveStatusFlag) {
        boolean vistexNextStepFlag = false;
        for (Phoenix_Bid_Line_Item__c line: bidlines) {
            
              if(line.Phoenix_Vistex_Status__c == 'Updated'){
                    
                    line.Phoenix_Vistex_Update_Final_Approval__c=true;
                }
         
            if (line.Phoenix_Vistex_Status__c == 'Pending') {
                //line.Phoenix_Final_Status__c = 'Not Approved';
                vistexNextStepFlag = true;
            }
            
            
            
        }
        if (bidlines.size() > 0) {
            update bidlines;
        }
        
        
        list < Phoenix_Bid_Process_Steps__c > bidProcessStepList = [SELECT Id, Name, Phoenix_Is_Criteria_Step__c,Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c,Phoenix_Approver__r.Email, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];
        list < Phoenix_Bid_Process_Steps__c > contractsStepLsit = new list < Phoenix_Bid_Process_Steps__c > ();
        for (Phoenix_Bid_Process_Steps__c step: bidProcessStepList) {
            
            
            
            if (step.Phoenix_Approver_Team__c == 'Home Office' && vistexNextStepFlag == false) {
                step.Phoenix_Status__c = approveStatusFlag == true ? 'Completed' : 'Do Not Bid';
                step.Phoenix_Approver__c=UserInfo.getUserId();
                contractsStepLsit.add(step);
            }
            
        }
        if (!contractsStepLsit.isEmpty()) {
            update contractsStepLsit;
        }
        WrapperForNextSteps wrapSteps = new WrapperForNextSteps();
        
        wrapSteps.updateProcessStepList = bidProcessStepList;
        
        wrapSteps.contractNextStepFlag = vistexNextStepFlag;
        
        
        return wrapSteps;
        
    }
    @AuraEnabled
    public static void updateNextVistexProcessSteps(string bidId, string bidName, list < Phoenix_Bid_Process_Steps__c > processStepLsit, boolean vistexNextStepFlag) {
        system.debug('In Contracts');
        
        system.debug('In processStepLsit' + processStepLsit.size());
        if (vistexNextStepFlag == false && !processStepLsit.isEmpty()) {
            Map < Integer, List < Phoenix_Bid_Process_Steps__c >> stepMap = new Map < Integer, List < Phoenix_Bid_Process_Steps__c >> ();
            Map < String, List < Phoenix_Bid_Process_Steps__c >> stepNamesMap = new Map < String, List < Phoenix_Bid_Process_Steps__c >> ();
            Map < String, Integer > stepnameNoMap = new Map < String, Integer > ();
            for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
                
                Integer stepNo = Integer.valueOf(step.Phoenix_Step__c);
                if (stepMap.get(stepNo) != null) {
                    List < Phoenix_Bid_Process_Steps__c > adededSteps = stepMap.get(stepNo);
                    adededSteps.add(step);
                    stepMap.put(stepNo, adededSteps);
                } else {
                    stepMap.put(stepNo, new List < Phoenix_Bid_Process_Steps__c > {
                        step
                            });
                }
                
                String stepName = step.Phoenix_Approver_Team__c;
                if (stepNamesMap.get(stepName) != null) {
                    List < Phoenix_Bid_Process_Steps__c > adededSteps = stepNamesMap.get(stepName);
                    adededSteps.add(step);
                    stepNamesMap.put(stepName, adededSteps);
                } else {
                    stepNamesMap.put(stepName, new List < Phoenix_Bid_Process_Steps__c > {
                        step
                            });
                }
                stepnameNoMap.put(stepName, stepNo);
                
            }
            system.debug('stepnamemap--' + stepnameNoMap.get('Home Office') + 1);
            
            List < Phoenix_Bid_Process_Steps__c > nextSteps = new list < Phoenix_Bid_Process_Steps__c > ();
            Integer stepNo;
            
            stepNo = stepnameNoMap.get('Home Office') + 1;
            system.debug('stepNo' + stepNo);
            system.debug('stepMap' + stepMap);
            nextSteps = stepMap.get(stepNo);
            
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Completed';
                } else {
                    step.Phoenix_Status__c = 'In Process';
                } //'In Process' Submitted //Diff b/w them            
            }
            if (!nextSteps.isEmpty()) {
                update nextSteps;
                
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Closed');
                update bid;
            }
            //Phoenix_SubmitBidForApprovalCtrl.sendForApproval(bidId,'Approval Required for '+bidName,nextSteps,'Bid_Approval');
        } else {
            Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Approval_Status__c = 'Closed');
            update bid;
        }
    }
    
}