UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_GCP_Opportunity_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Opp_Sales__c</fullName>
        <label>Customer Opp Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Opp_TPT_Perc__c</fullName>
        <label>Customer Opp TPT (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Opp_TPT__c</fullName>
        <label>Customer Opp TPT ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GCP Opportunity Trackers</relationshipLabel>
        <relationshipName>GCP_Market_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cogs_per_unit__c</fullName>
        <label>COGS Per Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>GCP Opportunity Tracker</label>
    <nameField>
        <displayFormat>GCP Opp Tracker-{0000000}</displayFormat>
        <label>GCP Opportunity Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Opportunity Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_12Months_Actual_Sales_Unit__c</fullName>
        <inlineHelpText>Rollup of last 12 months quantity</inlineHelpText>
        <label>12Months Actual Sales Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_12Months_Net_Sales__c</fullName>
        <label>12Months Net Sales$</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_12Months_Sales_Unit__c</fullName>
        <label>12Months Sales Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_12Mt_Sales_Ut_Actual__c</fullName>
        <inlineHelpText>12Mt Sales Ut Actual (Oct&apos;19 till Sept&apos;20)</inlineHelpText>
        <label>12Mt Sales Ut Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <label>NDC-11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_GCN_Sequence_Number__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GCN Sequence Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_GPI_Generic_Product_Identifier__c</fullName>
        <description>It contains 14 characters.</description>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GPI (Generic Product Identifier)  </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Exclude_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is Exclude Bid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <inlineHelpText>National Drug Code: SAP field</inlineHelpText>
        <label>NDC - 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Product Director</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Marketing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Rx_SRx_OTC__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Rx/SRx/OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OTC</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>SRx</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Is_CPT_Batch_Executed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be updated when Customer Product Tracker Creator Batch process the record.</description>
        <label>Is CPT Batch Executed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_NPR_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NPR Data</label>
        <referenceTo>Phoenix_NPR_Data__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/CusCntrPrdcreatorActcontractsBatchtest.cls
@istest
public class CusCntrPrdcreatorActcontractsBatchtest {
    static testmethod void testsetup(){
         // Account data
        List<Account> Acclist = new  List<Account>();
        Account acc =new Account();
        acc.name='test';
        Acclist.add(acc);
        insert Acclist;
        // Phoenix Data
        List<Phoenix_Contract__c> Ctlist  = new List<Phoenix_Contract__c>();
        Phoenix_Contract__c ct = new Phoenix_Contract__c ();
        ct.Phoenix_Contract_Number__c='122456';
        ct.Phoenix_Contract_Start_Date__c=Date.newInstance(2022, 02, 21);
        ct.Phoenix_Contract_End_Date__c=system.today();
      
        ctlist.add(ct);
          Phoenix_Contract__c ct1 = new Phoenix_Contract__c ();
        ct1.Phoenix_Contract_Number__c=null;
        ct1.Phoenix_Contract_Start_Date__c=Date.newInstance(2022, 02, 21);
        ct1.Phoenix_Contract_End_Date__c=system.today();
      
        ctlist.add(ct1);
        Phoenix_Contract__c ct2 = new Phoenix_Contract__c ();
        ct2.Phoenix_Contract_Number__c='100002333';
        ct2.Phoenix_Contract_Start_Date__c=Date.newInstance(2022, 02, 21);
        ct2.Phoenix_Contract_End_Date__c=system.today();
      
        ctlist.add(ct2);
        insert ctlist;
        user u=[select id,name from user where id =: userinfo.getUserId()];
        
        // Product Data
        list<Product2> plist = new list  < Product2>();
        
        Product2 p=new Product2();
        p.Name='abc pharma';
        p.Phoenix_NDC_11__c='23364848';
        p.ProductCode='123456';
        p.Phoenix_NDC__c='5555555';
        p.Phoenix_GPI_Generic_Product_Identifier__c = '11111';
        p.Family = 'Test Family';
        p.Phoenix_Throughput_cost__c=10.23456576;
        p.Phoenix_GCN_Sequence_Number__c='666666';
        p.Phoenix_Pkg_Size__c=25.0;
        p.Vision_Is_CPT_Batch_Executed__c = false;
        p.Phoenix_Is_Exclude_Bid__c = false;
        p.IsActive=true;
        p.Phoenix_Rx_SRx_OTC__c = 'Rx';
        p.Description='my testing';
        p.Phoenix_Product_Director__c=u.id;
        plist.add(p);
        insert plist;

        
        // NprData Data
        List<Phoenix_NPR_Data__c> nprdtlist = new  List<Phoenix_NPR_Data__c>();
        Phoenix_NPR_Data__c  npdata = new Phoenix_NPR_Data__c();
        npdata.Phoenix_12Months_Actual_Sales_Unit__c=20.00;
        npdata.Phoenix_12Months_Net_Sales__c=250.00;
        npdata.Phoenix_12Months_Sales_Unit__c=25.00;
        npdata.Phoenix_12Mt_Sales_Ut_Actual__c=22.0;
        npdata.Phoenix_Account__c=acc.Id;
        npdata.Phoenix_Contract__c=ct.Id;
        nprdtlist.add(npdata);
        insert nprdtlist;
        
  
        List<Vision_Customer_Product_Tracker__c> cpotlist= new List<Vision_Customer_Product_Tracker__c>();
        List<Phoenix_GCP_Opportunity_Tracker__c> optlist= new List<Phoenix_GCP_Opportunity_Tracker__c>();
        for ( Product2 pp:plist){
            Vision_Customer_Product_Tracker__c cpt = new Vision_Customer_Product_Tracker__c();
            cpt.Vision_Account__c=Acc.Id;
            cpt.Vision_Contract__c=ct.Id;
            
            cpt.Vision_NPR_Data__c=npdata.Id;
            cpt.Vision_Product__c=pp.Id;
            cpt.Vision_Product_Code__c='123456';
            cpt.Vision_Contract_Number__c='122456';
            Vision_Customer_Product_Tracker__c cpt1 = new Vision_Customer_Product_Tracker__c();
            cpt1.Vision_Account__c=Acc.Id;
            cpt.Vision_Contract__c=ct1.Id;
            
            cpt1.Vision_NPR_Data__c=npdata.Id;
            cpt1.Vision_Product__c=pp.Id;
            cpt1.Vision_Product_Code__c='126656';
            cpt.Vision_Contract_Number__c='133356';
            cpotlist.add(cpt1);
            Phoenix_GCP_Opportunity_Tracker__c opt = new Phoenix_GCP_Opportunity_Tracker__c();
            opt.cogs_per_unit__c=230;
            opt.GCP_Product_Family__c='rt12';
            opt.Phoenix_Customer__c=acc.Id;
            opt.Phoenix_Customer_Opp_Sales__c=25;
            opt.Phoenix_Customer_Opp_TPT__c=25;
            opt.Phoenix_Customer_Opp_TPT_Perc__c=50;
            opt.GCP_Product_Family__c='Uynn';
            optlist.add(opt);
            
        }
        insert cpotlist;
        insert optlist;
        test.startTest();
        //CustomerProductActiveContractsBatchCls Cuscnrcbatch = new CustomerProductActiveContractsBatchCls();
       // database.executeBatch(Cuscnrcbatch);
       CustomerProductActiveContractsBatchCls bl= new CustomerProductActiveContractsBatchCls();
        database.executeBatch(bl);
        bl.execute(null);
        test.stopTest();
        
    }
    
}