UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contracts_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contracts Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Phoenix_Contracts_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Name__c</fullName>
        <label>Bid Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Initial Order Discount for WAC Customers (No-Contract Price Offering)</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                    <label>One Time Buy – Good Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                    <label>One Time Buy – Short Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>One Time Buy Good Dated Shelf Life for New Product Launch</fullName>
                    <label>One Time Buy – Good Dated Shelf Life for New Product Launch</label>
                </value>
                <value>
                    <fullName>OTC New Product</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Good Dated</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Short Dated</fullName>
                </value>
                <value>
                    <fullName>OTC Price Change</fullName>
                </value>
                <value>
                    <fullName>OTC Product Addition</fullName>
                </value>
                <value>
                    <fullName>OTC Rebate Change</fullName>
                </value>
                <value>
                    <fullName>OTC RFP</fullName>
                </value>
                <value>
                    <fullName>OTC Volume Review</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                    <label>Product Removals</label>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>Sales Out Rebate</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                    <label>SRx Direct Pricing</label>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                    <label>SRx IPA Floor Pricing Update</label>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                    <label>SRx IPA Member Addition</label>
                </value>
                <value>
                    <fullName>SRx IPA Price Change</fullName>
                </value>
                <value>
                    <fullName>SRx IPA Product Addition</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                    <label>SRx NEW Individual Pricing Agreement (IPA)</label>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                    <label>SRx RCA/IPA Member GPO or Wholesaler Change</label>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                    <label>SRx RCA Member Addition</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Final_Status__c</fullName>
        <label>Final Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Is_IPA_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is IPA Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_IPARejectedLineItemsCls.cls
/**
 * @description       : 
 * @author            : Surender Patel (Dhruvsoft)
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
public class Phoenix_IPARejectedLineItemsCls {
    @AuraEnabled
    public static Wrapper getRelatedList(Id bidId) {
        Wrapper wrapperObject = new Wrapper();

        String query = '';
        String SobjectApiName = 'Phoenix_Bid_Line_Item__c';
        Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
        Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();

        String strFields = '';

        for (String fieldName: fieldMap.keyset()) {
            if (strFields == null || strFields == '') {
                strFields = fieldName;
            } else {
                strFields = strFields + ' , ' + fieldName;
            }
        }
        string notApproved = 'Not Approved';
        query = 'select Phoenix_Contract__r.Name,Phoenix_Bid__r.Phoenix_Customer__r.Phoenix_Contracts_Approver__r.Name,Phoenix_Contract__r.Id,Phoenix_Customer__r.Name,Phoenix_Customer__r.Id, Phoenix_Product__r.name,Phoenix_Bid__r.Phoenix_Bid_Name__c, ' + strFields + ' from ' + SobjectApiName + ' where Phoenix_Bid__c = : bidId and Phoenix_Product__r.Phoenix_Is_IPA_Product__c=true and Phoenix_Final_Status__c =: notApproved ORDER BY Phoenix_Product__r.Name ASC ';

        list < Phoenix_Bid_Line_Item__c > quoteList = Database.query(query);
        Phoenix_Bid__c bid = [SELECT Id, Name, Phoenix_Approval_Status__c, Phoenix_Customer__r.Name, Phoenix_Bid_Name__c, Phoenix_Bid_Type__c FROM Phoenix_Bid__c WHERE Id =: bidId];

        wrapperObject.lineItemsList = quoteList;
        wrapperObject.bidRecord = bid;

        return wrapperObject;

    }

    public class Wrapper {

        @AuraEnabled public List < Phoenix_Bid_Line_Item__c > lineItemsList;
        @AuraEnabled public Phoenix_Bid__c bidRecord;
        @AuraEnabled public string loggedInUserName;
        @AuraEnabled public string isContractsApprovePerson;
        @AuraEnabled public boolean showProceedBtn;
        Wrapper() {

            lineItemsList = new List < Phoenix_Bid_Line_Item__c > ();
            bidRecord = new Phoenix_Bid__c();
            loggedInUserName = '';
            isContractsApprovePerson = '';
        }
    }
    @AuraEnabled
    public static void deleteLineItems(String LineItemId) {
        if (LineItemId != null) {
            Phoenix_Bid_Line_Item__c deletedLineItem = [SELECT Id FROM Phoenix_Bid_Line_Item__c WHERE Id =: LineItemId];
            delete deletedLineItem;
        }
    }
    @AuraEnabled
    public static list < Phoenix_Bid_Line_Item__c > saveLineItems(List < Phoenix_Bid_Line_Item__c > LineItemList) {

        update LineItemList;
        return LineItemList;
    }
}