UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_RCA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Parent RCA Agreement</inlineHelpText>
        <label>RCA Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Phoenix_Contract__c.Phoenix_Is_RCA_Contract__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bids3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contracts_Approval_Comments__c</fullName>
        <label>Contracts Approval Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contracts_Approval__c</fullName>
        <label>Contracts Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Not_Processed</fullName>
                    <label>Not Processed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_RCA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RCA / IPA Contract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Phoenix_Contract__c.Phoenix_Is_RCA_Contract__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Phoenix_Contract__c.Phoenix_Is_IPA_Contract__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Vistex_Update_Comments__c</fullName>
        <label>Vistex Update Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Vistex_Update__c</fullName>
        <label>Vistex Update</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid_Process_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Process Steps</relationshipLabel>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bid Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_RCA_IPA_LINE__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>RCA IPA LINES</relationshipLabel>
        <relationshipName>RCA_IPA_LINES</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RCA IPA LINES</relationshipLabel>
        <relationshipName>RCA_IPA_LINES</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_New_RCA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New RCA / IPA Contract No.</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>RCA IPA LINES (New RCA Agreement)</relationshipLabel>
        <relationshipName>RCA_IPA_LINES1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Parent_IPA_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent IPA Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RCA IPA LINES (Parent IPA Customer)</relationshipLabel>
        <relationshipName>RCA_IPA_LINES1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_RAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RAM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RCA_IPA_LINES</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_RCA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RCA / IPA Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>RCA IPA LINES</relationshipLabel>
        <relationshipName>RCA_IPA_LINES</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RCA IPA LINE</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>RCA IPA LINE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RCA IPA LINES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_User_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Group_Behavior__c</fullName>
        <label>Approval Group Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single User</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
                <value>
                    <fullName>Account based</fullName>
                </value>
                <value>
                    <fullName>Product based</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver_Group_Name__c</fullName>
        <label>Approver Group Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phoenix_Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Phoenix_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Active_User__c</fullName>
        <formula>Phoenix_Approver__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Approval_Process_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approval Process User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Phoenix_User_Approval_Matrix__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Approval User Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phoenix_User_Approval_Matrix__c</referenceTo>
        <relationshipLabel>User_Groups</relationshipLabel>
        <relationshipName>User_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Approval Matrix</label>
    <nameField>
        <label>User Approval Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/globalValueSets/Phoenix_Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Business Head</fullName>
    </customValue>
    <customValue>
        <fullName>Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Country Head</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Government Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Home Office</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Head</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead OTC</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead SRx</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sr Director or VP Finance</fullName>
    </customValue>
    <customValue>
        <fullName>SRx IPA Contracts Approver</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Demand Planning</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Marketing Head</fullName>
        <isActive>false</isActive>
        <label>Sales &amp; Marketing Head</label>
    </customValue>
    <customValue>
        <fullName>VP / Director Finance</fullName>
        <isActive>false</isActive>
        <label>VP / Director Finance</label>
    </customValue>
    <customValue>
        <fullName>SCM &amp; Marketing</fullName>
        <isActive>false</isActive>
        <label>SCM &amp; Marketing</label>
    </customValue>
    <masterLabel>Phoenix_Teams</masterLabel>
</GlobalValueSet>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_RCAWholesalerEditLineCls.cls
/**
 * @description       : 
 * @author            : Surender Patel (Dhruvsoft)
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
public class Phoenix_RCAWholesalerEditLineCls {

    private static final String base64Chars = '' +
        'ABCDEFGHIJKLMNOPQRSTUVWXYZ' +
        'abcdefghijklmnopqrstuvwxyz' +
        '0123456789+/';
    @AuraEnabled
    public static Wrapper getRelatedList(Id bidId) {
        Wrapper wrapperObject = new Wrapper();

        String query = '';
        String SobjectApiName = 'Phoenix_RCA_IPA_LINE__c';
        Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
        Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();

        String strFields = '';

        for (String fieldName: fieldMap.keyset()) {
            if (strFields == null || strFields == '') {
                strFields = fieldName;
            } else {
                strFields = strFields + ' , ' + fieldName;
            }
        }
        query = 'select Phoenix_Bid__r.Name,Phoenix_RAM__r.Name,Phoenix_Parent_IPA_Customer__r.Name,Phoenix_RCA_Agreement__r.Name,Phoenix_New_RCA_Agreement__r.Name,Phoenix_Customer__r.Name , ' + strFields + ' from ' + SobjectApiName + ' where Phoenix_Bid__c = : bidId limit 20000';

        list < Phoenix_RCA_IPA_LINE__c > quoteList = Database.query(query);
        system.debug('quoteList--->' + quoteList);
        Map < String, String > userTeamUserIdMap = new Map < String, String > ();
        for (Phoenix_User_Approval_Matrix__c matrix: [Select Id, Name, RecordType.DeveloperName, User_Group__r.Phoenix_Approver_Group_Name__c, Phoenix_Approval_Group_Behavior__c, Phoenix_Approver__c, Phoenix_Approver__r.Email, Phoenix_Approver_Group_Name__c, Phoenix_Is_Active_User__c, Phoenix_Is_Approval_Process_User__c, User_Group__c from Phoenix_User_Approval_Matrix__c limit 1000]) {
            String userTeamUserIdMapKey = matrix.User_Group__r.Phoenix_Approver_Group_Name__c + '-' + matrix.Phoenix_Approver__c;
            userTeamUserIdMap.put(userTeamUserIdMapKey, matrix.Phoenix_Approver__c);
        }

        boolean isSRxApprovePerson = false;
          boolean isVistexApprovePerson = false;


        if (userTeamUserIdMap.containsKey('SRx IPA Contracts Approver-' + UserInfo.getUserId())) {
            isSRxApprovePerson = true;
        }
        if (userTeamUserIdMap.containsKey('Home Office-' + UserInfo.getUserId())) {
            isVistexApprovePerson = true;
        }
        



        Phoenix_Bid__c bid = [SELECT Id, Phoenix_Contracts_Approval_Comments__c, Phoenix_Contracts_Approval__c,Phoenix_Vistex_Update__c,Phoenix_Vistex_Update_Comments__c, Phoenix_Approval_Status__c, Name, Phoenix_Customer__r.Name, Phoenix_Bid_Name__c, Phoenix_Bid_Type__c FROM Phoenix_Bid__c WHERE Id =: bidId];

        wrapperObject.lineItemsList = quoteList;
        wrapperObject.bidRecord = bid;
        wrapperObject.isSRxApprovePerson = isSRxApprovePerson;
		wrapperObject.isVistexApprovePerson = isVistexApprovePerson;
        return wrapperObject;

    }
    public class Wrapper {

        @AuraEnabled public List < Phoenix_RCA_IPA_LINE__c > lineItemsList;
        @AuraEnabled public Phoenix_Bid__c bidRecord;
        @AuraEnabled public boolean isSRxApprovePerson;
		@AuraEnabled public boolean isVistexApprovePerson;
        Wrapper() {

            lineItemsList = new List < Phoenix_RCA_IPA_LINE__c > ();
            bidRecord = new Phoenix_Bid__c();

        }
    }
    @AuraEnabled
    public static Phoenix_Bid__c saveTobid(string bidId, string comments, string status,string approvalStatus,string visAppStatus,string visComm) {
     Phoenix_Bid__c bidRecord = new Phoenix_Bid__c();
        if(approvalStatus == 'Contracts'){
         bidRecord = new Phoenix_Bid__c(Id = bidId, Phoenix_Contracts_Approval__c = status, Phoenix_Contracts_Approval_Comments__c = comments);   
        }
        if(approvalStatus == 'Vistex Update'){
           bidRecord = new Phoenix_Bid__c(Id = bidId, Phoenix_Vistex_Update__c = visAppStatus, Phoenix_Vistex_Update_Comments__c = visComm);   
           
        } 
        update bidRecord;
        return bidRecord;
    }
    @AuraEnabled
    public static void makeApprovalsIPAContracts(String bidId, string comments, string status) {

        Phoenix_Bid_Process_Steps__c currentStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Step__c, Phoenix_Status__c, Phoenix_Approver_Team__c,Phoenix_Is_Criteria_Step__c, Phoenix_Process_Step__c, Phoenix_Approver__c,Phoenix_Approver__r.Email FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId AND(Phoenix_Status__c = 'In Process'
            OR Phoenix_Status__c = 'Not Processed') limit 1];
        List < Phoenix_Bid_Process_Steps__c > processStepLsit = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Step__c, Phoenix_Status__c, Phoenix_Approver_Team__c,Phoenix_Is_Criteria_Step__c, Phoenix_Process_Step__c, Phoenix_Approver__c,Phoenix_Approver__r.Email FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];


        if (string.isNotBlank(status) && status == 'Processed') {
            system.debug('status------' + status);


            for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
                if (step.Name.contains('Vistex')) {
                    step.Phoenix_Status__c = 'In Process';
                }
            }

            if (!processStepLsit.isEmpty()) {
                update processStepLsit;
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = comments;
                update currentStep;
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Contracts_Approval__c = status, Phoenix_Contracts_Approval_Comments__c = comments, Phoenix_Approval_Status__c = 'Vistex Update');
                update bid;
            }
            Phoenix_SubmitBidForApprovalCtrl.approvalRequestNotification(bidId , processStepLsit); 


        } 
        else {

            system.debug('currentStep----' + currentStep);

            for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Completed';
                }
                if (step.Name.contains('Vistex')) {
                    step.Phoenix_Status__c = 'Not Applicable';
                }
            }

            if (!processStepLsit.isEmpty()) {
                update processStepLsit;
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = comments;
                update currentStep;
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Contracts_Approval__c = status, Phoenix_Contracts_Approval_Comments__c = comments, Phoenix_Approval_Status__c = 'Contracts Rejected');
                update bid;
            }
        }
    }
@AuraEnabled
    public static void makeApprovalsVistex(String bidId, string comments, string status) {

        Phoenix_Bid_Process_Steps__c currentStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId AND(Phoenix_Status__c = 'In Process'
            OR Phoenix_Status__c = 'Not Processed') limit 1];
        List < Phoenix_Bid_Process_Steps__c > processStepLsit = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];


        if (string.isNotBlank(status) && status == 'Processed') {
            system.debug('status------' + status);


            for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Completed';
                }
            }

            if (!processStepLsit.isEmpty()) {
                update processStepLsit;
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = comments;
                update currentStep;
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Vistex_Update__c = status, Phoenix_Vistex_Update_Comments__c = comments, Phoenix_Approval_Status__c = 'Closed');
                update bid;
            }
        } else {

            system.debug('currentStep----' + currentStep);

            for (Phoenix_Bid_Process_Steps__c step: processStepLsit) {
                if (step.Name.contains('Closed')) {
                    step.Phoenix_Status__c = 'Completed';
                }
            }

            if (!processStepLsit.isEmpty()) {
                update processStepLsit;
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = comments;
                update currentStep;
                Phoenix_Bid__c bid = new Phoenix_Bid__c(id = bidId, Phoenix_Vistex_Update__c = status, Phoenix_Vistex_Update_Comments__c = comments, Phoenix_Approval_Status__c = 'Vistex Rejected');
                update bid;
                Map<Id,Phoenix_Bid_Line_Item__c> bidLinesMap = new Map<Id,Phoenix_Bid_Line_Item__c>([SELECT Id FROM Phoenix_Bid_Line_Item__c WHERE Phoenix_Bid__c=:bidId]);
                set<Id> bidLineItemIdset = bidLinesMap.keySet();
               
                Phoenix_SubmitBidForApprovalCtrl.BidRejectionEmailNotificationToAll(bidLineItemIdset,bidId);
            }
        }
    }







    @AuraEnabled
    public static void deleteLineItems(String LineItemId) {
        if (LineItemId != null) {
            Phoenix_RCA_IPA_LINE__c deletedLineItem = [SELECT Id FROM Phoenix_RCA_IPA_LINE__c WHERE Id =: LineItemId];
            delete deletedLineItem;
        }
    }
    @AuraEnabled
    public static list < Phoenix_RCA_IPA_LINE__c > saveLineItems(List < Phoenix_RCA_IPA_LINE__c > LineItemList) {
        list < Phoenix_RCA_IPA_LINE__c > updateList = new list < Phoenix_RCA_IPA_LINE__c > ();
        for (Phoenix_RCA_IPA_LINE__c rca: LineItemList) {
            Phoenix_RCA_IPA_LINE__c ril = new Phoenix_RCA_IPA_LINE__c();
            ril = rca;
            if (ril.Phoenix_New_GPO__c == '--None--') {
                ril.Phoenix_New_GPO__c = '';
            }
            if (ril.Phoenix_Wholesaler__c == '-- None --') {
                system.debug('ril.Phoenix_Wholesaler__c' + ril.Phoenix_Wholesaler__c);
                ril.Phoenix_Wholesaler__c = '';
                ril.Phoenix_Wholesaler_Location__c = '';
            } else if (ril.Phoenix_Wholesaler_Location__c == '-- None --') {
                ril.Phoenix_Wholesaler_Location__c = '';
                system.debug('ril.Phoenix_Wholesaler__c' + ril.Phoenix_Wholesaler__c);
                system.debug('ril.Phoenix_Wholesaler_Location__c' + ril.Phoenix_Wholesaler_Location__c);

                system.debug('ril.Phoenix_Wholesaler_Location__c' + ril.Phoenix_Wholesaler_Location__c);
            }

            updateList.add(ril);
        }
        update updateList;
        system.debug('updateList' + updateList);
        return updateList;
    }
    @AuraEnabled
    public static PicklistWrapper getDependentPicklist() {
        Map < String, List < String >> pickListMap = new Map < String, List < String >> ();
        List < String > GPOvalues = new List < String > ();
        PicklistWrapper pw = new PicklistWrapper();
        pw.pickListMap = pickListMap;



        Schema.sObjectType objType = Schema.getGlobalDescribe().get('Phoenix_RCA_IPA_LINE__c').newSObject().getSObjectType();
        Map < String, Schema.SObjectField > objFieldMap = objType.getDescribe().fields.getMap();

        if (!objFieldMap.containsKey('Phoenix_Wholesaler__c') || !objFieldMap.containsKey('Phoenix_Wholesaler_Location__c')) {
            return pw;
        }

        List < PicklistEntryWrapper > depEntries = (List < PicklistEntryWrapper > ) JSON.deserialize(JSON.serialize(objFieldMap.get('Phoenix_Wholesaler_Location__c').getDescribe().getPicklistValues()), List < PicklistEntryWrapper > .class);
        List < String > controllingValues = new List < String > ();

        for (Schema.PicklistEntry ple: objFieldMap.get('Phoenix_Wholesaler__c').getDescribe().getPicklistValues()) {
            pickListMap.put(ple.getLabel(), new List < String > ());
            controllingValues.add(ple.getLabel());
        }

        for (PicklistEntryWrapper plew: depEntries) {
            String validForBits = base64ToBits(plew.validFor);
            for (Integer i = 0; i < validForBits.length(); i++) {
                String bit = validForBits.mid(i, 1);
                if (bit == '1') {
                    pickListMap.get(controllingValues.get(i)).add(plew.label);
                }
            }
        }
        Schema.DescribeFieldResult fieldResult = Phoenix_RCA_IPA_LINE__c.Phoenix_New_GPO__c.getDescribe();
        List < Schema.PicklistEntry > pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pList) {
            GPOvalues.add(p.getLabel());
        }
        pw.pickListMap = pickListMap;
        pw.parentFieldLabel = objFieldMap.get('Phoenix_Wholesaler__c').getDescribe().getLabel();
        pw.childFieldLabel = objFieldMap.get('Phoenix_Wholesaler_Location__c').getDescribe().getLabel();
        pw.GPOvalues = GPOvalues;
        return pw;
    }

    //Refer from here https://salesforce.stackexchange.com/questions/4462/get-lists-of-dependent-picklist-options-in-apex
    public static String decimalToBinary(Integer val) {
        String bits = '';
        while (val > 0) {
            Integer remainder = Math.mod(val, 2);
            val = Integer.valueOf(Math.floor(val / 2));
            bits = String.valueOf(remainder) + bits;
        }
        return bits;
    }

    public static String base64ToBits(String validFor) {
        if (String.isEmpty(validFor)) return '';

        String validForBits = '';

        for (Integer i = 0; i < validFor.length(); i++) {
            String thisChar = validFor.mid(i, 1);
            Integer val = base64Chars.indexOf(thisChar);
            String bits = decimalToBinary(val).leftPad(6, '0');
            validForBits += bits;
        }

        return validForBits;
    }

    public class PicklistWrapper {
        @AuraEnabled
        public Map < String, List < String >> pickListMap;
        @AuraEnabled
        public String parentFieldLabel;
        @AuraEnabled
        public String childFieldLabel;
        @AuraEnabled
        public list < String > GPOvalues;
    }

    public class PicklistEntryWrapper {
        public String active;
        public String defaultValue;
        public String label;
        public String value;
        public String validFor;

    }
  
}