UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Is_Govt_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Lowest Price/SKU and CM fee</inlineHelpText>
        <label>Is Govt Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Preferred_Wholesaler__c</fullName>
        <label>Preferred Wholesaler for CM Fee</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABC</fullName>
                </value>
                <value>
                    <fullName>ANDA</fullName>
                </value>
                <value>
                    <fullName>Cardinal</fullName>
                </value>
                <value>
                    <fullName>McKesson</fullName>
                </value>
                <value>
                    <fullName>Morris and Dickson</fullName>
                </value>
                <value>
                    <fullName>Oncology Supply</fullName>
                </value>
                <value>
                    <fullName>Source program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Allocation Review</fullName>
                </value>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Customer Requested Pricing Confirmations</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                </value>
                <value>
                    <fullName>Exceptional Billings</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>In-Licensing</fullName>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                </value>
                <value>
                    <fullName>NDC Change</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                </value>
                <value>
                    <fullName>New Launch &amp; WAC</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>New Product WAC Pricing</fullName>
                </value>
                <value>
                    <fullName>One Time Buy - Price Load Req</fullName>
                </value>
                <value>
                    <fullName>One Time Buy - Price Override Sale</fullName>
                </value>
                <value>
                    <fullName>PHS Price Change</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>RCA/IPA Member Addition</fullName>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                </value>
                <value>
                    <fullName>Re-Bid (Pricing Only)</fullName>
                </value>
                <value>
                    <fullName>Request for Single Contract Product Removal</fullName>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>WAC Change Submissions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Matrix</label>
    <nameField>
        <label>Process #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Approval_Process_Step__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Matrix__c</fullName>
        <label>Approval Matrix</label>
        <referenceTo>Phoenix_Approval_Matrix__c</referenceTo>
        <relationshipLabel>Approval Process Steps</relationshipLabel>
        <relationshipName>Phoenix_Approval_Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approval Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Contracts Approved</fullName>
                </value>
                <value>
                    <fullName>SCM Approved</fullName>
                </value>
                <value>
                    <fullName>Marketing Approved</fullName>
                </value>
                <value>
                    <fullName>Finance Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Submitted</fullName>
                </value>
                <value>
                    <fullName>Proposal Accepted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid_Process_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Process Steps</relationshipLabel>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Do Not Bid</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bid Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Pheonix_BidWACChangeControllerTest.cls
@isTest
public class Pheonix_BidWACChangeControllerTest {
    @testSetup static void setupTestData() {
        Id phoenixRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Bid Accounts').getRecordTypeId();
        Account testAccount = new Account(Name = 'Test Account',Phoenix_Preferred_Wholesaler__c='ABC',Phoenix_Is_Govt_Customer__c=true);
        insert testAccount;
        
        Phoenix_Bid__c pb = new Phoenix_Bid__c();
        pb.Phoenix_Status__c = 'New';
        pb.Phoenix_Comments__c = 'Test Comments';
        pb.Phoenix_Approval_Status__c = 'Draft';
        pb.Phoenix_Customer__c = testAccount.Id;
        insert pb;
        
        
        
        
        
        //--------Approval Test Data-----START
        Phoenix_Approval_Matrix__c appro= new Phoenix_Approval_Matrix__c();
        appro.Phoenix_Bid_Type__c='WAC Change Submissions';
        appro.Name='Pricing Review';
        insert appro;
        
        Phoenix_Approval_Process_Step__c proI= new Phoenix_Approval_Process_Step__c();
        proI.Name='Initial Submission';
        proI.Phoenix_Order__c=1;
        proI.Phoenix_Approval_Matrix__c=appro.Id;
        insert proI;
        
        Phoenix_Approval_Process_Step__c pro= new Phoenix_Approval_Process_Step__c();
        pro.Name='Business Head';
        pro.Phoenix_Order__c=2;
        pro.Phoenix_Approval_Matrix__c=appro.Id;
        insert pro;
        
        Phoenix_Approval_Process_Step__c pro3= new Phoenix_Approval_Process_Step__c();
        pro3.Name='Country Head';
        pro3.Phoenix_Order__c=3;
        pro3.Phoenix_Approval_Matrix__c=appro.Id;
        insert pro3;
        
        Phoenix_Approval_Process_Step__c proF= new Phoenix_Approval_Process_Step__c();
        proF.Name='Finance';
        proF.Phoenix_Order__c=4;
        proF.Phoenix_Approval_Matrix__c=appro.Id;
        insert proF;
        
        Phoenix_Approval_Process_Step__c pro1= new Phoenix_Approval_Process_Step__c();
        pro1.Name='Contracts';
        pro1.Phoenix_Order__c=5;
        pro1.Phoenix_Approval_Matrix__c=appro.Id;
        insert pro1;
        
        Phoenix_Approval_Process_Step__c proClosed= new Phoenix_Approval_Process_Step__c();
        proClosed.Name='Closed';
        proClosed.Phoenix_Order__c=6;
        proClosed.Phoenix_Approval_Matrix__c=appro.Id;
        insert proClosed;
        
        List<Phoenix_Bid_Process_Steps__c> processSteps= new List<Phoenix_Bid_Process_Steps__c>();
        Phoenix_Bid_Process_Steps__c processStep1=new Phoenix_Bid_Process_Steps__c();
        processStep1.Phoenix_Bid__c=pb.Id;
        processStep1.Phoenix_Process_Step__c=proI.Id;
        processStep1.Phoenix_Status__c='Submitted';
        // processStep1.Phoenix_Sub_Step__c=1;
        processSteps.add(processStep1);
        insert processSteps;
        
        List<Phoenix_Bid_Process_Steps__c> processStepNext= new List<Phoenix_Bid_Process_Steps__c>();
        Phoenix_Bid_Process_Steps__c processStep=new Phoenix_Bid_Process_Steps__c();
        processStep.Phoenix_Bid__c=pb.Id;
        processStep.Phoenix_Process_Step__c=pro.Id;
        processStep.Phoenix_Status__c='In Process';
        // processStep.Phoenix_Sub_Step__c=2;
        processStepNext.add(processStep);
        insert processStepNext;
        
        
        List<Phoenix_Bid_Process_Steps__c> processStepNext2= new List<Phoenix_Bid_Process_Steps__c>();
        Phoenix_Bid_Process_Steps__c processStep2=new Phoenix_Bid_Process_Steps__c();
        processStep2.Phoenix_Bid__c=pb.Id;
        processStep2.Phoenix_Process_Step__c=pro.Id;
        processStep2.Phoenix_Status__c='Not Initiated';
        // processStep.Phoenix_Sub_Step__c=2;
        processStepNext2.add(processStep2);
        insert processStepNext2;
        
        List<Phoenix_Bid_Process_Steps__c> processStepNext3= new List<Phoenix_Bid_Process_Steps__c>();
        Phoenix_Bid_Process_Steps__c processStep3=new Phoenix_Bid_Process_Steps__c();
        processStep3.Phoenix_Bid__c=pb.Id;
        processStep3.Phoenix_Process_Step__c=pro3.Id;
        processStep3.Phoenix_Status__c='In Process';
        // processStep.Phoenix_Sub_Step__c=2;
        processStepNext3.add(processStep3);
        insert processStepNext3;
        
        
        List<Phoenix_Bid_Process_Steps__c> processStepNextStep4= new List<Phoenix_Bid_Process_Steps__c>();
        Phoenix_Bid_Process_Steps__c processStep4=new Phoenix_Bid_Process_Steps__c();
        processStep4.Phoenix_Bid__c=pb.Id;
        processStep4.Phoenix_Process_Step__c=proF.Id;
        processStep4.Phoenix_Status__c='Not Initiated';
        //  processStep3.Phoenix_Sub_Step__c=3;
        processStepNextStep4.add(processStep4);
        insert processStepNextStep4;
        
        
        List<Phoenix_Bid_Process_Steps__c> processStepNextStep5= new List<Phoenix_Bid_Process_Steps__c>();
        Phoenix_Bid_Process_Steps__c processStep5=new Phoenix_Bid_Process_Steps__c();
        processStep5.Phoenix_Bid__c=pb.Id;
        processStep5.Phoenix_Process_Step__c=pro1.Id;
        processStep5.Phoenix_Status__c='Not Initiated';
        // processStep3.Phoenix_Sub_Step__c=3;
        processStepNextStep5.add(processStep5);
        insert processStepNextStep5;
        
        List<Phoenix_Bid_Process_Steps__c> processStepClose= new List<Phoenix_Bid_Process_Steps__c>();
        Phoenix_Bid_Process_Steps__c processStepCl=new Phoenix_Bid_Process_Steps__c();
        processStepCl.Phoenix_Bid__c=pb.Id;
        processStepCl.Phoenix_Process_Step__c=proClosed.Id;
        processStepCl.Phoenix_Status__c='Not Initiated';
        // processStep3.Phoenix_Sub_Step__c=4;
        processStepClose.add(processStepCl);
        insert processStepClose;
        
        //-------Approval Test Data End-----------------
        
        
    }
    static testmethod void AddProductMethod(){
        
        Id phoenixRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Bid Accounts').getRecordTypeId();
        Account testAccount = new Account(Name = 'Test Account',Phoenix_Preferred_Wholesaler__c='ABC',Phoenix_Is_Govt_Customer__c=true);
        insert testAccount;
        
        list<Product2> prodList = new list<Product2>();
        Product_Family__c pf1 = new Product_Family__c();
        pf1.Name = 'Test Family';
        insert pf1;
        Product_Family__c pf2 = new Product_Family__c();
        pf2.Name = 'Sample Family';
        insert pf2;
        Product_Family__c pf3 = new Product_Family__c();
        pf3.Name = 'cetirizine';
        insert pf3;
        Product2 prod1 = new Product2(Name = 'Test Product',Product_Family__c = pf1.Id, Phoenix_Rx_SRx_OTC__c='Rx',Phoenix_Special_Product__c=true,Phoenix_GPI_Generic_Product_Identifier__c='11111',Phoenix_NDC_11__c='12345678902', Family = 'Test Family', IsActive = TRUE);
        Product2 prod2 = new Product2(Name = 'Test Product1',Product_Family__c = pf2.Id, Phoenix_Rx_SRx_OTC__c='Rx',Phoenix_Special_Product__c=true,Phoenix_GPI_Generic_Product_Identifier__c='22222',Phoenix_NDC_11__c='21345678902', Family = 'Sample Family', IsActive = TRUE);
        Product2 prod3 = new Product2(Name = 'Test Product2',Product_Family__c = pf3.Id, Phoenix_Rx_SRx_OTC__c='SRx',Phoenix_Special_Product__c=true,Phoenix_NDC_11__c='32145678902', Family = ' cetirizine', IsActive = TRUE);
        Product2 prod4 = new Product2(Name = 'Test Product3',Product_Family__c = pf3.Id, Phoenix_Rx_SRx_OTC__c='OTC',Phoenix_Special_Product__c=true,Phoenix_GPI_Generic_Product_Identifier__c='333333', Family = ' cetirizine', IsActive = TRUE);
        
        prodList.add(prod1);
        prodList.add(prod2);
        prodList.add(prod3);
        prodList.add(prod4);
        if(!prodList.isEmpty())
            insert prodList;
        
        Phoenix_Bid__c pb = new Phoenix_Bid__c();
        pb.Phoenix_Status__c = 'New';
        pb.Phoenix_Comments__c = 'Test Comments';
        pb.Phoenix_Approval_Status__c = 'Draft';
        pb.Phoenix_Customer__c = testAccount.Id;
        insert pb;
        
        
        list<Phoenix_BidWACCreatorCtrl.wrapperClass> wrap = new list<Phoenix_BidWACCreatorCtrl.wrapperClass>();
        list<string> productIds = new list<string>();
        for (Integer i = 0; i < prodList.size(); i++){
            Phoenix_BidWACCreatorCtrl.wrapperClass pbw = new Phoenix_BidWACCreatorCtrl.wrapperClass();
            pbw.prdlist = prodList[i];
            pbw.isSelected = true;
            pbw.currencyCode = '$';
            wrap.add(pbw);
            productIds.add(prodList[i].Id);
            
        }
        
        Phoenix_BidWACCreatorCtrl.BidWrapper pbWrapper2 = new Phoenix_BidWACCreatorCtrl.BidWrapper();
        pbWrapper2 = Pheonix_BidWACChangeController.getBidInfo(pb.Id);
        
        Phoenix_BidWACCreatorCtrl.BidWrapper pbWrapper3 = new Phoenix_BidWACCreatorCtrl.BidWrapper();
        pbWrapper3.bid = pb;
        pbWrapper3.isBidCreated = true;
        Pheonix_BidWACChangeController.getproducts1(pbWrapper3);
        
        string search = 'test';
        string searchFamily = 'test';
        list<string>RxSrxList=new list<string>();
        RxSrxList.add('Rx');
        list<string>directorList=new list<string>();
        directorList.add('Suseela Dhruvsoft');
        string searchNDC='12345678902 21345678902';
        Pheonix_BidWACChangeController.getSearch(wrap,directorList, search,searchFamily,RxSrxList,pbWrapper3);
        RxSrxList.add('SRx');
        Pheonix_BidWACChangeController.getSearch(wrap,directorList, '333333',searchFamily,RxSrxList,pbWrapper3);
        Pheonix_BidWACChangeController.getSearch(wrap,directorList, searchNDC,searchFamily,RxSrxList,pbWrapper3);
        Pheonix_BidWACChangeController.findBySrxOtc(RxSrxList,directorList,search,searchFamily,wrap,pbWrapper3);
        Pheonix_BidWACChangeController.getSearchFamily(wrap,directorList, searchFamily,search,RxSrxList,pbWrapper3);
        Pheonix_BidWACChangeController.getsearchDirectorResult(wrap,directorList, searchFamily,search,RxSrxList,pbWrapper3);
        Pheonix_BidWACChangeController.getProductDirectorList(pbWrapper3);
        Pheonix_BidWACChangeController.showselectedProducts(pb.Id);
        
        
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [
            SELECT Id, Title, LatestPublishedVersionId 
            FROM ContentDocument
        ];
        String docId=documents[0].Id;
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = pb.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        list<Phoenix_Bid_Line_Item__c> lineItemsList = new list<Phoenix_Bid_Line_Item__c>();
        for (Integer i = 0; i < prodList.size(); i++){
            Phoenix_Bid_Line_Item__c pbl = new Phoenix_Bid_Line_Item__c(Phoenix_Bid__c = pb.Id, Phoenix_Product__c = prodList[i].Id,Phoenix_Proposed_IPA_Price__c=100,Phoenix_IDN_Usage__c=10);
            lineItemsList.add(pbl);
        }
        insert lineItemsList;
        
        Phoenix_BidWACCreatorCtrl.BidWrapper pbWrapper = new Phoenix_BidWACCreatorCtrl.BidWrapper();
        pbWrapper = Pheonix_BidWACChangeController.getBidInfo(pb.Id);
        Phoenix_BidWACCreatorCtrl.BidWrapper pbWrapper1 = new Phoenix_BidWACCreatorCtrl.BidWrapper();
        pbWrapper1.bid = pb;
        pbWrapper1.isBidCreated = true;
        Pheonix_BidWACChangeController.getproducts1(pbWrapper1);
        list<Phoenix_BidWACCreatorCtrl.wrapperClass> wrap1 = new list<Phoenix_BidWACCreatorCtrl.wrapperClass>();
        list<string> productIds1 = new list<string>();
        for (Integer i = 0; i < prodList.size(); i++){
            Phoenix_BidWACCreatorCtrl.wrapperClass pbw = new Phoenix_BidWACCreatorCtrl.wrapperClass();
            pbw.prdlist = prodList[i];
            pbw.isSelected = true;
            pbw.currencyCode = '$';
            wrap1.add(pbw);
            productIds1.add(prodList[i].Id);
            
        }
        string search1 = 'test';
        string searchFamily1 = 'test';
        list<string>RxSrxList1=new list<string>();
        RxSrxList1.add('Rx');
        // string searchNDC='12345678902 21345678902';
        // Pheonix_BidWACChangeController.getSearch(wrap1, search,searchFamily,RxSrxList1);
        RxSrxList.add('SRx');
        // Pheonix_BidWACChangeController.getSearch(wra1, '333333',searchFamily,RxSrxList1);
        // Pheonix_BidWACChangeController.getSearch(wrap1, searchNDC,searchFamily,RxSrxList1);
        // Pheonix_BidWACChangeController.findBySrxOtc(RxSrxList1,search1,searchFamily1,wrap1);
        // Pheonix_BidWACChangeController.getSearchFamily(wrap1, searchFamily1,search1,RxSrxList1);
        list<Phoenix_BidWACCreatorCtrl.wrapperClass> wrap2 = new list<Phoenix_BidWACCreatorCtrl.wrapperClass>();
        for (Integer i = 0; i < prodList.size(); i++){
            Phoenix_BidWACCreatorCtrl.wrapperClass pbw = new Phoenix_BidWACCreatorCtrl.wrapperClass();
            Phoenix_Bid_Line_Item__c pbl = new Phoenix_Bid_Line_Item__c(Phoenix_Bid__c = pb.Id);
            pbw.qlItem=pbl;
            pbw.prdlist = prodList[i];
            wrap2.add(pbw);
        }
        
        Pheonix_BidWACChangeController.savequoteitems(wrap1, pbWrapper1);
        Pheonix_BidWACChangeController.fetchSortResults('Name',true,wrap);
        Pheonix_BidWACChangeController.getproductsrelatedtoBid(pbWrapper1);
        Pheonix_BidWACChangeController.deleteLineItems(lineItemsList[0].Id);
        Pheonix_BidWACChangeController.getDocs(pb.Id);
        Pheonix_BidWACChangeController.deleteAttachments(docId, pb.Id);
        Pheonix_BidWACChangeController.getProductDirectorList(pbWrapper);
        List<string> SearchKeyWordPD = new List<String>{'Test1','Test2','Test3'};
            Pheonix_BidWACChangeController.getsearchDirectorResult(wrap1,SearchKeyWordPD,'Find','Test Name',SearchKeyWordPD,pbWrapper1);
        
        //Pheonix_BidWACChangeController.editQuoteItems(wrap1, pbWrapper1);
        // Pheonix_BidWACChangeController.editQuoteItems(wrap1, pbWrapper1);
        
        System.assertEquals(1, 1);
        
    }
    static testmethod void businessApproval(){
        Phoenix_Bid__c pb=[SELECT Id FROM Phoenix_Bid__c LIMIT 1];
        Pheonix_BidWACChangeController.makeApprovalsBusiness(pb.Id,'test','Approved','Business Head');
        Pheonix_BidWACChangeController.makeApprovalsCountry(pb.Id,'test','Approved','Country Head');
        Pheonix_BidWACChangeController.makeApprovalsFinance(pb.Id,'test','Approved','Finance');
        Pheonix_BidWACChangeController.makeApprovalsContracts(pb.Id,'test','Processed','Contracts');
        Pheonix_BidWACChangeController.saveToBidBus(pb.Id,'test','Approved');
        Pheonix_BidWACChangeController.saveToBidCountry(pb.Id,'test','Approved');
        Pheonix_BidWACChangeController.saveToBidContr(pb.Id,'test','Processed');
        Pheonix_BidWACChangeController.saveToBidFin(pb.Id,'test','Approved');
        System.assertEquals(1, 1);
    }
    static testmethod void contractsApproval(){
        Phoenix_Bid__c pb=[SELECT Id FROM Phoenix_Bid__c LIMIT 1];
        Pheonix_BidWACChangeController.makeApprovalsBusiness(pb.Id,'test','Not Approved','Business Head');
        Pheonix_BidWACChangeController.saveToBidBus(pb.Id,'test','Not Approved');
        Pheonix_BidWACChangeController.saveToBidCountry(pb.Id,'test','Not Approved');
        Pheonix_BidWACChangeController.saveToBidContr(pb.Id,'test','Not Processed');
        Pheonix_BidWACChangeController.saveToBidFin(pb.Id,'test','Not Approved');
        System.assertEquals(1, 1);
    }
}