UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Phoenix_GR_HighTier_in__c</fullName>
        <label>GR (HighTier)% in $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Material_Number__c</fullName>
        <label>Material Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Net_Price_w_o_fee_CD__c</fullName>
        <label>Net Price w/o Fee-CD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Best_Price__c</fullName>
        <inlineHelpText>Best Price for Government Pricing</inlineHelpText>
        <label>Best Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Track_Best_price__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this to Track Best Price for this Product (Government Pricing)</inlineHelpText>
        <label>Track Best price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Type__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Type (ANDA / NDA)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_Best_Price_Batch_Test.cls
/**
 * @description       : 
 * @author            : Surender Dhruvsoft
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Dhruvsoft
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   25-05-2021   Surender Dhruvsoft   Initial Version
**/
@isTest
public class Phoenix_Best_Price_Batch_Test {
    static testmethod void test1() {
        Test.startTest();
        Account acc = new Account(name = 'Test Account');
        Insert acc;

        Product2 prod = new Product2(name = 'Test Product', ProductCode = '1234');
        prod.Phoenix_Best_Price__c = 10;
        prod.Phoenix_Type__c = 'NDA';
        prod.Phoenix_Track_Best_price__c = true;
        Insert prod;

        Phoenix_Contract__c cont = new Phoenix_Contract__c(name = 'Test contract');
        Phoenix_Contract__c cont2 = new Phoenix_Contract__c(name = 'Test contract2');
        List < Phoenix_Contract__c > contData = new List < Phoenix_Contract__c > {
            cont,
            cont2
        };

        insert contData;

        Phoenix_NPR_Data__c npr = new Phoenix_NPR_Data__c();
        npr.Phoenix_Material_Number__c = prod.ProductCode;
        npr.Phoenix_Product__c = prod.Id;
        npr.Phoenix_Account__c = acc.Id;
        npr.Phoenix_Contract__c = cont.Id;
        npr.Phoenix_Net_Price_w_o_fee_CD__c = 9;
        npr.Phoenix_Contract_Number__c = '1234';
        npr.Phoenix_GR_HighTier_in__c = 2;
        Phoenix_NPR_Data__c npr2 = new Phoenix_NPR_Data__c();
        npr2.Phoenix_Material_Number__c = prod.ProductCode;
        npr2.Phoenix_Product__c = prod.Id;
        npr2.Phoenix_Account__c = acc.Id;
        npr2.Phoenix_Contract__c = cont2.Id;
        npr2.Phoenix_Contract_Number__c = '12345';
        npr2.Phoenix_Net_Price_w_o_fee_CD__c = 8;
        npr2.Phoenix_GR_HighTier_in__c = 1;
        List < Phoenix_NPR_Data__c > nprData = new List < Phoenix_NPR_Data__c > {
            npr,
            npr2
        };
        Insert nprData;
        Phoenix_Best_Price_Batch bestPriceBatch = new Phoenix_Best_Price_Batch();
        bestPriceBatch.execute(null);
        Test.stopTest();
    }

}