UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Reference_Contract__c</fullName>
        <label>Reference Contract</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Name__c</fullName>
        <label>Bid Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Reference_Contracts__c</fullName>
        <label>Contracts</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <label>NDC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <formula>Phoenix_Pkg_Size1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pkg Size (Internal Use)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Director__c</fullName>
        <formula>Phoenix_Product_Director1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Director (Internal Use)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <formula>Phoenix_Throughput_Cost1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Throughput Cost (Internal Use)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid_Process_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Process Steps</relationshipLabel>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bid Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>OTC_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Private Label Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (OTC Customer)</relationshipLabel>
        <relationshipName>OTC_Customer_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_GCN_Sequence_Number__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GCN Sequence Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_GPI_Generic_Product_Identifier__c</fullName>
        <description>It contains 14 characters.</description>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GPI (Generic Product Identifier)  </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Exclude_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is Exclude Bid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Private_Label_OTC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Private Label</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <inlineHelpText>National Drug Code: SAP field</inlineHelpText>
        <label>NDC - 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Product Director</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Marketing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Is_CPT_Batch_Executed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be updated when Customer Product Tracker Creator Batch process the record.</description>
        <label>Is CPT Batch Executed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/Vision_NotifyDraftbids_Batch_Test.cls
@IsTest
private class Vision_NotifyDraftbids_Batch_Test {
    static testmethod void setup(){
         // Product Data
      
        // Account Data
        list<Account> alist= new list<account>();
        Account acc = new Account(Name='Test Account');
        alist.add(acc);
        insert alist;
          user u=[select id from user where id =: userinfo.getUserId()];
       list<Product2> plist = new list<Product2>();
        Product2 p=new Product2();
        p.Name='abc pharma';
        p.OTC_Customer__c=acc.id;
        p.IsActive=true;
        p.Phoenix_Is_Exclude_Bid__c=false;
        p.Vision_Is_CPT_Batch_Executed__c=false;
        p.Phoenix_Is_Private_Label_OTC__c=true;
       // p.Phoenix_NDC_11__c='23364348';
       // p.ProductCode='123567';
        // p.Phoenix_NDC_11__c='23364848';
        p.ProductCode='123566';
        p.Phoenix_Product_Director__c=u.id;
     //  p.Phoenix_NDC__c='5555555';
        p.Phoenix_GPI_Generic_Product_Identifier__c = '11111';
        p.Family = 'Test Family';
        p.Phoenix_Throughput_cost__c=10.23456576;
        p.Phoenix_GCN_Sequence_Number__c='666666';
        p.Phoenix_Pkg_Size__c=25.0;
        plist.add(p);
        insert plist;
        //Phoenix Contract data
        Phoenix_Contract__c ctr = new Phoenix_Contract__c();
        ctr.Name = 'Test Contract';
        ctr.Phoenix_Contract_Number__c = '46579';
        ctr.Phoenix_Customer__c = acc.Id;
        insert ctr;
        //Contact data
        contact c= new contact();
        c.lastname='test';
        c.AccountId=acc.id;
        insert c; 
        // Opp data
        List<Opportunity> oplist=new List<Opportunity>();
        Opportunity op=new opportunity();
        op.AccountId=acc.id;
        op.Contact__c=c.id;
        op.Vision_Reference_Contract__c='46579';
        op.StageName = 'Closed Won';
        op.Name='test1';
        op.CloseDate=system.today();
        oplist.add(op);
        insert oplist;
        // Bid data
        list<Phoenix_Bid__c> blist = new list<Phoenix_Bid__c>();
        Phoenix_Bid__c bidtest = new  Phoenix_Bid__c();
        bidtest.Phoenix_Approval_Status__c='Customer\'s Update';
        bidtest.Phoenix_Contact__c= c.Id;
        bidtest.Opportunity__c=op.Id;
        bidtest.Phoenix_Customer__c=alist[0].id;
        bidtest.Phoenix_Reference_Contracts__c='46579';
        bidtest.Phoenix_Bid_Name__c='test';
        bidtest.Phoenix_Customer_Type__c='New';
        bidtest.Phoenix_Bid_Type__c='New Customer';
        blist.add(bidtest);
        insert blist;
        // Bidline item data
        list<Phoenix_Bid_Line_Item__c> bllist = new list<Phoenix_Bid_Line_Item__c>();
        for(Phoenix_Bid__c bb :blist){
            Phoenix_Bid_Line_Item__c bidLine = new Phoenix_Bid_Line_Item__c();
            bidLine.Phoenix_Product__c = plist[0].Id;
            bidLine.Phoenix_Contract__c = ctr.Id;
            
            
            bidline.Phoenix_Bid__c=bidtest.Id;
            bllist.add(bidline);
            Vision_Customer_Product_Tracker__c cpt1 = new Vision_Customer_Product_Tracker__c();
            cpt1.Vision_Account__c=acc.Id;
            cpt1.Vision_Contract__c=ctr.Id;
            cpt1.Vision_Contract_Product_Status__c='In Opportunity';
            cpt1.Vision_Product__c=plist[0].Id;
            cpt1.Vision_Product_Code__c='300027884';
            cpt1.Vision_Contract_Number__c='46579';
            
            
            insert cpt1;
        }
        
        insert bllist;
        Phoenix_Approval_Matrix__c mm= new Phoenix_Approval_Matrix__c();
        insert mm;
        Phoenix_Approval_Process_Step__c n= new Phoenix_Approval_Process_Step__c();
        n.name= 'Customer\'s Update';
        n.Phoenix_Approval_Matrix__c = mm.id;
        insert n;
           Phoenix_Bid_Process_Steps__c ps = new Phoenix_Bid_Process_Steps__c();
        ps.Phoenix_Approver__c = UserInfo.getUserId();
        ps.Phoenix_Bid__c = blist[0].Id;
        ps.Phoenix_Approval_Sent_Time__c = system.now().adddays(-30);
        ps.Phoenix_Process_Step__c = n.id;
        ps.Phoenix_Status__c='In Process';
        //ps.Phoenix_Approval_Matrix__c = mm.id;
        insert ps;
        
        test.startTest();
        list<Document> lstDocument = [SELECT Id FROM Document WHERE DeveloperName = 'Vision_Logo'];
        Vision_NotifyDraftbids_Batch b= new Vision_NotifyDraftbids_Batch();
        database.executeBatch(b);
        //b.codecoverageBlock();
        test.stopTest();
        
    }
}