UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Overview__c</fullName>
        <label>Account Overview</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Account_Strategy__c</fullName>
        <label>Account Strategy</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Customer_s_Buying_Strategy__c</fullName>
        <label>Customer&apos;s Buying Strategy</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Growth_Goals__c</fullName>
        <label>Growth Goals</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Pricing_Strategy__c</fullName>
        <label>Pricing Strategy</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Risks_and_Challenges__c</fullName>
        <label>Risks and Challenges</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Outlook_DRL_Account_ProfileTest.cls
@isTest
public class Outlook_DRL_Account_ProfileTest 
{
	static testmethod void test()
    {
         Account acc = new Account();
        acc.Name = 'Test Account';
        
        //acc.Account__c=acc.Id;
        acc.Account_Overview__c='Test';
        acc.Account_Strategy__c='Test';
        acc.Pricing_Strategy__c='Test';
        acc.Customer_s_Buying_Strategy__c='Test';
        acc.Growth_Goals__c='Test';
        acc.Risks_and_Challenges__c='Test';
        insert  acc; 
        Outlook_DRL_Account_Profile_Controller.getAccounts();
        Outlook_DRL_Account_Profile_Controller.getAccountPlanDetails(acc.Id);
        Outlook_DRL_Account_Profile_Controller.sendDataAndSave(acc.Account_Strategy__c,acc.Pricing_Strategy__c,acc.Customer_s_Buying_Strategy__c,acc.Account_Strategy__c,acc.Growth_Goals__c,acc.Risks_and_Challenges__c,acc.Id);

        
    }
}