UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Awarded_Quantity__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Response_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response Line</label>
        <referenceTo>Phoenix_Customer_Response_Line__c</referenceTo>
        <relationshipLabel>Awarded Quantity</relationshipLabel>
        <relationshipName>Awarded_Quantity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Awarded_Quantity__c</fullName>
        <label>Awarded Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid Line Item</label>
        <referenceTo>Phoenix_Bid_Line_Item__c</referenceTo>
        <relationshipLabel>Awarded Quantity</relationshipLabel>
        <relationshipName>Awarded_Quantity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response</label>
        <referenceTo>Phoenix_Customer_Response__c</referenceTo>
        <relationshipLabel>Awarded Quantity</relationshipLabel>
        <relationshipName>Awarded_Quantity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Material_Code__c</fullName>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Awarded Quantity</relationshipLabel>
        <relationshipName>Awarded_Quantity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Supply_Effective_Date__c</fullName>
        <description>This info fetching from Customer Response line</description>
        <label>Supply Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Awarded Quantity</label>
    <nameField>
        <displayFormat>Awarded Quantity-{0000000}</displayFormat>
        <label>Awarded Quantity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awarded Quantity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Awarded_Quantity__c</fullName>
        <label>Awarded Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Status__c</fullName>
        <label>Bid Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Declined by Customer</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>DRL Rescinded</fullName>
                </value>
                <value>
                    <fullName>DRL submitting under New Bid Number</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Current_ASP_Dose__c</fullName>
        <formula>IF( Phoenix_Bid_Template_Refrence__c = &apos;ClarusOne&apos;, IF( Phoenix_Net_Sales_External__c != 0, (Phoenix_Net_Sales_External__c / Phoenix_Total_Selling_Unit__c), 0), IF(NOT(ISBLANK(Finance_Current_Sales__c)), (Finance_Current_Sales__c/ Phoenix_Total_Selling_Unit__c) ,IF(Phoenix_Current_Sales_Finance__c!= 0, (Phoenix_Current_Sales_Finance__c/ Phoenix_Total_Selling_Unit__c), 0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current ASP/ Dose</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Response_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response Line</label>
        <referenceTo>Phoenix_Customer_Response_Line__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response</label>
        <referenceTo>Phoenix_Customer_Response__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Proposed_ASP_Dose__c</fullName>
        <formula>Phoenix_Proposed_Sales__c / IF(Phoenix_SCM_Final_Approval__c,Phoenix_Total_SCM_Approved_Qty__c,Phoenix_Final_Total_Selling_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Proposed ASP/ Dose</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Supply_Effective_Date__c</fullName>
        <label>Supply Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Total_Selling_Unit__c</fullName>
        <formula>IF(Phoenix_Override_Total_units__c &gt;0,Phoenix_Override_Total_units__c ,Phoenix_Current_Direct_Selling_Unit__c +  Phoenix_Current_Indirect_Selling_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Selling Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Customer_Response__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Affected_Contract_s__c</fullName>
        <label>Contract #&apos;s for Position/Volume</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Customer Response</label>
    <nameField>
        <displayFormat>CR-{0000000}</displayFormat>
        <label>Customer Response No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Customer_Response_Line__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Awarded_Quantity__c</fullName>
        <label>Awarded Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid Line Item</label>
        <referenceTo>Phoenix_Bid_Line_Item__c</referenceTo>
        <relationshipLabel>Customer Response Lines</relationshipLabel>
        <relationshipName>Customer_Response_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response</label>
        <referenceTo>Phoenix_Customer_Response__c</referenceTo>
        <relationshipLabel>Customer Response Lines</relationshipLabel>
        <relationshipName>Customer_Response_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Supply_Effective_Date__c</fullName>
        <label>Supply Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Customer Response Line</label>
    <nameField>
        <displayFormat>CRLineItem-{0000000}</displayFormat>
        <label>Customer Response Line No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Response Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Awarded_Quantity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Awarded Quantity</label>
        <referenceTo>Phoenix_Awarded_Quantity__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bid_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid Line Item</label>
        <referenceTo>Phoenix_Bid_Line_Item__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Response_Effective_Date__c</fullName>
        <label>Customer Response Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Response_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response Line</label>
        <referenceTo>Phoenix_Customer_Response_Line__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Awarded_Volume__c</fullName>
        <label>Awarded Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Product_Status__c</fullName>
        <label>Contract Product Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Current_Product_Position__c</fullName>
        <label>Current Product Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Cus_Response_Lines_Created_Date__c</fullName>
        <label>Customer Response Lines Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Response_Created_Date__c</fullName>
        <label>Customer Response Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Response_Name__c</fullName>
        <label>Customer Response Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response</label>
        <referenceTo>Phoenix_Customer_Response__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_In_Customer_Response_Lines__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Customer Response Lines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Internal_DeadNet__c</fullName>
        <label>Internal DeadNet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Is_In_Awarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is In Awarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_On_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Contract?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Previous_DeadNet__c</fullName>
        <label>Previous DeadNet</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Previous_Volume__c</fullName>
        <label>Previous Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Supply_Effective_Date__c</fullName>
        <label>Supply Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <formula>Vision_Product_Code__c+&quot;_&quot;+Vision_Contract_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Identifier</label>
        <type>Text</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/AwardedQtyContractPrdStatusBatchCls.cls
/*
In this Class we will update Customerproducttracker Object fields when we find  Same Contract Number and Product Code that Mathches with Customerresponse lines,
We will Update Vision_Contract_Product_Status__c as 'Awarded',
Vision_Is_In_Awarded__c as 'True',
Vision_Supply_Effective_Date__c from Customerresponseline Phoenix_Supply_Effective_Date__c,
Vision_Awarded_Volume__c, from Phoenix_Awarded_Quantity__c field of  Phoenix_Awarded_Quantity__c object where Phoenix_Material_Code__c and Phoenix_Contract_Number__c which Matches with Customerresponseline's Contract Number and Product Code,
Vision_On_Contract__c as true,
Vision_Previous_Volume__c,Vision_Customer_Response_Name__c,Vision_Previous_DeadNet__c,Vision_Internal_DeadNet__c,Customer_Response_Line__c,Vision_Customer_Response_Created_Date__c,Vision_Customer_Response_Name__c from CustomerResponseLine.
*/
public class AwardedQtyContractPrdStatusBatchCls implements Database.Batchable < sObject > , Database.Stateful,Schedulable,Database.AllowsCallouts {
    public void execute(SchedulableContext sc) {
        //Database.executeBatch(new AwardedQtyContractPrdStatusBatchCls());
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //Query - If a New Account has become bid account in last 24 Hours
        string s='300018384';
        //String query = 'Select Phoenix_Bid_Line_Item__r.Phoenix_Awarded_Quantity__c,Phoenix_Bid_Line_Item__r.Phoenix_Total_Selling_Unit__c,Phoenix_Bid_Line_Item__r.Phoenix_Current_ASP_Dose__c,Phoenix_Bid_Line_Item__r.Phoenix_Proposed_ASP_Dose__c,Phoenix_Bid_Line_Item__r.Phoenix_Product__r.ProductCode, ' +Phoenix_Util.getsObjectFieds('Phoenix_Customer_Response_Line__c')+' from Phoenix_Customer_Response_Line__c Where CreatedDate = LAST_N_DAYS:1';
        String query = 'Select Phoenix_Bid_Line_Item__r.Phoenix_Awarded_Quantity__c,Phoenix_Bid_Line_Item__r.Phoenix_Total_Selling_Unit__c,Phoenix_Bid_Line_Item__r.Phoenix_Current_ASP_Dose__c,Phoenix_Bid_Line_Item__r.Phoenix_Proposed_ASP_Dose__c,Phoenix_Bid_Line_Item__r.Phoenix_Product__r.ProductCode, ' +Phoenix_Util.getsObjectFieds('Phoenix_Customer_Response_Line__c')+' from Phoenix_Customer_Response_Line__c';
        if(Test.isRunningTest())query += ' LIMIT 1';
        return Database.getQueryLocator(query);
        
    }
    public void execute(Database.BatchableContext BC, List <Phoenix_Customer_Response_Line__c> cusRespLinesList) {
        try{
            if(cusRespLinesList.size() > 0){
                List<Vision_Customer_Product_Tracker__c> cptUpdateList = new List<Vision_Customer_Product_Tracker__c>();
                map<String,list<Phoenix_Customer_Response_Line__c>> existingCusRespMap = new map<String,list<Phoenix_Customer_Response_Line__c>>();
                for(Phoenix_Customer_Response_Line__c cusResRec : cusRespLinesList){
                    if(!existingCusRespMap.containsKey(cusResRec.Phoenix_Customer_Response__c)){
                        existingCusRespMap.put(cusResRec.Phoenix_Customer_Response__c,new list<Phoenix_Customer_Response_Line__c>{cusResRec});
                    }
                    else{
                        existingCusRespMap.get(cusResRec.Phoenix_Customer_Response__c).add(cusResRec);
                    }
                }
               // system.debug('existingcusrespmap'+existingCusRespMap);
                map<String, Phoenix_Customer_Response__c> UniqueIdsMap = new map<String, Phoenix_Customer_Response__c>();
                map<String, Phoenix_Customer_Response_Line__c> existingCusRespLinesRecs = new map<String, Phoenix_Customer_Response_Line__c>();
                for(Phoenix_Customer_Response__c cusRes: [select Id,Phoenix_Affected_Contract_s__c,createdDate,Name from Phoenix_Customer_Response__c where id in : existingCusRespMap.keySet()] ){
                    //system.debug('cusrec'+cusres);
                    if (existingCusRespMap.containsKey(cusRes.Id)){
                        for(Phoenix_Customer_Response_Line__c cusResLine : existingCusRespMap.get(cusRes.Id)){
                            if(cusRes.Phoenix_Affected_Contract_s__c != null){
                                List<String> refContractsList = cusRes.Phoenix_Affected_Contract_s__c.split(',');
                                for(String cntrNum : refContractsList){
                                    if(cusResLine.Phoenix_Bid_Line_Item__r.Phoenix_Product__r.ProductCode != null && String.isNotBlank(cntrNum)){
                                        UniqueIdsMap.put(cusResLine.Phoenix_Bid_Line_Item__r.Phoenix_Product__r.ProductCode+'_'+cntrNum, cusRes);
                                        existingCusRespLinesRecs.put(cusResLine.Phoenix_Bid_Line_Item__r.Phoenix_Product__r.ProductCode+'_'+cntrNum, cusResLine);
                                    }
                                }
                                
                                
                                
                                
                            }
                        }
                    }
                }
                system.debug('uniqueidsmap'+UniqueIdsMap);
                system.debug('existingCusRespLinesRecs'+existingCusRespLinesRecs);
                map<String, Phoenix_Awarded_Quantity__c> existingAwardedQtyMap = new map<String, Phoenix_Awarded_Quantity__c>();
                for(Phoenix_Awarded_Quantity__c awardedQtyRec: [select id, Phoenix_Material_Code__c, Phoenix_Contract_Number__c,createdDate,Phoenix_Awarded_Quantity__c from Phoenix_Awarded_Quantity__c ORDER BY createdDate DESC]){
                    if(awardedQtyRec.Phoenix_Material_Code__c != null && awardedQtyRec.Phoenix_Contract_Number__c != null){
                        String awardedQtyUnqId = awardedQtyRec.Phoenix_Material_Code__c+'_'+awardedQtyRec.Phoenix_Contract_Number__c;
                        if(!existingAwardedQtyMap.containsKey(awardedQtyUnqId)){
                            existingAwardedQtyMap.put(awardedQtyUnqId,awardedQtyRec);
                        }
                    }
                }
                for(Vision_Customer_Product_Tracker__c cpt :[SELECT Id,Vision_On_Contract__c,Vision_Supply_Effective_Date__c,Vision_Is_In_Awarded__c,Vision_Contract_Product_Status__c,Vision_Cus_Response_Lines_Created_Date__c,Vision_Customer_Response__c,Vision_Customer_Response_Created_Date__c,Vision_Customer_Response_Name__c,Vision_In_Customer_Response_Lines__c,Vision_Unique_Identifier__c ,Customer_Response_Effective_Date__c , Customer_Response_Line__c,Vision_Awarded_Volume__c,Vision_Previous_Volume__c,Vision_Previous_DeadNet__c,Vision_Internal_DeadNet__c,Vision_Current_Product_Position__c from Vision_Customer_Product_Tracker__c Where Vision_Unique_Identifier__c in : existingCusRespLinesRecs.keySet()]){
                    if(existingCusRespLinesRecs.containsKey(cpt.Vision_Unique_Identifier__c)){
                        if(existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Bid_Status__c == 'Awarded'){
                            cpt.Vision_Contract_Product_Status__c = 'Awarded';
                            cpt.Vision_Is_In_Awarded__c=True;
                            //if(existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Supply_Effective_Date__c > system.today()){ 
                            cpt.Vision_On_Contract__c = True;
                            cpt.Vision_Supply_Effective_Date__c = existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Supply_Effective_Date__c;
                            
                           cpt.Customer_Response_Effective_Date__c = existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Price_Effective_Date__c;
                           cpt.Customer_Response_Line__c = existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Id;
                            cpt.Vision_Bid__c= existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Bid__c;
                           cpt.Bid_Line_Item__c=existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Bid_Line_Item__c;
                           
                           cpt.Vision_Current_Product_Position__c =  existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Award_Position__c;
                            //}
                            if(existingAwardedQtyMap.containsKey(cpt.Vision_Unique_Identifier__c)){
                                system.debug('entered here');
                                cpt.Vision_Awarded_Volume__c = existingAwardedQtyMap.get(cpt.Vision_Unique_Identifier__c).Phoenix_Awarded_Quantity__c;
                                cpt.Awarded_Quantity__c=existingAwardedQtyMap.get(cpt.Vision_Unique_Identifier__c).Id;
                                
                                //if(existingAwardedQtyMap.get(cpt.Vision_Unique_Identifier__c).Phoenix_Awarded_Quantity__c != null && cpt.Vision_Temp_Awarded_Value__c != null)
                                //	cpt.Vision_Awarded_Value__c = existingAwardedQtyMap.get(cpt.Vision_Unique_Identifier__c).Phoenix_Awarded_Quantity__c * cpt.Vision_Temp_Awarded_Value__c;
                            }
                            cpt.Vision_Previous_Volume__c = existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Bid_Line_Item__r.Phoenix_Total_Selling_Unit__c;
                            cpt.Vision_Previous_DeadNet__c = existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Bid_Line_Item__r.Phoenix_Current_ASP_Dose__c;
                            cpt.Vision_Internal_DeadNet__c = existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Bid_Line_Item__r.Phoenix_Proposed_ASP_Dose__c;
                           
                        }
                        else{
                            cpt.Vision_Contract_Product_Status__c = 'Non Awarded';
                        }
                        
                        cpt.Vision_Cus_Response_Lines_Created_Date__c = existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).createdDate;
                        cpt.Vision_In_Customer_Response_Lines__c = true;
                         cpt.Customer_Response_Line_Bid_status__c=existingCusRespLinesRecs.get(cpt.Vision_Unique_Identifier__c).Phoenix_Bid_Status__c;
                        if(UniqueIdsMap.containsKey(cpt.Vision_Unique_Identifier__c)){
                            cpt.Vision_Customer_Response__c = UniqueIdsMap.get(cpt.Vision_Unique_Identifier__c).Id;
                            cpt.Vision_Customer_Response_Created_Date__c = UniqueIdsMap.get(cpt.Vision_Unique_Identifier__c).createdDate;
                            cpt.Vision_Customer_Response_Name__c = UniqueIdsMap.get(cpt.Vision_Unique_Identifier__c).Name;
                        }
                    }
                    cptUpdateList.add(cpt);
                }
                if(cptUpdateList.size()>0){
                    update cptUpdateList;
                }
            }
            else{
               // system.debug('---No Records to Process---');
            }
        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'AwardedQtyContractPrdStatusBatchCls', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
    public void finish(Database.BatchableContext bc){
        //if(!Test.isRunningTest())
        	//Database.executeBatch(new NPRBasedContractProductUpdateBatchCls(),2000);
    }
    
}