UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/GCP_DOH_Trade_Partner_NDC__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GCP DOH Trade Partner NDC</relationshipLabel>
        <relationshipName>GCP_DOH_Trade_Partner_NDC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Unique_Identifier__c</fullName>
        <label>GCP_Unique_Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vision_gcp_ndc__c</fullName>
        <label>GCP NDC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vision_gcp_trade_partner_name__c</fullName>
        <label>GCP Trade Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP DOH Trade Partner NDC</label>
    <nameField>
        <displayFormat>DOH-NDC-{00000}</displayFormat>
        <label>GCP DOH Trade Partner NDC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP DOH Trade Partner NDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_GCN_Sequence_Number__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GCN Sequence Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_GPI_Generic_Product_Identifier__c</fullName>
        <description>It contains 14 characters.</description>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GPI (Generic Product Identifier)  </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Exclude_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is Exclude Bid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <inlineHelpText>National Drug Code: SAP field</inlineHelpText>
        <label>NDC - 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_GCP_Backorder_OTC__c.object
<CustomObject>
    <fields>
        <fullName>Vision_GCP_Unique_Identifier__c</fullName>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sku_Code__c</fullName>
        <label>Sku_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP Backorder OTC</label>
    <nameField>
        <displayFormat>backorder-OTC-{0000000}</displayFormat>
        <label>GCP Backorder OTC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Backorder OTCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_GCP_Backorder_SRx_Rx__c.object
<CustomObject>
    <fields>
        <fullName>Vision_GCP_Unique_Identifier__c</fullName>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP Backorder SRx Rx</label>
    <nameField>
        <displayFormat>backorder-Srx-Rx -{0000000}</displayFormat>
        <label>GCP Backorder SRX and RxName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Backorder SRx Rx</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/GoogleDOHTradePartnerNDCLevelFetchTest.cls
@istest
public class GoogleDOHTradePartnerNDCLevelFetchTest {
    
    static testmethod void setup(){
        List<Account> Acclist = new List<Account>();
        Account acc = new Account();
        acc.Name='test';
        Acclist.add(acc);
        Insert Acclist;
        list<Product2> plist = new list  < Product2>();
        
        Vision_GCP_Backorder_SRx_Rx__c data1 = new Vision_GCP_Backorder_SRx_Rx__c();
        data1.Vision_Sku_Code__c = '123566';
        insert data1;
        
        Vision_GCP_Backorder_OTC__c data2 = new Vision_GCP_Backorder_OTC__c();
        data2.Vision_Sku_Code__c = '123566';
        insert data2;
        
        Product2 p=new Product2();
        p.Name='abc pharma';
        p.Phoenix_NDC_11__c='4359834531';
        p.ProductCode='123566';
        p.Phoenix_NDC__c='4359834531';
        p.Phoenix_GPI_Generic_Product_Identifier__c = '11111';
        p.Family = 'Test Family';
        p.Phoenix_Throughput_cost__c=10.23456576;
        p.Phoenix_GCN_Sequence_Number__c='666666';
        p.Phoenix_Pkg_Size__c=25.0;
        p.IsActive = true;
        p.Phoenix_Is_Exclude_Bid__c = false;
        
        plist.add(p);
        insert plist;
        
        GCP_DOH_Trade_Partner_NDC__c obj = new GCP_DOH_Trade_Partner_NDC__c();
        obj.Product__c = p.id;
        //obj.Name = 'Deep';
        obj.vision_gcp_ndc__c = '4359834531';
        obj.vision_gcp_trade_partner_name__c = 'NORTH CAROLINA MUTUAL WHOLESALE DRUG CO';
        obj.Vision_GCP_Unique_Identifier__c = obj.vision_gcp_trade_partner_name__c + '_'+obj.vision_gcp_ndc__c;
        insert obj;
        
        test.startTest();
        Database.executeBatch(new GoogleDOHTradePartnerNDCLevelFetch(1,1));
        
        GoogleDOHTradePartnerNDCLevelFetch batch = new GoogleDOHTradePartnerNDCLevelFetch();
        batch.execute(null);
        Test.stopTest();
        
        

}
}