UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/New_Product_WAC_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Contracts</fullName>
                </value>
                <value>
                    <fullName>Closed-Country Head</fullName>
                </value>
                <value>
                    <fullName>Closed-Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Closed-Customer Service</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Closed-Finance</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing &amp; Finance</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Closed-Marketing Lead SRx</fullName>
                </value>
                <value>
                    <fullName>Closed-Sales &amp; Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Closed-SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Closed-Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Closed-SRx IPA Contracts Approver</fullName>
                </value>
                <value>
                    <fullName>Closed-Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Closed-Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Country Head</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Pending</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Customner&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>New Product WAC Pricing</label>
    <nameField>
        <displayFormat>WAC Price - {000000}</displayFormat>
        <label>WAC Price for New Launch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Product WAC Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_NewWacPricingTriggerHandler.cls
public class Phoenix_NewWacPricingTriggerHandler extends TriggerHandler {
    private list < New_Product_WAC_Pricing__c > triggerNew;
    private list < New_Product_WAC_Pricing__c > triggerOld;
    private Map < Id, New_Product_WAC_Pricing__c > newMap;
    private Map < Id, New_Product_WAC_Pricing__c > oldMap;
    public Phoenix_NewWacPricingTriggerHandler() {
        this.newMap = (Map < Id, New_Product_WAC_Pricing__c > ) Trigger.newMap;
        this.oldMap = (Map < Id, New_Product_WAC_Pricing__c > ) Trigger.oldMap;
        this.triggerNew = (List < New_Product_WAC_Pricing__c > ) Trigger.new;
        this.triggerOld = (List < New_Product_WAC_Pricing__c > ) Trigger.old;
        
        
    }
    public override void beforeInsert() {}
    public override void beforeUpdate() {}
    public override void afterUpdate() {
        List < Id > newWacIds = new List < Id > ();
        
        for (New_Product_WAC_Pricing__c newWac: triggerNew) {
            if (oldMap.get(newWac.Id).Phoenix_Approval_Status__c != newMap.get(newWac.Id).Phoenix_Approval_Status__c && newMap.get(newWac.Id).Phoenix_Approval_Status__c.contains('Closed')) {
                newWacIds.add(newWac.Id);
            }
        }
        if (newWacIds.size() > 0) Phoenix_SubmitBidForApprovalCtrl.BidClosureNotification(newWacIds);
        
    }
    public override void beforeDelete(){
         triggerOld[0].addError('You can\'t delete the New Product WAC Pricing');
   /*     List < Id > newWacIds = new List < Id > ();
        for (New_Product_WAC_Pricing__c newWac: triggerOld) {
            if (oldMap.get(newWac.Id).Phoenix_Approval_Status__c == 'Draft')
                newWacIds.add(newWac.Id);
            else 
                newWac.addError('You can\'t delete this New Product WAC Pricing, as it is already submitted for approval.');
            
        }
        if (newWacIds.size() > 0)Phoenix_SubmitBidForApprovalCtrl.deleteBidChildren(newWacIds);
        system.debug('deleting children');
   */ }
    
    
}