UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vision_Opportunity_Value__c</fullName>
        <label>Opportunity Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Name__c</fullName>
        <label>Bid Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Product_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Product Director</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Marketing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Market_Share_Expansion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Share Expansion</label>
        <referenceTo>Vision_Market_Share_Expansion__c</referenceTo>
        <relationshipLabel>Product Opportunity</relationshipLabel>
        <relationshipName>Product_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product Opportunity</relationshipLabel>
        <relationshipName>Product_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Opportunity</relationshipLabel>
        <relationshipName>Product_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Product Opportunity</relationshipLabel>
        <relationshipName>Product_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Opportunity_Value__c</fullName>
        <label>Opportunity Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_confidence_level__c</fullName>
        <label>Vision_confidence_level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_customer_expectation_lead_time__c</fullName>
        <label>Vision_customer_expectation_lead_time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_ext_mfg_scm_approved_by__c</fullName>
        <label>Vision_ext_mfg_scm_approved_by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_ext_mfg_scm_approved_on_date__c</fullName>
        <label>Vision_ext_mfg_scm_approved_on_date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_ext_mfg_scm_remarks__c</fullName>
        <label>Vision_ext_mfg_scm_remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_incremental_volume_by_scm__c</fullName>
        <label>Vision_incremental_volume_by_scm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_india_scm_approved_by__c</fullName>
        <label>Vision_india_scm_approved_by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_india_scm_approved_on_date__c</fullName>
        <label>Vision_india_scm_approved_on_date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_india_scm_remarks__c</fullName>
        <label>Vision_india_scm_remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_initialorder_volume_by_scm__c</fullName>
        <label>Vision_initialorder_volume_by_scm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_remarks_by_pm__c</fullName>
        <label>Vision_remarks_by_pm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_remarks_by_scm__c</fullName>
        <label>Vision_remarks_by_scm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_scm_approved_date__c</fullName>
        <label>Vision_scm_approved_date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_scm_manager__c</fullName>
        <label>Vision_scm_manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_sku_split_flag__c</fullName>
        <label>Vision_sku_split_flag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_supply_duration_scm__c</fullName>
        <label>Vision_supply_duration_scm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_supply_effectivedate_SCM__c</fullName>
        <label>Vision_supply_effectivedate_SCM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_supply_requirement__c</fullName>
        <label>Vision_supply_requirement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_total_incremental_volume_by_scm__c</fullName>
        <label>Vision_total_incremental_volume_by_scm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_total_initial_order_quantity_by_s__c</fullName>
        <label>Vision_total_initial_order_quantity_by_s</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Opportunity</label>
    <nameField>
        <label>Product Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Opportunity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/User.object
<CustomObject>
    <fields>
        <fullName>Last_logout__c</fullName>
        <label>Last logout</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Login_and_Logout__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Login and Logout</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_Alert__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vision Alerts</relationshipLabel>
        <relationshipName>Vision_Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vision Alert</label>
    <nameField>
        <label>Vision Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vision Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_Market_Share_Expansion__c.object
<CustomObject>
    <fields>
        <fullName>Task_Ident__c</fullName>
        <label>Task Ident</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Status__c</fullName>
        <label>Task Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent to OPPORTUNITY</fullName>
                </value>
                <value>
                    <fullName>Sent to BRIGHT</fullName>
                </value>
                <value>
                    <fullName>not_started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Share Expansions</relationshipLabel>
        <relationshipName>Market_Share_Expansions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Market Share Expansions</relationshipLabel>
        <relationshipName>Market_Share_Expansions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_confidence_level__c</fullName>
        <label>Vision confidence level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_customer_expectation_lead_time__c</fullName>
        <label>Vision customer expectation lead time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_ext_mfg_scm_approved_by__c</fullName>
        <label>Vision ext_mfg_scm_approved_by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_ext_mfg_scm_approved_on_date__c</fullName>
        <label>Vision ext_mfg_scm_approved_on_date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_ext_mfg_scm_remarks__c</fullName>
        <label>Vision ext_mfg_scm_remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_incremental_volume_by_scm__c</fullName>
        <label>Vision incremental_volume_by_scm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_india_scm_approved_by__c</fullName>
        <label>Vision india_scm_approved_by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_india_scm_approved_on_date__c</fullName>
        <label>Vision india_scm_approved_on_date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_india_scm_remarks__c</fullName>
        <label>Vision india_scm_remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_initialorder_volume_by_scm__c</fullName>
        <label>Vision initialorder_volume_by_scm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_remarks_by_pm__c</fullName>
        <label>Vision remarks_by_pm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_remarks_by_scm__c</fullName>
        <label>Vision remarks_by_scm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_scm_approved_date__c</fullName>
        <label>Vision scm approved date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_scm_manager__c</fullName>
        <label>Vision scm manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_sku_split_flag__c</fullName>
        <label>Vision sku_split_flag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_supply_duration_scm__c</fullName>
        <label>Vision supply_duration_scm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_supply_effectivedate_SCM__c</fullName>
        <label>Vision supply_effectivedate SCM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_supply_requirement__c</fullName>
        <label>Vision supply requirement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_total_incremental_volume_by_scm__c</fullName>
        <label>Vision total_incremental_volume_by_scm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_total_initial_order_quantity_by_s__c</fullName>
        <label>Vision total_initial_order_quantity_by_s</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Market Share Expansion</label>
    <nameField>
        <displayFormat>MktShareExp-{0000000}</displayFormat>
        <label>Market Share Expansion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Share Expansions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Vision_Home_Page_Class.cls
public class Vision_Home_Page_Class {
   /*  @AuraEnabled
    public static void getLoginDetailsUpdate() {
         User u = [SELECT Id,Login_and_Logout__c,Last_logout__c from User where id=:Userinfo.getUserId()];
        System.debug('current user==>'+Userinfo.getUserId());
            u.Last_logout__c = System.now();
            u.Login_and_Logout__c = true;
            update u;
    }*/
    @AuraEnabled
    public static MainWrapper getRecentOpportunities(){
        string userId = userInfo.getUserId();
        Timezone timeZone = userInfo.getTimeZone();
        String tz = String.valueOf(timeZone);
        //  DateTime userDate = DateTime.now();
        String userDate = DateTime.now().format('EEEE');
        string status = 'Customer'+ '\''+'s Update';

        List<String> approvalStaus = new List<String>();
        approvalStaus.add('Closed');
        approvalStaus.add('Closed-Draft');
        approvalStaus.add('Contracts Rejected');
        approvalStaus.add('Customer'+ '\''+'s Update');
        approvalStaus.add('Customer Rejected');
        approvalStaus.add('Vistex Update');
        approvalStaus.add('Vistex Update Rejected');
        approvalStaus.add('Vistex Customer Code Update');
        approvalStaus.add('Business Head Rejected'); //Added code by Rama
        approvalStaus.add('Customer Service Rejected');
        approvalStaus.add('Finance Rejected');
        approvalStaus.add('Marketing Head Rejected');
        approvalStaus.add('Marketing Lead Rejected');
        approvalStaus.add('Marketing Rejected');
        approvalStaus.add('Sr Director or VP Finance Rejected');
        approvalStaus.add('Supply Chain Rejected');
        
        //Added code by Rama
        List<String> approvalStatus = new List<String>();
        approvalStatus.add('Business Head');
        approvalStatus.add('Contracts');
        approvalStatus.add('Customer Service');
       // approvalStatus.add('Customer'+ '\''+'s Update');
        approvalStatus.add('Finance');
        approvalStatus.add('Marketing');
        approvalStatus.add('Marketing Head');
        approvalStatus.add('Marketing Lead');
        approvalStatus.add('SCM & Marketing');
        approvalStatus.add('Sr Director or VP Finance');
        approvalStatus.add('Supply Chain');
        //approvalStatus.add('Vistex Update');
        //approvalStatus.add('Vistex Customer Code Update');
       
        Date Date1;
        Date Date2;
        if(userDate == 'Friday'){
            Date1 = System.today();
            
            Date2 = System.today()+3;
             
        }
        else if(userDate == 'Saturday'){
            Date1 = System.today()+2;
            Date2 = System.today()+3;    
        }
        else if(userDate == 'Sunday'){
            Date1 = System.today()+1;
            Date2 = System.today()+2;    
        }
        else{
            Date1 = System.today();
            Date2 = System.today()+1;    
        }
        MainWrapper mainWrap = new MainWrapper();
        List<Opportunity> oppList = [SELECT ID,Name,CloseDate,Vision_Opportunity_Value__c,CreatedDate,Amount,StageName,Account.Name,AccountId, (SELECT Id,Name,Vision_Bid__c from Product_Opportunity__r where Product__c!=null) from Opportunity WHERE StageName = : 'Opportunity in progress' and   CreatedById =: userInfo.getUserId() order by CreatedDate DESC limit 10]; 
         mainwrap.oppList =oppList;
    
        List<Vision_Market_Share_Expansion__c> marketExpansionList = [SELECT ID,CreatedDate,Vision_Product_Family__c ,Task_Ident__c,Vision_Product__r.Phoenix_Product_Director__r.Name,Vision_Customer__c,Vision_Customer__r.Name,Vision_Customer__r.OwnerId,Vision_Product__r.Name,Task_Status__c,Vision_scm_manager__c,Vision_scm_approved_date__c,Vision_supply_requirement__c,
               Vision_confidence_level__c,Vision_customer_expectation_lead_time__c,Vision_supply_effectivedate_SCM__c,Vision_remarks_by_pm__c,Vision_remarks_by_scm__c,
               Vision_total_incremental_volume_by_scm__c,Vision_total_initial_order_quantity_by_s__c,Vision_supply_duration_scm__c,Vision_sku_split_flag__c,
               Vision_incremental_volume_by_scm__c,Vision_initialorder_volume_by_scm__c,Vision_india_scm_approved_by__c,Vision_india_scm_approved_on_date__c,
               Vision_india_scm_remarks__c,Vision_ext_mfg_scm_approved_by__c,Vision_ext_mfg_scm_approved_on_date__c,Vision_ext_mfg_scm_remarks__c
               from Vision_Market_Share_Expansion__c WHERE Vision_Customer__r.OwnerId =: userInfo.getUserId() order by CreatedDate DESC limit 10]; 
        
        Map<String, Vision_Market_Share_Expansion__c> expListMap = new Map<String, Vision_Market_Share_Expansion__c>();
        for(Vision_Market_Share_Expansion__c expnObj : marketExpansionList){
            if(!expListMap.containsKey(expnObj.Task_Ident__c))
                expListMap.put(expnObj.Task_Ident__c, expnObj);
            
        }
        mainWrap.marketExpansionList=expListMap.values();
       
        List<Phoenix_Bid__c> bidsList = [SELECT ID,Phoenix_Bid_Name__c,Name,Phoenix_Customer__c,Phoenix_Bid_Type__c,Phoenix_Customer__r.Name,Phoenix_Status__c,Phoenix_Approval_Status__c,Phoenix_Bid_Deadline_Date__c,Phoenix_Sent_to_Customer_Date__c,Phoenix_Internal_Target_Date__c  from Phoenix_Bid__c where (Phoenix_Bid_Owner__c =:userInfo.getUserId() or Phoenix_Salesperson__c =:userInfo.getUserId())  and ((Phoenix_Internal_Target_Date__c =:Date1 OR Phoenix_Internal_Target_Date__c >=: Date2) AND Phoenix_Approval_Status__c IN: approvalStatus) order by CreatedDate DESC limit 10]; 
        mainWrap.bidsList=bidsList;
        List<Phoenix_Bid__c> bidsCustomerUpdate = [SELECT ID,Phoenix_Bid_Name__c,Name,Phoenix_Customer__c,Phoenix_Bid_Type__c,Phoenix_Customer__r.Name,Phoenix_Status__c,Phoenix_Approval_Status__c,Phoenix_Bid_Deadline_Date__c,Phoenix_Sent_to_Customer_Date__c,Phoenix_Internal_Target_Date__c  from Phoenix_Bid__c where Phoenix_Approval_Status__c =: status and (Phoenix_Bid_Owner__c =:userInfo.getUserId() or Phoenix_Salesperson__c =:userInfo.getUserId()) order by CreatedDate DESC limit 10]; 
         mainWrap.bidsCustomerUpdate=bidsCustomerUpdate;
        List<Phoenix_Bid__c> bidsPastList = [SELECT ID,Phoenix_Bid_Name__c,Name,Phoenix_Customer__c,Phoenix_Bid_Type__c,Phoenix_Customer__r.Name,Phoenix_Status__c,Phoenix_Approval_Status__c,Phoenix_Bid_Deadline_Date__c,Phoenix_Sent_to_Customer_Date__c,Phoenix_Internal_Target_Date__c  from Phoenix_Bid__c where (Phoenix_Bid_Owner__c =:userInfo.getUserId() or Phoenix_Salesperson__c =:userInfo.getUserId()) and Phoenix_Internal_Target_Date__c < Today and Phoenix_Approval_Status__c NOT IN: approvalStaus order by CreatedDate DESC limit 10]; 
         mainWrap.bidsPastList=bidsPastList;
        List<Task> tasksList = [SELECT ID,Subject,WhatId,Description,Status,ActivityDate from Task where CreatedById =:userInfo.getUserId() order by CreatedDate DESC  limit 10]; 
        mainWrap.tasksList=tasksList;
        List<Event> eventList = [SELECT ID,Subject,WhatId,Type,Description,ActivityDate from Event where CreatedById =:userInfo.getUserId() order by CreatedDate DESC  limit 10]; 
        mainWrap.eventList=eventList;
        List<Vision_Alert__c> alertList = [SELECT ID,Name,Vision_Alert_Type__c,Vision_Notification_Due_Date__c from Vision_Alert__c where CreatedById =:userInfo.getUserId() order by CreatedDate DESC limit 10]; 
        mainWrap.alertList=alertList;
        return mainWrap;
        
    }
    
    
    @AuraEnabled
    public static MainWrapper getBidActions(){
        string userId = userInfo.getUserId();
        Timezone timeZone = userInfo.getTimeZone();
        String tz = String.valueOf(timeZone);
        //  DateTime userDate = DateTime.now();
        String userDate = DateTime.now().format('EEEE');
        string status = 'Customer'+ '\''+'s Update';
         
        //Added code by Rama
        List<String> approvalStatus2 = new List<String>();
        approvalStatus2.add('Business Head');
        approvalStatus2.add('Contracts');
        approvalStatus2.add('Customer Service');
        //approvalStatus2.add('Customer'+ '\''+'s Update');
        approvalStatus2.add('Finance');
        approvalStatus2.add('Marketing');
        approvalStatus2.add('Marketing Head');
        approvalStatus2.add('Marketing Lead');
        approvalStatus2.add('SCM & Marketing');
        approvalStatus2.add('Sr Director or VP Finance');
        approvalStatus2.add('Supply Chain');
       // approvalStatus2.add('Vistex Update');
        //approvalStatus2.add('Vistex Customer Code Update');
        
        Date Date1;
        Date Date2;
        if(userDate == 'Friday'){
            Date1 = System.today();
            Date2 = System.today()+3;
           }
        else if(userDate == 'Saturday'){
            Date1 = System.today()+2;
            Date2 = System.today()+3;    
        }
        else if(userDate == 'Sunday'){
            Date1 = System.today()+1;
            Date2 = System.today()+2;    
        }
        else{
            Date1 = System.today();
            Date2 = System.today()+1;    
        }
        MainWrapper mainWrap = new MainWrapper(); 
        List<BidPastActionWrapper> BidPastActionWrapperList = new List<BidPastActionWrapper>();
        List<BidUpcomingActionWrapper> BidUpcomingActionWrapperList = new List<BidUpcomingActionWrapper>();
        
        List<Phoenix_Bid__c> bidsList = [SELECT ID,Phoenix_Bid_Name__c,Name,Phoenix_Customer__c,Phoenix_Bid_Type__c,Phoenix_Customer__r.Name,Phoenix_Status__c,Phoenix_Approval_Status__c,Phoenix_Bid_Deadline_Date__c,Phoenix_Sent_to_Customer_Date__c,Phoenix_Internal_Target_Date__c  from Phoenix_Bid__c where (Phoenix_Bid_Owner__c =: userInfo.getUserId() or Phoenix_Salesperson__c =:userInfo.getUserId()) and ((Phoenix_Bid_Deadline_Date__c =:Date1 OR Phoenix_Bid_Deadline_Date__c >=:Date2) AND Phoenix_Approval_Status__c IN: approvalStatus2) order by CreatedDate DESC LIMIT 10]; 
         mainWrap.bidsList=bidsList;
        List<Phoenix_Bid__c> bidsPastList = [SELECT ID,Phoenix_Bid_Name__c,Name,Phoenix_Customer__c,Phoenix_Bid_Type__c,Phoenix_Customer__r.Name,Phoenix_Status__c,Phoenix_Approval_Status__c,Phoenix_Bid_Deadline_Date__c,Phoenix_Sent_to_Customer_Date__c,Phoenix_Internal_Target_Date__c  from Phoenix_Bid__c where (Phoenix_Bid_Owner__c =: userInfo.getUserId() or Phoenix_Salesperson__c =:userInfo.getUserId()) and Phoenix_Bid_Deadline_Date__c < Today  order by CreatedDate DESC LIMIT 10]; 
        mainWrap.bidsPastList=bidsPastList;
        if(bidsPastList.size() >0){
        for(Phoenix_Bid__c past : bidsPastList){
            BidPastActionWrapper wrap = new BidPastActionWrapper();
            wrap.NoOfDays = past.Phoenix_Internal_Target_Date__c.daysBetween(system.Today());
            wrap.bidNo = past.Name;
            wrap.bidName = past.Phoenix_Bid_Name__c;
            wrap.bidtype = past.Phoenix_Bid_Type__c;
            wrap.Customer = past.Phoenix_Customer__r.Name;
            wrap.Status = past.Phoenix_Approval_Status__c;
            wrap.bidId = past.Id;
            wrap.custId = past.Phoenix_Customer__c;
            
            BidPastActionWrapperList.add(wrap);
        }
        }
        mainWrap.BidPastActionList = BidPastActionWrapperList;
                if(bidsList.size() >0){
        for(Phoenix_Bid__c upcoming : bidsList){
            BidUpcomingActionWrapper wrap = new BidUpcomingActionWrapper();
            wrap.NoOfDays = system.Today().daysBetween(upcoming.Phoenix_Bid_Deadline_Date__c);
            wrap.bidNo = upcoming.Name;
            wrap.bidName = upcoming.Phoenix_Bid_Name__c;
            wrap.bidtype = upcoming.Phoenix_Bid_Type__c;
            wrap.Customer = upcoming.Phoenix_Customer__r.Name;
            wrap.Status = upcoming.Phoenix_Approval_Status__c;
            wrap.bidId = upcoming.Id;
            wrap.custId = upcoming.Phoenix_Customer__c;
            BidUpcomingActionWrapperList.add(wrap);
        }
                }
        mainWrap.BidUpcomingActionList = BidUpcomingActionWrapperList;
        return mainWrap;
    }
    public class MainWrapper{
        @AuraEnabled public List<Phoenix_Bid__c> bidsPastList; 
        @AuraEnabled public List<Phoenix_Bid__c> bidsCustomerUpdate;    
        @AuraEnabled public List<Vision_Market_Share_Expansion__c> marketExpansionList; 
        @AuraEnabled public List<Phoenix_Bid__c> bidsList;
        @AuraEnabled public List<Task> tasksList;   
        @AuraEnabled public List<Event> eventList;
        @AuraEnabled public List<Opportunity> oppList;
        @AuraEnabled public List<Vision_Alert__c> alertList;
        @AuraEnabled public List<BidPastActionWrapper> BidPastActionList;
        @AuraEnabled public List<BidUpcomingActionWrapper> BidUpcomingActionList;
        
        MainWrapper(){
            marketExpansionList=new List<Vision_Market_Share_Expansion__c>();
            bidsCustomerUpdate = new List<Phoenix_Bid__c>();
            bidsPastList = new List<Phoenix_Bid__c>();
            bidsList = new List<Phoenix_Bid__c>();
            tasksList = new List<Task>();
            oppList = new List<Opportunity>();
            eventList = new List<Event>();
            alertList = new List<Vision_Alert__c>();
            BidPastActionList = new List<BidPastActionWrapper>();
            BidUpcomingActionList = new List<BidUpcomingActionWrapper>();
            
        }
    }
    public class BidPastActionWrapper{
        @AuraEnabled public Integer NoOfDays; 
        @AuraEnabled public String bidNo;
        @AuraEnabled public String bidName;
        @AuraEnabled public String bidtype;
        @AuraEnabled public String Customer;
        @AuraEnabled public String Status;
        @AuraEnabled public String bidId;
        @AuraEnabled public String custId;
        
    }
    public class BidUpcomingActionWrapper{   
        @AuraEnabled public Integer NoOfDays;
        @AuraEnabled public String bidNo;
        @AuraEnabled public String bidName;
        @AuraEnabled public String bidtype;
        @AuraEnabled public String Customer;
        @AuraEnabled public String Status;
        @AuraEnabled public String bidId;
        @AuraEnabled public String custId;
        
    }
}