UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bids3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Business_Approval_Comments__c</fullName>
        <label>Business Head Approval Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Business_Approval__c</fullName>
        <label>Business Head Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Contracts_Approval_Comments__c</fullName>
        <label>Contracts Approval Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contracts_Approval__c</fullName>
        <label>Contracts Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Not_Processed</fullName>
                    <label>Not Processed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Country_Head_Approval__c</fullName>
        <label>Country Head Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Country_Head_Comments__c</fullName>
        <label>Country Head Approval Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Finance_Approval_Comments__c</fullName>
        <label>Finance Approval Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Finance_Approval__c</fullName>
        <label>Finance Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Contracts Approved</fullName>
                </value>
                <value>
                    <fullName>SCM Approved</fullName>
                </value>
                <value>
                    <fullName>Marketing Approved</fullName>
                </value>
                <value>
                    <fullName>Finance Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Submitted</fullName>
                </value>
                <value>
                    <fullName>Proposal Accepted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Finance_Approval__c</fullName>
        <label>Finance Approval</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid_Process_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approver_Team__c</fullName>
        <label>Approver Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phoenix_Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Process Steps</relationshipLabel>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Process_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Step</label>
        <referenceTo>Phoenix_Approval_Process_Step__c</referenceTo>
        <relationshipLabel>Bid Process Steps</relationshipLabel>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Do Not Bid</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Step__c</fullName>
        <formula>Phoenix_Process_Step__r.Phoenix_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Step</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bid Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bid Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/globalValueSets/Phoenix_Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Business Head</fullName>
    </customValue>
    <customValue>
        <fullName>Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Country Head</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Government Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Home Office</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Head</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead OTC</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead SRx</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sr Director or VP Finance</fullName>
    </customValue>
    <customValue>
        <fullName>SRx IPA Contracts Approver</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Demand Planning</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Marketing Head</fullName>
        <isActive>false</isActive>
        <label>Sales &amp; Marketing Head</label>
    </customValue>
    <customValue>
        <fullName>VP / Director Finance</fullName>
        <isActive>false</isActive>
        <label>VP / Director Finance</label>
    </customValue>
    <customValue>
        <fullName>SCM &amp; Marketing</fullName>
        <isActive>false</isActive>
        <label>SCM &amp; Marketing</label>
    </customValue>
    <masterLabel>Phoenix_Teams</masterLabel>
</GlobalValueSet>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Pheonix_BidWACChangeController.cls
/**
 * @description       : 
 * @author            : Surender Dhruvsoft
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Dhruvsoft
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   25-05-2021   Surender Dhruvsoft   Initial Version
**/
public class Pheonix_BidWACChangeController {
    public static Phoenix_Bid__c bid;

    static {
        bid = new Phoenix_Bid__c();
    }

    public Pheonix_BidWACChangeController() {

    }

    @AuraEnabled
    public static Phoenix_BidWACCreatorCtrl.BidWrapper getBidInfo(String bidId) {
        return Phoenix_BidWACCreatorCtrl.getbidInfo(bidId);
    }
    @AuraEnabled
    public static List < Phoenix_BidWACCreatorCtrl.wrapperClass > getproductsrelatedtoBid(Phoenix_BidWACCreatorCtrl.BidWrapper quotewrap) {
        return Phoenix_BidWACCreatorCtrl.getproductsrelatedtoBid(quotewrap);
    }

    @AuraEnabled
    public static list < Phoenix_BidWACCreatorCtrl.wrapperClass > getSearch(List < Phoenix_BidWACCreatorCtrl.wrapperClass > pItem, list < string > SearchKeyWordPD, string search, string family, list < string > RxSrxList, Phoenix_BidWACCreatorCtrl.BidWrapper quotewrap) {
        return Phoenix_BidWACCreatorCtrl.getSearch(pItem, SearchKeyWordPD, search, family, RxSrxList, quotewrap);
    }
    @AuraEnabled
    public static list < Phoenix_BidWACCreatorCtrl.wrapperClass > getsearchDirectorResult(List < Phoenix_BidWACCreatorCtrl.wrapperClass > pItem, list < string > SearchKeyWordPD, string Family, string searchName, list < string > RxSrxList, Phoenix_BidWACCreatorCtrl.BidWrapper quotewrap) {
        return Phoenix_BidWACCreatorCtrl.getsearchDirectorResult(pItem, SearchKeyWordPD, Family, searchName, RxSrxList, quotewrap);
    }

    @AuraEnabled
    public static list < Phoenix_BidWACCreatorCtrl.wrapperClass > getSearchFamily(List < Phoenix_BidWACCreatorCtrl.wrapperClass > pItem, list < string > SearchKeyWordPD, string search, string searchName, list < string > RxSrxList, Phoenix_BidWACCreatorCtrl.BidWrapper quotewrap) {
        return Phoenix_BidWACCreatorCtrl.getSearchFamily(pItem, SearchKeyWordPD, search, searchName, RxSrxList, quotewrap);
    }

    @AuraEnabled
    public static List < Phoenix_BidWACCreatorCtrl.wrapperClass > getproducts1(Phoenix_BidWACCreatorCtrl.BidWrapper quotewrap) {
        return Phoenix_BidWACCreatorCtrl.getproducts1(quotewrap);
    }
    @AuraEnabled
    public static List < Phoenix_BidWACCreatorCtrl.wrapperClass > showselectedProducts(string bidId) {
        return Phoenix_BidWACCreatorCtrl.showselectedProducts(bidId);
    }
    @AuraEnabled
    public static List < string > getProductDirectorList(Phoenix_BidWACCreatorCtrl.BidWrapper bidwrap) {
        return Phoenix_BidWACCreatorCtrl.getProductDirectorList(bidwrap);
    }

    @AuraEnabled
    public static list < Phoenix_BidWACCreatorCtrl.wrapperClass > fetchSortResults(string sortField, boolean isAsc, List < Phoenix_BidWACCreatorCtrl.wrapperClass > productList) {
        return Phoenix_BidWACCreatorCtrl.fetchSortResults(sortField, isAsc, productList);
    }

    @AuraEnabled
    public static list < Phoenix_BidWACCreatorCtrl.wrapperClass > findBySrxOtc(list < string > searchKey, list < string > SearchKeyWordPD, string searchName, string family, List < Phoenix_BidWACCreatorCtrl.wrapperClass > productList, Phoenix_BidWACCreatorCtrl.BidWrapper quotewrap) {
        return Phoenix_BidWACCreatorCtrl.findBySrxOtc(searchKey, SearchKeyWordPD, searchName, family, productList, quotewrap);
    }

    @AuraEnabled
    public static list < Phoenix_Bid_Line_Item__c > saveQuoteItems(list < Phoenix_BidWACCreatorCtrl.wrapperClass > saveitems, Phoenix_BidWACCreatorCtrl.BidWrapper bidWrapper) {
        return Phoenix_BidWACCreatorCtrl.saveQuoteItems(saveitems, bidWrapper);
    }

    @AuraEnabled
    public static list < Phoenix_Bid_Line_Item__c > editQuoteItems(list < Phoenix_BidWACCreatorCtrl.wrapperClass > saveitems, Phoenix_BidWACCreatorCtrl.BidWrapper bidWrapper, Date effDt) {
        return Phoenix_BidWACCreatorCtrl.editQuoteItems(saveitems, bidWrapper, effDt);
    }
    @AuraEnabled
    public static void deleteLineItems(String LineItemId){
        if (LineItemId != null) {
            Phoenix_Bid_Line_Item__c deletedLineItem = [SELECT Id, Phoenix_Bid__c FROM Phoenix_Bid_Line_Item__c WHERE Id =: LineItemId];
            delete deletedLineItem;
        }
    }
    @AuraEnabled
    public static List < ContentDocumentLink > getDocs(String bidId) {
        Phoenix_Bid__c bidRec = [select Id FROM Phoenix_Bid__c where id =: bidId];
        return [SELECT Id, LinkedEntityId, ContentDocument.Title, ContentDocument.FileExtension, ContentDocumentId FROM ContentDocumentLink where LinkedEntityId =: bidRec.Id];
    }
    @AuraEnabled
    public static void deleteAttachments(String LineItemId, String bidId) {
        List < ContentDocument > contentDocumentIds = [select Id from ContentDocument WHERE Id =: LineItemId];
        delete contentDocumentIds;

    }

    @AuraEnabled
    public static void makeApprovalsBusiness(String bidId, String finaceCom, string financeAppStatus, string approvStatus) {
        Phoenix_Bid_Process_Steps__c currentStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c
                                                    where Phoenix_Bid__c =: bidId AND Phoenix_Status__c = 'In Process'
                                                    LIMIT 1
                                                   ];
        List < Phoenix_Bid_Process_Steps__c > updateProcessStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c,Phoenix_Approver__r.Email, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];
        Map < Integer, List < Phoenix_Bid_Process_Steps__c >> stepMap = new Map < Integer, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, List < Phoenix_Bid_Process_Steps__c >> stepNamesMap = new Map < String, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, Integer > stepnameNoMap = new Map < String, Integer > ();
        for (Phoenix_Bid_Process_Steps__c step: updateProcessStep) {
            Integer stepNo = Integer.valueOf(step.Phoenix_Step__c);
            if (stepMap.get(stepNo) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepMap.get(stepNo);
                adededSteps.add(step);
                stepMap.put(stepNo, adededSteps);
            } else {
                stepMap.put(stepNo, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            String stepName = step.Phoenix_Approver_Team__c;
            System.debug('-----------stepName------' + stepName);
            if (stepNamesMap.get(stepName) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepNamesMap.get(stepName);
                adededSteps.add(step);
                stepNamesMap.put(stepName, adededSteps);
            } else {
                stepNamesMap.put(stepName, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            stepnameNoMap.put(stepName, stepNo);
        }
        Phoenix_Bid__c bidCurrent = [select id, Phoenix_Approval_Status__c from Phoenix_Bid__c where id =: bidId];
        List < Phoenix_Bid_Process_Steps__c > nextSteps = stepMap.get(3);
        List < Phoenix_Bid_Process_Steps__c > nextSteps2 = stepMap.get(4);
        List < Phoenix_Bid_Process_Steps__c > nextSteps3 = stepMap.get(5);
        List < Phoenix_Bid_Process_Steps__c > nextSteps4 = stepMap.get(6);
        if (financeAppStatus == 'Approved') {
            System.debug('----------financeAppStatus---------'+financeAppStatus);
            if (currentStep != null) {
                System.debug('-------updateProcessStep.Phoenix_Status__c-' + currentStep.Phoenix_Status__c);
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = finaceCom;
                update currentStep;
                System.debug('----------financeAppStatus--------2-'+financeAppStatus);
            }
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                step.Phoenix_Status__c = 'In Process'; //'In Process' Submitted //Diff b/w them            
            }
            if (!nextSteps.isEmpty()) {
                update nextSteps;
            }
            bidCurrent.Phoenix_Approval_Status__c = 'Country Head';
            update bidCurrent;
        } else if (financeAppStatus == 'Not Approved') {
            
            System.debug('----------financeAppStatus-------3--'+financeAppStatus);
            
            if (currentStep != null) {
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = finaceCom;
                update currentStep;
            }
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                System.debug('----------financeAppStatus-----4----'+financeAppStatus);
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            for (Phoenix_Bid_Process_Steps__c step: nextSteps2) {
                System.debug('----------financeAppStatus---5------'+financeAppStatus);
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            for (Phoenix_Bid_Process_Steps__c step: nextSteps3) {
                System.debug('----------financeAppStatus-----6----'+financeAppStatus);
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            for (Phoenix_Bid_Process_Steps__c step: nextSteps4) {
                System.debug('----------financeAppStatus---7------'+financeAppStatus);
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            
            if (!nextSteps.isEmpty()) {
                update nextSteps;
            }
            if (!nextSteps2.isEmpty()) {
                update nextSteps2;
            }
            if (!nextSteps3.isEmpty()) {
                update nextSteps3;
            }
            if (!nextSteps4.isEmpty()) {
                update nextSteps4;
            }
            
            bidCurrent.Phoenix_Approval_Status__c = 'Business Head Rejected';
            update bidCurrent;
            
        } else {
            
        }
    }
    
    @AuraEnabled
    public static void makeApprovalsCountry(String bidId, String finaceCom, string financeAppStatus, string approvStatus) {
        Phoenix_Bid_Process_Steps__c currentStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c
                                                    where Phoenix_Bid__c =: bidId AND Phoenix_Status__c = 'In Process'
                                                    LIMIT 1
                                                   ];
        List < Phoenix_Bid_Process_Steps__c > updateProcessStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c,Phoenix_Approver__r.Email, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];
        Map < Integer, List < Phoenix_Bid_Process_Steps__c >> stepMap = new Map < Integer, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, List < Phoenix_Bid_Process_Steps__c >> stepNamesMap = new Map < String, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, Integer > stepnameNoMap = new Map < String, Integer > ();
        for (Phoenix_Bid_Process_Steps__c step: updateProcessStep) {
            Integer stepNo = Integer.valueOf(step.Phoenix_Step__c);
            if (stepMap.get(stepNo) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepMap.get(stepNo);
                adededSteps.add(step);
                stepMap.put(stepNo, adededSteps);
            } else {
                stepMap.put(stepNo, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            String stepName = step.Phoenix_Approver_Team__c;
            System.debug('-----------stepName------' + stepName);
            if (stepNamesMap.get(stepName) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepNamesMap.get(stepName);
                adededSteps.add(step);
                stepNamesMap.put(stepName, adededSteps);
            } else {
                stepNamesMap.put(stepName, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            stepnameNoMap.put(stepName, stepNo);
        }
        Phoenix_Bid__c bidCurrent = [select id, Phoenix_Approval_Status__c from Phoenix_Bid__c where id =: bidId];
        List < Phoenix_Bid_Process_Steps__c > nextSteps = stepMap.get(4);
        List < Phoenix_Bid_Process_Steps__c > nextSteps2 = stepMap.get(5);
        List < Phoenix_Bid_Process_Steps__c > nextSteps3 = stepMap.get(6);
        if (financeAppStatus == 'Approved') {
            if (currentStep != null) {
                System.debug('-------updateProcessStep.Phoenix_Status__c-' + currentStep.Phoenix_Status__c);
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = finaceCom;
                update currentStep;
            }
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                step.Phoenix_Status__c = 'In Process'; //'In Process' Submitted //Diff b/w them            
            }
            if (!nextSteps.isEmpty()) {
                update nextSteps;
            }
            bidCurrent.Phoenix_Approval_Status__c = 'Finance';
            update bidCurrent;
        } else if (financeAppStatus == 'Not Approved') {
            
            if (currentStep != null) {
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = finaceCom;
                update currentStep;
            }
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            for (Phoenix_Bid_Process_Steps__c step: nextSteps2) {
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            for (Phoenix_Bid_Process_Steps__c step: nextSteps3) {
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            
            if (!nextSteps.isEmpty()) {
                update nextSteps;
            }
            if (!nextSteps2.isEmpty()) {
                update nextSteps2;
            }
            if (!nextSteps3.isEmpty()) {
                update nextSteps3;
            }
            
            
            bidCurrent.Phoenix_Approval_Status__c = 'Country Head Rejected';
            update bidCurrent;
            
        } else {
            
        }
    }
    
    
    
    @AuraEnabled
    public static void makeApprovalsFinance(String bidId, String finaceCom, string financeAppStatus, string approvStatus) {
        Phoenix_Bid_Process_Steps__c currentStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c
                                                    where Phoenix_Bid__c =: bidId AND Phoenix_Status__c = 'In Process'
                                                    LIMIT 1
                                                   ];
        List < Phoenix_Bid_Process_Steps__c > updateProcessStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c,Phoenix_Approver__r.Email, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];
        Map < Integer, List < Phoenix_Bid_Process_Steps__c >> stepMap = new Map < Integer, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, List < Phoenix_Bid_Process_Steps__c >> stepNamesMap = new Map < String, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, Integer > stepnameNoMap = new Map < String, Integer > ();
        for (Phoenix_Bid_Process_Steps__c step: updateProcessStep) {
            Integer stepNo = Integer.valueOf(step.Phoenix_Step__c);
            if (stepMap.get(stepNo) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepMap.get(stepNo);
                adededSteps.add(step);
                stepMap.put(stepNo, adededSteps);
            } else {
                stepMap.put(stepNo, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            String stepName = step.Phoenix_Approver_Team__c;
            System.debug('-----------stepName------' + stepName);
            if (stepNamesMap.get(stepName) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepNamesMap.get(stepName);
                adededSteps.add(step);
                stepNamesMap.put(stepName, adededSteps);
            } else {
                stepNamesMap.put(stepName, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            stepnameNoMap.put(stepName, stepNo);
        }
        Phoenix_Bid__c bidCurrent = [select id, Phoenix_Approval_Status__c from Phoenix_Bid__c where id =: bidId];
        List < Phoenix_Bid_Process_Steps__c > nextSteps = stepMap.get(5);
        List < Phoenix_Bid_Process_Steps__c > nextSteps2 = stepMap.get(6);
        if (financeAppStatus == 'Approved') {
            if (currentStep != null) {
                System.debug('-------updateProcessStep.Phoenix_Status__c-' + currentStep.Phoenix_Status__c);
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = finaceCom;
                update currentStep;
            }
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                step.Phoenix_Status__c = 'In Process'; //'In Process' Submitted //Diff b/w them            
            }
            if (!nextSteps.isEmpty()) {
                update nextSteps;
            }
            bidCurrent.Phoenix_Approval_Status__c = 'Contracts';
            update bidCurrent;
        } else if (financeAppStatus == 'Not Approved') {
            
            if (currentStep != null) {
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = finaceCom;
                update currentStep;
            }
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            for (Phoenix_Bid_Process_Steps__c step: nextSteps2) {
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            
            
            if (!nextSteps.isEmpty()) {
                update nextSteps;
            }
            if (!nextSteps2.isEmpty()) {
                update nextSteps2;
            }
            
            bidCurrent.Phoenix_Approval_Status__c = 'Finance Rejected';
            update bidCurrent;
            
        } else {
            
        }
    }
    
    @AuraEnabled
    public static void makeApprovalsContracts(String bidId, String finaceCom, string financeAppStatus, string approvStatus) {
        Phoenix_Bid_Process_Steps__c currentStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c
                                                    where Phoenix_Bid__c =: bidId AND Phoenix_Status__c = 'In Process'
                                                    LIMIT 1
                                                   ];
        List < Phoenix_Bid_Process_Steps__c > updateProcessStep = [SELECT Id, Name, Phoenix_Bid__c, Phoenix_Process_Step__c, Phoenix_Step__c, Phoenix_Approver__c,Phoenix_Approver__r.Email, Phoenix_Status__c, Phoenix_Approver_Team__c FROM Phoenix_Bid_Process_Steps__c where Phoenix_Bid__c =: bidId];
        Map < Integer, List < Phoenix_Bid_Process_Steps__c >> stepMap = new Map < Integer, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, List < Phoenix_Bid_Process_Steps__c >> stepNamesMap = new Map < String, List < Phoenix_Bid_Process_Steps__c >> ();
        Map < String, Integer > stepnameNoMap = new Map < String, Integer > ();
        for (Phoenix_Bid_Process_Steps__c step: updateProcessStep) {
            Integer stepNo = Integer.valueOf(step.Phoenix_Step__c);
            if (stepMap.get(stepNo) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepMap.get(stepNo);
                adededSteps.add(step);
                stepMap.put(stepNo, adededSteps);
            } else {
                stepMap.put(stepNo, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            String stepName = step.Phoenix_Approver_Team__c;
            System.debug('-----------stepName------' + stepName);
            if (stepNamesMap.get(stepName) != null) {
                List < Phoenix_Bid_Process_Steps__c > adededSteps = stepNamesMap.get(stepName);
                adededSteps.add(step);
                stepNamesMap.put(stepName, adededSteps);
            } else {
                stepNamesMap.put(stepName, new List < Phoenix_Bid_Process_Steps__c > {
                    step
                        });
            }
            stepnameNoMap.put(stepName, stepNo);
        }
        Phoenix_Bid__c bidCurrent = [select id, Phoenix_Approval_Status__c from Phoenix_Bid__c where id =: bidId];
        List < Phoenix_Bid_Process_Steps__c > nextSteps = stepMap.get(6);
        if (financeAppStatus == 'Processed') {
            if (currentStep != null) {
                System.debug('-------updateProcessStep.Phoenix_Status__c-' + currentStep.Phoenix_Status__c);
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = finaceCom;
                update currentStep;
            }
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                step.Phoenix_Status__c = 'Completed'; //'In Process' Submitted //Diff b/w them            
            }
            if (!nextSteps.isEmpty()) {
                update nextSteps;
            }
            bidCurrent.Phoenix_Approval_Status__c = 'Closed';
            update bidCurrent;
        } else if (financeAppStatus == 'Not_Processed') {
            
            if (currentStep != null) {
                currentStep.Phoenix_Status__c = 'Completed';
                currentStep.Phoenix_Approver__c = userinfo.getuserid();
                currentStep.Phoenix_Description__c = finaceCom;
                update currentStep;
            }
            
            for (Phoenix_Bid_Process_Steps__c step: nextSteps) {
                step.Phoenix_Status__c = 'Not Applicable'; //'In Process' Submitted //Diff b/w them            
            }
            
            if (!nextSteps.isEmpty()) {
                update nextSteps;
            }
            bidCurrent.Phoenix_Approval_Status__c = 'Contracts Rejected';
            update bidCurrent;
        } else {
            
        }
    }
    @AuraEnabled
    public static void saveToBidBus(string bidId, String busStatus, String busCom) {
        Phoenix_Bid__c bidRecord = [select Id, Phoenix_Business_Approval__c, Phoenix_Business_Approval_Comments__c FROM Phoenix_Bid__c WHERE Id =: bidId limit 1];
        bidRecord.Phoenix_Business_Approval__c = busStatus;
        bidRecord.Phoenix_Business_Approval_Comments__c = busCom;
        update bidRecord;
    }
    @AuraEnabled
    public static void saveToBidCountry(string bidId, String countryStatus, String countryCom) {
        Phoenix_Bid__c bidRecord = [select Id, Phoenix_Business_Approval__c, Phoenix_Business_Approval_Comments__c FROM Phoenix_Bid__c WHERE Id =: bidId limit 1];
        bidRecord.Phoenix_Country_Head_Approval__c = countryStatus;
        bidRecord.Phoenix_Country_Head_Comments__c = countryCom;
        update bidRecord;
    }
    @AuraEnabled
    public static void saveToBidContr(string bidId, String contrStatus, String contrCom) {
        Phoenix_Bid__c bidRecord = [select Id, Phoenix_Contracts_Approval__c, Phoenix_Contracts_Approval_Comments__c FROM Phoenix_Bid__c WHERE Id =: bidId limit 1];
        bidRecord.Phoenix_Contracts_Approval__c = contrStatus;
        bidRecord.Phoenix_Contracts_Approval_Comments__c = contrCom;
        update bidRecord;
    }
    @AuraEnabled
    public static void saveToBidFin(string bidId, String finStatus, String finCom) {
        Phoenix_Bid__c bidRecord = [select Id, Phoenix_Finance_Approval__c, Phoenix_Finance_Approval_Comments__c FROM Phoenix_Bid__c WHERE Id =: bidId limit 1];
        bidRecord.Phoenix_Finance_Approval__c = finStatus;
        bidRecord.Phoenix_Finance_Approval_Comments__c = finCom;
        update bidRecord;
    }
}