UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Initial Order Discount for WAC Customers (No-Contract Price Offering)</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                    <label>One Time Buy – Good Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                    <label>One Time Buy – Short Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>One Time Buy Good Dated Shelf Life for New Product Launch</fullName>
                    <label>One Time Buy – Good Dated Shelf Life for New Product Launch</label>
                </value>
                <value>
                    <fullName>OTC New Product</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Good Dated</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Short Dated</fullName>
                </value>
                <value>
                    <fullName>OTC Price Change</fullName>
                </value>
                <value>
                    <fullName>OTC Product Addition</fullName>
                </value>
                <value>
                    <fullName>OTC Rebate Change</fullName>
                </value>
                <value>
                    <fullName>OTC RFP</fullName>
                </value>
                <value>
                    <fullName>OTC Volume Review</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                    <label>Product Removals</label>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>Sales Out Rebate</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                    <label>SRx Direct Pricing</label>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                    <label>SRx IPA Floor Pricing Update</label>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                    <label>SRx IPA Member Addition</label>
                </value>
                <value>
                    <fullName>SRx IPA Price Change</fullName>
                </value>
                <value>
                    <fullName>SRx IPA Product Addition</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                    <label>SRx NEW Individual Pricing Agreement (IPA)</label>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                    <label>SRx RCA/IPA Member GPO or Wholesaler Change</label>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                    <label>SRx RCA Member Addition</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Review_Details__c</fullName>
        <label>Pricing Review Details</label>
        <type>TextArea</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_AllocationReviewBidType.cls
/**
 * @description       : 
 * @author            : Surender Dhruvsoft
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Dhruvsoft
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   25-05-2021   Surender Dhruvsoft   Initial Version
**/
public class Phoenix_AllocationReviewBidType {
    @AuraEnabled
    public static Phoenix_Bid__c getbidInfo(String bidId) {
        Phoenix_Bid__c bidWrap = new Phoenix_Bid__c();
        if (bidId != null) {
            Phoenix_Bid__c bid = new Phoenix_Bid__c();
            bid = [SELECT Id, Phoenix_Review_Details__c, Phoenix_Bid_Type__c, Phoenix_Customer__c FROM Phoenix_Bid__c WHERE Id =: bidId LIMIT 1];
            bidWrap = bid;
        }

        return bidWrap;
    }
}