UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Terms_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Customary_Practices_Customarily__c</fullName>
        <inlineHelpText>List any major customary practices for this customer not found in agreement (IOD&apos;s, special language/sending requirements, etc.)</inlineHelpText>
        <label>Customary Practices not in AGR</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customary_Practices_not_in_AGR1__c</fullName>
        <label>Customary Practices not in AGR</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_BonafideFee_CONSOLIDATE__c</fullName>
        <inlineHelpText>Please list all Related Fees to this account in this section</inlineHelpText>
        <label>Total Bonafide Fee Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Rebate_CONSOLIDATED_Det__c</fullName>
        <inlineHelpText>Please list all Related Rebates to this account in this section</inlineHelpText>
        <label>Total Rebate Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Total_Bonafide_Fee_Details1__c</fullName>
        <label>Total Bonafide Fee Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Total_Rebate_Details1__c</fullName>
        <label>Total Rebate Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Terms Matrix</label>
    <nameField>
        <label>Term Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/PhoenixTermsMatrixTriggerHandler.cls
public class PhoenixTermsMatrixTriggerHandler extends TriggerHandler{
	private list<Phoenix_Terms_Matrix__c> triggerNew;
    private list<Phoenix_Terms_Matrix__c> triggerOld;
    private Map<Id, Phoenix_Terms_Matrix__c> newMap;
    private Map<Id, Phoenix_Terms_Matrix__c> oldMap;
    
    public PhoenixTermsMatrixTriggerHandler(){
        this.newMap = (Map<Id, Phoenix_Terms_Matrix__c>)Trigger.newMap;
        this.oldMap = (Map<Id, Phoenix_Terms_Matrix__c>)Trigger.oldMap;
        this.triggerNew = (List<Phoenix_Terms_Matrix__c>)Trigger.new;
        this.triggerOld = (List<Phoenix_Terms_Matrix__c>)Trigger.old;
        
    }
    public override void beforeInsert(){
        
        for(Phoenix_Terms_Matrix__c termMatrix : triggerNew){
             termMatrix.Phoenix_Total_Rebate_Details1__c	= termMatrix.Phoenix_Customer_Rebate_CONSOLIDATED_Det__c;
             termMatrix.Phoenix_Total_Bonafide_Fee_Details1__c = termMatrix.Phoenix_Customer_BonafideFee_CONSOLIDATE__c ;
             termMatrix.Phoenix_Customary_Practices_not_in_AGR1__c = termMatrix.Phoenix_Customary_Practices_Customarily__c ;
        }
    }
    public override void beforeUpdate(){
        for(Phoenix_Terms_Matrix__c termMatrix : triggerNew ){
            termMatrix.Phoenix_Total_Rebate_Details1__c	= termMatrix.Phoenix_Customer_Rebate_CONSOLIDATED_Det__c;
            termMatrix.Phoenix_Total_Bonafide_Fee_Details1__c = termMatrix.Phoenix_Customer_BonafideFee_CONSOLIDATE__c ;
            termMatrix.Phoenix_Customary_Practices_not_in_AGR1__c = termMatrix.Phoenix_Customary_Practices_Customarily__c ;
        }
        
        
    }
}