UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_12Months_Sales_Unit__c</fullName>
        <label>12Months Sales Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Price__c</fullName>
        <label>Contract Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Phoenix_Dead_Net_Tracking_GR__c</fullName>
        <label>Dead Net(Tracking GR)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_NPR_Status__c</fullName>
        <label>NPR Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Price_Effective_Value_From__c</fullName>
        <label>Price Effective Value From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Price_Effective_Value_To__c</fullName>
        <label>Price Effective Value To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Position__c</fullName>
        <label>Product Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Product_Position__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Positions</relationshipLabel>
        <relationshipName>Product_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <label>Vision Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_Customer_Product_Log__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Customer Product Logs</relationshipLabel>
        <relationshipName>Customer_Product_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Product Logs</relationshipLabel>
        <relationshipName>Customer_Product_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_NPR_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NPR Data</label>
        <referenceTo>Phoenix_NPR_Data__c</referenceTo>
        <relationshipLabel>Customer Product Logs</relationshipLabel>
        <relationshipName>Customer_Product_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_New_Existing_Product__c</fullName>
        <label>New / Existing Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Product</fullName>
                </value>
                <value>
                    <fullName>Existing Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Price_Effective_Value_From__c</fullName>
        <label>Price Effective Value From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Price_Effective_Value_To__c</fullName>
        <label>Price Effective Value To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Product Logs</relationshipLabel>
        <relationshipName>Customer_Product_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Awarded_Volume__c</fullName>
        <label>Awarded Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Deadnet_Price__c</fullName>
        <label>Deadnet Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Customer Product Log</label>
    <nameField>
        <displayFormat>CPLog-{000000}</displayFormat>
        <label>Customer Product Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Awarded_Date__c</fullName>
        <label>Awarded Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Awarded_Price__c</fullName>
        <label>Awarded Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Awarded_Value__c</fullName>
        <label>Awarded Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Awarded_Volume__c</fullName>
        <label>Awarded Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Product_Status__c</fullName>
        <label>Contract Product Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Current_Product_Position__c</fullName>
        <label>Current Product Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_In_NPR_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In NPR Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Is_In_Awarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is In Awarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_NPR_Created_Date__c</fullName>
        <label>NPR Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_NPR_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NPR Data</label>
        <referenceTo>Phoenix_NPR_Data__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_On_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Contract?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Price_Effective_Date__c</fullName>
        <label>Price Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Price_End_Date__c</fullName>
        <label>Price End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <formula>Vision_Product_Code__c+&quot;_&quot;+Vision_Contract_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Identifier</label>
        <type>Text</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/NPRBasedContractProductUpdateBatchCls.cls
/*
In this Class we will update Customerproducttracker Object fields when we find  Same Contract Number and Product Code that Mathches that of  NPR Data,
We will Update Vision_Contract_Product_Status__c as 'Awarded',
Vision_Awarded_Date__c from Npr's Phoenix_Price_Effective_Value_From__c Field,
Vision_NPR_Data__c as Npr Lookup,
Vision_Price_Effective_Date__c,Phoenix_Price_Effective_Value_To__c of Npr,
Vision_Awarded_Price__c from contract Price Od Npr,
Vision_Awarded_Value__c as Phoenix_Contract_Price__c*Phoenix_12Months_Sales_Unit__c of Npr,
Vision_Awarded_Volume__c from Phoenix_12Months_Sales_Unit__c from Npr
*/
public class NPRBasedContractProductUpdateBatchCls implements Database.Batchable < sObject > , Database.Stateful, Schedulable{
    public void execute(SchedulableContext sc) {
        //Database.executeBatch(new NPRBasedContractProductUpdateBatchCls());
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //Querying the NPR Lines created in last 24 Hrs.
       // string s='300011866';
        //string p='1000000785';
        string status='Active';
        //String query = 'Select Phoenix_Product__r.ProductCode,Phoenix_Contract__r.Phoenix_Contract_Number__c, '+Phoenix_Util.getsObjectFieds('Phoenix_NPR_Data__c')+' from Phoenix_NPR_Data__c Where CreatedDate = LAST_N_DAYS:1';
        String query = 'Select Phoenix_Product__r.ProductCode,Phoenix_Contract__r.Phoenix_Contract_Number__c, '+Phoenix_Util.getsObjectFieds('Phoenix_NPR_Data__c')+' from Phoenix_NPR_Data__c where Phoenix_NPR_Status__c=:status';
        if(Test.isRunningTest())query += ' LIMIT 1';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List <Phoenix_NPR_Data__c> nprList) {
        try{
            if(nprList.size() > 0){
                List<Vision_Customer_Product_Tracker__c> listOfCustomerProductTracker = new List<Vision_Customer_Product_Tracker__c>();
              //  List<Vision_Customer_Product_Log__c> listOfCustomerProductLog = new List<Vision_Customer_Product_Log__c>();
                Map<String,Phoenix_NPR_Data__c> existingNPRData = new Map<String,Phoenix_NPR_Data__c>();
                for(Phoenix_NPR_Data__c npr : nprList){
                    string uniqueIdentifier = npr.Phoenix_Product__r.ProductCode+'_'+npr.Phoenix_Contract__r.Phoenix_Contract_Number__c;
                    existingNPRData.put(uniqueIdentifier,npr);
                }
                for(Vision_Customer_Product_Tracker__c track: [SELECT Id,Vision_On_Contract__c,Vision_Price_Effective_Date__c,Vision_Price_End_Date__c,Vision_Awarded_Date__c,Vision_NPR_Data__c,Vision_Contract_Product_Status__c,Vision_Is_In_Awarded__c,Vision_Current_Product_Position__c,Vision_Unique_Identifier__c ,Vision_Contract__c, Vision_Account__c,Vision_Awarded_Volume__c  FROM Vision_Customer_Product_Tracker__c WHERE Vision_Unique_Identifier__c IN:existingNPRData.keySet()]){
                    if(existingNPRData.containsKey(track.Vision_Unique_Identifier__c)){
                        track.Vision_Contract_Product_Status__c = 'Awarded';
                        track.Vision_Is_In_Awarded__c=True;
                       track.Vision_Current_Product_Position__c= existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Product_Position__c;
                        track.Vision_Awarded_Date__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Price_Effective_Value_From__c;
                        track.Vision_NPR_Data__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Id;
                       // track.Vision_In_NPR_Data__c = true;
                        track.Vision_On_Contract__c = True;
                        track.Vision_NPR_Created_Date__c = existingNPRData.get(track.Vision_Unique_Identifier__c).createdDate;
                        track.Vision_Price_Effective_Date__c=existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Price_Effective_Value_From__c;
                        track.Vision_Price_End_Date__c=existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Price_Effective_Value_To__c;
                        
                        	track.Vision_Awarded_Volume__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_12Months_Sales_Unit__c;
                        	track.Vision_Awarded_Price__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Contract_Price__c;
                            if(existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Contract_Price__c != null && existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_12Months_Sales_Unit__c !=null)
                            	track.Vision_Awarded_Value__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Contract_Price__c * existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_12Months_Sales_Unit__c;
                            //if(existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_12Months_Sales_Unit__c != null && track.Vision_Temp_Awarded_Value__c != null)
                            //	track.Vision_Awarded_Value__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_12Months_Sales_Unit__c * track.Vision_Temp_Awarded_Value__c;
                        
                        listOfCustomerProductTracker.add(track);
                     /*  Vision_Customer_Product_Log__c log = new Vision_Customer_Product_Log__c(
                            Phoenix_Customer__c = track.Vision_Account__c,
                            Phoenix_Contract__c = track.Vision_Contract__c,
                            Phoenix_NPR_Data__c = track.Vision_NPR_Data__c,
                            Vision_Awarded_Volume__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_12Months_Sales_Unit__c,
                            Vision_Deadnet_Price__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Dead_Net_Tracking_GR__c,
                            Phoenix_New_Existing_Product__c = 'New Product',
                            Phoenix_Status__c = 'Active',
                            Phoenix_Price_Effective_Value_From__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Price_Effective_Value_From__c,
                            Phoenix_Price_Effective_Value_To__c = existingNPRData.get(track.Vision_Unique_Identifier__c).Phoenix_Price_Effective_Value_To__c
                        );
                        listOfCustomerProductLog.add(log);*/
                    }
                }
                update listOfCustomerProductTracker;
              //  insert listOfCustomerProductLog;
            }
            else{
              }
        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'NPRBasedContractProductUpdateBatchCls', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
    public void finish(Database.BatchableContext BC) {
        if(!Test.isRunningTest())
           Database.executeBatch(new AwardedQtyContractPrdStatusBatchCls(),2000);
    }
}