UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Approval_Delegation_History__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Delegated_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Delegation_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Delegation_End_Time__c</fullName>
        <label>Delegation End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Delegation_Start_Time__c</fullName>
        <label>Delegation Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Active_delegator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active  delegator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Delegation_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Delegation History</label>
    <nameField>
        <displayFormat>ApprovalDelegation-{000000}</displayFormat>
        <label>User Delegation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Delegation History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/User.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Delegated_Approver__c</fullName>
        <label>Delegated Approver</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <valueField>$Source.ProfileId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <relationshipName>Phoenix_Delegated_Approvers</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Phoenix_Delegation_End_Time__c</fullName>
        <label>Delegation End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Delegation_Start_Time__c</fullName>
        <label>Delegation Start Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Phoenix_ActiveDelegatorChecker.cls
Public class Phoenix_ActiveDelegatorChecker implements Schedulable {
    Public void execute(SchedulableContext SC) {
        List<Phoenix_Approval_Delegation_History__c> deleHistory = [Select Id,	Phoenix_Delegated_Approver__c,Phoenix_User__c,	Phoenix_Delegation_Start_Time__c,Phoenix_Delegation_End_Time__c,Phoenix_Is_Active_delegator__c From Phoenix_Approval_Delegation_History__c ];
        List<Phoenix_Approval_Delegation_History__c> updatedDeleHistory = new  List<Phoenix_Approval_Delegation_History__c>();
       set<ID> userIds = new set<ID>();
        for(Phoenix_Approval_Delegation_History__c historyRecord : deleHistory){  if(historyRecord.Phoenix_Delegation_End_Time__c < System.now() && historyRecord.Phoenix_Is_Active_delegator__c == True )  {historyRecord.Phoenix_Is_Active_delegator__c = False; updatedDeleHistory.add(historyRecord);userIds.add(historyRecord.Phoenix_User__c); }
            
        }
        if (updatedDeleHistory.size()>0) { update updatedDeleHistory;List<User> users= new List<User>();
            for(Id uId:userIds)          {users.add(new User(Id=uId,Phoenix_Delegated_Approver__c = null,	Phoenix_Delegation_End_Time__c=null,Phoenix_Delegation_Start_Time__c=null));}update users; }
    }
  //  system.schedule('Phoenix_ActiveDelegatorChecker', '0 0 0/1 1/1 * ? *', New Phoenix_ActiveDelegatorChecker());

}