UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_WAC_Change__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>WAC Changes</relationshipLabel>
        <relationshipName>WAC_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WAC Change</label>
    <nameField>
        <displayFormat>WAC Change-{000000}</displayFormat>
        <label>WAC Change Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WAC Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_WAC_Change_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>WAC Change Line Items</relationshipLabel>
        <relationshipName>WAC_Change_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_WAC_Change__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WAC Change</label>
        <referenceTo>Phoenix_WAC_Change__c</referenceTo>
        <relationshipLabel>WAC Change Line Items</relationshipLabel>
        <relationshipName>WAC_Change_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>WAC Change Line Items</relationshipLabel>
        <relationshipName>WAC_Change_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WAC Change Line Item</label>
    <nameField>
        <displayFormat>WAC Change Line-{000000}</displayFormat>
        <label>WAC Change Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WAC Change Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product_Family__c.object
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/UpdateWACLineItemsBatch.cls
public class UpdateWACLineItemsBatch implements Database.Batchable < sObject > {
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Name, Phoenix_Product_Family__c, Phoenix_WAC_Change__c, Phoenix_WAC_Change__r.Product_Family__c, Product_Family__c, Phoenix_Product__c, Phoenix_Product__r.Product_Family__c FROM Phoenix_WAC_Change_Line_Item__c WHERE Product_Family__c = null';
        if(Test.isRunningTest())query += ' LIMIT 1';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List <Phoenix_WAC_Change_Line_Item__c> lineItemsList) {
        try{
            if(lineItemsList.size() > 0){
                Map<String,Phoenix_WAC_Change__c> mapOfWACChangesToUpdate = new Map<String,Phoenix_WAC_Change__c>();
                List<Phoenix_WAC_Change__c> wacChangesToUpdate = new List<Phoenix_WAC_Change__c>();
                for(Phoenix_WAC_Change_Line_Item__c lineItem: lineItemsList){
                    Phoenix_WAC_Change__c wacChange = lineItem.Phoenix_WAC_Change__r;
                    lineItem.Product_Family__c = lineItem.Phoenix_Product__r.Product_Family__c;
                    wacChange.Product_Family__c = lineItem.Phoenix_Product__r.Product_Family__c;
                    mapOfWACChangesToUpdate.put(lineItem.Phoenix_WAC_Change__c, wacChange);
                }
                if(mapOfWACChangesToUpdate != null){
                    update mapOfWACChangesToUpdate.values();
                }
                update lineItemsList;
            }
        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'UpdateWACLineItemsBatch', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
    public void finish(Database.BatchableContext BC) {
        
    }
}