UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_GCP_Opportunity_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>current_position__c</fullName>
        <label>GCP Current Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP Opportunity Tracker</label>
    <nameField>
        <displayFormat>GCP Opp Tracker-{0000000}</displayFormat>
        <label>GCP Opportunity Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Opportunity Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Current_Product_Position__c</fullName>
        <label>Current Product Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/UpdateOptyTrackerCurrentPositionBatchCls.cls
public class UpdateOptyTrackerCurrentPositionBatchCls implements Database.Batchable < sObject > , Database.Stateful,Schedulable,Database.AllowsCallouts {
    public void execute(SchedulableContext sc) {
        //Database.executeBatch(new UpdateOptyTrackerCurrentPositionBatchCls () );
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        
        String query = 'Select  ' +Phoenix_Util.getsObjectFieds('Phoenix_GCP_Opportunity_Tracker__c')+' from Phoenix_GCP_Opportunity_Tracker__c';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List <Phoenix_GCP_Opportunity_Tracker__c> OptyTrackerRecords) {
        try{
            if(OptyTrackerRecords.size() > 0){
                List<Phoenix_GCP_Opportunity_Tracker__c> OppTracker = new List<Phoenix_GCP_Opportunity_Tracker__c>();
                Map<String,Phoenix_GCP_Opportunity_Tracker__c> OptyTracker = new Map<String,Phoenix_GCP_Opportunity_Tracker__c>();
                for(Phoenix_GCP_Opportunity_Tracker__c PGOT:OptyTrackerRecords){
                    OptyTracker.put(PGOT.GCP_Product_Family__c,PGOT);  
                }
                
                for(Vision_Customer_Product_Tracker__c VCPT:[select Vision_Product_Family__c from Vision_Customer_Product_Tracker__c where Vision_Product_Family__c in : OptyTracker.keyset()]){
                    OptyTracker.get(VCPT.Vision_Product_Family__c).current_position__c=VCPT.Vision_Current_Product_Position__c;
                    OppTracker.add(OptyTracker.get(VCPT.Vision_Product_Family__c));
                }
                
               
                if(OppTracker.size()>0){
                    Update OppTracker; 
                }
                
            }
            
        }

        
        
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'UpdateOptyTrackerCurrentPositionBatchCls', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
        public void finish(Database.BatchableContext bc){
                    /*  Integer Records=[select count() from Phoenix_GCP_Opportunity_Tracker__c];
                string RecordsCount= String.valueOf(Records);
                
                Phoenix_Util.sendBatchJobCompletionEmail('GCP Opportunity Tracker current position ', 'RecordsCount');*/
            
        
    }
}