UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Marketing_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Product Director</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Marketing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product_Family__c.object
<CustomObject>
    <fields>
        <fullName>Family_Group__c</fullName>
        <label>Family Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>SRx</fullName>
                </value>
                <value>
                    <fullName>OTC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/SRx_IndirectSales_Summary_Table__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hospital_Name__c</fullName>
        <label>Hospital Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Name__c</fullName>
        <label>Sales Rep Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Settlement_Paid_Date__c</fullName>
        <label>Settlement Paid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>SRx IndirectSales Summary Table</label>
    <nameField>
        <label>SRx IndirectSales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SRx IndirectSales Summary Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/IndirectSalesDataClsTest.cls
@isTest
public class IndirectSalesDataClsTest {
    
    @isTest
    public static void test1()
    {
        String salesRepName = 'TestSalesRep';
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@example.com',
            UserName = 'testuser@example.com',
            Alias = 'TUser',
            CommunityNickname = 'testuser',
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );

        //insert testUser;
        //String userId = DirectSalesDataCls.getuser(salesRepName);
        //System.assertNotEquals('', userId, 'User ID should not be empty');
        
        //String userName = DirectSalesDataCls.getuserName(testUser.Id);
        //System.assertNotEquals('', userName, 'User Name should not be empty');
        
        
        
        
        Product2 p2 = new Product2();
        p2.Family = 'Daptomycin Inj 500mg US';
        p2.Name = 'Test';
        p2.ProductCode = '300029858';
        p2.Phoenix_Marketing_Lead__c = UserInfo.getUserId();
        p2.Phoenix_Product_Director__c = UserInfo.getUserId();
        insert p2;
        
        Product2 p3 = new Product2();
        p3.Family = 'Abiraterone Acetate Tab';
        p3.ProductCode = '300029858';
        p3.Name = 'Test Product';
        p3.Phoenix_Product_Director__c = UserInfo.getUserId();
        p3.Phoenix_Marketing_Lead__c = UserInfo.getUserId();
        p3.Phoenix_Product_Director__c = UserInfo.getUserId();
        insert p3;
        
        Product_Family__c pd = new Product_Family__c();
        pd.Name = 'FLUPHENAZINE';
        pd.Family_Group__c = 'FLUPHENAZINE TABS';
        pd.Vision_Segment__c = 'Rx';
        pd.Vision_IsActive__c = true;
        insert pd;
        
        Product_Family__c pd1 = new Product_Family__c();
        pd1.Name = 'ALLOPURINOL';
        pd1.Family_Group__c = 'Allopurinol';
        pd1.Vision_Segment__c = 'Rx';
        pd1.Vision_IsActive__c = true;
        insert pd1;
        
        SRx_IndirectSales_Summary_Table__c s1 = new SRx_IndirectSales_Summary_Table__c();
        s1.Sales_Rep_Name__c = 'Brenda Kern';
        s1.Hospital_Name__c = 'FRESNO COMM MC MAIL ORDER PHY (SAP)';
        //s1.Customer_Name__c ='HC Pharmacy Central INC';
        s1.Product_Family__c = 'Palonosetron Hydrochloride';
        s1.Product__c = 'Palonosetron HCL Inj 0.25mg/5ml USA 505j';
        s1.Sales__c=1660.8;
        s1.Units__c = 240;
        s1.Contract__c = 'Test1';
        s1.Contract_Number__c = '380991';
        s1.Settlement_Paid_Date__c = date.newinstance(2023,10,11);
        s1.Region__c = 'East';
        insert s1;
        
        SRx_IndirectSales_Summary_Table__c s2 = new SRx_IndirectSales_Summary_Table__c();
        s2.Sales_Rep_Name__c = 'Heather Harris';
        s2.Hospital_Name__c = 'MERCY HEALTH CENTER PHCY (SAP)';
        //s2.Customer_Name__c ='Pinnacle Distribution, Inc';
        s2.Product_Family__c = 'Ertapenem';
        s2.Product__c = 'Ertapenem for Inj. 1g/vial 10s';
        s2.Sales__c=140400;
        s2.Units__c = 7200;
        s2.Contract__c = 'Test1';
        s2.Contract_Number__c = '380991';
        s2.Settlement_Paid_Date__c = date.newinstance(2023,04,28);
        s2.Region__c = 'East';
        insert s2;
        
        SRx_IndirectSales_Summary_Table__c s3 = new SRx_IndirectSales_Summary_Table__c();
        s3.Sales_Rep_Name__c = 'Brenda Kern';
        s3.Hospital_Name__c = 'THE JOHN M & SALLY B THORNTON (SAP)';
        //s3.Customer_Name__c ='HC Pharmacy Central INC';
        s3.Product_Family__c = 'Bivalirudin';
        s3.Product__c = 'Bivalirudin Injection 250mg/Vial 10s USA';
        s3.Sales__c=19680;
        s3.Units__c = 480;
        s3.Contract__c = 'Test1';
        s3.Contract_Number__c = '380991';
        s3.Settlement_Paid_Date__c = date.newinstance(2023,07,11);
        s3.Region__c = 'East';
        insert s3;
        
        list<String> customerlist = new list<string>{'FRESNO COMM MC MAIL ORDER PHY (SAP)','THE JOHN M & SALLY B THORNTON (SAP)'};
        list<String> productList = new list<string>{'Ertapenem for Inj. 1g/vial 10s','Bivalirudin Injection 250mg/Vial 10s USA'};
        List<String> contracts = new List<String>{'Test1','Test2'};
        //List<WrapperClass> result= DirectSalesDataCls.getDirectSalesList('Brenda Kern','HC Pharmacy Central INC');
        IndirectSalesDataCls.CustomerSpecific_getIndirectSalesList('Test1','FRESNO COMM MC MAIL ORDER PHY (SAP)','Brenda Kern',contracts,customerlist,productList);
        IndirectSalesDataCls.productFamily_getIndirectSalesList('Test1','THE JOHN M & SALLY B THORNTON (SAP)','Bivalirudin','Brenda Kern',contracts,customerlist,productList);
        IndirectSalesDataCls.ContractSpecific_getIndirectSalesList('Test1','Brenda Kern',contracts,customerlist,productList);
        
        IndirectSalesDataCls.getIndirectSalesList(contracts,'Brenda Kern',customerlist,productList);
        IndirectSalesDataCls.getProductNames('Brenda Kern');
        IndirectSalesDataCls.getCustomerNames('Brenda Kern');
        IndirectSalesDataCls.getContracts();
        
    }

}