UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_GCN_Sequence_Number__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GCN Sequence Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_GPI_Generic_Product_Identifier__c</fullName>
        <description>It contains 14 characters.</description>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GPI (Generic Product Identifier)  </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Exclude_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is Exclude Bid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <inlineHelpText>National Drug Code: SAP field</inlineHelpText>
        <label>NDC - 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Vision_GCP_SFDC_Profitability_SKU_Level__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Number__c</fullName>
        <label>GCP Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GCP SFDC Profitability SKU Level</relationshipLabel>
        <relationshipName>GCP_SFDC_Profitability_SKU_Level</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GCP SFDC Profitability SKU Level</relationshipLabel>
        <relationshipName>GCP_SFDC_Profitability_SKU_Level</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_SKU_Code__c</fullName>
        <label>GCP SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP SFDC Profitability SKU Level</label>
    <nameField>
        <displayFormat>Pro-SKU-Level-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP SFDC Profitability SKU Level</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/GoogleSFDCProfitabilitySKULevelTest.cls
@istest
public class GoogleSFDCProfitabilitySKULevelTest {
    static testmethod void setup(){
        Account a= new Account();
        a.Name='test';
        a.AccountNumber='123';
        insert a;
        Product2 p=new Product2();
        p.Name='abc pharma';
      //  p.Phoenix_NDC_11__c='23364848';
        p.ProductCode='123566';
       // p.Phoenix_NDC__c='5555555';
       // p.Phoenix_GPI_Generic_Product_Identifier__c = '11111';
       // p.Family = 'Test Family';
       // p.Phoenix_Throughput_cost__c=10.23456576;
       // p.Phoenix_GCN_Sequence_Number__c='666666';
       // p.Phoenix_Pkg_Size__c=25.0;
       // p.IsActive = true;
       // p.Phoenix_Is_Exclude_Bid__c = false;
        
        insert p;
        Vision_GCP_SFDC_Profitability_SKU_Level__c sfp= new  Vision_GCP_SFDC_Profitability_SKU_Level__c();
        
        
        sfp.Vision_SKU_Code__c='123566';
        sfp.Vision_Customer_Number__c='123';
        sfp.Vision_Product_Family__c='su';
        // sfp.Vision_Customer__c=a.id;
        // sfp.Vision_Product__c=p.id;
        sfp.GCP_Product_Family__c='gf 1%e';
        insert sfp;
        test.startTest();
        GoogleSFDCProfitabilitySKULevel b = new GoogleSFDCProfitabilitySKULevel();
       Database.executeBatch(new GoogleSFDCProfitabilitySKULevel(1,1));
        Database.executeBatch(b);
        test.stopTest();
    
    }
    
}