UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Rx_Compliance_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Is_Initial_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Initial Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>M1_Direct_Net_Dollar__c</fullName>
        <label>M1 Direct Net Dollar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>M1_Direct_Quantity__c</fullName>
        <label>M1 Direct Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M2_Direct_Quantity__c</fullName>
        <label>M2 Direct Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M2_Direct_Value_Compliance__c</fullName>
        <formula>IF( AND( ISNULL(M2_Direct_Net_Dollar__c) ,ISNULL(Vision_Direct_Awarded_Value_Monthly__c)) , 0,(M2_Direct_Net_Dollar__c/Vision_Direct_Awarded_Value_Monthly__c)*100 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>M2 Direct Value Compliance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M2_Indirect_Value_Compliance__c</fullName>
        <formula>IF( AND( ISNULL(M2_Indirect_Net_Dollar__c) ,ISNULL(Vision_Indirect_Awarded_Value_Monthly__c)) , 0,(M2_Indirect_Net_Dollar__c/Vision_Indirect_Awarded_Value_Monthly__c)*100 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>M2 Indirect Value Compliance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M2_Total_Compliance__c</fullName>
        <formula>IF(AND(M2_Total_Quantity__c &gt;0,Vision_Total_Awarded_Qty_Monthly__c &gt;0) ,(M2_Total_Quantity__c / Vision_Total_Awarded_Qty_Monthly__c)*100 , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>M2 Total Compliance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month1__c</fullName>
        <label>Month1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month2__c</fullName>
        <label>Month2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month3__c</fullName>
        <label>Month3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vision Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Rx_Compliance_Direct_Sales_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Direct_Awarded_Qty__c</fullName>
        <label>Direct Awarded Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Direct_Awarded_Value_Monthly__c</fullName>
        <formula>IF( ISNULL(Vision_Direct_Awarded_Value__c) , 0, Vision_Direct_Awarded_Value__c/12)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Direct Awarded Value Monthly</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Direct_Awarded_Value__c</fullName>
        <label>Direct Awarded Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Indirect_Awarded_Value_Monthly__c</fullName>
        <formula>IF( ISNULL(Vision_Indirect_Awarded_Value__c) , 0, Vision_Indirect_Awarded_Value__c/12)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Indirect Awarded Value Monthly</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Indirect_Awarded_Value__c</fullName>
        <label>Indirect Awarded Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_NDC__c</fullName>
        <label>NDC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Package_Size__c</fullName>
        <label>Package Size</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vision Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rx_Compliance_Direct_Sales_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Total_Awarded_Value_Monthly__c</fullName>
        <formula>Vision_Direct_Awarded_Value_Monthly__c  +  Vision_Indirect_Awarded_Value_Monthly__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vision Total Awarded Value Monthly</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Total_Awarded_Value__c</fullName>
        <formula>Vision_Direct_Awarded_Value__c  +  Vision_Indirect_Awarded_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vision Total Awarded Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Rx Compliance Summary</label>
    <nameField>
        <label>Rx Compliance Direct Sales Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rx Compliance Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/Vision_Rx_Compliance_Awarded_Qty_Test.cls
@isTest
public class Vision_Rx_Compliance_Awarded_Qty_Test {
    static testmethod void  test(){
        Product2 pro = new Product2();
        pro.Name ='test product';
        pro.Phoenix_Pkg_Size__c = 1;
        pro.Phoenix_NDC_11__c = '1532468';
        pro.ProductCode ='test code';
        insert pro;
        
        Account acc = new Account();
        acc.Name= 'Walgreen Company';
        insert acc;
        
        
        
        Rx_Compliance_Summary__c summaryObj = new Rx_Compliance_Summary__c();
        summaryObj.Vision_Product__c = pro.Id;
        summaryObj.Vision_Account__c = acc.Id;
        summaryObj.Vision_Package_Size__c = pro.Phoenix_Pkg_Size__c;
        summaryObj.Vision_NDC__c = pro.Phoenix_NDC_11__c;
        summaryObj.M1_Direct_Quantity__c = 10;
        summaryObj.M2_Direct_Quantity__c = 15;
        summaryObj.Is_Initial_Order__c = False;
        summaryObj.Month1__c = 'Oct 21';
        summaryObj.Month2__c = 'Nov 21';
        summaryObj.Month3__c = 'Dec 21';
        summaryObj.Month3__c = 'Jan 22';
        summaryObj.Month3__c = 'Feb 22';
        summaryObj.Month3__c = 'Mar 22';
        //summaryObj.M2_Direct_Value_Compliance__c = 10;
        //summaryObj.M2_Indirect_Value_Compliance__c = 10;
        summaryObj.M1_Direct_Net_Dollar__c = 10000;
        summaryObj.Vision_Direct_Awarded_Qty__c = 50;
        //summaryObj.M2_Total_Compliance__c = 10;
        summaryObj.Vision_Direct_Awarded_Value__c = 0;
        //summaryObj.Vision_Direct_Awarded_Value_Monthly__c = 0;
        summaryObj.Vision_Indirect_Awarded_Value__c = 1772;
        //summaryObj.Vision_Indirect_Awarded_Value_Monthly__c = 148;
        //summaryObj.Vision_Total_Awarded_Value__c = 1772;
        //summaryObj.Vision_Total_Awarded_Value_Monthly__c = 148;
        
        insert summaryObj;
        
        //String customerId='Walgreen Company';
        
        Vision_Rx_Compliance_Awarded_Qty.getComplianceData(acc.Id);
        Vision_Rx_Compliance_Awarded_Qty.getAwardedPositionData(acc.Id, pro.ProductCode);
          Vision_Rx_Compliance_Awarded_Qty.getDirectAwardedPositionData(acc.Id, pro.ProductCode);
          Vision_Rx_Compliance_Awarded_Qty.getIndirectAwardedPositionData(acc.Id, pro.ProductCode);
        Vision_Rx_Compliance_Awarded_Qty.getOnlyComplianceData(acc.Id, true, false);              
        Vision_Rx_Compliance_Awarded_Qty.getOnlyComplianceData(acc.Id, true, true); 
        Vision_Rx_Compliance_Awarded_Qty.getOnlyComplianceDataHistoricalsales(acc.Id, true, false);
        Vision_Rx_Compliance_Awarded_Qty.getOnlyComplianceDataHistoricalsales(acc.Id, true, true);
    }

}