UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/SRx_IndirectSales_Summary_Table__c.object
<CustomObject>
    <fields>
        <fullName>Hospital_Name__c</fullName>
        <label>Hospital Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Settlement_Paid_Date__c</fullName>
        <label>Settlement Paid Date</label>
        <type>Date</type>
    </fields>
    <label>SRx IndirectSales Summary Table</label>
    <nameField>
        <label>SRx IndirectSales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SRx IndirectSales Summary Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/deleteIndirectSalesSummaryBatchTest.cls
@isTest
public class deleteIndirectSalesSummaryBatchTest {
    
    @isTest
    public static void test1()
    {
        SRx_IndirectSales_Summary_Table__c s1 = new SRx_IndirectSales_Summary_Table__c();
        s1.Hospital_Name__c = 'test';
        s1.Settlement_Paid_Date__c = system.today();
        s1.Product__c = 'test';
        insert s1;
        
        SRx_IndirectSales_Summary_Table__c s2 = new SRx_IndirectSales_Summary_Table__c();
        s2.Hospital_Name__c = 'test';
        s2.Settlement_Paid_Date__c = system.today();
        s2.Product__c = 'test';
        insert s2;
        
        Database.executeBatch(new deleteIndirectSalesSummaryBatch());
    }

}