UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Vision_Bid_Simulator__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Vision_Bid_Simulators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Vision_Bid_Simulators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Scenario_Type__c</fullName>
        <label>Scenario Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Proposed Price Fine Tuning</fullName>
                </value>
                <value>
                    <fullName>Customer Deadnet Refinment</fullName>
                </value>
                <value>
                    <fullName>TPT Cost Per pack Fine Tuning</fullName>
                </value>
                <value>
                    <fullName>DRL Deadnet Enhancement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid Simulator</label>
    <nameField>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vision Bid Simulators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Vision_BidSimulatorController.cls
public class Vision_BidSimulatorController {
    public class simWrapper{
        @auraEnabled
        Public Account accObj;
        @auraEnabled
        public Product2 prodObj;
        @auraEnabled
        Public List<Vision_Bid_Simulator__c> scenList;
        @auraEnabled
        public boolean isError = false;
        @auraEnabled
        public string errorMessage;
    }
    
    @auraEnabled
    public static simWrapper getProdList(String prodId, String accId){
        simWrapper wrapObj = new simWrapper();
        List<Vision_Bid_Simulator__c> bidSimList = database.query('SELECT '+Phoenix_Util.getsObjectFieds('Vision_Bid_Simulator__c')+' FROM Vision_Bid_Simulator__c WHERE Product__c =: prodId AND Account__c =: accId');
        Product2 prodObj = database.query('SELECT '+Phoenix_Util.getsObjectFieds('Product2')+' FROM Product2 WHERE Id =: prodId');
        Account accObj = database.query('SELECT '+Phoenix_Util.getsObjectFieds('Account')+' FROM Account WHERE Id =: accId');
        wrapObj.accObj = accObj;
        wrapObj.prodObj = prodObj;
        wrapObj.scenList = bidSimList;
        return wrapObj;
    }
    
    @auraEnabled
    public static List<String> getScenarioList(){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Vision_Bid_Simulator__c.Vision_Scenario_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }
}