PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GPO1__c</fullName>
        <label>GPO 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ahold Indirect Contract</fullName>
                </value>
                <value>
                    <fullName>Intalere</fullName>
                </value>
                <value>
                    <fullName>Asembia</fullName>
                </value>
                <value>
                    <fullName>HPG</fullName>
                </value>
                <value>
                    <fullName>Innovatix</fullName>
                </value>
                <value>
                    <fullName>MedAssets</fullName>
                </value>
                <value>
                    <fullName>MHA</fullName>
                </value>
                <value>
                    <fullName>MMCAP</fullName>
                </value>
                <value>
                    <fullName>Vizient</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>PACT</fullName>
                </value>
                <value>
                    <fullName>ROi</fullName>
                </value>
                <value>
                    <fullName>The Resource Group</fullName>
                </value>
                <value>
                    <fullName>CHPC</fullName>
                </value>
                <value>
                    <fullName>Gerimed</fullName>
                </value>
                <value>
                    <fullName>Health Trust</fullName>
                </value>
                <value>
                    <fullName>Intersectta</fullName>
                </value>
                <value>
                    <fullName>ION</fullName>
                </value>
                <value>
                    <fullName>TRG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_RCA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Parent RCA Agreement</inlineHelpText>
        <label>RCA Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Phoenix_Contract__c.Phoenix_Is_RCA_Contract__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler1__c</fullName>
        <label>Wholesaler #1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AmerisourceBergen</fullName>
                </value>
                <value>
                    <fullName>HPG</fullName>
                </value>
                <value>
                    <fullName>McKesson</fullName>
                </value>
                <value>
                    <fullName>Novation</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>ASD Specialty Healthcare</fullName>
                </value>
                <value>
                    <fullName>Cardinal</fullName>
                </value>
                <value>
                    <fullName>Oncology Supply</fullName>
                </value>
                <value>
                    <fullName>Morris &amp; Dickson</fullName>
                </value>
                <value>
                    <fullName>HD Smith</fullName>
                </value>
                <value>
                    <fullName>Anda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wholesaler_DC_1__c</fullName>
        <label>Wholesaler #1 DC</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Wholesaler1__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Amityville, NY</fullName>
                </value>
                <value>
                    <fullName>Anchorage, AK</fullName>
                </value>
                <value>
                    <fullName>Atlanta, GA</fullName>
                </value>
                <value>
                    <fullName>Auburn, WA</fullName>
                </value>
                <value>
                    <fullName>Aurora, CO</fullName>
                </value>
                <value>
                    <fullName>Aurora, IL</fullName>
                </value>
                <value>
                    <fullName>Bethlehem, PA</fullName>
                </value>
                <value>
                    <fullName>Birmingham, AL</fullName>
                </value>
                <value>
                    <fullName>Boston, MA</fullName>
                </value>
                <value>
                    <fullName>Buffalo, NY</fullName>
                </value>
                <value>
                    <fullName>Carol Stream, IL</fullName>
                </value>
                <value>
                    <fullName>Carson, CA</fullName>
                </value>
                <value>
                    <fullName>Chicago, IL</fullName>
                </value>
                <value>
                    <fullName>Clear Lake, IA</fullName>
                </value>
                <value>
                    <fullName>Columbus, OH</fullName>
                </value>
                <value>
                    <fullName>Conroe, TX</fullName>
                </value>
                <value>
                    <fullName>Corona, CA</fullName>
                </value>
                <value>
                    <fullName>Dallas, TX</fullName>
                </value>
                <value>
                    <fullName>Delran, NJ</fullName>
                </value>
                <value>
                    <fullName>Denver, CO</fullName>
                </value>
                <value>
                    <fullName>Detroit, MI</fullName>
                </value>
                <value>
                    <fullName>Elk Grove, CA</fullName>
                </value>
                <value>
                    <fullName>Everett, WA</fullName>
                </value>
                <value>
                    <fullName>Flower Mound, TX</fullName>
                </value>
                <value>
                    <fullName>Greensboro, NC</fullName>
                </value>
                <value>
                    <fullName>Groveport, OH (NLC)</fullName>
                </value>
                <value>
                    <fullName>Hawaii, HI</fullName>
                </value>
                <value>
                    <fullName>Honolulu, HI</fullName>
                </value>
                <value>
                    <fullName>Houston, TX</fullName>
                </value>
                <value>
                    <fullName>Kansas City, MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Phoenix_RCA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RCA / IPA Contract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Phoenix_Contract__c.Phoenix_Is_RCA_Contract__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Phoenix_Contract__c.Phoenix_Is_IPA_Contract__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_RCA_Change_Date__c</fullName>
        <label>Change Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Contracts Approved</fullName>
                </value>
                <value>
                    <fullName>SCM Approved</fullName>
                </value>
                <value>
                    <fullName>Marketing Approved</fullName>
                </value>
                <value>
                    <fullName>Finance Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Submitted</fullName>
                </value>
                <value>
                    <fullName>Proposal Accepted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_IPA_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is IPA Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_RCA_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is RCA Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_RCA_IPA_LINE__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>RCA IPA LINES</relationshipLabel>
        <relationshipName>RCA_IPA_LINES</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_RCA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RCA / IPA Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>RCA IPA LINES</relationshipLabel>
        <relationshipName>RCA_IPA_LINES</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_RCA_Change_Date__c</fullName>
        <label>Change Date</label>
        <type>Date</type>
    </fields>
    <label>RCA IPA LINE</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>RCA IPA LINE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RCA IPA LINES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/IPAMemberAdditionClsTest.cls
/**
 * @description       : 
 * @author            : Surender Dhruvsoft
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Dhruvsoft
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   25-05-2021   Surender Dhruvsoft   Initial Version
**/
@isTest
public class IPAMemberAdditionClsTest {
    static testmethod void IPAMemberAdditionClsMethod() {
        Id phoenixRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Bid Accounts').getRecordTypeId();
        Phoenix_Contract__c pc1 = new Phoenix_Contract__c(Name = 'Test Contract1', Phoenix_Contract_Start_Date__c = system.today(), Phoenix_Contract_End_Date__c = system.today() + 10, Phoenix_Is_RCA_Contract__c = true, Phoenix_Contract_Number__c = '1234567', Phoenix_Is_IPA_Contract__c = true);
        insert pc1;
        Phoenix_Bid__c pb = new Phoenix_Bid__c();
        pb.Phoenix_Status__c = 'New';

        pb.Phoenix_Comments__c = 'Test Comments';
        pb.Phoenix_RCA_Change_Date__c = system.today();
        insert pb;
        list < Account > accList = new list < Account > ();
        Account testAccount = new Account(Name = 'Test Account', Phoenix_RCA_Agreement__c = pc1.Id, GPO1__c = 'Ahold Indirect Contract', Wholesaler1__c = 'AmerisourceBergen', Wholesaler_DC_1__c = 'Amityville, NY', Street_Address_1__c = 'Madhapur', State__c = 'AK', City__c = 'Hyderabad', Zip__c = '500082');
        Account testAccount1 = new Account(Name = 'Test Account1', Phoenix_RCA_Agreement__c = pc1.Id, GPO1__c = 'Ahold Indirect Contract', Wholesaler1__c = 'AmerisourceBergen', Wholesaler_DC_1__c = 'Amityville, NY');
        Account testAccount2 = new Account(Name = 'Test Account2', Phoenix_RCA_Agreement__c = pc1.Id, GPO1__c = 'Ahold Indirect Contract', Wholesaler1__c = 'AmerisourceBergen', Wholesaler_DC_1__c = 'Amityville, NY');
        accList.add(testAccount);
        accList.add(testAccount1);
        accList.add(testAccount2);
        insert accList;
        Contact con = new Contact(LastName = 'Test', Email = 'suseela+test@gmail.com', Phone = '56784242', Phoenix_Phone_External__c = '75377346');
        insert con;

        IPAMemberAdditionCls.getIPAMemberList(pb.Id);
        IPAMemberAdditionCls.PicklistWrapper pbw = new IPAMemberAdditionCls.PicklistWrapper();
        IPAMemberAdditionCls.PicklistEntryWrapper pbw1 = new IPAMemberAdditionCls.PicklistEntryWrapper();

        list < string > productIds = new list < string > ();
        list < Phoenix_RCA_IPA_LINE__c > rcList = new list < Phoenix_RCA_IPA_LINE__c > ();
        for (Integer i = 0; i < accList.size(); i++) {


            Phoenix_RCA_IPA_LINE__c rcItem = new Phoenix_RCA_IPA_LINE__c(Phoenix_Bid__c = pb.Id, Phoenix_RCA_Change_Date__c = pb.Phoenix_RCA_Change_Date__c, Phoenix_Customer__c = accList[i].Id, Phoenix_Contact__c = con.Id, Phoenix_Current_GPO__c = accList[i].GPO1__c, Phoenix_Current_Wholesaler__c = accList[i].Wholesaler1__c, Phoenix_RAM__c = accList[i].OwnerId);
            rcList.add(rcItem);



        }
        IPAMemberAdditionCls.saveIPAMembers(rcList, pb);
        IPAMemberAdditionCls.processIPAMember(pb.Id);
        IPAMemberAdditionCls.getIPAmemberInfo(accList[0].Id, con.Id);
        IPAMemberAdditionCls.getDependentPicklist();


    }





}