PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_External_Description__c</fullName>
        <inlineHelpText>Contract  External Description is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract External Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Volume Review</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Customer_Closing_Date__c</fullName>
        <label>Customer Bid Deadline Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Internal_Closing_Date__c</fullName>
        <label>Internal Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Opportunity_Number__c</fullName>
        <displayFormat>Opp - {0000}</displayFormat>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
                <value>
                    <fullName>Dropped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Deadline_Date__c</fullName>
        <label>Customer Bid Deadline Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Name__c</fullName>
        <label>Bid Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Submitted_Date__c</fullName>
        <label>Bid Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Initial Order Discount for WAC Customers (No-Contract Price Offering)</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                    <label>One Time Buy – Good Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>One Time Buy Good Dated Shelf Life for New Product Launch</fullName>
                    <label>One Time Buy – Good Dated Shelf Life for New Product Launch</label>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                    <label>One Time Buy – Short Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>OTC New Product</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Good Dated</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Short Dated</fullName>
                </value>
                <value>
                    <fullName>OTC Price Change</fullName>
                </value>
                <value>
                    <fullName>OTC Product Addition</fullName>
                </value>
                <value>
                    <fullName>OTC Rebate Change</fullName>
                </value>
                <value>
                    <fullName>OTC RFP</fullName>
                </value>
                <value>
                    <fullName>OTC Volume Review</fullName>
                </value>
                <value>
                    <fullName>Platform OTB</fullName>
                    <label>Pharmabid</label>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                    <label>Product Removals</label>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>Sales Out Rebate</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                    <label>SRx Direct Pricing</label>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                    <label>SRx IPA Floor Pricing Update</label>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                    <label>SRx IPA Member Addition</label>
                </value>
                <value>
                    <fullName>SRx IPA Price Change</fullName>
                </value>
                <value>
                    <fullName>SRx IPA Product Addition</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                    <label>SRx NEW Individual Pricing Agreement (IPA)</label>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                    <label>SRx RCA/IPA Member GPO or Wholesaler Change</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Internal_Target_Date__c</fullName>
        <label>Internal Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Proactive_Reactive__c</fullName>
        <label>Proactive/Reactive</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Proactive</fullName>
                </value>
                <value>
                    <fullName>Reactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_External_Description__c</fullName>
        <label>Contract External Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Internal_Description__c</fullName>
        <label>Contract Internal Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Status__c</fullName>
        <formula>IF(ISBLANK(Phoenix_Contract_End_Date__c),&quot;&quot;,IF(Phoenix_Contract_End_Date__c &lt; TODAY(),&quot;Expired&quot;, &quot;Active&quot; ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_Market_Share_Expansion__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Contract_Effective_Date__c</fullName>
        <label>Plan Contract Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_End_Date__c</fullName>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Start_Date__c</fullName>
        <label>Plan Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Task_Comment__c</fullName>
        <label>Task Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Internal_Target_Date__c</fullName>
        <label>Internal Target Date</label>
        <type>Date</type>
    </fields>
    <label>Market Share Expansion</label>
    <nameField>
        <displayFormat>MktShareExp-{0000000}</displayFormat>
        <label>Market Share Expansion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Share Expansions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Vision_AllCustomer_Calendar_Cls.cls
public class Vision_AllCustomer_Calendar_Cls {
    //@AuraEnabled
    /*  public static list<Event> getAllEvents(){
list<Event> eventlist =[Select id, EndDateTime,StartDateTime,Subject from Event where createdById=:Userinfo.getUserId()] ;
return eventlist;
}*/
    @auraEnabled
    public static Account getAccObj(){
        String query = 'SELECT '+Phoenix_Util.getsObjectFieds('Account')+' FROM Account ';
        Account accObj = Database.query(query);
        return accObj;
    }
    
    @AuraEnabled
    public static List<CalendarWrapper> fetchOpportunitiesAndBids(){
        
        try{
            
            
            List<Opportunity> oppList = [Select Id, Name, Vision_Opportunity_Number__c, Vision_Internal_Closing_Date__c, Bid_Type__c,
                                         Description, Type, StageName, 	Vision_Customer_Closing_Date__c, Account.Name
                                         From Opportunity 
                                         ];
            
            
            
            List<Phoenix_Bid__c> bidList = [Select Id, Name, Phoenix_Bid_Name__c,  Phoenix_Internal_Target_Date__c,
                                            Phoenix_Bid_Type__c, Phoenix_Comments__c, Phoenix_Proactive_Reactive__c,
                                            Phoenix_Approval_Status__c, Phoenix_Bid_Submitted_Date__c, 
                                            Phoenix_Bid_Deadline_Date__c, Phoenix_Customer__r.Name
                                            From  Phoenix_Bid__c
                                            ];
             List<Phoenix_Contract__c> contractList = [Select Id, Name, Phoenix_Contract_External_Description__c,
                                                      Phoenix_Contract_Internal_Description__c,Phoenix_Contract_Start_Date__c,
                                                      Phoenix_Contract_Status__c,Phoenix_Contract_End_Date__c
                                                     from Phoenix_Contract__c];
            List<Vision_Market_Share_Expansion__c> panoramaList = [Select Id, Name, GCP_Product_Family__c,Vision_Internal_Target_Date__c, Plan_End_Date__c,
                                                                   Plan_Start_Date__c,Plan_Contract_Effective_Date__c,Task_Comment__c,
                                                                   Task_Type__c, 	Task_Status__c, Task_Variant__c,Vision_Product_Family__c
                                                                   From  Vision_Market_Share_Expansion__c
                                                                   ];
            Map<String, Vision_Market_Share_Expansion__c> mapPanoramaList = new Map<String,Vision_Market_Share_Expansion__c>();
            for(Vision_Market_Share_Expansion__c panorama : panoramaList ){
                
                if(!mapPanoramaList.containsKey(panorama.Vision_Product_Family__c)){mapPanoramaList.put(panorama.Vision_Product_Family__c, panorama);
                    
                }
                
            } 
            
          
            List<Task> taskList = [Select Id, Subject, ActivityDate,Status
                                   From Task 
                                  ];
            
            List<Event> eventList = [Select Id, Subject, StartDateTime, EndDateTime
                                     From Event 
                                     ];
            List<Vision_Alert__c> alertsList = [Select Id, Name, 	Vision_Notification_Due_Date__c
                                                From Vision_Alert__c 
                                                ];
            
          
            List<CalendarWrapper> calendarWrapperList = new List<CalendarWrapper>();
             if(contractList.size() > 0){
                for(Phoenix_Contract__c con : contractList){
                    system.debug('con-----'+con);
                    
                    CalendarWrapper cw = new CalendarWrapper();  cw.id = con.Id; cw.name = con.Phoenix_Contract_External_Description__c; cw.startDate = con.Phoenix_Contract_Start_Date__c;  cw.endDate = con.Phoenix_Contract_End_Date__c; cw.status = con.Phoenix_Contract_Status__c;  cw.type = 'Contract';
                    calendarWrapperList.add(cw);
                    
                }
                 for(Phoenix_Contract__c con : contractList){
                    system.debug('con-----'+con);
                    
                    CalendarWrapper cw = new CalendarWrapper();
                    cw.id = con.Id;
                    cw.name = con.Phoenix_Contract_External_Description__c;
                    cw.startDate = con.Phoenix_Contract_Start_Date__c;
                    cw.endDate = con.Phoenix_Contract_End_Date__c;//bid.Phoenix_Internal_Target_Date__c;
                    cw.status = con.Phoenix_Contract_Status__c; 
                    cw.type = 'Contract Start Date';
                    calendarWrapperList.add(cw);
                    
                }
            }
            if(taskList.size() > 0){
                for(Task task : taskList){
                    if(task.ActivityDate != null){
                        CalendarWrapper cw = new CalendarWrapper();
                        cw.id = task.Id;
                        cw.name = task.Subject;
                        cw.status = task.Status;
                        cw.startDate = task.ActivityDate;
                        cw.type = 'Task';
                        calendarWrapperList.add(cw);
                    }
                }
            }
            
            if(eventList.size() > 0){
                for(Event event : eventList){
                    if(event.StartDateTime != null){
                        CalendarWrapper cw = new CalendarWrapper();
                        cw.id = event.Id;
                        cw.name = event.Subject;
                        cw.startDateTime= event.StartDateTime;
                        cw.endDateTime= event.EndDateTime;
                        cw.startDate = Date.newinstance(event.StartDateTime.year(), event.StartDateTime.month(), event.StartDateTime.day());
                        cw.endDate = event.EndDateTime != null ? Date.newinstance(event.EndDateTime.year(), event.EndDateTime.month(), event.EndDateTime.day()) : null;
                        cw.type = 'Event';
                        calendarWrapperList.add(cw);
                    }
                }
            }
            if(alertsList.size() > 0){
                for(Vision_Alert__c alert : alertsList){
                    //if(event.StartDateTime != null){
                    CalendarWrapper cw = new CalendarWrapper();
                    cw.id = alert.Id;
                    cw.name = alert.Name;
                    cw.startDate = alert.Vision_Notification_Due_Date__c;
                    //Date.newinstance(event.StartDateTime.year(), event.StartDateTime.month(), event.StartDateTime.day());
                    cw.endDate = alert.Vision_Notification_Due_Date__c;
                    //event.EndDateTime != null ? Date.newinstance(event.EndDateTime.year(), event.EndDateTime.month(), event.EndDateTime.day()) : null;
                    cw.type = 'Alert';
                    calendarWrapperList.add(cw);
                    //}
                }
            }
            if(oppList.size() > 0){
                for(Opportunity opp : oppList){
                    if(opp.Vision_Internal_Closing_Date__c != null){
                        CalendarWrapper cw = new CalendarWrapper();
                        cw.id = opp.Id;
                        cw.name = opp.Name;
                        cw.bidOppNumber = opp.Vision_Opportunity_Number__c;
                        cw.internalClosingDate = opp.Vision_Internal_Closing_Date__c;
                        cw.startDate = opp.Vision_Internal_Closing_Date__c;
                        cw.customerClosingDate =  opp.Vision_Customer_Closing_Date__c;
                        cw.endDate = opp.Vision_Customer_Closing_Date__c;//opp.Vision_Internal_Closing_Date__c;
                        cw.status = opp.StageName;
                        cw.type = 'Opportunity';
                        calendarWrapperList.add(cw);
                    }
                }
            }
            
            
            
            if(bidList.size() > 0){
                for(Phoenix_Bid__c bid : bidList){
                    if(bid.Phoenix_Internal_Target_Date__c != null){
                        CalendarWrapper cw = new CalendarWrapper();
                        cw.id = bid.Id;
                        cw.name = bid.Phoenix_Bid_Name__c;
                        cw.bidOppNumber = bid.Name;
                        cw.internalClosingDate = bid.Phoenix_Internal_Target_Date__c;
                        cw.startDate = bid.Phoenix_Internal_Target_Date__c;
                        cw.endDate = bid.Phoenix_Bid_Deadline_Date__c;//bid.Phoenix_Internal_Target_Date__c;
                        cw.customerClosingDate = bid.Phoenix_Bid_Deadline_Date__c;
                        cw.status = bid.Phoenix_Approval_Status__c;
                        cw.bidType = bid.Phoenix_Bid_Type__c;
                        cw.type = 'Bid';
                        calendarWrapperList.add(cw);
                    }
                }
            }
            
            if(mapPanoramaList.size() > 0){
                for(Vision_Market_Share_Expansion__c panorama : mapPanoramaList.values()){
                    // if(panorama.Plan_Start_Date__c != null){
                    CalendarWrapper cw = new CalendarWrapper();
                    cw.id = panorama.Id; cw.name = panorama.Vision_Product_Family__c;cw.startDate = panorama.Vision_Internal_Target_Date__c; cw.endDate = panorama.Plan_Contract_Effective_Date__c ; cw.internalClosingDate = panorama.Vision_Internal_Target_Date__c; cw.status = panorama.Task_Status__c; cw.type = 'Panorama Task'; calendarWrapperList.add(cw);
                    // }
                }
            }
           return calendarWrapperList;
            
        }
        catch(Exception ex){
            return null;
        }
    }
    
  /*  @AuraEnabled
    public static List<Contact> getContactScores(String accountId){
        try{
            List<Contact> contactList = [Select Id, Name, Influence_Score__c, Affinity_Score__c From Contact Where AccountId = : accountId];
            return contactList;
        }
        catch(Exception ex){
            return null;
        }
    }
    */
    public class CalendarWrapper{
        @AuraEnabled
        public ID id{ get; set; }
        
        @AuraEnabled
        public String name{ get; set; }
        
        @AuraEnabled
        public String bidOppNumber{ get; set; }
        
        @AuraEnabled
        public String bidType{ get; set; }
        
        @AuraEnabled
        public Date internalClosingDate{ get; set; }
        
        @AuraEnabled
        public Date customerClosingDate{ get; set; }
        
        @AuraEnabled
        public Date startDate{ get; set; }
          @AuraEnabled
        public DateTime startDateTime{ get; set; }
        @AuraEnabled
        public DateTime endDateTime{ get; set; }
        @AuraEnabled
        public Date endDate{ get; set; }
        
        @AuraEnabled
        public String status{ get; set; }
        
        @AuraEnabled
        public String type{ get; set; }
    }
    
    
    @AuraEnabled
    public static void updateEvent(string eventid,string eventdate){
        system.debug(eventid);
        system.debug(eventdate);
        string eventdatelist = eventdate.replace('T',' ');
        
        system.debug(eventdatelist);
        Event e= new event(id = eventid);
        e.StartDateTime = DateTime.valueof(eventdatelist);
        update e;
        
    }
  }