PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Direct_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Direct Customer- For Price Calc</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Internal_Description__c</fullName>
        <label>Contract Internal Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Direct_Customer__c</fullName>
        <formula>Phoenix_Customer__r.Phoenix_Is_Direct_Customer__c</formula>
        <label>Is Direct Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Exclusion_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field is used for calculating Lowest Price / SKU</inlineHelpText>
        <label>Is Exclusion Contract</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_12Months_Sales_Unit__c</fullName>
        <label>12Months Sales Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Add_ABS_Value__c</fullName>
        <label>Add ABS Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Internal_Description__c</fullName>
        <label>Contract Internal Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Phoenix_Dead_Net_Tracking_GR__c</fullName>
        <label>Dead Net(Tracking GR)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Phoenix_ProdEvaluationPriceProcessorTest.cls
/**
 * @description       : 
 * @author            : Surender Patel (Dhruvsoft)
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
@isTest
public class Phoenix_ProdEvaluationPriceProcessorTest {
    @isTest
    public static void ProdEvaluationPriceProcessor() {
        Account acc = new Account();
        acc.Name = 'Test';
        acc.AccountNumber = '1234';
        acc.Phoenix_Is_Direct_Customer__c = false;
        insert acc;

        Phoenix_Contract__c cont = new Phoenix_Contract__c();
        cont.Name = '1234 - Test';
        cont.Phoenix_Contract_End_Date__c = System.today() + 1;
        cont.Phoenix_Contract_Number__c = '1234';
        cont.Phoenix_Is_Exclusion_Contract__c = false;
        cont.Phoenix_Contract_Internal_Description__c = 'Test';
        cont.Phoenix_Customer__c = acc.Id;
        insert cont;

        List < Product2 > proList = new List < Product2 > ();
        Product2 pro1 = new Product2();
        pro1.Name = 'Test';
        pro1.IsActive = true;
        proList.add(pro1);
        Product2 pro2 = new Product2();
        pro2.Name = 'Test';
        pro2.IsActive = true;
        proList.add(pro2);
        insert proList;

        Phoenix_NPR_Data__c npr1 = new Phoenix_NPR_Data__c();
        npr1.Phoenix_Account__c = acc.Id;
        npr1.Phoenix_Contract__c = cont.Id;
        npr1.Phoenix_Contract_Type__c = 'Direct';
        npr1.Phoenix_Product__c = proList[1].Id;
        npr1.Phoenix_12Months_Sales_Unit__c = 3.00;
        npr1.Phoenix_Dead_Net_Tracking_GR__c = 2.00;
         insert npr1;
          Phoenix_NPR_Data__c npr2 = new Phoenix_NPR_Data__c();
        npr2.Phoenix_Account__c = acc.Id;
        npr2.Phoenix_Contract__c = cont.Id;
        npr2.Phoenix_Contract_Type__c = 'Direct';
        npr2.Phoenix_Product__c = proList[1].Id;
        npr2.Phoenix_12Months_Sales_Unit__c = 5.00;
        npr2.Phoenix_Dead_Net_Tracking_GR__c = 1.00;
        insert npr2;

        /*  Phoenix_Contract__c cont= new Phoenix_Contract__c();
cont.Name='Test';
cont.Phoenix_Contract_End_Date__c =System.today()+1;
cont.Phoenix_Contract_Number__c='1234';
cont.Phoenix_Is_Exclusion_Contract__c=false;
cont.Phoenix_Customer__c=acc.Id;
insert cont;

List<Phoenix_NPR_Data__c> nprList= new List<Phoenix_NPR_Data__c>();

Phoenix_NPR_Data__c npr1= new Phoenix_NPR_Data__c();
npr1.Phoenix_Account__c=acc.Id;
npr1.Phoenix_Contract__c=cont.Id;
npr1.Phoenix_Contract_Type__c='Indirect';
npr1.Phoenix_Product__c=proList[1].Id;
npr1.Phoenix_12Months_Sales_Unit__c=3.00;
npr1.Phoenix_Add_ABS_Value__c=2.00;
npr1.Phoenix_Dead_Net_Tracking_GR__c=2.00;
//  insert npr1;
//  nprList.add(npr1);

Phoenix_NPR_Data__c npr2= new Phoenix_NPR_Data__c();
npr2.Phoenix_Account__c=acc.Id;
npr2.Phoenix_Contract_Type__c='Indirect';
npr2.Phoenix_Contract__c=cont.Id;
npr2.Phoenix_Product__c=proList[1].Id;
npr2.Phoenix_12Months_Sales_Unit__c=2.00;
npr2.Phoenix_Add_ABS_Value__c=2.00;
npr2.Phoenix_Dead_Net_Tracking_GR__c=1.00;
nprList.add(npr2);
Phoenix_NPR_Data__c npr3= new Phoenix_NPR_Data__c();
npr3.Phoenix_Account__c=acc.Id;
npr3.Phoenix_Contract_Type__c='Direct';
npr3.Phoenix_Contract__c=cont.Id;
// npr3.Phoenix_Product__c=proList[1].Id;
npr3.Phoenix_Add_ABS_Value__c=1.00;
npr3.Phoenix_12Months_Sales_Unit__c=1.00;
npr3.Phoenix_Dead_Net_Tracking_GR__c=1.00;
nprList.add(npr3);
if(!nprList.isEmpty()){
// insert nprList;

}*/

        Phoenix_ProductEvaluationPriceProcessor ProdEvaluationPriceProcessor = new Phoenix_ProductEvaluationPriceProcessor();
      //  DataBase.executeBatch(ProdEvaluationPriceProcessor);
        ProdEvaluationPriceProcessor.execute(null);
        System.assertEquals(1, 1);
    }
}