PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_DRL_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DRL Sales</relationshipLabel>
        <relationshipName>DRL_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Month__c</fullName>
        <label>Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Month_dtls__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>DRL Sales</relationshipLabel>
        <relationshipName>DRL_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Sales_Dollar__c</fullName>
        <label>Sales Dollar</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RX</fullName>
                </value>
                <value>
                    <fullName>SRX</fullName>
                </value>
                <value>
                    <fullName>OTC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_TPT_Dollar__c</fullName>
        <label>TPT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_TPT_Pct__c</fullName>
        <label>TPT %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DRL Sales</label>
    <nameField>
        <displayFormat>DRLSales-{0000000}</displayFormat>
        <label>DRL Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_DRL_Sales_External__c.object
<CustomObject>
    <fields>
        <fullName>Quantity_in_Units__c</fullName>
        <label>Quantity in Units</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>DRL_Sales_External</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Month__c</fullName>
        <label>Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Month_dtls__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>DRL_Sales_External</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Sales_Dollar__c</fullName>
        <label>Sales Dollar</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>SRx</fullName>
                </value>
                <value>
                    <fullName>OTC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_TPT_Dollar__c</fullName>
        <label>TPT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_TPT_Pct__c</fullName>
        <label>TPT %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DRL Sales External</label>
    <nameField>
        <displayFormat>DRLSalesExt-{0000000}</displayFormat>
        <label>DRL Sales External Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Sales External</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_DRL_Sales_External_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DRL Sales External Summary</relationshipLabel>
        <relationshipName>DRL_Sales_External_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Processed_Date__c</fullName>
        <formula>IF(AND(ISNULL(Vision_month__c) ,ISNULL(Vision_year__c)),null,DATE( VALUE(Vision_year__c) ,IF(LEN(Vision_month__c)== 2,VALUE(Vision_month__c),VALUE(&apos;0&apos;+Vision_month__c)) ,01))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>DRL Sales External Summary</relationshipLabel>
        <relationshipName>DRL_Sales_External_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Sales__c</fullName>
        <label>Sales Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>QTY Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_month__c</fullName>
        <label>Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRL Sales External Summary</label>
    <nameField>
        <displayFormat>drl-ext-summ-{0000000}</displayFormat>
        <label>DRL Sales External Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Sales External Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_InternalDRLSales_ProductSummary__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vision Internal Sales Product Summarys</relationshipLabel>
        <relationshipName>Vision_Internal_Sales_Product_Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Is_OTC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is OTC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Is_Rx__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Rx</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Is_SRx__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is SRx</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Processed_Date__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <formula>IF( Vision_Is_Rx__c , &apos;Rx&apos;, IF( Vision_Is_SRx__c , &apos;SRx&apos;, IF( Vision_Is_OTC__c , &apos;OTC&apos;, &apos;&apos;)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_TPT_Dollar__c</fullName>
        <label>TPT Dollar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_TPT_Percent__c</fullName>
        <label>TPT Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vision Internal Sales Product Summary</label>
    <nameField>
        <displayFormat>DRL Sales Summary-{0000}</displayFormat>
        <label>VisionInternal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vision Internal Sales Product Summarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/VisionExtDRLSalesProductLevelBtchTestCls.cls
@isTest
public class VisionExtDRLSalesProductLevelBtchTestCls {
	
    static testmethod void testMe(){
       
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Account acc1 = new Account();
        acc1.Name = 'Test Account';
        insert acc1;
         Product2 pro=new Product2(Name='Test',Family='Allopurinol');
        insert pro;
        Vision_DRL_Sales_External_Summary__c sales = new Vision_DRL_Sales_External_Summary__c();
        sales.Vision_Customer__c = acc1.Id;
       sales.Vision_Sales__c =123.45;
        sales.Vision_Units__c = 600;
        sales.Vision_Product__c=pro.id;
        //sales.Vision_TPT_Pct__c=1;
       sales.Vision_year__c='2021';
        sales.Vision_month__c='4';
       // sales.Vision_TPT_Dollar__c = 334;
       //sales.Vision_Month_dtls__c = system.today()-475;
        sales.Vision_Product_Family__c='Diclofenac Gel';
        sales.Vision_Segment__c = 'OTC';
        insert sales;
        Vision_DRL_Sales_External_Summary__c sales11 = new Vision_DRL_Sales_External_Summary__c();
        sales11.Vision_Customer__c = acc1.Id;
      // sales11.Vision_Sales_Dollar__c =123.45;
        sales11.Vision_Units__c = 600;
               // sales11.Vision_TPT_Pct__c=1;

        sales11.Vision_Product__c=pro.id;
        sales11.Vision_year__c='2021';
        sales11.Vision_month__c='1';
       // sales.Vision_TPT_Dollar__c = 334;
       // sales.Vision_Month_dtls__c = system.today()-475;
        sales11.Vision_Product_Family__c='Diclofenac Gel';
        sales11.Vision_Segment__c = 'Rx';
        insert sales11;
        
         Vision_DRL_Sales_External_Summary__c sales1 = new Vision_DRL_Sales_External_Summary__c();
        sales1.Vision_Customer__c = acc.Id;
        sales1.Vision_Product__c=pro.id;
              //  sales1.Vision_TPT_Pct__c=1;

       sales1.Vision_year__c='2021';
        sales1.Vision_month__c='1';
        //Vision_Sales_Dollar__c
       //sales1.Vision_Sales_Dollar__c =123.45;
        sales1.Vision_Units__c = 500;
        //sales1.Vision_TPT_Dollar__c = 234;
        //sales1.Vision_Month_dtls__c = system.today()-465;
        sales1.Vision_Product_Family__c='Diclofenac Gel';
        sales1.Vision_Segment__c = 'SRx';
        insert sales1;
        
        Vision_DRL_Sales_External_Summary__c sales2 = new Vision_DRL_Sales_External_Summary__c();
        sales2.Vision_Customer__c = acc.Id;
               // sales2.Vision_TPT_Pct__c=1;

        sales2.Vision_Product__c=pro.id;
        sales2.Vision_year__c='2021';
        sales2.Vision_month__c='1';
      // sales2.Vision_Sales_Dollar__c =123.45;
        sales2.Vision_Units__c = 500;
       // sales2.Vision_TPT_Dollar__c = 234;
      //  sales2.Vision_Month_dtls__c = system.today()-465;
        sales2.Vision_Product_Family__c='Diclofenac Gel';
        sales2.Vision_Segment__c = 'OTC';
        insert sales2;
        
         
        Vision_DRL_Sales_External_Summary__c sales3 = new Vision_DRL_Sales_External_Summary__c();
        sales3.Vision_Customer__c = acc.Id;
        sales3.Vision_Product__c=pro.id;
              //  sales3.Vision_TPT_Pct__c=1;

        sales3.Vision_year__c='2021';
        sales3.Vision_month__c='1';
       //sales3.Vision_Sales_Dollar__c =123.45;
        sales3.Vision_Units__c = 500;
       // sales3.Vision_TPT_Dollar__c = 234;
       // sales3.Vision_Month_dtls__c = system.today()-475;
        sales3.Vision_Product_Family__c='Diclofenac Gel';
        sales3.Vision_Segment__c = 'SRx';
        insert sales3;
        
     /*    Vision_DRL_Sales__c sales4 = new Vision_DRL_Sales__c();
        sales4.Vision_Customer__c = acc.Id;
        sales4.Vision_Product__c=pro.id;
        //sales4.Vision_year__c='2021';
        //sales4.Vision_month__c='1';
        sales4.Vision_Sales__c =1000;
        sales4.Vision_Units__c = 500;
        //sales4.Vision_TPT_Dollar__c = 234;
        //sales4.Vision_Month_dtls__c = system.today()-475;
        sales4.Vision_Product_Family__c='Diclofenac Gel';
        sales4.Vision_Segment__c = 'OTC';
        insert sales4;*/
       
        
        /*Vision_InternalDRLSales_ProductSummary__c intsales1= new Vision_InternalDRLSales_ProductSummary__c();
        intsales1.Vision_Customer__c = acc.Id;
        intsales1.Vision_Sales__c =173.45;
        intsales1.Vision_Units__c = 500;
        intsales1.Vision_Is_Rx__c  = true;
                intsales1.Vision_TPT_Percent__c=1;

        intsales1.Vision_TPT_Dollar__c = 234;
        intsales1.Vision_Processed_Date__c = system.today()-475;
        intsales1.Vision_Product_Family__c='Diclofenac Gel';
        intsales1.Vision_Unique_Identifier__c = 'Test Account-Diclofenac Gel-Rx_2021_2';
        insert intsales1;
              Vision_InternalDRLSales_ProductSummary__c intsales2= new Vision_InternalDRLSales_ProductSummary__c();
        intsales2.Vision_Customer__c = acc1.Id;
        intsales2.Vision_Sales__c =165.45;
        intsales2.Vision_Units__c = 500;
        intsales2.Vision_Is_OTC__c  = true;
               intsales2.Vision_TPT_Percent__c=1;

        intsales2.Vision_TPT_Dollar__c = 234;
        intsales2.Vision_Processed_Date__c = system.today()-200;
        intsales2.Vision_Product_Family__c='Diclofenac Gel';
        intsales2.Vision_Unique_Identifier__c = 'Test Account-Diclofenac Gel-OTC_2021_2';

        insert intsales2;
		
        Vision_InternalDRLSales_ProductSummary__c intsales3= new Vision_InternalDRLSales_ProductSummary__c();
        intsales3.Vision_Customer__c = acc1.Id;
        intsales3.Vision_Sales__c =500.45;
        intsales3.Vision_Units__c = 500;
        intsales3.Vision_Is_SRx__c  = true;
        intsales3.Vision_TPT_Percent__c=1;
        intsales3.Vision_TPT_Dollar__c = 234;
        intsales3.Vision_Processed_Date__c = system.today()-365;
        intsales3.Vision_Product_Family__c='Diclofenac Gel';
        intsales3.Vision_Unique_Identifier__c = 'Test Account-Diclofenac Gel-SRx_2021_2';

        insert intsales3;*/
        Vision_InternalDRLSales_ProductSummary__c intsales1= new Vision_InternalDRLSales_ProductSummary__c();
        intsales1.Vision_Customer__c = acc.Id;
        intsales1.Vision_Sales__c =123.45;
        intsales1.Vision_Units__c = 500;
        intsales1.Vision_Is_Rx__c  = true;
        intsales1.Vision_TPT_Dollar__c = 234;
        intsales1.Vision_Processed_Date__c = system.today()-200;
        intsales1.Vision_Product_Family__c='Diclofenac Gel';
        intsales1.Vision_Unique_Identifier__c = 'Test Account-Diclofenac Gel-Rx_2021_2';
        
           Vision_InternalDRLSales_ProductSummary__c intsales2= new Vision_InternalDRLSales_ProductSummary__c();
        intsales2.Vision_Customer__c = acc1.Id;
        intsales2.Vision_Sales__c =123.45;
        intsales2.Vision_Units__c = 500;
        intsales2.Vision_Is_SRx__c  = true;
        intsales2.Vision_TPT_Dollar__c = 234;
        intsales2.Vision_Processed_Date__c = system.today()-200;
        intsales2.Vision_Product_Family__c='Diclofenac Gel';
        intsales2.Vision_Unique_Identifier__c = 'Test Account-Diclofenac Gel-SRx_2021_2';

        insert intsales2;
        Vision_InternalDRLSales_ProductSummary__c intsales3= new Vision_InternalDRLSales_ProductSummary__c();
        intsales3.Vision_Customer__c = acc1.Id;
        intsales3.Vision_Sales__c =123.45;
        intsales3.Vision_Units__c = 500;
        intsales3.Vision_Is_SRx__c  = true;
        intsales3.Vision_TPT_Dollar__c = 234;
        intsales3.Vision_Processed_Date__c = system.today()-200;
        intsales3.Vision_Product_Family__c='Diclofenac Gel';
        intsales3.Vision_Unique_Identifier__c = 'Test Account-Diclofenac Gel-OTC_2021_2';

        insert intsales3;
        
     /*   Vision_DRL_Sales_External__c externalSales1 = new Vision_DRL_Sales_External__c();
        externalSales1.Vision_Customer_Name__c =  acc.Id;
        externalSales1.Vision_Segment__c = 'Rx';
        externalSales1.Vision_Month_dtls__c = system.today()-475;
        externalSales1.Vision_Sales_Dollar__c = 173.45;
        externalSales1.Quantity_in_Units__c = 500;
        externalSales1.Vision_Product_Family__c = 'Diclofenac Gel';
        insert externalSales1;
        
        Vision_DRL_Sales_External__c externalSales2 = new Vision_DRL_Sales_External__c();
        externalSales2.Vision_Customer_Name__c =  acc1.Id;
        externalSales2.Vision_Segment__c = 'SRx';
        externalSales2.Vision_Month_dtls__c = system.today()-365;
        externalSales2.Vision_Sales_Dollar__c =500.45;
        externalSales2.Quantity_in_Units__c = 500;
        externalSales2.Vision_Product_Family__c = 'Diclofenac Gel';
        insert externalSales2;
        
        Vision_DRL_Sales_External__c externalSales3 = new Vision_DRL_Sales_External__c();
        externalSales3.Vision_Customer_Name__c =  acc1.Id;
        externalSales3.Vision_Segment__c = 'OTC';
        externalSales3.Vision_Month_dtls__c = system.today()-200;
        externalSales3.Vision_Sales_Dollar__c =165.45;
        externalSales3.Quantity_in_Units__c = 500;
        externalSales3.Vision_Product_Family__c = 'Diclofenac Gel';
        insert externalSales3;
        
        List < Vision_DRL_Sales_External__c > externalSalesList = new List < Vision_DRL_Sales_External__c >();
        externalSalesList.add(externalSales1);
        externalSalesList.add(externalSales2);
        externalSalesList.add(externalSales3);*/
        
        
        
       
        
        Test.startTest();
        VisionExtDRLSalesProductLevelBatchCls batch = new VisionExtDRLSalesProductLevelBatchCls();
       	Id jobid= Database.executeBatch(batch,5);
        //batch.execute(null);
        Test.stopTest();     
    }
    
   /* static testmethod void testMethod1(){
        Test.startTest();
        //Database.executeBatch(new VisionDRLSalesSummaryBatchCls()); 
        Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'VisionDRLSalesSummaryBatchCls', Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
        insert exp;
        Test.stopTest(); 
       
        
    }*/
    
    
}