PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_DRL_Sales__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Unique_Identifier__c</fullName>
        <externalId>true</externalId>
        <label>GCP Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DRL Sales</relationshipLabel>
        <relationshipName>DRL_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Month_dtls__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sales_Dollar__c</fullName>
        <label>Sales Dollar</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RX</fullName>
                </value>
                <value>
                    <fullName>SRX</fullName>
                </value>
                <value>
                    <fullName>OTC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DRL Sales</label>
    <nameField>
        <displayFormat>DRLSales-{0000000}</displayFormat>
        <label>DRL Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_Intrenal_DRL_Sales_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Intrenal DRL Sales Summarys</relationshipLabel>
        <relationshipName>Intrenal_DRL_Sales_Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Processed_Date__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <formula>IF( Vision_Is_Rx__c , &apos;Rx&apos;,  IF( Vision_Is_SRx__c , &apos;SRx&apos;, IF( Vision_Is_OTC__c , &apos;OTC&apos;, &apos;&apos;)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Internal DRL Sales Summary</label>
    <nameField>
        <displayFormat>DRL Sales Summary-{0000}</displayFormat>
        <label>Intrenal DRL Sales Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intrenal DRL Sales Summarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/VisionInternalDRLSalesSummaryBatchTest.cls
@isTest
public class VisionInternalDRLSalesSummaryBatchTest {	
    
    /*static testmethod void testMe(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Account acc1 = new Account();
        acc1.Name = 'Test Account';
        insert acc1;
        Product2 pro=new Product2(Name='Test',Family='Allopurinol');
        insert pro;
        Product2 pro1=new Product2(Name='Test1',Family='Allopurinol');
        insert pro1;
        
        Vision_Intrenal_DRL_Sales_Summary__c sales = new Vision_Intrenal_DRL_Sales_Summary__c();
        sales.Vision_Customer__c = acc1.Id;
        sales.Vision_Sales__c =223.45;
        sales.Vision_Units__c = 600;
        sales.Vision_Product_Family__c='Diclofenac Gel';
        sales.Vision_Unique_Identifier__c = 'ab';
        sales.Vision_Processed_Date__c = system.today()-475;
        insert sales;
        Vision_Intrenal_DRL_Sales_Summary__c sales11 = new Vision_Intrenal_DRL_Sales_Summary__c();
        sales11.Vision_Customer__c = acc1.Id;
        sales11.Vision_Sales__c =223.45;
        sales11.Vision_Units__c = 600;
        sales11.Vision_Product_Family__c='Diclofenac Gel';
        sales11.Vision_Unique_Identifier__c = 'ab';
        sales11.Vision_Processed_Date__c = system.today()-470;
        insert sales11;
        
        Vision_Intrenal_DRL_Sales_Summary__c sales1 = new Vision_Intrenal_DRL_Sales_Summary__c();
        sales1.Vision_Customer__c = acc.Id;
        sales1.Vision_Sales__c =123.45;
        sales1.Vision_Units__c = 500;
        sales1.Vision_Product_Family__c='Diclofenac Gel';
        sales1.Vision_Unique_Identifier__c = 'ab';
        sales1.Vision_Processed_Date__c = system.today()-470;
        insert sales1;
        
        Vision_Intrenal_DRL_Sales_Summary__c sales2 = new Vision_Intrenal_DRL_Sales_Summary__c();
        sales2.Vision_Customer__c = acc.Id;
        sales2.Vision_Sales__c =123.45;
        sales2.Vision_Units__c = 500;
        sales2.Vision_Product_Family__c='Diclofenac Gel';
        sales2.Vision_Unique_Identifier__c = 'ab';
        sales2.Vision_Processed_Date__c = system.today()-470;
        insert sales2;
        
         
        Vision_Intrenal_DRL_Sales_Summary__c sales3 = new Vision_Intrenal_DRL_Sales_Summary__c();
        sales3.Vision_Customer__c = acc.Id;
        sales3.Vision_Sales__c =123.45;
        sales3.Vision_Units__c = 500;
        sales3.Vision_Product_Family__c='Diclofenac Gel';
        sales3.Vision_Unique_Identifier__c = 'ab';
        sales3.Vision_Processed_Date__c = system.today()-475;
        insert sales3;
        
        Vision_DRL_Sales__c intsales1= new Vision_DRL_Sales__c();
        intsales1.Vision_Customer_Name__c = acc.Id;
        intsales1.Vision_Sales_Dollar__c =173.45;
        intsales1.Vision_Units__c = 500;
        intsales1.Vision_Segment__c  = 'Rx';
        intsales1.Vision_Month_dtls__c = system.today()-475;
        intsales1.Vision_Product_Family__c='Diclofenac Gel';
        intsales1.GCP_Unique_Identifier__c = 'ab';
        insert intsales1;
        
        Vision_DRL_Sales__c intsales2= new Vision_DRL_Sales__c();
        intsales2.Vision_Customer_Name__c = acc.Id;
        intsales2.Vision_Sales_Dollar__c =173.45;
        intsales2.Vision_Units__c = 500;
        intsales2.Vision_Segment__c  = 'Rx';
        intsales2.Vision_Month_dtls__c = system.today()-475;
        intsales2.Vision_Product_Family__c='Diclofenac Gel';
        intsales2.GCP_Unique_Identifier__c = 'ab';
        insert intsales2;
        
        Vision_DRL_Sales__c intsales3= new Vision_DRL_Sales__c();
        intsales3.Vision_Customer_Name__c = acc1.Id;
        intsales3.Vision_Sales_Dollar__c =173.45;
        intsales3.Vision_Units__c = 500;
        intsales3.Vision_Segment__c  = 'Rx';
        intsales3.Vision_Month_dtls__c = system.today()-400;
        intsales3.Vision_Product_Family__c='Diclofenac Gel';
        intsales3.GCP_Unique_Identifier__c = 'ab';
        insert intsales3;
        
        Test.startTest();
        //Database.executeBatch(new VisionInternalDRLSalesSummaryBatchCls(), 5); //uncomment this before running/deploying
        Test.stopTest();   
    }
    
    static testmethod void test2(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Account acc1 = new Account();
        acc1.Name = 'Test Account';
        insert acc1;
        Product2 pro=new Product2(Name='Test',Family='Allopurinol');
        insert pro;
        Product2 pro1=new Product2(Name='Test1',Family='Allopurinol');
        insert pro1;
        
        Vision_DRL_Sales__c intsales2= new Vision_DRL_Sales__c();
        intsales2.Vision_Customer_Name__c = acc1.Id;
        intsales2.Vision_Sales_Dollar__c =165.45;
        intsales2.Vision_Units__c = 500;
        intsales2.Vision_Segment__c  = 'SRx';
        intsales2.Vision_Month_dtls__c = system.today()-475;
        intsales2.Vision_Product_Family__c='Diclofenac Gel';
        intsales2.GCP_Unique_Identifier__c = 'Test Account-OTC_2021_1';
        
        insert intsales2;
        
        Vision_DRL_Sales__c intsales3= new Vision_DRL_Sales__c();
        intsales3.Vision_Customer_Name__c = acc1.Id;
        intsales3.Vision_Sales_Dollar__c =165.45;
        intsales3.Vision_Units__c = 500;
        intsales3.Vision_Segment__c  = 'SRx';
        intsales3.Vision_Month_dtls__c = system.today()-400;
        intsales3.Vision_Product_Family__c='Diclofenac Gel';
        intsales3.GCP_Unique_Identifier__c = 'Test Account-OTC_2021_1';
        
        insert intsales3;
        
        Test.startTest();
        //Database.executeBatch(new VisionInternalDRLSalesSummaryBatchCls(), 5); //uncomment this before running/deploying
        Test.stopTest();   
    }
    
    static testmethod void test3(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Account acc1 = new Account();
        acc1.Name = 'Test Account';
        insert acc1;
        Product2 pro=new Product2(Name='Test',Family='Allopurinol');
        insert pro;
        Product2 pro1=new Product2(Name='Test1',Family='Allopurinol');
        insert pro1;
        
        Vision_DRL_Sales__c intsales3= new Vision_DRL_Sales__c();
        intsales3.Vision_Customer_Name__c = acc1.Id;
        intsales3.Vision_Sales_Dollar__c =500.45;
        intsales3.Vision_Units__c = 500;
        intsales3.Vision_Segment__c  = 'OTC';
        intsales3.Vision_Month_dtls__c = system.today()-365;
        intsales3.Vision_Product_Family__c='Diclofenac Gel';
        intsales3.GCP_Unique_Identifier__c = 'Test Account-SRx_2021_1';
        
        insert intsales3;
        Vision_DRL_Sales__c intsales4= new Vision_DRL_Sales__c();
        intsales4.Vision_Customer_Name__c = acc1.Id;
        intsales4.Vision_Sales_Dollar__c =500.45;
        intsales4.Vision_Units__c = 500;
        intsales4.Vision_Segment__c  = 'OTC';
        intsales4.Vision_Month_dtls__c = system.today()-300;
        intsales4.Vision_Product_Family__c='Diclofenac Gel';
        intsales4.GCP_Unique_Identifier__c = 'Test Account-SRx_2021_1';
        
        insert intsales4;
        
        Test.startTest();
        //Database.executeBatch(new VisionInternalDRLSalesSummaryBatchCls(), 5); //uncomment this before running/deploying
        Test.stopTest();   
    }
    
    /*static testmethod void test4(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Account acc1 = new Account();
        acc1.Name = 'Test Account';
        insert acc1;
        Product2 pro=new Product2(Name='Test',Family='Allopurinol');
        insert pro;
        Product2 pro1=new Product2(Name='Test1',Family='Allopurinol');
        insert pro1;
        
        Vision_DRL_Sales__c intsales4= new Vision_DRL_Sales__c();
        intsales4.Vision_Customer_Name__c = acc.Id;
        intsales4.Vision_Sales_Dollar__c =500.45;
        intsales4.Vision_Units__c = 500;
        intsales4.Vision_Segment__c  = 'Rx';
        intsales4.Vision_Month_dtls__c = system.today()-365;
        intsales4.Vision_Product_Family__c='Diclofenac Gel';
        intsales4.GCP_Unique_Identifier__c = 'Test Account-SRx_2021_1';
        
        insert intsales4;
        
        Test.startTest();
        Database.executeBatch(new VisionInternalDRLSalesSummaryBatchCls(), 5);
        Test.stopTest();   
    }*/
}