PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/doh_report_dates_info__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Vision_Update_Date__c</fullName>
        <label>Update Date</label>
        <type>TextArea</type>
    </fields>
    <label>DOH Report Dates Info</label>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/DoH_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Package_Description__c</fullName>
        <label>Package Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Partner_Name__c</fullName>
        <label>Trade Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>DoH_Summaries</relationshipLabel>
        <relationshipName>DoH_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>W3_DOH__c</fullName>
        <label>W3 DOH</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DoH_Summary</label>
    <nameField>
        <label>DoH_Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DoH_Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/GCP_Trade_Partner_DOH_Report__c.object
<CustomObject>
    <fields>
        <fullName>Package_Description__c</fullName>
        <label>Package Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Partner_Name__c</fullName>
        <label>Trade Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GCP Trade Partner DOH Reports</relationshipLabel>
        <relationshipName>GCP_Trade_Partner_DOH_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>W3_DOH__c</fullName>
        <label>W3 DOH</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>GCP Trade Partner DOH Report</label>
    <nameField>
        <displayFormat>GCP trade-rep-{0000000}</displayFormat>
        <label>GCP Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Trade Partner DOH Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Rx_SRx_OTC__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Rx/SRx/OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OTC</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>SRx</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Vision_DOH_ReportCls_Test.cls
@isTest
public class Vision_DOH_ReportCls_Test {
    
    static testmethod void  test(){
        List<String> prodType = new List<String>{'Rx','SRx','OTC'};
            Account acc = new Account();
        acc.Name = 'Amazon'; 
        insert acc;
        Product2 prod = new Product2();
        prod.Name = 'Alloprinol';
        prod.Phoenix_Rx_SRx_OTC__c = 'Rx';
        insert prod;
        GCP_Trade_Partner_DOH_Report__c tradeDoH= new GCP_Trade_Partner_DOH_Report__c(Trade_Partner_Name__c='test Trade',Package_Description__c='testProduct',W3_DOH__c=2,Vision_Product__c=prod.Id);
        insert tradeDoH;
        doh_report_dates_info__c dohRepinfo = new  doh_report_dates_info__c(Vision_Update_Date__c ='2022-02-11', Name='Test');
        insert dohRepinfo;
        DoH_Summary__c dohSummary = new DoH_Summary__c();
        dohSummary.Name = 'Test';
        dohSummary.Trade_Partner_Name__c = acc.Id;
        insert dohSummary;
        Vision_DOH_ReportCls.getAccountGroups();
        Vision_DOH_ReportCls.getRxDoHData(prodType,'Amazon','Ama');
                Vision_DOH_ReportCls.getFilterDoHData('Amazon','Ama',prodType);
                Vision_DOH_ReportCls.getProdFamData('Amazon','Alloprinol');
                Vision_DOH_ReportCls.fetchSortResults('Package_Description__c',true,'Amazon','Ama');

    }
    
    
}