PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Status__c</fullName>
        <formula>IF(ISBLANK(Phoenix_Contract_End_Date__c),&quot;&quot;,IF(Phoenix_Contract_End_Date__c &lt; TODAY(),&quot;Expired&quot;, &quot;Active&quot; ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_GCP_Opportunity_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GCP Opportunity Trackers</relationshipLabel>
        <relationshipName>GCP_Market_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>GCP Opportunity Trackers</relationshipLabel>
        <relationshipName>GCP_Opportunity_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GCP Opportunity Tracker</label>
    <nameField>
        <displayFormat>GCP Opp Tracker-{0000000}</displayFormat>
        <label>GCP Opportunity Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Opportunity Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>OTC_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Private Label Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (OTC Customer)</relationshipLabel>
        <relationshipName>OTC_Customer_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Exclude_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is Exclude Bid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Private_Label_OTC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Private Label</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Product Director</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Marketing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Is_CPT_Batch_Executed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be updated when Customer Product Tracker Creator Batch process the record.</description>
        <label>Is CPT Batch Executed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product_Family__c.object
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Product Trackers (Product Family)</relationshipLabel>
        <relationshipName>Customer_Product_Trackers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Created_Date__c</fullName>
        <label>Contract Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Name__c</fullName>
        <label>Contract Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Product_Status__c</fullName>
        <label>Contract Product Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Is_True_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is True Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Created_Date__c</fullName>
        <label>Product Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Director__c</fullName>
        <label>Product Director</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <formula>Vision_Product_Code__c+&quot;_&quot;+Vision_Contract_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Identifier</label>
        <type>Text</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/CustomerContractOTCPrdCreatorBatchCls.cls
/*
 We will create Cpt records based on OTC Products,
Vision_Contract_Number__c from Relatedlist of contracts from Customer related to that Product
All Product Related fields are also created in cpt like Account,Productcode ,Productcreateddate etc from Product
 */
public class CustomerContractOTCPrdCreatorBatchCls implements Database.Batchable < sObject > , Database.Stateful,Schedulable,Database.AllowsCallouts {
    public void execute(SchedulableContext sc) {
        //Database.executeBatch(new CustomerContractProductCreatorBatchCls());
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //Query Active Bid Products and Find Products for Which This Batch has not Run even Once
        String query = 'Select Phoenix_Product_Director__r.Name,OTC_Customer__r.Name,OTC_Customer__r.AccountNumber,'+Phoenix_Util.getsObjectFieds('Product2')+' from Product2 where IsActive = true AND Phoenix_Is_Exclude_Bid__c = false AND Vision_Is_CPT_Batch_Executed__c = false AND Phoenix_Is_Private_Label_OTC__c = true';
        if(Test.isRunningTest())query += ' LIMIT 1';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List <Product2> prdList) {
       // system.debug(prdlist);
        try{
            if(prdList.size() > 0){
                list<Vision_Customer_Product_Tracker__c> cusPrdTrackerRecs = new list<Vision_Customer_Product_Tracker__c>();
                list<Phoenix_GCP_Opportunity_Tracker__c> gcpOptyTrackerRecs = new list<Phoenix_GCP_Opportunity_Tracker__c>();
                map<id,list<Phoenix_Contract__c>> contrmap= new map<id,list<Phoenix_Contract__c>>();
                set<string> cusset=new set<string>();
                for(Product2 prd:prdList){
                    cusset.add(prd.OTC_Customer__r.AccountNumber);
            }
                
                for(Phoenix_Contract__c contr:[select id,Phoenix_Customer__c,Phoenix_Contract_Number__c from Phoenix_Contract__c where Phoenix_Contract_Status__c =:'Active' and Phoenix_Customer__r.Accountnumber in:cusset]){
                    if(contrMap.containskey(contr.Phoenix_Customer__c)){
                        contrMap.get(contr.Phoenix_Customer__c).add(contr);
                    }
                    else{
                        contrMap.put(contr.Phoenix_Customer__c, new list<Phoenix_Contract__c>{contr});
                    }
                    
                }
                   
                
                
               
                //Updating Vision_Is_CPT_Batch_Executed__c when batch process the record inorder to exclude this rec in next batch
                Map<String,Product2> existingPrdMap = new Map<String,Product2>();
                Map<String,Id> activePrdFamilyMap = new Map<String,Id>();
                map<string,Phoenix_Contract__c> contrmap2 =  new  map<string,Phoenix_Contract__c>();
                for(Product2 prd:prdList){
                    
                    if(prd.ProductCode != null && prd.OTC_Customer__c != null && contrmap.containskey(prd.OTC_Customer__c) ){
                        if(contrmap.get(prd.OTC_Customer__c).size()>0){
                            for(integer i=0;i<contrmap.get(prd.OTC_Customer__c).size();i++){
                                 String unqId = prd.ProductCode+'_'+contrmap.get(prd.OTC_Customer__c)[i].Phoenix_Contract_Number__c;
                                existingPrdMap.put(unqId,prd);
                                 contrmap2.put(unqId,contrmap.get(prd.OTC_Customer__c)[i]);
                                 prd.Vision_Is_CPT_Batch_Executed__c = true;

                                
                            }
                        }  
                      
                        
                                           }
                    
                    activePrdFamilyMap.put(prd.Family,prd.Id);
                }
                //existing Contracts Map
                Map<String,Phoenix_Contract__c> existingCntrMap = new Map<String,Phoenix_Contract__c>();
                for(Phoenix_Contract__c cntr : [select Id, createdDate, Name, Phoenix_Customer__c, Phoenix_Contract_Number__c, Phoenix_Customer__r.Name,Phoenix_Contract_Status__c from Phoenix_Contract__c where Phoenix_Contract_Status__c =: 'Active']){
                    existingCntrMap.put(cntr.Phoenix_Contract_Number__c,cntr);
                }
                //For Active Bid Product - Query "Customer Product Tracker". 
                //If record doesnot exist create Customer Product Tracker.
               // system.debug('existing prd map...'+existingPrdMap.size());
                List<String> existingCusPrdTrkRecs = new List<String>();
                Set<String> UniqueIds = new Set<String>();
                for(Vision_Customer_Product_Tracker__c cusRec : [select Vision_Unique_Identifier__c from Vision_Customer_Product_Tracker__c Where Vision_Unique_Identifier__c in : existingPrdMap.keySet()]){
                    UniqueIds.add(cusRec.Vision_Unique_Identifier__c);
                }
               
                
                for(String key : existingPrdMap.keySet()){  
                    if(!UniqueIds.contains(key)){
                        Vision_Customer_Product_Tracker__c cusPrdTrk = new Vision_Customer_Product_Tracker__c();
                        //contract details
                        cusPrdTrk.Vision_Contract_Number__c =contrmap2.get(key).Phoenix_Contract_Number__c;
                        if(existingCntrMap.containsKey(contrmap2.get(key).Phoenix_Contract_Number__c)){
                            cusPrdTrk.Vision_Contract__c = existingCntrMap.get(contrmap2.get(key).Phoenix_Contract_Number__c).Id;
                            cusPrdTrk.Vision_Contract_Created_Date__c = existingCntrMap.get(contrmap2.get(key).Phoenix_Contract_Number__c).createdDate;
                            cusPrdTrk.Vision_Contract_Name__c = existingCntrMap.get(contrmap2.get(key).Phoenix_Contract_Number__c).Name;
                            
                        }
                        // product details
                        if(cusPrdTrk.Vision_Contract_Number__c.startsWith('3000')){
                            cusPrdTrk.Vision_Contract_Type__c='Indirect';
                        }
                        else if(cusPrdTrk.Vision_Contract_Number__c.startsWith('1000')){
                            cusPrdTrk.Vision_Contract_Type__c='Direct';
                        }
                        
                        cusPrdTrk.Vision_Product__c = existingPrdMap.get(key).Id;
                        cusPrdTrk.Vision_Product_Code__c = existingPrdMap.get(key).ProductCode;
                        cusPrdTrk.Vision_Product_Created_Date__c = existingPrdMap.get(key).createdDate;
                        cusPrdTrk.Vision_Product_Description__c = existingPrdMap.get(key).Description;
                        cusPrdTrk.Vision_Product_Director__c = existingPrdMap.get(key).Phoenix_Product_Director__r.Name;
                        cusPrdTrk.Vision_Product_Name__c = existingPrdMap.get(key).Name;
                        cusPrdTrk.Product_Family__c = existingPrdMap.get(key).Product_Family__c;
                        cusPrdTrk.Vision_Account__c = existingPrdMap.get(key).OTC_Customer__c;
                        cusPrdTrk.Vision_Customer_Name__c = existingPrdMap.get(key).OTC_Customer__r.Name;
                        cusPrdTrk.Vision_Customer_Code__c = existingPrdMap.get(key).OTC_Customer__r.AccountNumber;
                        cusPrdTrk.Vision_Contract_Product_Status__c = 'True Opportunity';
                        cusPrdTrk.Vision_Is_True_Opportunity__c = True;
                        cusPrdTrackerRecs.add(cusPrdTrk);
                    }
                }
                //For Active Bid Product, fetch product family - Query "Opportunity Tracker". 
                //If there is a new product family we need to insert Opportunity Tracker
                /*Set<String> optyTrackerFamily =new Set<String>();
                for(Phoenix_GCP_Opportunity_Tracker__c optyTrk : [select Phoenix_Product_Family__c From Phoenix_GCP_Opportunity_Tracker__c where Phoenix_Product_Family__c in : activePrdFamilyMap.keySet()])
                {
                    optyTrackerFamily.add(optyTrk.Phoenix_Product_Family__c); 
                }
                
                for(String fmyName : activePrdFamilyMap.keySet()){
                    if(!optyTrackerFamily.contains(fmyName)){
                        Phoenix_GCP_Opportunity_Tracker__c gcpOptyTrk = new Phoenix_GCP_Opportunity_Tracker__c();
                        gcpOptyTrk.Vision_Product__c = activePrdFamilyMap.get(fmyName);
                        gcpOptyTrackerRecs.add(gcpOptyTrk);
                    }
                }*/
                update prdList;
                upsert cusPrdTrackerRecs;
                //insert gcpOptyTrackerRecs;
            }
            
        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'CustomerContractProductCreatorBatchCls', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
    public void finish(Database.BatchableContext BC) {
        if(!Test.isRunningTest())  
            Database.executeBatch(new OptyBasedContractPrdStatusBatchCls(),2000);
    
}

}