PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Account_Cooling_Period__c</fullName>
        <label>Account Cooling Period (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Est_Market_Share__c</fullName>
        <label>Customer Est Market Share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Max_Est_Share_of_Wallet__c</fullName>
        <label>Customer Max Est Share of Wallet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Final_Direct_Selling_Units_Calc__c</fullName>
        <label>Final Direct Selling Units Calc</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Final_Indirect_Selling_Units_Cal__c</fullName>
        <label>Final Indirect Selling Units Calc</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Lowest_Price_SKU__c</fullName>
        <formula>Phoenix_Lowest_Price_SKU1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lowest Price /SKU (Internal Use)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <formula>Phoenix_Pkg_Size1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pkg Size (Internal Use)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Family__c</fullName>
        <formula>Phoenix_Product_Family1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family (Internal Use)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Proposed_Sales__c</fullName>
        <label>Proposed Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Family_Name__c</fullName>
        <description>This field is created to get Product Family Lookup from the Product Master</description>
        <formula>Product_Family__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_GCP_Opportunity_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Cust_Act_Sales_Mat__c</fullName>
        <label>Customer Account Sales Mat</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Cust_Act_Volume_Mat_Eu__c</fullName>
        <label>Customer Account Volume Mat Eu</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GCP Opportunity Trackers</relationshipLabel>
        <relationshipName>GCP_Market_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_AcctShareofWalletUserInput__c</fullName>
        <label>Est Acct Share of Wallet (User Input)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Mkt_Share_Method__c</fullName>
        <label>Est Acct Mkt Share Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use Est Account Value Input</fullName>
                </value>
                <value>
                    <fullName>Use User Input</fullName>
                </value>
                <value>
                    <fullName>Use Default Header</fullName>
                </value>
                <value>
                    <fullName>Use Customer Feedback (Bright)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Mkt_Share_User_Input__c</fullName>
        <label>Est Acct Mkt Share  (User Input)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Price_EU_User_Input__c</fullName>
        <label>Est Acct Price ($/EU) (User Input)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Share_of_Wallet_Method__c</fullName>
        <label>Est Acct Share of Wallet Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use User Input</fullName>
                </value>
                <value>
                    <fullName>Use Default Header</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Share_of_Wallet__c</fullName>
        <label>Estimate Account Share of Wallet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Total_Vol_EU__c</fullName>
        <label>Estimate Account Total Vol (EU)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Vol_EU_BRIGHT__c</fullName>
        <label>Est Acct Vol (EU) (BRIGHT)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Vol_EU_User_Input__c</fullName>
        <label>Est Acct Vol (EU) (User Input)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Acct_Vol_Method__c</fullName>
        <label>Est Acct Vol Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use User Input</fullName>
                </value>
                <value>
                    <fullName>Use Calculation of Est Acct Mkt Share</fullName>
                </value>
                <value>
                    <fullName>Use Proposed Total Selling Units (BRIGHT)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Price_EU_Lowest_Price__c</fullName>
        <label>Est Price ($/EU)(Lowest Price)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Price_EU__c</fullName>
        <label>Estimate Price($/EU)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Est_Price_Method__c</fullName>
        <label>Est Price Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use User Input</fullName>
                </value>
                <value>
                    <fullName>Use Lowest Price</fullName>
                </value>
                <value>
                    <fullName>Use GCP Suggested Price</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Estimate_Account_Marketing_Share__c</fullName>
        <label>Estimate Account Marketing Share</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Phoenix_Ims_Mat_Volume_Eu__c</fullName>
        <label>Ims Mat Volume Eu</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Total_Market_Vol_MAT_EU__c</fullName>
        <label>Total Market Vol(MAT - EU)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>GCP Opportunity Trackers</relationshipLabel>
        <relationshipName>GCP_Opportunity_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <description>- True Opportunity --&gt; Where it is out of colling period and It is not under price/Supply Constraint. It can be Modified by the user to Not an Oppty
- Not An Opportunity --&gt; User Input followed by his comments in the comments - Just open Comment section after selecting this Option.
- Price Constraint  --&gt;  This will be Auto selected If It is rejected by Marketing in bid process. Can Also be a user selection without any bid. After selecting this option, pop out a message &apos;Do you want to send it to Panorama for Cost Improvment Program(CIP)?&apos; 
- Supply Constraint  --&gt;This will be Auto selected If It is rejected by SCM in bid process. Can Also be a user selection without any bid. After selecting this option, pop out a message &apos;Do you want to send it to Panorama for Cost Improvment Program(CIP)?&apos;
- Awarded --&gt; When there is an active award or contract on this prod. This is automatically selected.
- In Bid --&gt; If there is a bid in progress on this prod, automatically selected.</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>True Opportunity</fullName>
                </value>
                <value>
                    <fullName>Not An Opportunity</fullName>
                </value>
                <value>
                    <fullName>Price Constraint</fullName>
                </value>
                <value>
                    <fullName>Supply Constraint</fullName>
                </value>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>In Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GCP Opportunity Tracker</label>
    <nameField>
        <displayFormat>GCP Opp Tracker-{0000000}</displayFormat>
        <label>GCP Opportunity Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Opportunity Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Lowest_Price_SKU__c</fullName>
        <inlineHelpText>Auto-generated field</inlineHelpText>
        <label>Lowest Price /SKU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Vision_CxAnalysisController.cls
public class Vision_CxAnalysisController {
    
    public class wrapperObj{
        @auraEnabled
        public Account accObj;
        @auraEnabled
        public Integer totalCxSales = 0;
        @auraEnabled
        public Integer drlCurrentSales = 0;
        @auraEnabled
        public Integer drlOptySales = 0;
        @auraEnabled
        public Integer shareOfWalletSales = 0;
        @auraEnabled
        public Integer shareOfWalletVol = 0;
        @auraEnabled
        public String currentUser;
    }
    
    @auraEnabled
    public static wrapperObj getAccountGroups(String accId){
        wrapperObj wrapObj = new wrapperObj();
        Id currentUserId = '0051K000008f7uFQAQ';//UserInfo.getUserId();
        wrapObj.currentUser = currentUserId;
        String query = 'SELECT '+Phoenix_Util.getsObjectFieds('Account')+' FROM Account';
        if(accId == 'noAccSelected')
            query += ' WHERE Phoenix_Customer_Est_Market_Share__c = null AND ownerId =: currentUserId ORDER BY Name ASC';
        else
            query += ' WHERE Id=: accId';
        
        list<Account> accList = Database.query(query);
        Account accObj = new Account();
        if(accList.size()>0)
            accObj = accList[0];
        else{
            query = 'SELECT '+Phoenix_Util.getsObjectFieds('Account')+' FROM Account ORDER BY Name ASC LIMIT 1';
            accObj = database.query(query);
        }
        Id acctId = accObj.Id;
        if((accObj.Phoenix_Customer_Est_Market_Share__c == null || accObj.Phoenix_Customer_Est_Market_Share__c == 0) && 
           (accObj.Phoenix_Customer_Max_Est_Share_of_Wallet__c == null || accObj.Phoenix_Customer_Max_Est_Share_of_Wallet__c == 0) && 
           (accObj.Phoenix_Account_Cooling_Period__c == null || accObj.Phoenix_Account_Cooling_Period__c == 0)){
               accObj.Phoenix_Customer_Est_Market_Share__c = 20;
               accObj.Phoenix_Customer_Max_Est_Share_of_Wallet__c = 65;
               accObj.Phoenix_Account_Cooling_Period__c = 90; 
               update accObj;
           }
        String childQuery = 'SELECT '+Phoenix_Util.getsObjectFieds('Phoenix_GCP_Opportunity_Tracker__c')+' FROM Phoenix_GCP_Opportunity_Tracker__c WHERE Phoenix_Customer__c =: acctId ';// ORDER BY GCP_Product_Family__c';
        list<Phoenix_GCP_Opportunity_Tracker__c> gcpList = database.query(childQuery);
        list<Phoenix_GCP_Opportunity_Tracker__c> updateGcpList = new list<Phoenix_GCP_Opportunity_Tracker__c>();
        
        List<String> prodFamNameList = new List<String>();
        for(Phoenix_GCP_Opportunity_Tracker__c gcpObj : gcpList){
            if(gcpObj.Phoenix_Product_Family__c != null){
                prodFamNameList.add(gcpObj.Phoenix_Product_Family__c);
            }
        }
        
        Map<String,dateTime> productFamilywithCreatedDateMap = new Map<String, dateTime>();
        Map<String,Decimal> productFamilywithUnitsMap = new Map<String, Decimal>();
        Map<String,Decimal> productFamilyLowPriceMap = new Map<String, Decimal>();
        Map<String,Decimal> producFamilyTotalPropSales = new Map<String, Decimal>();
        Map<String,String> rejectedStageMap = new Map<String, String>();
        
        
        List<AggregateResult> AggregateResultList = [SELECT Product_Family_Name__c , Sum(Phoenix_Final_Direct_Selling_Units_Calc__c) proposedDirectUnits,
                                                     Sum(Phoenix_Final_Indirect_Selling_Units_Cal__c) proposedIndirectUnits,  
                                                     Sum(Phoenix_Proposed_Sales__c) proposedSales 
                                                     FROM Phoenix_Bid_Line_Item__c 
                                                     where Phoenix_Bid__r.Phoenix_Customer__c =: acctId 
                                                     AND Product_Family_Name__c =: prodFamNameList
                                                     GROUP BY Product_Family_Name__c 
                                                     LIMIT 5000];
        
        List<Product2> productList = [SELECT Id, Name, Product_Family__r.Name,Phoenix_Pkg_Size__c, Phoenix_Lowest_Price_SKU__c, Family 
                                      FROM Product2 WHERE Product_Family__r.Name =: prodFamNameList AND IsActive = true
                                      AND Phoenix_Lowest_Price_SKU__c > 0 AND Phoenix_Pkg_Size__c > 0];
        for(Product2 prodObj : productList){ 
            Decimal newCalc = prodObj.Phoenix_Lowest_Price_SKU__c/prodObj.Phoenix_Pkg_Size__c;  
            if(productFamilyLowPriceMap.containsKey(prodObj.Product_Family__r.Name)){
                Decimal lowestPrice = productFamilyLowPriceMap.get(prodObj.Product_Family__r.Name);
                if(newCalc < lowestPrice)
                    productFamilyLowPriceMap.put(prodObj.Product_Family__r.Name,newCalc);                        
            }
            else
                productFamilyLowPriceMap.put(prodObj.Product_Family__r.Name,newCalc); 
        }
        
        
        if(AggregateResultList != null && AggregateResultList.size() > 0){
            for(AggregateResult aggr:AggregateResultList){ 
                decimal totalUnits = (aggr.get('proposedDirectUnits') != null ?(decimal)aggr.get('proposedDirectUnits'):0)+(aggr.get('proposedIndirectUnits') !=null ? (decimal)aggr.get('proposedIndirectUnits'):0); 
                String productFamily = (String) aggr.get('Product_Family_Name__c');
                decimal totalPropSales = aggr.get('proposedSales') != null ?(decimal)aggr.get('proposedSales'):0;
                if(productFamily != null){
                    productFamilywithUnitsMap.put(productFamily,totalUnits);
                    producFamilyTotalPropSales.put(productFamily,totalPropSales);
                }
            } 
        }
        Decimal totalEstSales = 0;
        for(Phoenix_GCP_Opportunity_Tracker__c gcpObj : gcpList){
            String prodFamily = gcpObj.Phoenix_Product_Family__c;
            Decimal proposedTotal = 0; Decimal lowestPrice = 0; String latestBidDate = '';
            if(productFamilywithUnitsMap.containsKey(prodFamily))
                proposedTotal = productFamilywithUnitsMap.get(prodFamily); gcpObj.Phoenix_Est_Acct_Vol_EU_BRIGHT__c = proposedTotal;
            if(productFamilyLowPriceMap.containsKey(prodFamily))
                lowestPrice = productFamilyLowPriceMap.get(prodFamily);gcpObj.Phoenix_Est_Price_EU_Lowest_Price__c = lowestPrice;
            
            if(gcpObj.Phoenix_Ims_Mat_Volume_Eu__c != null)
                gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c = gcpObj.Phoenix_Ims_Mat_Volume_Eu__c;
            if(gcpObj.Phoenix_Est_Acct_Share_of_Wallet_Method__c == null || gcpObj.Phoenix_Est_Acct_Share_of_Wallet_Method__c == 'Use Default Header')
                gcpObj.Phoenix_Est_Acct_Share_of_Wallet__c = accObj.Phoenix_Customer_Max_Est_Share_of_Wallet__c != null ? accObj.Phoenix_Customer_Max_Est_Share_of_Wallet__c : 0;
            else if(gcpObj.Phoenix_Est_Acct_Share_of_Wallet_Method__c == 'Use User Input')
                gcpObj.Phoenix_Est_Acct_Share_of_Wallet__c = gcpObj.Phoenix_Est_AcctShareofWalletUserInput__c != null ? gcpObj.Phoenix_Est_AcctShareofWalletUserInput__c : 0;
            
            if(gcpObj.Phoenix_Est_Acct_Mkt_Share_Method__c == null || gcpObj.Phoenix_Est_Acct_Mkt_Share_Method__c == 'Use Default Header')gcpObj.Phoenix_Estimate_Account_Marketing_Share__c = accObj.Phoenix_Customer_Est_Market_Share__c != null ? accObj.Phoenix_Customer_Est_Market_Share__c :0;
            else if(gcpObj.Phoenix_Est_Acct_Mkt_Share_Method__c == 'Use User Input')
                gcpObj.Phoenix_Estimate_Account_Marketing_Share__c = gcpObj.Phoenix_Est_Acct_Mkt_Share_User_Input__c != null ? gcpObj.Phoenix_Est_Acct_Mkt_Share_User_Input__c: 0;
            else if(gcpObj.Phoenix_Est_Acct_Mkt_Share_Method__c == 'Use Usage Data'){ //'Use Customer Feedback (BRIGHT)'){
                gcpObj.Phoenix_Estimate_Account_Marketing_Share__c = (gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c !=null && gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c > 0) ? 
                    (gcpObj.Phoenix_Est_Acct_Vol_EU_BRIGHT__c != null ? gcpObj.Phoenix_Est_Acct_Vol_EU_BRIGHT__c : 0)/(gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c) : 0;
            }
            
            if(gcpObj.Phoenix_Est_Acct_Vol_Method__c == 'Use User Input')gcpObj.Phoenix_Est_Acct_Total_Vol_EU__c = gcpObj.Phoenix_Est_Acct_Vol_EU_User_Input__c != null ? gcpObj.Phoenix_Est_Acct_Vol_EU_User_Input__c : 0;
            else if (gcpObj.Phoenix_Est_Acct_Vol_Method__c == 'Use Proposed Total Selling Units (BRIGHT)')gcpObj.Phoenix_Est_Acct_Total_Vol_EU__c = gcpObj.Phoenix_Est_Acct_Vol_EU_BRIGHT__c != null ? gcpObj.Phoenix_Est_Acct_Vol_EU_BRIGHT__c : 0;
            else if (gcpObj.Phoenix_Est_Acct_Vol_Method__c == null || gcpObj.Phoenix_Est_Acct_Vol_Method__c == 'Use Calculation of Est Acct Mkt Share')
                gcpObj.Phoenix_Est_Acct_Total_Vol_EU__c = (gcpObj.Phoenix_Est_Acct_Share_of_Wallet__c/100)*(gcpObj.Phoenix_Estimate_Account_Marketing_Share__c/100)*(gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c!=null?gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c:0);
            
            if((gcpObj.Product_Status__c == 'Awarded' && gcpObj.Phoenix_Est_Price_Method__c == null) || gcpObj.Phoenix_Est_Price_Method__c == 'DRL Customer Actuals Average Price'){
                if(gcpObj.Phoenix_Cust_Act_Volume_Mat_Eu__c != null && gcpObj.Phoenix_Cust_Act_Volume_Mat_Eu__c > 0)
                    gcpObj.Phoenix_Est_Price_EU__c = (gcpObj.Cust_Act_Sales_Mat__c != null ? gcpObj.Cust_Act_Sales_Mat__c : 0)/gcpObj.Phoenix_Cust_Act_Volume_Mat_Eu__c;
                else{ 
                    if(gcpObj.Phoenix_Est_Price_Method__c == 'Use User Input')
                        gcpObj.Phoenix_Est_Price_EU__c = gcpObj.Phoenix_Est_Acct_Price_EU_User_Input__c != null ? gcpObj.Phoenix_Est_Acct_Price_EU_User_Input__c : 0;
                    else if(gcpObj.Phoenix_Est_Price_Method__c == 'Use Lowest Price')
                        gcpObj.Phoenix_Est_Price_EU__c = gcpObj.Phoenix_Est_Price_EU_Lowest_Price__c != null ? gcpObj.Phoenix_Est_Price_EU_Lowest_Price__c : 0;
                    else if(gcpObj.Phoenix_Est_Price_Method__c == null || gcpObj.Phoenix_Est_Price_Method__c == 'Marketing (Panorama) suggested Price' || gcpObj.Phoenix_Est_Price_Method__c == 'Use GCP suggested Price')
                        gcpObj.Phoenix_Est_Price_EU__c = gcpObj.Phoenix_GCP_Suggested_Lowest_Price__c != null ? gcpObj.Phoenix_GCP_Suggested_Lowest_Price__c : 0;
                }
            }
            else{
                if(gcpObj.Phoenix_Est_Price_Method__c == 'Use User Input')
                    gcpObj.Phoenix_Est_Price_EU__c = gcpObj.Phoenix_Est_Acct_Price_EU_User_Input__c != null ? gcpObj.Phoenix_Est_Acct_Price_EU_User_Input__c : 0; else if(gcpObj.Phoenix_Est_Price_Method__c == 'Use Lowest Price')gcpObj.Phoenix_Est_Price_EU__c = gcpObj.Phoenix_Est_Price_EU_Lowest_Price__c != null ? gcpObj.Phoenix_Est_Price_EU_Lowest_Price__c : 0;
                else if(gcpObj.Phoenix_Est_Price_Method__c == null || gcpObj.Phoenix_Est_Price_Method__c == 'Marketing (Panorama) suggested Price' || gcpObj.Phoenix_Est_Price_Method__c == 'Use GCP suggested Price')
                    gcpObj.Phoenix_Est_Price_EU__c = gcpObj.Phoenix_GCP_Suggested_Lowest_Price__c != null ? gcpObj.Phoenix_GCP_Suggested_Lowest_Price__c : 0;
            }
            
            gcpObj.Phoenix_Est_Acct_Sales__c = (gcpObj.Phoenix_Est_Acct_Share_of_Wallet__c/100) * gcpObj.Phoenix_Est_Acct_Total_Vol_EU__c * (gcpObj.Phoenix_Est_Price_EU__c!=null?gcpObj.Phoenix_Est_Price_EU__c:0);
            if(gcpObj.Product_Status__c == 'Awarded' && (gcpObj.Phoenix_Current_Position__c == 'Formulary A Awards' || gcpObj.Phoenix_Current_Position__c == '100% Products')){
                gcpObj.Phoenix_Customer_Opp_Sales__c = null;
                gcpObj.Phoenix_Customer_Opp_TPT__c = null;
                gcpObj.Phoenix_Customer_Opp_TPT_Perc__c = null;
            }
            else{
                gcpObj.Phoenix_Customer_Opp_Sales__c = gcpObj.Phoenix_Est_Acct_Sales__c - (gcpObj.Cust_Act_Sales_Mat__c != null ? gcpObj.Cust_Act_Sales_Mat__c : 0);
                gcpObj.Phoenix_Customer_Opp_TPT__c = ((gcpObj.Phoenix_Est_Acct_Share_of_Wallet__c/100)*(gcpObj.Phoenix_Est_Acct_Total_Vol_EU__c)*(gcpObj.cogs_per_unit__c != null ? gcpObj.cogs_per_unit__c : 0)) - (gcpObj.Phoenix_Cust_Act_Volume_Mat_Eu__c!=null ? gcpObj.Phoenix_Cust_Act_Volume_Mat_Eu__c :0)* (gcpObj.cogs_per_unit__c != null ? gcpObj.cogs_per_unit__c : 0);
                gcpObj.Phoenix_Customer_Opp_TPT_Perc__c = (gcpObj.Phoenix_Customer_Opp_Sales__c != null && gcpObj.Phoenix_Customer_Opp_Sales__c > 0) ? (gcpObj.Phoenix_Customer_Opp_TPT__c/gcpObj.Phoenix_Customer_Opp_Sales__c)*100 : 0;
            }
            
            gcpObj.Phoenix_Cust_Act_Mkt_Sh__c = (gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c != null && gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c >0) ? ((gcpObj.Phoenix_Cust_Act_Volume_Mat_Eu__c!= null ? gcpObj.Phoenix_Cust_Act_Volume_Mat_Eu__c : 0)/gcpObj.Phoenix_Total_Market_Vol_MAT_EU__c)*100 : 0;
            gcpObj.Phoenix_Cooling_Period__c = gcpObj.Phoenix_Cooling_Period__c != null ? gcpObj.Phoenix_Cooling_Period__c : accObj.Phoenix_Account_Cooling_Period__c;
            
            totalEstSales = totalEstSales + ((gcpObj.Phoenix_Est_Acct_Share_of_Wallet__c != null && gcpObj.Phoenix_Est_Acct_Share_of_Wallet__c > 0) ? (gcpObj.Phoenix_Est_Acct_Sales__c != null ? gcpObj.Phoenix_Est_Acct_Sales__c : 0)*(gcpObj.Phoenix_Est_Acct_Share_of_Wallet__c/100): 0 );
            
            updateGcpList.add(gcpObj);
        }
        update updateGcpList; 
        AggregateResult totalAggrigates = [select sum(Phoenix_Est_Acct_Sales__c) EstAcctSales, sum(Cust_Act_Sales_Mat__c) custActualSales,
                                           sum(Phoenix_Customer_Opp_Sales__c) custOptySales,sum(Phoenix_Cust_Act_Volume_Mat_Eu__c) cxActVol,
                                           sum(Phoenix_Est_Acct_Total_Vol_EU__c) actTotal, sum(Phoenix_Est_Acct_Share_of_Wallet__c) shareOfWallet,
                                           sum(Phoenix_Drl_Act_Volume_Eu__c) drlAccVol, sum(Phoenix_Drl_Act_Sales__c) drlAccSales,
                                           sum(Phoenix_Drl_Act_Price__c) drlAccPrice, sum(Phoenix_DRL_Actual_TPT__c) drlAccTpt,
                                           sum(Phoenix_Total_Market_Vol_MAT_EU__c) totalMktVol, sum(Phoenix_Total_Market_Sales__c) totalMktShares,
                                           sum(Phoenix_Cust_Act_Volume_Mat_Eu__c) custActVol, sum(Phoenix_Cust_Act_Mkt_Sh__c) custActMktShare,
                                           sum(Phoenix_Customer_Opp_TPT__c) custActOppTpt
                                           FROM Phoenix_GCP_Opportunity_Tracker__c  WHERE Phoenix_Customer__c =: acctId 
                                           AND Phoenix_Product_Family__c =: prodFamNameList];
        accObj.Phoenix_Total_Customer_Opportunity__c = totalAggrigates.get('EstAcctSales') != null ? (Decimal)totalAggrigates.get('EstAcctSales') : 0;
        accObj.Phoenix_DRL_Current_Sales__c = totalAggrigates.get('custActualSales') != null ? (decimal)totalAggrigates.get('custActualSales') : 0;
        accObj.Phoenix_DRL_Opportunity_Sales__c = totalAggrigates.get('custOptySales') != null ? (Decimal)totalAggrigates.get('custOptySales') : 0;
        
        accObj.Phoenix_DRL_Total_Est_Account_Sales__c = totalEstSales;//accObj.Phoenix_Total_Customer_Opportunity__c*((totalAggrigates.get('shareOfWallet') != null ? (Decimal)totalAggrigates.get('shareOfWallet') : 0)/100);// + accObj.Phoenix_DRL_Opportunity_Sales__c;
        accObj.Phoenix_DRL_Share_of_Wallet__c = accObj.Phoenix_Total_Customer_Opportunity__c > 0 ? (accObj.Phoenix_DRL_Current_Sales__c/(accObj.Phoenix_Total_Customer_Opportunity__c))*100 : 0;
        accObj.Phoenix_DRL_Share_of_Wallet_Vol__c = (totalAggrigates.get('actTotal') != null && (Decimal)totalAggrigates.get('actTotal') > 0) ? ((totalAggrigates.get('cxActVol') != null ? (Decimal)totalAggrigates.get('cxActVol') : 0)/(Decimal)totalAggrigates.get('actTotal'))*100 : 0;
        
        update accObj;
        wrapObj.accObj = accObj;
        
        return wrapObj;
    }
}