PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/GCP_Product_Family_Map__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SULFADIAZINE 1 CREAM</fullName>
                </value>
                <value>
                    <fullName>HABITROL PATCH</fullName>
                </value>
                <value>
                    <fullName>FENOFIBRATE CAPS</fullName>
                </value>
                <value>
                    <fullName>RANITIDINE CAPS</fullName>
                </value>
                <value>
                    <fullName>FEBUXOSTAT</fullName>
                </value>
                <value>
                    <fullName>PEMETREXED DISODIUM LYO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Product_Family__c</fullName>
        <label>SFDC Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SSD Cream</fullName>
                </value>
                <value>
                    <fullName>Fenofibrate Capsules</fullName>
                </value>
                <value>
                    <fullName>Ranitidine Caps</fullName>
                </value>
                <value>
                    <fullName>Febuxostat</fullName>
                </value>
                <value>
                    <fullName>Naproxen Sodium</fullName>
                </value>
                <value>
                    <fullName>Pemetrexed for Injection</fullName>
                </value>
                <value>
                    <fullName>Fesoterodine</fullName>
                </value>
                <value>
                    <fullName>Sorafenib</fullName>
                </value>
                <value>
                    <fullName>Nicotine Lozenge Original</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GCP Product Family Map</label>
    <nameField>
        <displayFormat>GCPFamilyMap-{0000000}</displayFormat>
        <label>GCP Product Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Product Family Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family_Map__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Product Family Map</label>
        <referenceTo>GCP_Product_Family_Map__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Exclude_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is Exclude Bid</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_DRL_Sales_External_Summary__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>DRL Sales External Summary</relationshipLabel>
        <relationshipName>DRL_Sales_External_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DRL Sales External Summary</relationshipLabel>
        <relationshipName>DRL_Sales_External_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_agreement_no__c</fullName>
        <label>Agreement Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_customer_code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRL Sales External Summary</label>
    <nameField>
        <displayFormat>drl-ext-summ-{0000000}</displayFormat>
        <label>DRL Sales External Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Sales External Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/GoogleBigQueryDRLSalesExtFetchTest.cls
@istest
public class GoogleBigQueryDRLSalesExtFetchTest {
    @istest(seealldata=true)
     public static  void main(){
        Account a = new Account();
        a.Name='test';
        a.AccountNumber='1234';
        insert a;
        Phoenix_Contract__c ct= new Phoenix_Contract__c();
        ct.Phoenix_Contract_Number__c='1223';
        ct.Phoenix_Contract_Start_Date__c=date.newInstance(2022, 04, 17);
        ct.Phoenix_Contract_End_Date__c=system.Today()+1;
        insert ct;
        Product2 p = new Product2();
        p.Name='abc';
        p.ProductCode='1222';
        p.IsActive=true;
        p.Phoenix_Is_Exclude_Bid__c=false;
        insert p;
          GCP_Product_Family_Map__c gcp = new GCP_Product_Family_Map__c();
        gcp.GCP_Product_Family__c = 'GCP DRL Sales Record';
        gcp.SFDC_Product_Family__c = 'Test DRL Sales Record';
        insert gcp;
      Vision_DRL_Sales_External_Summary__c extsales = new Vision_DRL_Sales_External_Summary__c();
        extsales.Vision_agreement_no__c='123456';
        extsales.Vision_Contract__c=ct.id;
        extsales.Vision_Customer__c=a.id;
        extsales.Vision_SKU_Code__c='1222';
        extsales.Vision_customer_code__c='1234';
        extsales.GCP_Product_Family__c='abc';
        insert extsales;
        test.startTest();
        GoogleBigQueryDRLSalesExtFetch b = new GoogleBigQueryDRLSalesExtFetch();
        database.executeBatch(b);
        database.executeBatch(new GoogleBigQueryDRLSalesExtFetch (1,1));
        
        
       
        test.stopTest();
    }

}