PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/GCP_Product_Family_Map__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SULFADIAZINE 1 CREAM</fullName>
                </value>
                <value>
                    <fullName>HABITROL PATCH</fullName>
                </value>
                <value>
                    <fullName>FENOFIBRATE CAPS</fullName>
                </value>
                <value>
                    <fullName>RANITIDINE CAPS</fullName>
                </value>
                <value>
                    <fullName>FEBUXOSTAT</fullName>
                </value>
                <value>
                    <fullName>PEMETREXED DISODIUM LYO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Product_Family__c</fullName>
        <label>SFDC Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SSD Cream</fullName>
                </value>
                <value>
                    <fullName>Fenofibrate Capsules</fullName>
                </value>
                <value>
                    <fullName>Ranitidine Caps</fullName>
                </value>
                <value>
                    <fullName>Febuxostat</fullName>
                </value>
                <value>
                    <fullName>Naproxen Sodium</fullName>
                </value>
                <value>
                    <fullName>Pemetrexed for Injection</fullName>
                </value>
                <value>
                    <fullName>Fesoterodine</fullName>
                </value>
                <value>
                    <fullName>Sorafenib</fullName>
                </value>
                <value>
                    <fullName>Nicotine Lozenge Original</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GCP Product Family Map</label>
    <nameField>
        <displayFormat>GCPFamilyMap-{0000000}</displayFormat>
        <label>GCP Product Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Product Family Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/GCP_VIR_Report__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GCP VIR Report</relationshipLabel>
        <relationshipName>GCP_VIR_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Agreement_Number__c</fullName>
        <label>Agreement Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Agreement__c</fullName>
        <label>GCP Agreement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Customer_Code__c</fullName>
        <label>GCP Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Customer__c</fullName>
        <label>GCP Customer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_End_Date__c</fullName>
        <label>GCP End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Month_Text__c</fullName>
        <label>GCP Month Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Month__c</fullName>
        <label>GCP Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Start_Date__c</fullName>
        <label>GCP Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Tenure__c</fullName>
        <label>GCP Tenure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_GCP_Year__c</fullName>
        <label>GCP Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Gcp_Direct_Sales__c</fullName>
        <label>Gcp Direct Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>GCP VIR Report</label>
    <nameField>
        <displayFormat>GCP VIR Report-{0000000}</displayFormat>
        <label>GCP VIR Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP VIR Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/GoogleVIRReportDataFetchTest.cls
@istest
public class GoogleVIRReportDataFetchTest {
    static  testmethod void setup(){
        Account a = new Account();
        a.Name='es';
        a.AccountNumber='12563';
        insert a;
         Account bv = new Account();
        bv.Name='esq';
        bv.AccountNumber='12565';
        insert bv;
          Phoenix_Contract__c cc= new Phoenix_Contract__c();
        cc.Phoenix_Contract_Start_Date__c=system.today();
        cc.Phoenix_Contract_Number__c='11111';
        cc.Phoenix_Contract_End_Date__c=system.today()+30;
        cc.Phoenix_Customer__c=a.id;
        insert cc;
        GCP_Product_Family_Map__c gcpf= new GCP_Product_Family_Map__c();
        gcpf.SFDC_Product_Family__c='A';
        gcpf.GCP_Product_Family__c='A';
        insert gcpf;
        GCP_VIR_Report__c vir = new GCP_VIR_Report__c();
        vir.Vision_GCP_Agreement__c='122';
        vir.Vision_Account__c=a.id;
        vir.Vision_GCP_Customer__c='ABC';
        vir.Vision_GCP_Customer_Code__c='12563';
        vir.Vision_GCP_Month__c=25;
        vir.Vision_GCP_Month_Text__c='april';
        vir.Vision_GCP_Tenure__c='Jan21toDEC23';
        vir.Vision_Gcp_Direct_Sales__c=2225.22;
        vir.Vision_GCP_Year__c='2021';
        vir.Vision_Agreement_Number__c='11111';
        //vir.Vision_GCP_Start_Date__c=date.newInstance(2022, 03, 05);
       // vir.Vision_GCP_End_Date__c=date.newInstance(2022, 12, 05);
      
        insert vir;
         GCP_VIR_Report__c vir1 = new GCP_VIR_Report__c();
        vir1.Vision_Agreement_Number__c='122';
       // vir1.Vision_Account__c=a.id;
        vir1.Vision_GCP_Customer__c=null;
        vir1.Vision_GCP_Customer_Code__c='12562';
        vir1.Vision_GCP_Month__c=25;
        vir1.Vision_GCP_Month_Text__c='jan';
        vir1.Vision_GCP_Tenure__c='jan21 to dec22';
        vir1.Vision_Gcp_Direct_Sales__c=2225.22;
        vir1.Vision_GCP_Year__c='2022';
        //vir.Vision_GCP_Start_Date__c=date.newInstance(2022, 03, 05);
       // vir.Vision_GCP_End_Date__c=date.newInstance(2022, 12, 05);
        
        insert vir1;
        test.startTest();
        GoogleVIRReportDataFetch b = new GoogleVIRReportDataFetch();
        database.executeBatch(b);
         Database.executeBatch(new GoogleVIRReportDataFetch(5,1));
        test.stopTest();
    }
        static  testmethod void setup1(){
        Account a = new Account();
        a.Name='es';
        a.AccountNumber='12563';
        insert a;
         Account bv = new Account();
        bv.Name='esq';
        bv.AccountNumber='12565';
        insert bv;
          Phoenix_Contract__c cc= new Phoenix_Contract__c();
        cc.Phoenix_Contract_Start_Date__c=system.today();
        cc.Phoenix_Contract_Number__c='11111';
        cc.Phoenix_Contract_End_Date__c=system.today()+30;
        cc.Phoenix_Customer__c=a.id;
        insert cc;
        GCP_Product_Family_Map__c gcpf= new GCP_Product_Family_Map__c();
        gcpf.SFDC_Product_Family__c='A';
        gcpf.GCP_Product_Family__c='A';
        insert gcpf;
        GCP_VIR_Report__c vir = new GCP_VIR_Report__c();
        vir.Vision_GCP_Agreement__c='122';
        vir.Vision_Account__c=a.id;
        vir.Vision_GCP_Customer__c='ABC';
        vir.Vision_GCP_Customer_Code__c='12563';
        vir.Vision_GCP_Month__c=25;
        vir.Vision_GCP_Month_Text__c='april';
        vir.Vision_GCP_Tenure__c='Jan21toDEC23';
        vir.Vision_Gcp_Direct_Sales__c=2225.22;
        vir.Vision_GCP_Year__c='2021';
        vir.Vision_Agreement_Number__c='11111';
        //vir.Vision_GCP_Start_Date__c=date.newInstance(2022, 03, 05);
       // vir.Vision_GCP_End_Date__c=date.newInstance(2022, 12, 05);
      
        insert vir;
         GCP_VIR_Report__c vir1 = new GCP_VIR_Report__c();
        vir1.Vision_Agreement_Number__c='122';
       // vir1.Vision_Account__c=a.id;
        vir1.Vision_GCP_Customer__c=null;
        vir1.Vision_GCP_Customer_Code__c='12562';
        vir1.Vision_GCP_Month__c=25;
        vir1.Vision_GCP_Month_Text__c='jan';
        vir1.Vision_GCP_Tenure__c='jan21 to dec22';
        vir1.Vision_Gcp_Direct_Sales__c=2225.22;
        vir1.Vision_GCP_Year__c='2022';
        //vir.Vision_GCP_Start_Date__c=date.newInstance(2022, 03, 05);
       // vir.Vision_GCP_End_Date__c=date.newInstance(2022, 12, 05);
        
        insert vir1;
        test.startTest();
        GoogleVIRReportDataFetch b = new GoogleVIRReportDataFetch();
        database.executeBatch(b);
         Database.executeBatch(new GoogleVIRReportDataFetch(5,1));
        test.stopTest();
        
        
    }

}