PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Is_Govt_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Lowest Price/SKU and CM fee</inlineHelpText>
        <label>Is Govt Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Preferred_Wholesaler__c</fullName>
        <label>Preferred Wholesaler for CM Fee</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABC</fullName>
                </value>
                <value>
                    <fullName>Cardinal</fullName>
                </value>
                <value>
                    <fullName>McKesson</fullName>
                </value>
                <value>
                    <fullName>Morris and Dickson</fullName>
                </value>
                <value>
                    <fullName>Source program</fullName>
                </value>
                <value>
                    <fullName>Oncology Supply</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Allocation Review</fullName>
                </value>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Customer Requested Pricing Confirmations</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                </value>
                <value>
                    <fullName>Exceptional Billings</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>In-Licensing</fullName>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                </value>
                <value>
                    <fullName>NDC Change</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                </value>
                <value>
                    <fullName>New Launch &amp; WAC</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>New Product WAC Pricing</fullName>
                </value>
                <value>
                    <fullName>Platform OTB</fullName>
                </value>
                <value>
                    <fullName>Platform PO OTB</fullName>
                    <label>One Time Buy - Platform PO</label>
                </value>
                <value>
                    <fullName>One Time Buy - Price Load Req</fullName>
                </value>
                <value>
                    <fullName>One Time Buy - Price Override Sale</fullName>
                </value>
                <value>
                    <fullName>PHS Price Change</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>RCA/IPA Member Addition</fullName>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                </value>
                <value>
                    <fullName>Re-Bid (Pricing Only)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval Matrix</label>
    <nameField>
        <label>Process #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Approval_Process_Step__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Matrix__c</fullName>
        <label>Approval Matrix</label>
        <referenceTo>Phoenix_Approval_Matrix__c</referenceTo>
        <relationshipLabel>Approval Process Steps</relationshipLabel>
        <relationshipName>Phoenix_Approval_Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approval Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
                <value>
                    <fullName>Dropped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Contracts Approved</fullName>
                </value>
                <value>
                    <fullName>SCM Approved</fullName>
                </value>
                <value>
                    <fullName>Marketing Approved</fullName>
                </value>
                <value>
                    <fullName>Finance Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Submitted</fullName>
                </value>
                <value>
                    <fullName>Proposal Accepted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_Bid_Process_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Process Steps</relationshipLabel>
        <relationshipName>Bid_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Do Not Bid</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Not Initiated</fullName>
                    <default>true</default>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bid Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Phoenix_PricingReviewApprovalsTest.cls
/**
 * @description       : 
 * @author            : Surender Patel (Dhruvsoft)
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
@isTest
public class Phoenix_PricingReviewApprovalsTest {

    @testSetup static void setupTestData() {
        Id phoenixRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Bid Accounts').getRecordTypeId();
        Account testAccount = new Account(Name = 'Test Account', Phoenix_Preferred_Wholesaler__c = 'ABC', Phoenix_Is_Govt_Customer__c = true);
        insert testAccount;

        Phoenix_Bid__c bid = new Phoenix_Bid__c();
        bid.Phoenix_Status__c = 'New';
        bid.Phoenix_Comments__c = 'Test Comments';
        bid.Phoenix_Approval_Status__c = 'Draft';
        bid.Phoenix_Customer__c = testAccount.Id;
        insert bid;

        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;
        List < ContentDocument > documents = [
            SELECT Id, Title, LatestPublishedVersionId
            FROM ContentDocument
        ];
        String docId = documents[0].Id;
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = bid.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;

        //--------------Approval--------------
        Phoenix_Approval_Matrix__c appro = new Phoenix_Approval_Matrix__c();
        appro.Phoenix_Bid_Type__c = 'Customer Requested Pricing Confirmations';
        appro.Name = 'Pricing Review';
        insert appro;

        Phoenix_Approval_Process_Step__c proI = new Phoenix_Approval_Process_Step__c();
        proI.Name = 'Initial Submission';
        proI.Phoenix_Order__c = 1;
        proI.Phoenix_Approval_Matrix__c = appro.Id;
        insert proI;

        Phoenix_Approval_Process_Step__c pro = new Phoenix_Approval_Process_Step__c();
        pro.Name = 'Business Head';
        pro.Phoenix_Order__c = 2;
        pro.Phoenix_Approval_Matrix__c = appro.Id;
        insert pro;

        Phoenix_Approval_Process_Step__c pro1 = new Phoenix_Approval_Process_Step__c();
        pro1.Name = 'Contracts';
        pro1.Phoenix_Order__c = 3;
        pro1.Phoenix_Approval_Matrix__c = appro.Id;
        insert pro1;

        Phoenix_Approval_Process_Step__c proClosed = new Phoenix_Approval_Process_Step__c();
        proClosed.Name = 'Closed';
        proClosed.Phoenix_Order__c = 4;
        proClosed.Phoenix_Approval_Matrix__c = appro.Id;
        insert proClosed;

        List < Phoenix_Bid_Process_Steps__c > processSteps = new List < Phoenix_Bid_Process_Steps__c > ();
        Phoenix_Bid_Process_Steps__c processStep1 = new Phoenix_Bid_Process_Steps__c();
        processStep1.Phoenix_Bid__c = bid.Id;
        processStep1.Phoenix_Process_Step__c = proI.Id;
        processStep1.Phoenix_Status__c = 'Submitted';
        // processStep1.Phoenix_Sub_Step__c=1;
        processSteps.add(processStep1);
        insert processSteps;

        List < Phoenix_Bid_Process_Steps__c > processStepNext = new List < Phoenix_Bid_Process_Steps__c > ();
        Phoenix_Bid_Process_Steps__c processStep = new Phoenix_Bid_Process_Steps__c();
        processStep.Phoenix_Bid__c = bid.Id;
        processStep.Phoenix_Process_Step__c = pro.Id;
        processStep.Phoenix_Status__c = 'In Process';
        // processStep.Phoenix_Sub_Step__c=2;
        processStepNext.add(processStep);
        insert processStepNext;

        List < Phoenix_Bid_Process_Steps__c > processStepNextStep = new List < Phoenix_Bid_Process_Steps__c > ();
        Phoenix_Bid_Process_Steps__c processStep3 = new Phoenix_Bid_Process_Steps__c();
        processStep3.Phoenix_Bid__c = bid.Id;
        processStep3.Phoenix_Process_Step__c = pro1.Id;
        processStep3.Phoenix_Status__c = 'Not Initiated';
        processStep3.Phoenix_Sub_Step__c = 3;
        processStepNextStep.add(processStep3);
        insert processStepNextStep;

        List < Phoenix_Bid_Process_Steps__c > processStepClose = new List < Phoenix_Bid_Process_Steps__c > ();
        Phoenix_Bid_Process_Steps__c processStepCl = new Phoenix_Bid_Process_Steps__c();
        processStepCl.Phoenix_Bid__c = bid.Id;
        processStepCl.Phoenix_Process_Step__c = proClosed.Id;
        processStepCl.Phoenix_Status__c = 'Not Initiated';
        processStep3.Phoenix_Sub_Step__c = 4;
        processStepClose.add(processStepCl);
        insert processStepClose;

        //-------Approval Test Data End-----------------

    }

    static testmethod void getBid() {

        Phoenix_Bid__c bid = [SELECT Id FROM Phoenix_Bid__c WHERE Phoenix_Approval_Status__c = 'Draft'
            LIMIT 1
        ];

        bid.Phoenix_Review_Details__c = 'Test';
        update bid;
        ContentDocumentLink bid1 = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: bid.Id LIMIT 1];
        List < Phoenix_Bid_Process_Steps__c > bidProcess = [select id, Phoenix_Status__c from Phoenix_Bid_Process_Steps__c where Phoenix_Sub_Step__c = 3];
        bidProcess[0].Phoenix_Status__c = 'In Process';
        update bidProcess;

        Phoenix_PricingReviewApprovals.saveToBid(bid.Id, 'test');
        Phoenix_PricingReviewApprovals.saveToBidBus(bid.Id, 'Approved', 'Business Head');
        Phoenix_PricingReviewApprovals.saveToBidContr(bid.Id, 'Processed', 'Business Head');
        Phoenix_PricingReviewApprovals.getBid(bid.Id);
        Phoenix_PricingReviewApprovals.deleteAttachments(bid1.ContentDocumentId, bid.Id);
        Phoenix_PricingReviewApprovals.getDocs(bid.Id);
        Phoenix_PricingReviewApprovals.makeApprovalsBusiness(bid.Id, 'test', 'Approved', 'Business Head');
        Phoenix_PricingReviewApprovals.makeApprovalsBusiness(bid.Id, 'test', 'Not Approved', 'Business Head');
        //  Phoenix_PricingReviewApprovals.makeApprovalsContracts(bid.Id,'test','Processed','Contracts');
    }

    static testmethod void contractsApproval() {
        Phoenix_Bid__c bid = [SELECT Id FROM Phoenix_Bid__c LIMIT 1];
        Phoenix_PricingReviewApprovals.makeApprovalsContracts(bid.Id, 'test', 'Not Processed', 'Contracts');

    }
}