PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>OTC</fullName>
        <active>true</active>
        <description>OTC Customers</description>
        <label>OTC</label>
    </recordTypes>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_DRL_Sales_External_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Desc__c</fullName>
        <label>Customer Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Hierarchy__c</fullName>
        <label>Customer Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DRL Sales External Summary</relationshipLabel>
        <relationshipName>DRL_Sales_External_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Cutomer_Hierarchy_Code__c</fullName>
        <label>Cutomer Hierarchy Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_DIVISION_DESC__c</fullName>
        <label>DIVISION_DESC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Processed_Date__c</fullName>
        <formula>IF(AND(ISNULL(Vision_month__c) ,ISNULL(Vision_year__c)),null,DATE( VALUE(Vision_year__c) ,IF(LEN(Vision_month__c)== 2,VALUE(Vision_month__c),VALUE(&apos;0&apos;+Vision_month__c)) ,01))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sales__c</fullName>
        <label>Sales Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>QTY Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_customer_code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_direct_qty__c</fullName>
        <label>Direct QTY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_indirect_qty__c</fullName>
        <label>Indirect QTY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_net_sales__c</fullName>
        <label>Net Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_sales_direct__c</fullName>
        <label>Sales Direct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_sales_indirect__c</fullName>
        <label>Sales Indirect</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>DRL Sales External Summary</label>
    <nameField>
        <displayFormat>drl-ext-summ-{0000000}</displayFormat>
        <label>DRL Sales External Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Sales External Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_DRL_Sales_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Direct_Sales__c</fullName>
        <label>Direct Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Direct_Units__c</fullName>
        <label>Direct Units</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Indirect_Sales__c</fullName>
        <label>Indirect Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Indirect_Units__c</fullName>
        <label>Indirect Units</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Desc__c</fullName>
        <label>Customer Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Hierarchy__c</fullName>
        <label>Customer Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DRL Sales Summarys</relationshipLabel>
        <relationshipName>DRL_Sales_Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Cutomer_Hierarchy_Code__c</fullName>
        <label>Cutomer Hierarchy Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_DIVISION_DESC__c</fullName>
        <label>Division Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Is_OTC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is OTC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Is_Rx__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Rx</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Is_SRx__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is SRx</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Processed_Date__c</fullName>
        <label>Processed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Segment__c</fullName>
        <formula>IF( Vision_Is_Rx__c , &apos;Rx&apos;,  IF( Vision_Is_SRx__c , &apos;SRx&apos;, IF( Vision_Is_OTC__c , &apos;OTC&apos;, &apos;&apos;)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_customer_code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRL Sales Summary</label>
    <nameField>
        <displayFormat>DRL Sales Summar-{000000}</displayFormat>
        <label>DRL Sales Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRL Sales Summarys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/VisionDRLSalesSummaryBatchCls.cls
public class VisionDRLSalesSummaryBatchCls implements Database.Batchable < sObject > , Database.Stateful,Schedulable,Database.AllowsCallouts {
    
    public void execute(SchedulableContext sc) {
        //Database.executeBatch(new VisionDRLSalesSummaryBatchCls());
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        delete[select id from Vision_DRL_Sales_Summary__c WHERE CreatedDate != Today limit 200];
       String code = '0011K00002RDd8IQAT';
        String query = 'Select Vision_Customer__r.Name, '+Phoenix_Util.getsObjectFieds('Vision_DRL_Sales_External_Summary__c')+' from Vision_DRL_Sales_External_Summary__c where Vision_Customer__c = :code ORDER BY Vision_Customer_Desc__c,Vision_Processed_Date__c  NULLS LAST';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List < Vision_DRL_Sales_External_Summary__c > externalSalesList) {
        try{
            Map<String, Map<Integer, Vision_DRL_Sales_Summary__c>> finalMap = new Map<String, Map<Integer, Vision_DRL_Sales_Summary__c>>();
            Map<String, Vision_DRL_Sales_Summary__c> summaryRecordsToInsert = new  Map<String, Vision_DRL_Sales_Summary__c>();
             set<String> existingUniqueIds = new set<String>();
            for(Vision_DRL_Sales_External_Summary__c externalSalesRecord: externalSalesList){
                String mapKey = externalSalesRecord.Vision_Cutomer_Hierarchy_Code__c+'-'+externalSalesRecord.Vision_Customer_Desc__c+'-'+externalSalesRecord.Vision_DIVISION_DESC__c+'-'+externalSalesRecord.Vision_Segment__c+'_'+externalSalesRecord.Vision_Processed_Date__c.year();
               
               /* if(Test.isRunningTest()){
                    Vision_DRL_Sales_Summary__c intsales2= new Vision_DRL_Sales_Summary__c();
                    //intsales2.Vision_Customer__c = 'test';
                    intsales2.Vision_Sales__c =165.45;
                    intsales2.Vision_Units__c = 500;
                    intsales2.Vision_Is_OTC__c  = true;
                    //intsales2.Vision_TPT_Dollar__c = 234;
                    intsales2.Vision_Processed_Date__c = system.today()-200;
                    intsales2.Vision_Product_Family__c='Diclofenac Gel';
                    intsales2.Vision_Unique_Identifier__c = intsales2.Id;
            
                    insert intsales2;
                     Map<Integer, Vision_DRL_Sales_Summary__c> oneStepInnerMap1 = new Map<Integer, Vision_DRL_Sales_Summary__c>(); 
                    oneStepInnerMap1.put(1, intsales2);
                    finalMap.put('Test Account-Rx_2021', oneStepInnerMap1);        
                }*/
                
                if(finalMap.containsKey(mapKey)){
					Map<Integer, Vision_DRL_Sales_Summary__c> oneStepInnerMap = finalMap.get(mapKey);
                    if(oneStepInnerMap.containsKey(externalSalesRecord.Vision_Processed_Date__c.month())){
                        Vision_DRL_Sales_Summary__c summaryRec = oneStepInnerMap.get(externalSalesRecord.Vision_Processed_Date__c.month());
                        if(externalSalesRecord.Vision_Segment__c == 'Rx'){
                            summaryRec.Vision_Is_Rx__c = true;
                         } else if(externalSalesRecord.Vision_Segment__c == 'SRx'){
                            summaryRec.Vision_Is_SRx__c = true;
                        } else if(externalSalesRecord.Vision_Segment__c == 'OTC'){
                            summaryRec.Vision_Is_OTC__c =  true;
                        }
                        summaryRec.Vision_Customer__c = externalSalesRecord.Vision_Customer__c;
                        summaryRec.Vision_Processed_Date__c = externalSalesRecord.Vision_Processed_Date__c;
                        summaryRec.Vision_Sales__c = summaryRec.Vision_Sales__c+externalSalesRecord.Vision_net_sales__c;
                        summaryRec.Vision_Units__c = summaryRec.Vision_Units__c+externalSalesRecord.Vision_Units__c;
                        summaryRec.Direct_Sales__c = summaryRec.Direct_Sales__c+externalSalesRecord.Vision_sales_direct__c;
                        summaryRec.Direct_Units__c = summaryRec.Direct_Units__c+externalSalesRecord.Vision_direct_qty__c;
                        summaryRec.Indirect_Sales__c = summaryRec.Indirect_Sales__c+externalSalesRecord.Vision_sales_indirect__c;
                        summaryRec.Indirect_Units__c = summaryRec.Indirect_Units__c+externalSalesRecord.Vision_indirect_qty__c;
                        summaryRec.Vision_Product_Family__c = externalSalesRecord.Vision_Product_Family__c;
                        summaryRec.Vision_Cutomer_Hierarchy_Code__c = externalSalesRecord.Vision_Cutomer_Hierarchy_Code__c;
                        summaryRec.Vision_Customer_Hierarchy__c = externalSalesRecord.Vision_Customer_Hierarchy__c;
                        summaryRec.Vision_Customer_Desc__c = externalSalesRecord.Vision_Customer_Desc__c;
                        summaryRec.Vision_customer_code__c = externalSalesRecord.Vision_customer_code__c;
                        summaryRec.Vision_Category__c = externalSalesRecord.Vision_Category__c;
                        summaryRec.Vision_DIVISION_DESC__c=externalSalesRecord.Vision_DIVISION_DESC__c;
                        summaryRec.Vision_Unique_Identifier__c = mapKey+'_'+externalSalesRecord.Vision_Processed_Date__c.month();
                     } 
                    else{
                        Vision_DRL_Sales_Summary__c newSummaryRec = new Vision_DRL_Sales_Summary__c();
                        if(externalSalesRecord.Vision_Segment__c == 'Rx' || externalSalesRecord.Vision_Segment__c == 'RX'){
                            newSummaryRec.Vision_Is_Rx__c = true;
                        } else if(externalSalesRecord.Vision_Segment__c == 'SRx' || externalSalesRecord.Vision_Segment__c == 'SRX'){
                            newSummaryRec.Vision_Is_SRx__c = true;
                        } else if(externalSalesRecord.Vision_Segment__c == 'OTC'){
                            newSummaryRec.Vision_Is_OTC__c =  true;
                        }
                        newSummaryRec.Vision_Customer__c = externalSalesRecord.Vision_Customer__c;
                        newSummaryRec.Vision_Processed_Date__c = externalSalesRecord.Vision_Processed_Date__c;
                        newSummaryRec.Vision_Sales__c = externalSalesRecord.Vision_net_sales__c;
                        newSummaryRec.Vision_Units__c = externalSalesRecord.Vision_Units__c;
                        newSummaryRec.Direct_Sales__c = externalSalesRecord.Vision_sales_direct__c;
                        newSummaryRec.Direct_Units__c = externalSalesRecord.Vision_direct_qty__c;
                        newSummaryRec.Indirect_Sales__c = externalSalesRecord.Vision_sales_indirect__c;
                        newSummaryRec.Indirect_Units__c = externalSalesRecord.Vision_indirect_qty__c;
                        newSummaryRec.Vision_Product_Family__c = externalSalesRecord.Vision_Product_Family__c;
                        newSummaryRec.Vision_Cutomer_Hierarchy_Code__c = externalSalesRecord.Vision_Cutomer_Hierarchy_Code__c;
                        newSummaryRec.Vision_Customer_Hierarchy__c = externalSalesRecord.Vision_Customer_Hierarchy__c;
                        newSummaryRec.Vision_Customer_Desc__c = externalSalesRecord.Vision_Customer_Desc__c;
                        newSummaryRec.Vision_customer_code__c = externalSalesRecord.Vision_customer_code__c;
                        newSummaryRec.Vision_Category__c = externalSalesRecord.Vision_Category__c;
                         newsummaryRec.Vision_DIVISION_DESC__c=externalSalesRecord.Vision_DIVISION_DESC__c;
                        newSummaryRec.Vision_Unique_Identifier__c = mapKey+'_'+externalSalesRecord.Vision_Processed_Date__c.month();
                        oneStepInnerMap.put(externalSalesRecord.Vision_Processed_Date__c.month(), newSummaryRec);
                     }
                    
                } 
                else{
                    Vision_DRL_Sales_Summary__c newSummaryRec = new Vision_DRL_Sales_Summary__c();
                    if(externalSalesRecord.Vision_Segment__c == 'Rx' || externalSalesRecord.Vision_Segment__c == 'RX'){
                            newSummaryRec.Vision_Is_Rx__c = true;
                        } else if(externalSalesRecord.Vision_Segment__c == 'SRx' || externalSalesRecord.Vision_Segment__c == 'SRX'){
                            newSummaryRec.Vision_Is_SRx__c = true;
                        } else if(externalSalesRecord.Vision_Segment__c == 'OTC'){
                            newSummaryRec.Vision_Is_OTC__c =  true;
                        }
                    newSummaryRec.Vision_Customer__c = externalSalesRecord.Vision_Customer__c;
                    newSummaryRec.Vision_Processed_Date__c = externalSalesRecord.Vision_Processed_Date__c;
                    newSummaryRec.Vision_Sales__c = externalSalesRecord.Vision_net_sales__c;
                    newSummaryRec.Vision_Units__c = externalSalesRecord.Vision_Units__c;
                    newSummaryRec.Direct_Sales__c = externalSalesRecord.Vision_sales_direct__c;
                    newSummaryRec.Direct_Units__c = externalSalesRecord.Vision_direct_qty__c;
                    newSummaryRec.Indirect_Sales__c = externalSalesRecord.Vision_sales_indirect__c;
                    newSummaryRec.Indirect_Units__c = externalSalesRecord.Vision_indirect_qty__c;
                    newSummaryRec.Vision_Cutomer_Hierarchy_Code__c = externalSalesRecord.Vision_Cutomer_Hierarchy_Code__c;
                    newSummaryRec.Vision_Customer_Hierarchy__c = externalSalesRecord.Vision_Customer_Hierarchy__c;
                    newSummaryRec.Vision_Customer_Desc__c = externalSalesRecord.Vision_Customer_Desc__c;
                    newSummaryRec.Vision_Category__c = externalSalesRecord.Vision_Category__c;
                    newSummaryRec.Vision_customer_code__c = externalSalesRecord.Vision_customer_code__c;
                     newsummaryRec.Vision_DIVISION_DESC__c=externalSalesRecord.Vision_DIVISION_DESC__c;
                    newSummaryRec.Vision_Unique_Identifier__c = mapKey+'_'+externalSalesRecord.Vision_Processed_Date__c.month();
                    Map<Integer, Vision_DRL_Sales_Summary__c> oneStepInnerMap = new Map<Integer, Vision_DRL_Sales_Summary__c>();
                    oneStepInnerMap.put(externalSalesRecord.Vision_Processed_Date__c.month(), newSummaryRec);
                    finalMap.put(mapKey, oneStepInnerMap);
                }
                
            
                if(finalMap.size() > 0){
                    for(String custKey: finalMap.keySet()){
                        Map<Integer, Vision_DRL_Sales_Summary__c> custSpecificData = finalMap.get(custKey);
                        for(Integer monthKey: custSpecificData.keySet()){
                            existingUniqueIds.add(custSpecificData.get(monthKey).Vision_Unique_Identifier__c);
                            summaryRecordsToInsert.put(custSpecificData.get(monthKey).Vision_Unique_Identifier__c, custSpecificData.get(monthKey));
                        }
                    }
                }
            }
            for(Vision_DRL_Sales_Summary__c intDRLSalesRec : [select Id,Vision_Sales__c,Direct_Sales__c,Direct_Units__c,Indirect_Sales__c,Indirect_Units__c,Vision_Units__c,Vision_Unique_Identifier__c From Vision_DRL_Sales_Summary__c Where Vision_Unique_Identifier__c in : existingUniqueIds]){
                if(intDRLSalesRec.Vision_Unique_Identifier__c!=null && summaryRecordsToInsert.containsKey(intDRLSalesRec.Vision_Unique_Identifier__c)){
                if( intDRLSalesRec.Id != null){
                summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Id = intDRLSalesRec.Id;
                }
                if(summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Sales__c != null && intDRLSalesRec.Vision_Sales__c != null){
               
                summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Sales__c = summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Sales__c + intDRLSalesRec.Vision_Sales__c;
                }
                if(summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Units__c != null && intDRLSalesRec.Vision_Units__c != null){
                    summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Units__c = summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_Units__c + intDRLSalesRec.Vision_Units__c;
                }
                }
               //    summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_TPT_Percent__c = summaryRecordsToInsert.get(intDRLSalesRec.Vision_Unique_Identifier__c).Vision_TPT_Percent__c + intDRLSalesRec.Vision_TPT_Percent__c;
            }
            if(summaryRecordsToInsert.size() > 0){
                for(String key : summaryRecordsToInsert.keySet()){
                  }
                upsert summaryRecordsToInsert.values();
            //insert summaryRecordsToInsert.values();
            }
        }catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'VisionDRLSalesSummaryBatchCls', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
        
    }
    
    public void finish(Database.BatchableContext BC) {}
   
}