PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>RX</fullName>
        <active>true</active>
        <description>Used for All RX Team Accounts</description>
        <label>RX</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Status__c</fullName>
        <formula>IF(ISBLANK(Phoenix_Contract_End_Date__c),&quot;&quot;,IF(Phoenix_Contract_End_Date__c &lt; TODAY(),&quot;Expired&quot;, &quot;Active&quot; ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Is_Cus_Prd_Tracker_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Field will be checked when Customer Product Tracker record is created</description>
        <label>Is Customer Product Tracker Created</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Is_Exclude_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Is Exclude Bid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Private_Label_OTC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Private Label</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Product Director</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Marketing</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Rx_SRx_OTC__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Rx/SRx/OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OTC</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>SRx</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product_Family__c.object
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Product Trackers (Product Family)</relationshipLabel>
        <relationshipName>Customer_Product_Trackers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Created_Date__c</fullName>
        <label>Contract Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Name__c</fullName>
        <label>Contract Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Product_Status__c</fullName>
        <label>Contract Product Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Is_True_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is True Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Created_Date__c</fullName>
        <label>Product Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Director__c</fullName>
        <label>Product Director</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <formula>Vision_Product_Code__c+&quot;_&quot;+Vision_Contract_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Identifier</label>
        <type>Text</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/CustomerProductActiveContractsBatchCls.cls
/*
 We will create cpt records from Active Contracts 
 */
public class CustomerProductActiveContractsBatchCls implements Database.Batchable < sObject > , Database.Stateful,Schedulable,Database.AllowsCallouts {
    public void execute(SchedulableContext sc) {        Database.executeBatch(new CustomerProductActiveContractsBatchCls());
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //Query - If a New Account has become bid account in last 24 Hours
        //String query = 'Select '+Phoenix_Util.getsObjectFieds('Phoenix_Contract__c')+' from Phoenix_Contract__c where Phoenix_Contract_Status__c =\'Active\' AND CreatedDate = LAST_N_DAYS:1';
        String query = 'Select Phoenix_Customer__r.Name,Phoenix_Customer__r.AccountNumber,'+Phoenix_Util.getsObjectFieds('Phoenix_Contract__c')+' from Phoenix_Contract__c where Phoenix_Contract_Status__c =\'Active\' AND Phoenix_Contract_Number__c != null';
      if(Test.isRunningTest())query += ' LIMIT 1';
	  return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List <Phoenix_Contract__c> contractList) {
        try{
            if(contractList.size() > 0){
                list<Vision_Customer_Product_Tracker__c> cusPrdTrackerRecs = new list<Vision_Customer_Product_Tracker__c>();
                //Update Contract level Checkbox Customer Product Tracker records Created as True
                Map<String,Phoenix_Contract__c> existingCntrMap = new Map<String,Phoenix_Contract__c>();
                for(Phoenix_Contract__c cntr : contractList){
					cntr.Vision_Is_Cus_Prd_Tracker_Created__c = true;
                    existingCntrMap.put(cntr.Phoenix_Contract_Number__c,cntr);
                }
                //Create All Customer Product Tracker records for all products
                String query = 'Select Id,ProductCode,createdDate,Family,Description,Name,Phoenix_Rx_SRx_OTC__c,Phoenix_Product_Director__r.Name from Product2 where IsActive = true AND Phoenix_Is_Exclude_Bid__c = false AND ProductCode != null AND ((Phoenix_Rx_SRx_OTC__c = \'Rx\' or Phoenix_Rx_SRx_OTC__c = \'SRx\') or Phoenix_Is_Private_Label_OTC__c = false) LIMIT 30000';
                Map<String,Product2> existingPrdMap = new Map<String,Product2>();
                for(Product2 prd:Database.query(query))                   
                    existingPrdMap.put(prd.ProductCode,prd);
                
                Set<String> UnqFormIds = new Set<String>();
                for(String prdCode : existingPrdMap.keySet()){
                    for(String cntrNum : existingCntrMap.keySet()){                       
                        String unqId = prdCode+'_'+cntrNum;                       
                        UnqFormIds.add(unqId);
                    }
                }
                
                List<String> existingCusPrdTrkRecs = new List<String>();
                for(Vision_Customer_Product_Tracker__c cusRec : [select Vision_Unique_Identifier__c from Vision_Customer_Product_Tracker__c Where Vision_Unique_Identifier__c in : UnqFormIds])                    existingCusPrdTrkRecs.add(cusRec.Vision_Unique_Identifier__c);
                
                for(String unqId : UnqFormIds){
                    if(!existingCusPrdTrkRecs.contains(unqId)){
                        List<String> unqSepList = unqId.split('_');
                        Vision_Customer_Product_Tracker__c cusPrdTrk = new Vision_Customer_Product_Tracker__c();
                        if(existingCntrMap.containsKey(unqSepList[1])){
                            if(unqSepList[1].startsWith('3000')){                               
                                cusPrdTrk.Vision_Contract_Type__c='Indirect';
                            }
                            else if(unqSepList[1].startsWith('1000')){                               
                                cusPrdTrk.Vision_Contract_Type__c='Direct';
                            }
                            cusPrdTrk.Vision_Contract__c = existingCntrMap.get(unqSepList[1]).Id;
                            cusPrdTrk.Vision_Contract_Number__c = unqSepList[1];
                            cusPrdTrk.Vision_Contract_Created_Date__c = existingCntrMap.get(unqSepList[1]).createdDate;
                            cusPrdTrk.Vision_Contract_Name__c = existingCntrMap.get(unqSepList[1]).Name;
                            if(existingCntrMap.get(unqSepList[1]).Phoenix_Customer__c != null){
                                cusPrdTrk.Vision_Account__c = existingCntrMap.get(unqSepList[1]).Phoenix_Customer__c;
                                cusPrdTrk.Vision_Customer_Name__c = existingCntrMap.get(unqSepList[1]).Phoenix_Customer__r.Name;
                                cusPrdTrk.Vision_Customer_Code__c = existingCntrMap.get(unqSepList[1]).Phoenix_Customer__r.AccountNumber;
                            }
                        }
                        system.debug('existingprdmap...>'+existingPrdMap.keyset());
                        system.debug('unqsew'+unqSepList[0]);
                        if(existingPrdMap.containsKey(unqSepList[0])){
                            cusPrdTrk.Vision_Product__c = existingPrdMap.get(unqSepList[0]).Id;
                            cusPrdTrk.Vision_Product_Code__c = unqSepList[0];
                            cusPrdTrk.Vision_Product_Created_Date__c = existingPrdMap.get(unqSepList[0]).createdDate;
                            cusPrdTrk.Vision_Product_Description__c = existingPrdMap.get(unqSepList[0]).Description;
                            cusPrdTrk.Vision_Product_Director__c = existingPrdMap.get(unqSepList[0]).Phoenix_Product_Director__r.Name;
                            cusPrdTrk.Vision_Product_Name__c = existingPrdMap.get(unqSepList[0]).Name;
                            cusPrdTrk.Product_Family__c = existingPrdMap.get(unqSepList[0]).Product_Family__c;
                        }
                        cusPrdTrk.Vision_Contract_Product_Status__c = 'True Opportunity';
                        cusPrdTrk.Vision_Is_True_Opportunity__c = True;
                        cusPrdTrackerRecs.add(cusPrdTrk);
                    }
                }
                insert cusPrdTrackerRecs;
                update contractList;
            }
        }
        Catch(Exception e) {            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'CustomerProductActiveContractsBatchCls', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
    public void finish(Database.BatchableContext BC) {
     if(!Test.isRunningTest())  
         Database.executeBatch(new CustomerContractOTCPrdCreatorBatchCls(),1);
    }
    
}