PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <inlineHelpText>Contract Number is populated from NPR when a Customer is created</inlineHelpText>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Bid_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick to make the customer visible for Bid Creation</inlineHelpText>
        <label>Is Bid Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>NPR Data</relationshipLabel>
        <relationshipName>NPR_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Phoenix_GR_TrackingTier__c</fullName>
        <label>GR% (TrackingTier)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Phoenix_VIR_History_Batch_Test.cls
/**
 * @description       : 
 * @author            : Surender Patel (Dhruvsoft)
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
@isTest
public class Phoenix_VIR_History_Batch_Test {
    static testmethod void test1() {

        Account acc = new Account(name = 'Test Account',Phoenix_Is_Bid_Account__c=true);
        acc.Phoenix_Contract_Number__c = '1234';
        acc.Phoenix_Is_Bid_Account__c=True;
        Account acc2 = new Account(name = 'Test Account2');
        acc2.Phoenix_Contract_Number__c = '1234567';
        acc2.Phoenix_Is_Bid_Account__c = True;
        List < Account > accountList = new List < Account > {
            acc,
            acc2
        };
        Insert accountList;
        Phoenix_Contract__c cont = new Phoenix_Contract__c(name = 'Test contract');
        cont.Phoenix_Customer__c = acc.Id;
        cont.Phoenix_Contract_Number__c = '1234';
        Insert cont;
        Phoenix_NPR_Data__c npr1 = new Phoenix_NPR_Data__c();
        npr1.Phoenix_Account__c = acc.Id;
        npr1.Phoenix_Contract__c = cont.Id;
        npr1.Phoenix_GR_TrackingTier__c = 15;
        Phoenix_NPR_Data__c npr2 = new Phoenix_NPR_Data__c();
        npr2.Phoenix_Account__c = acc.Id;
        npr2.Phoenix_Contract__c = cont.Id;
        npr2.Phoenix_GR_TrackingTier__c = 20;
        Phoenix_NPR_Data__c npr3 = new Phoenix_NPR_Data__c();
        npr3.Phoenix_Account__c = acc2.Id;
        npr3.Phoenix_Contract__c = cont.Id;
        npr3.Phoenix_GR_TrackingTier__c = 25;
        List < Phoenix_NPR_Data__c > nprdata = new List < Phoenix_NPR_Data__c > {
            npr1,
            npr2,
            npr3
        };
        Insert nprdata;
        Test.startTest();
        Phoenix_VIR_History_Batch virHistoryBatch = new Phoenix_VIR_History_Batch();
        virHistoryBatch.execute(null);
        Database.executeBatch(new Phoenix_VIR_History_Batch(), 200);
        Test.stopTest();
    }

}