PCS BAckup 26Dec2023/Backup-Source/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Phoenix_NDC_Change_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NDC Change Line Items</relationshipLabel>
        <relationshipName>NDC_Change_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NDC Change Line Item</label>
    <nameField>
        <displayFormat>NDCChangeLineItem-{000000}</displayFormat>
        <label>NDC Change Line Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NDC Change Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Offer_Template__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Offer Templates</relationshipLabel>
        <relationshipName>Offer_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Related_To__c</fullName>
        <label>Related To</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bid Template</fullName>
                </value>
                <value>
                    <fullName>NDC Change</fullName>
                </value>
                <value>
                    <fullName>WAC Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_VF_Page_Name__c</fullName>
        <label>VF Page Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Offer Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_WAC_Change_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WAC Change Line Items</relationshipLabel>
        <relationshipName>WAC_Change_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WAC Change Line Item</label>
    <nameField>
        <displayFormat>WAC Change Line-{000000}</displayFormat>
        <label>WAC Change Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WAC Change Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Phoenix_OfferGenerationDocumentCls.cls
/**
 * @description       : 
 * @author            : Surender Patel (Dhruvsoft)
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
public class Phoenix_OfferGenerationDocumentCls {
    //static Map<id,integer> DocumentNameVersioningList=new map<id,integer>();

    public Phoenix_OfferGenerationDocumentCls() {}
    /*public Phoenix_Bid__c bid{get;set;}
public user currentuser{get;set;}
public Phoenix_OfferGenerationDocumentCls(string bidId, String selectedProductFamily){
currentuser=[Select Id,Name,Email,Title from User where Id=:userinfo.getuserId()];
if(BidId != null)  bid=[SELECT Id, Name, Phoenix_Customer__c, Phoenix_Customer__r.Name, Phoenix_Customer__r.City__c, Phoenix_Customer__r.State__c, Phoenix_Customer__r.Zip__c,Phoenix_Customer__r.Street_Address_1__c FROM Phoenix_Bid__c  WHERE ID=:BidId LIMIT 1];
}*/

    @AuraEnabled
    public static String generateDocument(Id bidId, string templateName, string offerDocumentName, string productFamily, string relatedTo, string customerId) {
        try {
            PageReference pdf = new PageReference('/apex/' + templateName);

            String parentId = bidId; // add parent id to the parameters for standardcontroller
            pdf.getParameters().put('BidId', bidId);
            pdf.getParameters().put('productFamily', productFamily);
            pdf.getParameters().put('relatedTo', relatedTo);
            pdf.getParameters().put('customerId', customerId);
            List < Attachment > atchList = [Select Id, ParentId, Name from Attachment where ParentId =: bidId];

            // create the new attachment
            Attachment attach = new Attachment();
            // the contents of the attachment from the pdf
            Blob body;

            try {

                // returns the output of the page as a PDF
                body = pdf.getContent();

                // need to pass unit test -- current bug	
            } catch (VisualforceException e) {
                body = Blob.valueOf('Error at: ' + e.getLineNumber() + 'Message: ' + e.getMessage());

            }

            attach.Body = body;
            // add the user entered name


            if (atchList.size() > 0) {
                attach.Name = offerDocumentName + '.doc';
            } else {
                attach.Name = offerDocumentName + '.doc';
            }
            attach.IsPrivate = false;
            // attach the pdf to the account
            attach.ParentId = parentId;
            attach.ContentType = 'application/msword';
            insert attach;
        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'Phoenix_SubmitBidForApprovalCtrl', Phoenix_Method_Name__c = 'calculateFinanceGrid', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
        return 'Success';
    }

    public static Map < string, List < Phoenix_Bid_Line_Item__c >> mapOfProductFamily {
        get;
        set;
    }

    @AuraEnabled
    public static offerDocWrapper getOfferTemplates(String customerId, Id bidId) {

        offerDocWrapper docWrapper = new offerDocWrapper();
        Set < string > setOfLineItemsFamilies = new Set < string > ();
        List < string > listOfLineItemsFamilies = new List < string > ();
        mapOfProductFamily = new Map < string, List < Phoenix_Bid_Line_Item__c >> ();
        try {
            List < Phoenix_Offer_Template__c > offTemp;
            List < Phoenix_Offer_Template__c > QueryoffTemp = [SELECT Id, Name, Phoenix_Account__c, Phoenix_VF_Page_Name__c, Phoenix_Related_To__c FROM Phoenix_Offer_Template__c WHERE Phoenix_Account__r.Id =: customerId AND Phoenix_Related_To__c=:'Bid Template' ORDER BY Name ASC];
            if(QueryoffTemp.size() > 0){
                offTemp=QueryoffTemp;
            }
            else{
                offTemp=[SELECT Id, Name, Phoenix_Account__c, Phoenix_VF_Page_Name__c, Phoenix_Related_To__c FROM Phoenix_Offer_Template__c WHERE Phoenix_Account__c = null AND Phoenix_Related_To__c=:'Bid Template' ORDER BY Name ASC];
            }
            List < Phoenix_Bid__c > bidInfo = [SELECT Id, Name, Phoenix_Bid_Type__c, Phoenix_Bid_Name__c, Phoenix_Customer__c, Phoenix_Approval_Status__c, Phoenix_Customer__r.Name FROM Phoenix_Bid__c WHERE ID =: bidId LIMIT 1];

            List < Phoenix_Bid_Line_Item__c > lineItemsInfo;
            if (bidInfo[0].Phoenix_Bid_Type__c == 'Volume Review Only') {
                lineItemsInfo = [SELECT Id, Name, Product_Family__c, Product_Family_Name__c,Product_Family__r.Name, Phoenix_Product_Family__c, Phoenix_Product__r.Name, Phoenix_Bid__c, Phoenix_Product__c, Phoenix_Product__r.Phoenix_API_Supplier_Name__c, Phoenix_Product__r.Phoenix_FEI_of_API_Manufacturing_Site__c, Phoenix_Product__r.Phoenix_FEI_of_Finished_Goods_MFR__c FROM Phoenix_Bid_Line_Item__c WHERE Phoenix_Bid__r.Id =: bidId AND(Phoenix_SCM_Approval_Y_N__c =: 'Y- Only Current Monthly Demand Approved'
                    OR Phoenix_SCM_Approval_Y_N__c =: 'Y- Current + Inc Demand Approved')];
            } else {
                lineItemsInfo = [SELECT Id, Name, Product_Family__c,Product_Family_Name__c, Product_Family__r.Name, Phoenix_Product_Family__c, Phoenix_Product__r.Name, Phoenix_Bid__c, Phoenix_Product__c, Phoenix_Product__r.Phoenix_API_Supplier_Name__c, Phoenix_Product__r.Phoenix_FEI_of_API_Manufacturing_Site__c, Phoenix_Product__r.Phoenix_FEI_of_Finished_Goods_MFR__c FROM Phoenix_Bid_Line_Item__c WHERE Phoenix_Bid__r.Id =: bidId AND Phoenix_Finance_Approval__c =: 'Approved'];
            }
              if(bidInfo[0].Phoenix_Bid_Type__c == 'Initial Order Discount for WAC Customers (No-Contract Price Offering)'){
                offTemp=[SELECT Id, Name, Phoenix_Account__c, Phoenix_VF_Page_Name__c, Phoenix_Related_To__c FROM Phoenix_Offer_Template__c WHERE Phoenix_Account__c = null AND Phoenix_Related_To__c=:'Bid Template' AND (Phoenix_VF_Page_Name__c ='IOD_Stocking_Dis_With_ShelfLife' OR Phoenix_VF_Page_Name__c ='IOD_Stocking_Discount_Normal' OR Phoenix_VF_Page_Name__c ='IOD_Mck_Stocking_Allowance' OR Phoenix_VF_Page_Name__c ='IOD_Cardinal_GWSA_Template' OR Phoenix_VF_Page_Name__c ='IOD_Cardinal_NonGWSA_Template') ORDER BY Name ASC];
            }
            string defaultOfferDocumentName;
            //
            //if(DocumentNameVersioningList.containsKey(bidId)){
            //
            // Integer bytes = DocumentNameVersioningList.get(bidId);
            //  defaultOfferDocumentName = 'Offer-'+bidInfo[0].Name+'-'+bidInfo[0].Phoenix_Customer__r.Name+'-'+bidInfo[0].Phoenix_Bid_Type__c+'-'+Date.today().format()+' V'+bytes;
            // DocumentNameVersioningList.put(bidId,bytes);


            //}
            //else{
            defaultOfferDocumentName = 'Offer-' + bidInfo[0].Name + '-' + bidInfo[0].Phoenix_Customer__r.Name + '-' + bidInfo[0].Phoenix_Bid_Type__c + '-' + Date.today().format();

            //DocumentNameVersioningList.put(bidId,1);


            //  }
            for (Phoenix_Bid_Line_Item__c item: lineItemsInfo) {
                //lineItemsIds.add(item.Id);
                setOfLineItemsFamilies.add(item.Product_Family_Name__c);
            }
            for (string item: setOfLineItemsFamilies) {
                listOfLineItemsFamilies.add(item);
            }



            docWrapper.offTemp = offTemp;
            docWrapper.offerDefaultName = defaultOfferDocumentName;
            docWrapper.lineItems = lineItemsInfo;
            docWrapper.listOfLineItemsFamilies = listOfLineItemsFamilies;

        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'Phoenix_SubmitBidForApprovalCtrl', Phoenix_Method_Name__c = 'calculateFinanceGrid', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
        return docWrapper;
    }


    @AuraEnabled
    public static offerDocWrapper getNDCOfferTemplates(Id ndcId) {

        offerDocWrapper docWrapper = new offerDocWrapper();
        Set < string > setOfLineItemsFamilies = new Set < string > ();
        List < string > listOfLineItemsFamilies = new List < string > ();
        Set<Id> setOfLineItemsCustomers = new Set<Id>();
        try {
            List < Phoenix_Offer_Template__c > offTemp = [SELECT Id, Name, Phoenix_Account__c, Phoenix_VF_Page_Name__c, Phoenix_Related_To__c FROM Phoenix_Offer_Template__c WHERE Phoenix_Related_To__c=:'NDC Change' ORDER BY Name ASC];
            List < Phoenix_NDC_Change__c > ndcInfo = [SELECT Id, Name FROM Phoenix_NDC_Change__c WHERE ID =: ndcId LIMIT 1];

            List < Phoenix_NDC_Change_Line_Item__c > lineItemsInfo;
            lineItemsInfo = [SELECT Id, Name, Phoenix_Account__c, Phoenix_Current_Product__r.Product_Family__c, Phoenix_Current_Product__r.Product_Family__r.Name, Phoenix_Current_Product__r.Family FROM Phoenix_NDC_Change_Line_Item__c WHERE Phoenix_NDC_Change__c =: ndcId AND Phoenix_Finance_Approval__c =: 'Approved'];
            string defaultOfferDocumentName;
            //
            //if(DocumentNameVersioningList.containsKey(bidId)){
            //
            // Integer bytes = DocumentNameVersioningList.get(bidId);
            //  defaultOfferDocumentName = 'Offer-'+bidInfo[0].Name+'-'+bidInfo[0].Phoenix_Customer__r.Name+'-'+bidInfo[0].Phoenix_Bid_Type__c+'-'+Date.today().format()+' V'+bytes;
            // DocumentNameVersioningList.put(bidId,bytes);


            //}
            //else{
            defaultOfferDocumentName = 'Offer-' + ndcInfo[0].Name+'-' + Date.today().format();

            //DocumentNameVersioningList.put(bidId,1);


            //  }
            for (Phoenix_NDC_Change_Line_Item__c item: lineItemsInfo) {
                //lineItemsIds.add(item.Id);
                setOfLineItemsFamilies.add(item.Phoenix_Current_Product__r.Product_Family__r.Name);
                setOfLineItemsCustomers.add(item.Phoenix_Account__c);
            }
            for (string item: setOfLineItemsFamilies) {
                listOfLineItemsFamilies.add(item);
            }
            List<Account> customers = [select Id, Name from Account where Id =: setOfLineItemsCustomers];


            docWrapper.offTemp = offTemp;
            docWrapper.offerDefaultName = defaultOfferDocumentName;
            docWrapper.ndcLineItems = lineItemsInfo;
            docWrapper.listOfLineItemsFamilies = listOfLineItemsFamilies;
            docWrapper.listOfLineItemsAccounts = customers;

        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'Phoenix_SubmitBidForApprovalCtrl', Phoenix_Method_Name__c = 'calculateFinanceGrid', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
        return docWrapper;
    }

    public class offerDocWrapper {
        @AuraEnabled public List < Phoenix_Offer_Template__c > offTemp;
        @AuraEnabled public List < Phoenix_Bid__c > bidInfo;
        @AuraEnabled public List < Phoenix_WAC_Change__c > wacInfo;
        @AuraEnabled public List < Phoenix_NDC_Change__c > ndcInfo;
        @AuraEnabled public List < string > listOfLineItemsFamilies;
        @AuraEnabled public List < Account > listOfLineItemsAccounts;
        @AuraEnabled public List < Phoenix_Bid_Line_Item__c > lineItems;
        @AuraEnabled public List < Phoenix_WAC_Change_Line_Item__c > wacLineItems;
        @AuraEnabled public List < Phoenix_NDC_Change_Line_Item__c > ndcLineItems;
        @AuraEnabled public string offerDefaultName;

        offerDocWrapper() {
            offTemp = new List < Phoenix_Offer_Template__c > ();
            listOfLineItemsFamilies = new List < string > ();
            lineItems = new List < Phoenix_Bid_Line_Item__c > ();
            bidInfo = new List < Phoenix_Bid__c > ();
            wacInfo = new List < Phoenix_WAC_Change__c > ();
            wacLineItems = new List < Phoenix_WAC_Change_Line_Item__c > ();
            ndcInfo = new List < Phoenix_NDC_Change__c > ();
            ndcLineItems = new List < Phoenix_NDC_Change_Line_Item__c > ();
            listOfLineItemsAccounts = new List < Account >();
            offerDefaultName = '';
        }
    }


}