PCS BAckup 26Dec2023/Backup-Source/objects/GCP_Product_Family_Map__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SULFADIAZINE 1 CREAM</fullName>
                </value>
                <value>
                    <fullName>HABITROL PATCH</fullName>
                </value>
                <value>
                    <fullName>FENOFIBRATE CAPS</fullName>
                </value>
                <value>
                    <fullName>RANITIDINE CAPS</fullName>
                </value>
                <value>
                    <fullName>FEBUXOSTAT</fullName>
                </value>
                <value>
                    <fullName>PEMETREXED DISODIUM LYO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Product_Family__c</fullName>
        <label>SFDC Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SSD Cream</fullName>
                </value>
                <value>
                    <fullName>Fenofibrate Capsules</fullName>
                </value>
                <value>
                    <fullName>Ranitidine Caps</fullName>
                </value>
                <value>
                    <fullName>Febuxostat</fullName>
                </value>
                <value>
                    <fullName>Naproxen Sodium</fullName>
                </value>
                <value>
                    <fullName>Pemetrexed for Injection</fullName>
                </value>
                <value>
                    <fullName>Fesoterodine</fullName>
                </value>
                <value>
                    <fullName>Sorafenib</fullName>
                </value>
                <value>
                    <fullName>Nicotine Lozenge Original</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GCP Product Family Map</label>
    <nameField>
        <displayFormat>GCPFamilyMap-{0000000}</displayFormat>
        <label>GCP Product Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Product Family Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family_Map__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Product Family Map</label>
        <referenceTo>GCP_Product_Family_Map__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_GCN_Sequence_Number__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GCN Sequence Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_GPI_Generic_Product_Identifier__c</fullName>
        <description>It contains 14 characters.</description>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>GPI (Generic Product Identifier)  </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC_11__c</fullName>
        <inlineHelpText>National Drug Code: (Auto -generated field)</inlineHelpText>
        <label>NDC - 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <inlineHelpText>National Drug Code: SAP field</inlineHelpText>
        <label>NDC - 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product_Family__c.object
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_GCP_Backorder_OTC__c.object
<CustomObject>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Average_Forecast__c</fullName>
        <label>Average Forecast</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Back_Order_Value__c</fullName>
        <label>Back Order Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Backorder_Qty__c</fullName>
        <label>Backorder Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Backorder_Report_Date__c</fullName>
        <label>Backorder Report Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vision_Count__c</fullName>
        <label>Count</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Current_Month_Total_Monthly_Order__c</fullName>
        <label>Current Month Total Monthly Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Current_Order_Qty__c</fullName>
        <label>Current Order Qty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Gcp_Update_Date__c</fullName>
        <label>GCP Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_MoH__c</fullName>
        <label>MoH</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Order_Value__c</fullName>
        <label>Order Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Vision_GCP_Backorder_OTC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Short_Term_Forecast__c</fullName>
        <label>Short Term Forecast</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Sku_Code__c</fullName>
        <label>Sku_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Total_Open_Order_Qty__c</fullName>
        <label>Total Open Order Qty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Unit_Sales_Value__c</fullName>
        <label>Unit Sales Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_current_month__c</fullName>
        <label>Current Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_last_month_forecast__c</fullName>
        <label>Last Month Forecast</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP Backorder OTC</label>
    <nameField>
        <displayFormat>backorder-OTC-{0000000}</displayFormat>
        <label>GCP Backorder OTC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Backorder OTCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/GoogleBackOrderOTCFetchTest.cls
@istest
public class GoogleBackOrderOTCFetchTest {
    static testmethod void setup(){
        
        Account a= new Account();
        a.name='test';
        a.AccountNumber='123456';
        insert a;
        Account a1= new Account();
        a1.name='test1';
        a1.AccountNumber=null;
        insert a1;
        Product2 p=new Product2();
        p.Name='abc pharma';
        p.Phoenix_NDC_11__c='23364848';
        p.ProductCode='123566';
        p.Phoenix_NDC__c='5555555';
        p.Phoenix_GPI_Generic_Product_Identifier__c = '11111';
        p.Family = 'Test Family';
        p.Phoenix_Throughput_cost__c=10.23456576;
        p.Phoenix_GCN_Sequence_Number__c='666666';
        p.Phoenix_Pkg_Size__c=25.0;
        insert p;
        GCP_Product_Family_Map__c gcpf= new GCP_Product_Family_Map__c();
        gcpf.SFDC_Product_Family__c='A';
        gcpf.GCP_Product_Family__c='A';
        insert gcpf;
        Vision_GCP_Backorder_OTC__c borx = new Vision_GCP_Backorder_OTC__c();
        borx.Product_Family__c='A';
       // borx.Vision_Average_Forecast__c=23.0;
       // borx.Vision_Back_Order_Value__c=23;
        borx.Vision_Backorder_Qty__c=24;
        borx.Vision_Comments__c='test';
        borx.Vision_Backorder_Report_Date__c='2022-10-20';
       // borx.Vision_Count__c=24.00;
        borx.Vision_current_month__c='november';
        borx.Vision_Current_Month_Total_Monthly_Order__c='250';
       // borx.Vision_Current_Order_Qty__c=250;
       // borx.Vision_Gcp_Update_Date__c='23-02-2022';
        borx.Vision_last_month_forecast__c='errfc';
      //  borx.Vision_Order_Value__c=250;
        borx.Vision_MoH__c='active';
        borx.Vision_Sku_Code__c='12345';
        borx.Vision_Product__c=p.id;
        borx.Vision_Short_Term_Forecast__c='5322';
       // borx.Vision_Total_Open_Order_Qty__c=1253;
        borx.Vision_Unit_Sales_Value__c='123';
        insert borx;
        test.startTest();
        GoogleBackOrderOTCFetch b = new GoogleBackOrderOTCFetch();
        database.executeBatch(b);
         Database.executeBatch(new GoogleBackOrderOTCFetch(1,1));
        test.stopTest();
            
        
    }

}