PCS BAckup 26Dec2023/Backup-Source/objects/GCP_100PCT_Analysis_SKU__c.object
<CustomObject>
    <description>This Object&apos;s Records are same for all the accounts.</description>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>GCP 100PCT Analysis SKU</relationshipLabel>
        <relationshipName>GCP_100PCT_Analysis_SKU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP 100PCT Analysis SKU</label>
    <nameField>
        <displayFormat>100PCT-Analysis-SKU-{00000}</displayFormat>
        <label>GCP 100PCT Analysis SKU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP 100PCT Analysis SKU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/GCP_100Pct_Analysis_Unique__c.object
<CustomObject>
    <description>This Object&apos;s Records are same for all the accounts.</description>
    <fields>
        <fullName>GCP_Product_Family__c</fullName>
        <label>GCP Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP 100Pct Analysis Unique</label>
    <nameField>
        <displayFormat>100%-Anay-SKU-UNQ-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP 100Pct Analysis Unique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/objects/Product_Family__c.object
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_Backup_All_8Jan2024_0624/Backup-Source/classes/Googlesfdc100PctAnalysisUniqueTest.cls
@istest
public class Googlesfdc100PctAnalysisUniqueTest {
   static testmethod void setup() {
         Account a = new Account();
        a.Name='es';
        a.AccountNumber='12563';
        insert a;
        Product_Family__c p= new Product_Family__c();
        p.name='abc';
        insert p;
        GCP_100Pct_Analysis_Unique__c gcp=new GCP_100Pct_Analysis_Unique__c();
        gcp.GCP_Product_Family__c='abc';
        insert gcp;
       product2 pp=new product2();
       pp.name='abc';
       pp.ProductCode='1234';
       insert pp;
       GCP_100PCT_Analysis_SKU__c gg= new GCP_100PCT_Analysis_SKU__c();
       gg.GCP_Product_Family__c='abc';
       gg.SKU_Code__c='1234';
       insert gg;
       
        test.starttest();
         Googlesfdc100PctAnalysisUnique b = new Googlesfdc100PctAnalysisUnique();
        database.executeBatch(b);
         Database.executeBatch(new Googlesfdc100PctAnalysisUnique(5,1));
         Googlesfdc100pctanalysisSKULevel c = new Googlesfdc100pctanalysisSKULevel();
        database.executeBatch(c);
         Database.executeBatch(new Googlesfdc100pctanalysisSKULevel(5,1));
        test.stopTest();
    }
}