PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Allocation Review</fullName>
                </value>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Customer Requested Pricing Confirmations</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                </value>
                <value>
                    <fullName>Exceptional Billings</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>In-Licensing</fullName>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                </value>
                <value>
                    <fullName>NDC Change</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                </value>
                <value>
                    <fullName>New Launch &amp; WAC</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>New Product WAC Pricing</fullName>
                </value>
                <value>
                    <fullName>Platform OTB</fullName>
                </value>
                <value>
                    <fullName>Platform PO OTB</fullName>
                    <label>One Time Buy - Platform PO</label>
                </value>
                <value>
                    <fullName>One Time Buy - Price Load Req</fullName>
                </value>
                <value>
                    <fullName>One Time Buy - Price Override Sale</fullName>
                </value>
                <value>
                    <fullName>PHS Price Change</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>RCA/IPA Member Addition</fullName>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                </value>
                <value>
                    <fullName>Re-Bid (Pricing Only)</fullName>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>VIP Rebate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Criteria_Matrix__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Criteria Matrix?</label>
        <type>Checkbox</type>
    </fields>
    <label>Approval Matrix</label>
    <nameField>
        <label>Process #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Approval_Process_Step__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Matrix__c</fullName>
        <label>Approval Matrix</label>
        <referenceTo>Phoenix_Approval_Matrix__c</referenceTo>
        <relationshipLabel>Approval Process Steps</relationshipLabel>
        <relationshipName>Phoenix_Approval_Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Approver_Team__c</fullName>
        <label>Approver Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phoenix_Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Phoenix_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Criteria_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Criteria Step?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Notification_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Notification Only?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phoenix_Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Approval Process Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bids3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Initial Order Discount for WAC Customers (No-Contract Price Offering)</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                    <label>One Time Buy – Good Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>One Time Buy Good Dated Shelf Life for New Product Launch</fullName>
                    <label>One Time Buy – Good Dated Shelf Life for New Product Launch</label>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                    <label>One Time Buy – Short Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>OTC New Product</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Good Dated</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Short Dated</fullName>
                </value>
                <value>
                    <fullName>OTC Price Change</fullName>
                </value>
                <value>
                    <fullName>OTC Product Addition</fullName>
                </value>
                <value>
                    <fullName>OTC Rebate Change</fullName>
                </value>
                <value>
                    <fullName>OTC RFP</fullName>
                </value>
                <value>
                    <fullName>OTC Volume Review</fullName>
                </value>
                <value>
                    <fullName>Platform OTB</fullName>
                    <label>Pharmabid</label>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                    <label>Product Removals</label>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>Sales Out Rebate</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                    <label>SRx Direct Pricing</label>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                    <label>SRx IPA Floor Pricing Update</label>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                    <label>SRx IPA Member Addition</label>
                </value>
                <value>
                    <fullName>SRx IPA Price Change</fullName>
                </value>
                <value>
                    <fullName>SRx IPA Product Addition</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                    <label>SRx NEW Individual Pricing Agreement (IPA)</label>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                    <label>SRx RCA/IPA Member GPO or Wholesaler Change</label>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                    <label>SRx RCA Member Addition</label>
                </value>
                <value>
                    <fullName>VIP Rebate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_User_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Group_Behavior__c</fullName>
        <label>Approval Group Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single User</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
                <value>
                    <fullName>Account based</fullName>
                </value>
                <value>
                    <fullName>Product based</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver_Group_Name__c</fullName>
        <label>Approver Group Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phoenix_Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Phoenix_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Is_Approval_Process_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approval Process User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Phoenix_User_Approval_Matrix__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Approval User Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phoenix_User_Approval_Matrix__c</referenceTo>
        <relationshipLabel>User_Groups</relationshipLabel>
        <relationshipName>User_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Approval Matrix</label>
    <nameField>
        <label>User Approval Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Approval Matrix</pluralLabel>
    <recordTypes>
        <fullName>Approval_User_Group</fullName>
        <active>true</active>
        <description>This will be used to manage different approver teams and their approval behavior.</description>
        <label>Approval User Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Approval_Users</fullName>
        <active>true</active>
        <label>Approval Users</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/globalValueSets/Phoenix_Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Business Head</fullName>
    </customValue>
    <customValue>
        <fullName>Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Country Head</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Government Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Home Office</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Head</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead OTC</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Lead SRx</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sr Director or VP Finance</fullName>
    </customValue>
    <customValue>
        <fullName>SRx IPA Contracts Approver</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Demand Planning</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>OTC Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales &amp; Marketing Head</fullName>
        <isActive>false</isActive>
        <label>Sales &amp; Marketing Head</label>
    </customValue>
    <customValue>
        <fullName>VP / Director Finance</fullName>
        <isActive>false</isActive>
        <label>VP / Director Finance</label>
    </customValue>
    <customValue>
        <fullName>SCM &amp; Marketing</fullName>
        <isActive>false</isActive>
        <label>SCM &amp; Marketing</label>
    </customValue>
    <masterLabel>Phoenix_Teams</masterLabel>
</GlobalValueSet>

PCS BAckup 26Dec2023/Backup-Source/classes/Phoenix_TestDataCreator.cls
/**
 * @description       : 
 * @author            : Surender Dhruvsoft
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Dhruvsoft
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   25-05-2021   Surender Dhruvsoft   Initial Version
**/
public class Phoenix_TestDataCreator {
    public List < Phoenix_User_Approval_Matrix__c > approvalGroups = new List < Phoenix_User_Approval_Matrix__c > ();
    public List < Phoenix_User_Approval_Matrix__c > approvalUsers = new List < Phoenix_User_Approval_Matrix__c > ();
    public List < User > users = new List < User > ();
    public List < Phoenix_Bid__c > bidsList = new List < Phoenix_Bid__c > ();
    public List < Phoenix_Bid__c > bidItemList = new List < Phoenix_Bid__c > ();
    public List < Product2 > productList = new List < Product2 > ();
    public List < Phoenix_Approval_Matrix__c > bidMatrixList = new List < Phoenix_Approval_Matrix__c > ();


    public Phoenix_TestDataCreator() {

    }

    public void generateApprovalMatrix() {
        if (approvalGroups.size() == 0) {
            Phoenix_User_Approval_Matrix__c group1 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Sales', Phoenix_Approval_Group_Behavior__c = 'Single User');
            approvalGroups.add(group1);
            Phoenix_User_Approval_Matrix__c group2 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Supply Chain', Phoenix_Approval_Group_Behavior__c = 'Team');
            approvalGroups.add(group2);
            Phoenix_User_Approval_Matrix__c group3 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Marketing', Phoenix_Approval_Group_Behavior__c = 'Product based');
            approvalGroups.add(group3);

            Phoenix_User_Approval_Matrix__c group4 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Finance', Phoenix_Approval_Group_Behavior__c = 'Team');
            approvalGroups.add(group4);
            Phoenix_User_Approval_Matrix__c group5 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_User_Group').getRecordTypeId(), Phoenix_Approver_Group_Name__c = 'Contracts', Phoenix_Approval_Group_Behavior__c = 'Account based');
            approvalGroups.add(group5);

            insert approvalGroups;
        }
        if (approvalUsers.size() == 0) {
            generateUsers();
            Phoenix_User_Approval_Matrix__c userApp1 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[0].Id);
            approvalUsers.add(userApp1);
            Phoenix_User_Approval_Matrix__c userApp2 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = users[0].Id, User_Group__c = approvalGroups[2].Id);
            approvalUsers.add(userApp2);
            Phoenix_User_Approval_Matrix__c userApp3 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[1].Id);
            approvalUsers.add(userApp3);
            Phoenix_User_Approval_Matrix__c userApp4 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[2].Id);
            approvalUsers.add(userApp4);
            Phoenix_User_Approval_Matrix__c userApp5 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[3].Id);
            approvalUsers.add(userApp5);
            Phoenix_User_Approval_Matrix__c userApp6 = new Phoenix_User_Approval_Matrix__c(RecordTypeId = Phoenix_User_Approval_Matrix__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Approval_Users').getRecordTypeId(), Phoenix_Is_Approval_Process_User__c = true, Phoenix_Approver__c = UserInfo.getUserId(), User_Group__c = approvalGroups[4].Id);
            approvalUsers.add(userApp6);

            insert approvalUsers;
        }

        if (bidMatrixList.size() == 0) {

            Phoenix_Approval_Matrix__c matrixRFP = new Phoenix_Approval_Matrix__c(Phoenix_Bid_Type__c = 'RFP Bids', Phoenix_Is_Criteria_Matrix__c = false);
            bidMatrixList.add(matrixRFP);
            Phoenix_Approval_Matrix__c matrix2 = new Phoenix_Approval_Matrix__c(Phoenix_Bid_Type__c = 'VIP Rebate', Phoenix_Is_Criteria_Matrix__c = false);
            bidMatrixList.add(matrix2);
            Phoenix_Approval_Matrix__c matrix3 = new Phoenix_Approval_Matrix__c(Phoenix_Bid_Type__c = 'Customer Requested Pricing Confirmations', Phoenix_Is_Criteria_Matrix__c = false);
            bidMatrixList.add(matrix3);
            Phoenix_Approval_Matrix__c matrix4 = new Phoenix_Approval_Matrix__c(Phoenix_Bid_Type__c = 'RCA Member Addition', Phoenix_Is_Criteria_Matrix__c = false);
            bidMatrixList.add(matrix4);
            Phoenix_Approval_Matrix__c matrix5 = new Phoenix_Approval_Matrix__c(Phoenix_Bid_Type__c = 'NEW Individual Pricing Agreement (IPA)', Phoenix_Is_Criteria_Matrix__c = false);
            bidMatrixList.add(matrix5);
            insert bidMatrixList;

            List < Phoenix_Approval_Process_Step__c > stepsList = new List < Phoenix_Approval_Process_Step__c > ();
            // List<String> bidTypes = new List<String>(){'RFP Bids','VIP Rebate','Customer Requested Pricing Confirmations','RCA Member Addition','NEW Individual Pricing Agreement (IPA)'};
            for (Phoenix_Approval_Matrix__c matrix: bidMatrixList) {
                Phoenix_Approval_Process_Step__c rfpStep1 = new Phoenix_Approval_Process_Step__c(Name = 'Initial Submission', Phoenix_Order__c = 1, Phoenix_Is_Notification_Only__c = false, Phoenix_Approval_Matrix__c = matrix.Id);
                stepsList.add(rfpStep1);
                Phoenix_Approval_Process_Step__c rfpStep2 = new Phoenix_Approval_Process_Step__c(Name = 'Supply Chain', Phoenix_Order__c = 2, Phoenix_Is_Notification_Only__c = false, Phoenix_Approver_Team__c = 'Supply Chain', Phoenix_Approval_Matrix__c = matrix.Id, Phoenix_Approver__c = UserInfo.getUserId());
                stepsList.add(rfpStep2);
                Phoenix_Approval_Process_Step__c rfpStep3 = new Phoenix_Approval_Process_Step__c(Name = 'Marketing', Phoenix_Order__c = 3, Phoenix_Is_Notification_Only__c = false, Phoenix_Approver_Team__c = 'Marketing', Phoenix_Approval_Matrix__c = matrix.Id);
                stepsList.add(rfpStep3);
                Phoenix_Approval_Process_Step__c rfpStep4 = new Phoenix_Approval_Process_Step__c(Name = 'Business Head', Phoenix_Order__c = 4, Phoenix_Is_Notification_Only__c = false, Phoenix_Approver_Team__c = 'Business Head', Phoenix_Is_Criteria_Step__c = true, Phoenix_Approval_Matrix__c = matrix.Id);
                stepsList.add(rfpStep4);

                Phoenix_Approval_Process_Step__c rfpStep5 = new Phoenix_Approval_Process_Step__c(Name = 'Finance', Phoenix_Order__c = 5, Phoenix_Is_Notification_Only__c = false, Phoenix_Approver_Team__c = 'Finance', Phoenix_Approval_Matrix__c = matrix.Id);
                stepsList.add(rfpStep5);
                Phoenix_Approval_Process_Step__c rfpStep6 = new Phoenix_Approval_Process_Step__c(Name = 'Contracts', Phoenix_Order__c = 6, Phoenix_Is_Notification_Only__c = false, Phoenix_Approver_Team__c = 'Contracts', Phoenix_Approval_Matrix__c = matrix.Id);
                stepsList.add(rfpStep6);
                Phoenix_Approval_Process_Step__c rfpStep7 = new Phoenix_Approval_Process_Step__c(Name = 'Closed', Phoenix_Order__c = 7, Phoenix_Is_Notification_Only__c = false, Phoenix_Approval_Matrix__c = matrix.Id);
                stepsList.add(rfpStep7);
            }



            insert stepsList;















        }
    }

    public void generateBids() {
        if (bidsList.size() == 0) {

            Phoenix_Bid__c bid1 = new Phoenix_Bid__c(Phoenix_Bid_Type__c = 'RFP Bids', Phoenix_Approval_Status__c = 'Draft');
            bidsList.add(bid1);
            Phoenix_Bid__c bid2 = new Phoenix_Bid__c(Phoenix_Bid_Type__c = 'VIP Rebate', Phoenix_Approval_Status__c = 'Draft');
            bidsList.add(bid2);
            Phoenix_Bid__c bid3 = new Phoenix_Bid__c(Phoenix_Bid_Type__c = 'Customer Requested Pricing Confirmations', Phoenix_Approval_Status__c = 'Draft');
            bidsList.add(bid3);
            Phoenix_Bid__c bid4 = new Phoenix_Bid__c(Phoenix_Bid_Type__c = 'RCA Member Addition', Phoenix_Approval_Status__c = 'Draft');
            bidsList.add(bid4);
            Phoenix_Bid__c bid5 = new Phoenix_Bid__c(Phoenix_Bid_Type__c = 'NEW Individual Pricing Agreement (IPA)', Phoenix_Approval_Status__c = 'Draft');
            bidsList.add(bid5);

            insert bidsList;
        }
        generateProducts();
        List < Phoenix_Bid_Line_Item__c > bItems = new List < Phoenix_Bid_Line_Item__c > ();
        Phoenix_Bid_Line_Item__c item1 = new Phoenix_Bid_Line_Item__c(Phoenix_Bid__c = bidsList[0].Id, Phoenix_Product__c = productList[0].Id, Phoenix_Product_Family1__c = 'Levocetrizine');
        Phoenix_Bid_Line_Item__c item2 = new Phoenix_Bid_Line_Item__c(Phoenix_Bid__c = bidsList[0].Id, Phoenix_Product__c = productList[1].Id, Phoenix_Product_Family1__c = 'Levocetrizine2');
        Phoenix_Bid_Line_Item__c item3 = new Phoenix_Bid_Line_Item__c(Phoenix_Bid__c = bidsList[0].Id, Phoenix_Product__c = productList[2].Id, Phoenix_Product_Family1__c = 'Levocetrizine');
        bItems.addAll(new List < Phoenix_Bid_Line_Item__c > {
            item1,
            item2,
            item3
        });
        insert bItems;

    }

    public void generateProducts() {
        generateUsers();
        if (productList.size() == 0) {
            Product2 prod1 = new Product2(Name = 'Product1', ProductCode = '1234', Phoenix_Product_Director__c = users[0].Id,Phoenix_Marketing_Lead__c = UserInfo.getUserId());
            Product2 prod2 = new Product2(Name = 'Product1', ProductCode = '12345', Phoenix_Product_Director__c = UserInfo.getUserId(),Phoenix_Marketing_Lead__c = UserInfo.getUserId());
            Product2 prod3 = new Product2(Name = 'Product1', ProductCode = '123456', Phoenix_Product_Director__c = UserInfo.getUserId(),Phoenix_Marketing_Lead__c = UserInfo.getUserId());
            productList.addAll(new List < Product2 > {
                prod1,
                prod2,
                prod3
            });
            insert productList;
        }
    }

    public void generateUsers() {
        if (users.size() == 0) {
            Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
            String uid = ('Phoenix' + System.now().getTime()).SubString(0, 8);
            User u1 = new User(Alias = uid, Email = uid + '@phoenix.com', EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/New_York', UserName = uid + '@phoenix.com');


            users.add(u1);


            insert users;
        }
    }
}