PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
                <value>
                    <fullName>Dropped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Name__c</fullName>
        <label>Bid Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Submitted_Date__c</fullName>
        <label>Bid Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Initial Order Discount for WAC Customers (No-Contract Price Offering)</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                    <label>One Time Buy – Good Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>One Time Buy Good Dated Shelf Life for New Product Launch</fullName>
                    <label>One Time Buy – Good Dated Shelf Life for New Product Launch</label>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                    <label>One Time Buy – Short Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>OTC New Product</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Good Dated</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Short Dated</fullName>
                </value>
                <value>
                    <fullName>OTC Price Change</fullName>
                </value>
                <value>
                    <fullName>OTC Product Addition</fullName>
                </value>
                <value>
                    <fullName>OTC Rebate Change</fullName>
                </value>
                <value>
                    <fullName>OTC RFP</fullName>
                </value>
                <value>
                    <fullName>OTC Volume Review</fullName>
                </value>
                <value>
                    <fullName>Platform OTB</fullName>
                    <label>Pharmabid</label>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                    <label>Product Removals</label>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>Sales Out Rebate</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                    <label>SRx Direct Pricing</label>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                    <label>SRx IPA Floor Pricing Update</label>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                    <label>SRx IPA Member Addition</label>
                </value>
                <value>
                    <fullName>SRx IPA Price Change</fullName>
                </value>
                <value>
                    <fullName>SRx IPA Product Addition</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                    <label>SRx NEW Individual Pricing Agreement (IPA)</label>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                    <label>SRx RCA/IPA Member GPO or Wholesaler Change</label>
                </value>
                <value>
                    <fullName>RCA Member Addition</fullName>
                    <label>SRx RCA Member Addition</label>
                </value>
                <value>
                    <fullName>VIP Rebate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/VisionSearchSelectBidsCtrl.cls
public class VisionSearchSelectBidsCtrl {
    @AuraEnabled
    public static List<Phoenix_Bid__c> getBids(String searchText){
        List<String> approvalStatus = new List<String>{'Closed', 'Vistex Update', 'Contracts', 'Contracts Rejected', 'Customer Rejected', 'Customer\'s Update'};
        List<String> bidTypes = new List<String>{'Contracts Only', 'Initial Order Discount for WAC Customers (No-Contract Price Offering)', 'Direct Order Form Pricing Update', 'IPA Floor Pricing Update', 'IPA Member Addition', 'SRx IPA Price Change', 'SRx IPA Product Addition', 'NEW Individual Pricing Agreement (IPA)', 'RCA/IPA Member GPO or Wholesaler Change', 'RCA Member Addition', 'VIP Rebate'};
        String query = 'SELECT Name, Phoenix_Bid_Name__c, Phoenix_Bid_Owner__r.Name, Phoenix_Bid_Submitted_Date__c, Phoenix_Bid_Type__c, Phoenix_Customer__c, Phoenix_Customer__r.Name, Phoenix_Bid_Owner__c FROM Phoenix_Bid__c WHERE (Phoenix_Approval_Status__c IN: approvalStatus AND Phoenix_Bid_Type__c NOT IN: bidTypes)';
        if(!String.isBlank(searchText)){
            Set<String> splittedText = new Set<String>();
            List<String> splittedTextComma = searchText.split(',');
            //splittedText.addAll(splittedTextComma);
            List<String> searchBids = new List<String>();
            for(String str: splittedTextComma){
                string searchItem='%'+str+'%';
                searchBids.add(searchItem);
            }
            query += 'AND (Name LIKE: searchBids OR Phoenix_Bid_Name__c LIKE: searchBids)';
        }
        query += ' ORDER BY Name ASC LIMIT 1000';
        List<Phoenix_Bid__c> bids = Database.query(query);
        return bids;
    }
    
    @AuraEnabled
    public static List<Phoenix_Bid__c> getRFPBids(String searchText){
        List<Phoenix_Bid__c> RFPBids = VisionPositionWiseAnalysisCls.getRFPBids(searchText);
        return RFPBids;
    }
    
    @AuraEnabled
    public static List <Phoenix_Bid__c> fetchSortResults(string sortField, boolean isAsc, List < Phoenix_Bid__c > bidList) {
        set < Id > bidIds = new set < Id > ();
        list < Phoenix_Bid__c > sortResults = new list < Phoenix_Bid__c > ();
        List < Phoenix_Bid__c > bidslist = new List < Phoenix_Bid__c > ();
        for (Phoenix_Bid__c w: bidList) {
            bidIds.add(w.Id);
        }
        String sSoql = 'SELECT Name, Phoenix_Bid_Name__c, Phoenix_Bid_Owner__r.Name, Phoenix_Bid_Submitted_Date__c, Phoenix_Bid_Type__c, Phoenix_Customer__c, Phoenix_Customer__r.Name, Phoenix_Bid_Owner__c FROM Phoenix_Bid__c WHERE ID IN:bidIds';
        if (sortField != null && sortField != '') {
            sSoql += ' order by ' + sortField;
            if (isAsc) {
                sSoql += ' ASC ';
            } else {
                sSoql += ' DESC ';
            }
        }
        sSoql += ' NULLS LAST ';
        sortResults = Database.query(sSoql);
        for (Phoenix_Bid__c bid: sortResults) {
            for (Phoenix_Bid__c wr: bidList) {
                if (wr.Id == bid.Id) {
                    bidslist.add(wr);
                }
            }
        }
        
        return bidslist;
    }
}