PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Phoenix_Future_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Future NPR Data</relationshipLabel>
        <relationshipName>Future_NPR_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Phoenix_NPR_Status__c</fullName>
        <label>NPR Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Future_NPR_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Future NPR Data</label>
    <nameField>
        <displayFormat>FutureNPR-{0000000}</displayFormat>
        <label>Phoenix_Future_NPR_Data__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_NDC__c</fullName>
        <inlineHelpText>National Drug Code: SAP field</inlineHelpText>
        <label>NDC - 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Pkg_Size__c</fullName>
        <inlineHelpText>User Input field</inlineHelpText>
        <label>Pkg Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Phoenix_FutureNPRData_Testing.cls
@isTest
public class Phoenix_FutureNPRData_Testing{
    @isTest static void TestFutureNPRWrapper(){
        Account acc = new Account();
        acc.Name = 'Sri';
        insert acc;
        Phoenix_Contract__c	 cont=new Phoenix_Contract__c();
        cont.Name = 'ashu';
        insert cont;
        Product2 prod = new Product2();
        prod.Name = 'Alloprinol';
        prod.Phoenix_NDC__c = '123';
        prod.Phoenix_Pkg_Size__c = 1231 ;
        prod.Phoenix_Throughput_cost__c = 1564;
        insert prod;
        Phoenix_Future_NPR_Data__c testRecord = new Phoenix_Future_NPR_Data__c();
        testRecord.Phoenix_NPR_Status__c = 'Active';
        testRecord.Phoenix_Product__c= prod.Id;
        testRecord.Phoenix_Contract__c= cont.Id;
        insert testRecord;
     Phoenix_FutureNPRData.futureNPR(prod.Id);
        
    }
}