PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Product_Position__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_General_Category__c</fullName>
        <label>General Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Current_Product_Position__c</fullName>
        <label>Current Product Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/updatepositiongeneralcategory_Test.cls
@istest
public class updatepositiongeneralcategory_Test {
    static testmethod void setup(){
        Phoenix_Product_Position__c p= new Phoenix_Product_Position__c();
        p.name='Primary';
        p.Phoenix_General_Category__c='Primary';
        insert p;
          Phoenix_Product_Position__c p1= new Phoenix_Product_Position__c();
        p1.name='Secondary';
        p1.Phoenix_General_Category__c='Secondary';
        insert p1;
        
        Vision_Customer_Product_Tracker__c cpt= new Vision_Customer_Product_Tracker__c();
        cpt.Vision_Current_Product_Position__c='Primary';
        insert cpt;
         Vision_Customer_Product_Tracker__c cpt1= new Vision_Customer_Product_Tracker__c();
        cpt1.Vision_Current_Product_Position__c='Secondary';
        insert cpt1;
         Vision_Customer_Product_Tracker__c cpt2= new Vision_Customer_Product_Tracker__c();
        cpt2.Vision_Current_Product_Position__c='Multi';
        insert cpt2;
        
    }
}