PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bright_Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Current_User__c</fullName>
        <label>Current User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Issue_Status__c</fullName>
        <label>Issue Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phoenix_Occurrence_Time__c</fullName>
        <label>Occurrence Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phoenix_Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bright Exceptions</label>
    <nameField>
        <displayFormat>Exception-{0000000000}</displayFormat>
        <label>Bright Exceptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bright Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phoenix_Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_Customer_Product_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Is_Initial_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates whether it is initial order or not</description>
        <label>Is Initial Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Phoenix_Contract__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Current_Product_Position__c</fullName>
        <label>Current Product Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_NPR_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NPR Data</label>
        <referenceTo>Phoenix_NPR_Data__c</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Order_Quantity__c</fullName>
        <label>Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_PO_Number__c</fullName>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Product Trackers</relationshipLabel>
        <relationshipName>Customer_Product_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Unique_Identifier__c</fullName>
        <formula>Vision_Product_Code__c+&quot;_&quot;+Vision_Contract_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Identifier</label>
        <type>Text</type>
    </fields>
    <label>Customer Product Tracker</label>
    <nameField>
        <displayFormat>cus-prd-tracker-{00000}</displayFormat>
        <label>Customer Product Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Vision_GCP_Customer_Order_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GCP Customer Order Trends</relationshipLabel>
        <relationshipName>GCP_Customer_Order_Trends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_PO_Number__c</fullName>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_SKU_Code__c</fullName>
        <label>SKU  Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP Customer Order Trend</label>
    <nameField>
        <displayFormat>GCP cus-ord-trend-{0000000}</displayFormat>
        <label>GCP Customer Order Trend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Customer Order Trends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/objects/Vision_GCP_SFDC_Order_Status__c.object
<CustomObject>
    <fields>
        <fullName>Vision_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GCP SFDC Order Status</relationshipLabel>
        <relationshipName>GCP_SFDC_Order_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Order_Quantity__c</fullName>
        <label>Order Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_PO_Number__c</fullName>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GCP SFDC Order Status</relationshipLabel>
        <relationshipName>GCP_SFDC_Order_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GCP SFDC Order Status</label>
    <nameField>
        <displayFormat>sfdc-ord-status-{0000000}</displayFormat>
        <label>GCP SFDC Order Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP SFDC Order Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/OrderBasedCntrctProductStatusUpdate.cls
public class OrderBasedCntrctProductStatusUpdate implements Database.Batchable < sObject > , Database.Stateful, Schedulable{
    public void execute(SchedulableContext sc) {
        //Database.executeBatch(new OrderBasedCntrctProductStatusUpdate());
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //String customer = '0017c00000n9vA4AAI';
        String query = 'Select Vision_Product__r.Name, ' +Phoenix_Util.getsObjectFieds('Vision_GCP_SFDC_Order_Status__c')+' from Vision_GCP_SFDC_Order_Status__c';
        //String query = 'Select Vision_Product__r.Name, ' +Phoenix_Util.getsObjectFieds('Vision_GCP_SFDC_Order_Status__c')+' from Vision_GCP_SFDC_Order_Status__c Where CreatedDate = LAST_N_DAYS:1';
        //String query = 'Select ' +Phoenix_Util.getsObjectFieds('Vision_GCP_Customer_Order_Trend__c')+' from Vision_GCP_Customer_Order_Trend__c WHERE Vision_Customer__c =:customer';
        if(Test.isRunningTest())query += ' LIMIT 1';
        return Database.getQueryLocator(query);
    }
   
    public void execute(Database.BatchableContext BC, List <Vision_GCP_SFDC_Order_Status__c> orderList) {
        try{
            if(orderList.size() > 0){
                Map<String, List<Vision_GCP_SFDC_Order_Status__c>> mapOfCustomerOrders = new Map<String, List<Vision_GCP_SFDC_Order_Status__c>>();
                for(Vision_GCP_SFDC_Order_Status__c order: orderList){
                    if(mapOfCustomerOrders.containsKey(order.Vision_Account__c)){
                        mapOfCustomerOrders.get(order.Vision_Account__c).add(order);
                        //mapOfCustomerOrders.put(order.Vision_Account__c,tempList);                        
                    } else{
                        mapOfCustomerOrders.put(order.Vision_Account__c, new List < Vision_GCP_SFDC_Order_Status__c > {
                            order
                                });
                    }
                }
                //String customer = '0017c00000n9vA4AAI';
                //List<Vision_Customer_Product_Tracker__c> trackList = [SELECT Id, Vision_Product_Code__c, Vision_Contract__r.Phoenix_Contract_Start_Date__c, Vision_Unique_Identifier__c,Vision_Current_Product_Position__c ,Vision_Contract__c, Vision_Account__c, Vision_NPR_Data__c  FROM Vision_Customer_Product_Tracker__c WHERE Vision_NPR_Data__r.Phoenix_Contract_Type__c = 'Direct' AND Vision_Account__c IN:mapOfCustomerOrders.keySet()];
                Map<String, Vision_Customer_Product_Tracker__c> mapOfRecords = new Map<String, Vision_Customer_Product_Tracker__c>();
                for(Vision_Customer_Product_Tracker__c track: [SELECT Id, Vision_Product_Code__c, Vision_Contract__r.Phoenix_Contract_Start_Date__c, Vision_Unique_Identifier__c,Vision_Current_Product_Position__c ,Vision_Contract__c, Vision_Account__c, Vision_NPR_Data__c  FROM Vision_Customer_Product_Tracker__c WHERE Vision_NPR_Data__r.Phoenix_Contract_Type__c = 'Direct' AND Vision_Account__c IN:mapOfCustomerOrders.keySet()]){
                    //List<Vision_GCP_SFDC_Order_Status__c> orders = mapOfCustomerOrders.get(track.Vision_Account__c);
                    if(mapOfCustomerOrders.containsKey(track.Vision_Account__c)){
                        for(Vision_GCP_SFDC_Order_Status__c order: mapOfCustomerOrders.get(track.Vision_Account__c)){
                            if(track.Vision_Product_Code__c == order.Vision_SKU_Code__c && track.Vision_Contract__r.Phoenix_Contract_Start_Date__c!= null && order.Vision_Order_Date__c !=null && track.Vision_Contract__r.Phoenix_Contract_Start_Date__c < order.Vision_Order_Date__c){
                                track.Is_Initial_Order__c = true;
                                track.Vision_Order_Quantity__c = order.Vision_Order_Quantity__c;
                                track.Vision_PO_Number__c = order.Vision_PO_Number__c;
                                mapOfRecords.put(track.Id, track);
                            }
                        }   
                    }
                }
                upsert mapOfRecords.values();
            }
            else{
              }
        }
        Catch(Exception e) {
            Phoenix_Bright_Exceptions__c exp = new Phoenix_Bright_Exceptions__c(Phoenix_Class__c = 'OrderBasedCntrctProductStatusUpdate', Phoenix_Error_Message__c = e.getMessage(), Phoenix_Issue_Status__c = 'Pending', Phoenix_Method_Name__c = 'execute', Phoenix_Occurrence_Time__c = System.now(), Phoenix_Stack_Trace__c = e.getStackTraceString(), Phoenix_Current_User__c = UserInfo.getName() + '(' + UserInfo.getUserId() + ')');
            insert exp;
        }
    }
    public void finish(Database.BatchableContext BC) {
        
    }
}