PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Head</fullName>
                </value>
                <value>
                    <fullName>Business Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed-Draft</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Contracts Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer&apos;s Update</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rejected</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Marketing Head</fullName>
                </value>
                <value>
                    <fullName>Marketing Head Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing Lead Rejected</fullName>
                </value>
                <value>
                    <fullName>Marketing Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>SCM &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance</fullName>
                </value>
                <value>
                    <fullName>Sr Director or VP Finance Rejected</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Supply Chain Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Update</fullName>
                </value>
                <value>
                    <fullName>Vistex Update Rejected</fullName>
                </value>
                <value>
                    <fullName>Vistex Customer Code Update</fullName>
                </value>
                <value>
                    <fullName>Dropped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts Only</fullName>
                </value>
                <value>
                    <fullName>Customer Rebate Change</fullName>
                </value>
                <value>
                    <fullName>Initial Order Discount for WAC Customers (No-Contract Price Offering)</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>New Product Launch</fullName>
                </value>
                <value>
                    <fullName>Good Dated OTB</fullName>
                    <label>One Time Buy – Good Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>One Time Buy Good Dated Shelf Life for New Product Launch</fullName>
                    <label>One Time Buy – Good Dated Shelf Life for New Product Launch</label>
                </value>
                <value>
                    <fullName>Short Dated OTB</fullName>
                    <label>One Time Buy – Short Dated Shelf Life</label>
                </value>
                <value>
                    <fullName>OTC New Product</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Good Dated</fullName>
                </value>
                <value>
                    <fullName>OTC OTB Short Dated</fullName>
                </value>
                <value>
                    <fullName>OTC Price Change</fullName>
                </value>
                <value>
                    <fullName>OTC Product Addition</fullName>
                </value>
                <value>
                    <fullName>OTC Rebate Change</fullName>
                </value>
                <value>
                    <fullName>OTC RFP</fullName>
                </value>
                <value>
                    <fullName>OTC Volume Review</fullName>
                </value>
                <value>
                    <fullName>Platform OTB</fullName>
                    <label>Pharmabid</label>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Product Addition</fullName>
                </value>
                <value>
                    <fullName>Product Discontinuation Process</fullName>
                </value>
                <value>
                    <fullName>Mass Product Removals</fullName>
                    <label>Product Removals</label>
                </value>
                <value>
                    <fullName>RFP Bids</fullName>
                </value>
                <value>
                    <fullName>Sales Out Rebate</fullName>
                </value>
                <value>
                    <fullName>Direct Order Form Pricing Update</fullName>
                    <label>SRx Direct Pricing</label>
                </value>
                <value>
                    <fullName>IPA Floor Pricing Update</fullName>
                    <label>SRx IPA Floor Pricing Update</label>
                </value>
                <value>
                    <fullName>IPA Member Addition</fullName>
                    <label>SRx IPA Member Addition</label>
                </value>
                <value>
                    <fullName>SRx IPA Price Change</fullName>
                </value>
                <value>
                    <fullName>SRx IPA Product Addition</fullName>
                </value>
                <value>
                    <fullName>NEW Individual Pricing Agreement (IPA)</fullName>
                    <label>SRx NEW Individual Pricing Agreement (IPA)</label>
                </value>
                <value>
                    <fullName>RCA/IPA Member GPO or Wholesaler Change</fullName>
                    <label>SRx RCA/IPA Member GPO or Wholesaler Change</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Phoenix_Is_Bid_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bids</relationshipLabel>
        <relationshipName>Bids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid</label>
    <nameField>
        <displayFormat>Bid-{0000000}</displayFormat>
        <label>Bid No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Bid_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Status__c</fullName>
        <label>Bid Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Declined by Customer</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>DRL Rescinded</fullName>
                </value>
                <value>
                    <fullName>DRL submitting under New Bid Number</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer_Response_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Response Line</label>
        <referenceTo>Phoenix_Customer_Response_Line__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <formula>Phoenix_Throughput_Cost1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Throughput Cost (Internal Use)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Bid Line Items</relationshipLabel>
        <relationshipName>Bid_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bid Line Item</label>
    <nameField>
        <displayFormat>BidLineItem-{0000000}</displayFormat>
        <label>Bid Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bid Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_Customer_Response_Line__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Bid_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid Line Item</label>
        <referenceTo>Phoenix_Bid_Line_Item__c</referenceTo>
        <relationshipLabel>Customer Response Lines</relationshipLabel>
        <relationshipName>Customer_Response_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phoenix_Bid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid</label>
        <referenceTo>Phoenix_Bid__c</referenceTo>
        <relationshipLabel>Customer Response Lines</relationshipLabel>
        <relationshipName>Customer_Response_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used this field to store the GCP Product Family</description>
        <label>Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Customer Response Lines</relationshipLabel>
        <relationshipName>Customer_Response_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Response Line</label>
    <nameField>
        <displayFormat>CRLineItem-{0000000}</displayFormat>
        <label>Customer Response Line No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Response Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Phoenix_Throughput_cost__c</fullName>
        <inlineHelpText>Finance User Input field</inlineHelpText>
        <label>Throughput Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCP Product Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/VisionPositionWiseAnalysisCls.cls
public class VisionPositionWiseAnalysisCls{
    @AuraEnabled 
    public static finalWrapper getData(List<String> selectedBids){
        String query = 'Select Phoenix_Product__r.Product_Family__r.Name, Phoenix_Product__r.Product_Family__c, Phoenix_Bid__r.Name, Phoenix_Bid__r.Phoenix_Customer__c, Phoenix_Product__r.Phoenix_Throughput_cost__c, Phoenix_Product__r.Name, Phoenix_Bid__r.Phoenix_Approval_Status__c, Phoenix_Bid__r.Phoenix_Bid_Type__c, ' +Phoenix_Util.getsObjectFieds('Phoenix_Bid_Line_Item__c')+', (Select '+Phoenix_Util.getsObjectFieds('Phoenix_Customer_Response_Line__c')+' from Customer_Response_Lines__r) from Phoenix_Bid_Line_Item__c WHERE Phoenix_Customer_Response_Line__c != null AND Phoenix_Bid__c IN: selectedBids';
        List<Phoenix_Bid_Line_Item__c> bidLineItems = Database.query(query);
        List<String> positions = new List<String> {'Lost Primary', 'Primary to Backup', 'Retained Primary', 'Backup to Primary', 'Retained Backup', 'Lost Backup', 'Bid in RFP didn\'t win', 'New Backup', 'New Primary'};
        Map<String, List<Phoenix_Bid_Line_Item__c>> mapOfPositions = new Map<String, List<Phoenix_Bid_Line_Item__c>>();
        for(String position: positions){
            mapOfPositions.put(position, new List<Phoenix_Bid_Line_Item__c>());
        }
        List<Phoenix_Bid_Line_Item__c> ignoredBidLineItems = new List<Phoenix_Bid_Line_Item__c>();
        for(Phoenix_Bid_Line_Item__c bidLineItem: bidLineItems){
            if(bidLineItem.Customer_Response_Lines__r.size() > 0 && ((bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Declined by Customer' || bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'DRL Rescinded') && (bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Primary' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'primary') && bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == null)){
                if(mapOfPositions.containsKey('Lost Primary')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('Lost Primary');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Lost Primary', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Lost Primary', positionItemsList);
                }
            } else if(bidLineItem.Customer_Response_Lines__r.size() > 0 && (bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Awarded' && (bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Primary' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'primary') && (bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Primary' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'primary'))){
                if(mapOfPositions.containsKey('Retained Primary')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('Retained Primary');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Retained Primary', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Retained Primary', positionItemsList);
                }
            } else if(bidLineItem.Customer_Response_Lines__r.size() > 0 && (bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Awarded' && (bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Primary' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'primary') && (bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Backup' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'backup' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Secondary' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'secondary'))){
                if(mapOfPositions.containsKey('Primary to Backup')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('Primary to Backup');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Primary to Backup', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Primary to Backup', positionItemsList);
                }
            } else if(bidLineItem.Customer_Response_Lines__r.size() > 0 && (bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Awarded' && (bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Backup' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'backup' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Secondary' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'secondary') && (bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Primary' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'primary'))){
                if(mapOfPositions.containsKey('Backup to Primary')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('Backup to Primary');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Backup to Primary', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Backup to Primary', positionItemsList);
                }
            } else if(bidLineItem.Customer_Response_Lines__r.size() > 0 && (bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Awarded' && (bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Backup' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'backup' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Secondary' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'secondary') && (bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Backup' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'backup' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Secondary' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'secondary'))){
                if(mapOfPositions.containsKey('Retained Backup')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('Retained Backup');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Retained Backup', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Retained Backup', positionItemsList);
                }
            } else if(bidLineItem.Customer_Response_Lines__r.size() > 0 && ((bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Declined by Customer' || bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'DRL Rescinded') && (bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Backup' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'backup'|| bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'Secondary' || bidLineItem.Customer_Response_Lines__r[0].General_Category__c == 'secondary') && bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == null)){
                if(mapOfPositions.containsKey('Lost Backup')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('Lost Backup');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Lost Backup', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Lost Backup', positionItemsList);
                }
            } else if(bidLineItem.Customer_Response_Lines__r.size() > 0 && ((bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Declined by Customer' || bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'DRL Rescinded') && bidLineItem.Customer_Response_Lines__r[0].General_Category__c == null && bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == null)){
                if(mapOfPositions.containsKey('Bid in RFP didn\'t win')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('Bid in RFP didn\'t win');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Bid in RFP didn\'t win', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('Bid in RFP didn\'t win', positionItemsList);
                }
            } else if(bidLineItem.Customer_Response_Lines__r.size() > 0 && (bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Awarded' && bidLineItem.Customer_Response_Lines__r[0].General_Category__c == null && (bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Backup' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'backup' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Secondary' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'secondary'))){
                if(mapOfPositions.containsKey('New Backup')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('New Backup');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('New Backup', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('New Backup', positionItemsList);
                }
            } else if(bidLineItem.Customer_Response_Lines__r.size() > 0 && (bidLineItem.Customer_Response_Lines__r[0].Phoenix_Bid_Status__c == 'Awarded' && bidLineItem.Customer_Response_Lines__r[0].General_Category__c == null && (bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'Primary' || bidLineItem.Customer_Response_Lines__r[0].Awarded_General_Category__c == 'primary'))){
                if(mapOfPositions.containsKey('New Primary')){
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = mapOfPositions.get('New Primary');
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('New Primary', positionItemsList);
                } else{
                    List<Phoenix_Bid_Line_Item__c> positionItemsList = new List<Phoenix_Bid_Line_Item__c>();
                    positionItemsList.add(bidLineItem);
                    mapOfPositions.put('New Primary', positionItemsList);
                }
            }
            ignoredBidLineItems.add(bidLineItem);   
        }
        
        Map<String, List<categoryWrapper>> categoryWrapperList = new Map<String, List<categoryWrapper>>();
        for(String key: mapOfPositions.keySet()){
            categoryWrapper wrap = new categoryWrapper();
            if(key == 'Lost Primary' || key == 'Retained Primary' || key == 'Primary to Backup'){
                wrap.category = 'Primary';
            } else if(key == 'Backup to Primary' || key == 'Retained Backup' || key == 'Lost Backup'){
                wrap.category = 'Backup';
            } else if(key == 'Bid in RFP didn\'t win' || key == 'New Backup' || key == 'New Primary'){
                wrap.category = 'New Opportunity';
            }
            wrap.position = key;
            wrap.bidLineItems = mapOfPositions.get(key);
            wrap.length1 = wrap.bidLineItems.size();
            if(categoryWrapperList.containsKey(wrap.category)){
                List<categoryWrapper> wrapperList = categoryWrapperList.get(wrap.category);
                wrapperList.add(wrap);
                categoryWrapperList.put(wrap.category, wrapperList);                
            } else{
                List<categoryWrapper> wrapperList = new List<categoryWrapper>();
                wrapperList.add(wrap);
                categoryWrapperList.put(wrap.category, wrapperList);
            }
        }
        List<categoryWrapper> primaryCategory = new List<categoryWrapper>();
        List<categoryWrapper> backupCategory = new List<categoryWrapper>();
        List<categoryWrapper> optyCategory = new List<categoryWrapper>();
        for(String key: categoryWrapperList.keySet()){
            if(key == 'New Opportunity'){
                optyCategory = categoryWrapperList.get(key);
            } else if(key == 'Primary'){
                primaryCategory = categoryWrapperList.get(key);
            } else if(key == 'Backup'){
                backupCategory = categoryWrapperList.get(key);
            }
        }
        finalWrapper finalWrap = new finalWrapper();
        finalWrap.primaryCategory = primaryCategory;
        finalWrap.backupCategory = backupCategory;
        finalWrap.optyCategory = optyCategory;
        finalWrap.ignoredBidLineItems = ignoredBidLineItems;
        return finalWrap;
    }
    
    @AuraEnabled
    public static List<Phoenix_Bid__c> getRFPBids(String searchText){
        String RFP = 'RFP Bids'; List<String> approvalStatus = new List<String>{'Closed', 'Vistex Update', 'Customer Rejected'};
        String query = 'SELECT Name, Phoenix_Bid_Name__c, Phoenix_Bid_Owner__r.Name, Phoenix_Bid_Submitted_Date__c, Phoenix_Bid_Type__c, Phoenix_Customer__c, Phoenix_Customer__r.Name, Phoenix_Bid_Owner__c FROM Phoenix_Bid__c WHERE (Phoenix_Bid_Type__c =:RFP AND Phoenix_Approval_Status__c IN: approvalStatus)';
        if(!String.isBlank(searchText)){
            Set<String> splittedText = new Set<String>();
            List<String> splittedTextSpace = searchText.split(' ');
            List<String> splittedTextComma = searchText.split(',');
            splittedText.addAll(splittedTextSpace);
            splittedText.addAll(splittedTextComma);
            List<String> searchBids = new List<String>();
            for(String str: splittedText){
                string searchItem='%'+str+'%';
                searchBids.add(searchItem);
            }
            query += 'AND (Name LIKE: searchBids OR Phoenix_Bid_Name__c LIKE: searchBids)';
        }
        query += ' ORDER BY Name ASC LIMIT 1000'; 
        List<Phoenix_Bid__c> bids = Database.query(query);
        return bids;
    }
    
    public class categoryWrapper{
        @AuraEnabled public String category;
        @AuraEnabled public String position;
        @AuraEnabled public List<Phoenix_Bid_Line_Item__c> bidLineItems;
        @AuraEnabled public Map<String, List<Phoenix_Bid_Line_Item__c>> mapOfPositions;
        @AuraEnabled public boolean expandCategory;
        @AuraEnabled public Integer length1;
    }
    
    public class finalWrapper{
        @AuraEnabled public List<categoryWrapper> primaryCategory;
        @AuraEnabled public List<categoryWrapper> backupCategory;
        @AuraEnabled public List<categoryWrapper> optyCategory;
        @AuraEnabled public List<Phoenix_Bid_Line_Item__c> ignoredBidLineItems;
    }
}