PCS BAckup 26Dec2023/Backup-Source/objects/Phoenix_NPR_Data__c.object
<CustomObject>
    <fields>
        <fullName>Phoenix_NPR_Status__c</fullName>
        <label>NPR Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NPR Data</label>
    <nameField>
        <displayFormat>NPR-{000000}</displayFormat>
        <label>NPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPR Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PCS BAckup 26Dec2023/Backup-Source/classes/Phoenix_NPRDataActiveChecker.cls
public class Phoenix_NPRDataActiveChecker implements Database.Batchable<sObject>,Database.Stateful,Schedulable {
    public  Map<String,Product2> newlyCreatedProdsMap = new Map<String,Product2>();
    
    public Phoenix_NPRDataActiveChecker() {
    }
    
    //schedule controller
    public void execute(SchedulableContext sc) {        database.executeBatch(new Phoenix_NPRDataActiveChecker(), 200);
    }
    
    
    public Database.QueryLocator start(Database.BatchableContext BC){
       // DateTime today10AM = DateTime.newInstanceGMT(System.today(), Time.newInstance(5, 0, 0, 0));
         DateTime today10AM = DateTime.newInstanceGMT(Date.newInstance(System.now().year(), System.now().monthGmt(), System.now().dayGmt()), Time.newInstance(5, 0, 0, 0));

        String query = 'SELECT Id,LastModifiedDate FROM Phoenix_NPR_Data__c ';
        
        if(Test.isRunningTest()){query += ' Limit 1';}
        else { query += ' WHERE LastModifiedDate < TODAY'; //' WHERE LastModifiedDate < :today10AM';
             
             }
        return Database.getQueryLocator(query);
    }
    
    
    public void execute(Database.BatchableContext BC, List<Phoenix_NPR_Data__c> nprList){
        List<Phoenix_NPR_Data__c> updatedNPRs = new List<Phoenix_NPR_Data__c>();
        
        for(Phoenix_NPR_Data__c npr : nprList){            npr.Phoenix_NPR_Status__c = 'In Active';            updatedNPRs.add(npr);
        }
        
        update updatedNPRs; 
        
    }
    
    public void finish(Database.BatchableContext BC){        Phoenix_SubmitBidForApprovalCtrl.reportDuplicateNprStagingRecords();
         System.scheduleBatch(new Phoenix_FutureNPRDataActiveChecker(), 'Phoenix_FutureNPRDataActiveChecker', 1, 200);
    }
}