PCS BAckup 26Dec2023/Backup-Source/objects/Response_Time__c.object
<CustomObject>
    <fields>
        <fullName>Avg_Customer_Response__c</fullName>
        <label>Avg Customer Response</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Internal_Approval__c</fullName>
        <label>Avg Internal Approval</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Benchmark_1__c</fullName>
        <label>Benchmark-1</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Benchmark_2__c</fullName>
        <label>Benchmark-2</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Response_Date__c</fullName>
        <label>Response Date</label>
        <type>Date</type>
    </fields>
    <label>Response Time</label>
    <nameField>
        <displayFormat>RT-{00}</displayFormat>
        <label>Response Time No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UAT_AllStar_8Jan2024_0636/Backup-Source/classes/AvgCustomerResponseScheduledTest.cls
/**
* @description       : This test class contains Avg Customer Response Date & Internal Approval values map into another Object (Response Time).create the record every day at 12AM
* @Class Name        : AvgCustomerResponseScheduled
* @author            : Ramakrishna Y
* @Created on        : 26-10-2021
* @last modified on  : 27-10-2021
* @last modified by  : Ramakrishna Y
**/
@isTest(SeeAllData=true)
private class AvgCustomerResponseScheduledTest
{
   public static testMethod void testRunAs() 
    {  
        // Create your test data
        Response_Time__c rt=new Response_Time__c();
        rt.Response_Date__c=System.today();
        rt.Avg_Customer_Response__c = 9.25;
        rt.Benchmark_1__c=10;
        rt.Avg_Internal_Approval__c = 10.12;
        rt.Benchmark_2__c=5;
        insert rt;
        
    
        Test.StartTest();
        AvgCustomerResponseScheduled testsche = new AvgCustomerResponseScheduled();
        String sch = '0 0 23 * * ?';
      //  system.schedule('Test status Check', sch, testsche );
	testsche.execute(null);
        Test.stopTest();
         
         
    }
}